# Generated by Django 5.0.1 on 2026-06-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('rfc_solicitante', models.CharField(max_length=13)),
                ('tipo_solicitud', models.CharField(choices=[('CFDI', 'CFDI'), ('Metadata', 'Metadata')], default='CFDI', max_length=10)),
                ('direccion', models.CharField(choices=[('emitidos', 'Emitidos'), ('recibidos', 'Recibidos')], max_length=10)),
                ('estado', models.IntegerField(choices=[(1, 'Aceptada'), (2, 'En Proceso'), (3, 'Terminada'), (4, 'Error'), (5, 'Rechazada'), (6, 'Vencida')], default=1)),
                ('codigo_estado', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_cfdis', models.IntegerField(blank=True, null=True)),
                ('ids_paquetes', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud SAT',
                'verbose_name_plural': 'Solicitudes SAT',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['fecha_inicial', 'fecha_final', 'direccion'], name='sat_client__fecha_i_2e0f19_idx'), models.Index(fields=['rfc_solicitante', 'tipo_solicitud', 'estado'], name='sat_client__rfc_sol_db08c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogDescargaSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('mensaje', models.TextField()),
                ('cfdis_descargados', models.IntegerField(default=0)),
                ('cfdis_nuevos', models.IntegerField(default=0)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='sat_client.solicituddescarga')),
            ],
            options={
                'verbose_name': 'Log descarga SAT',
                'verbose_name_plural': 'Logs descarga SAT',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CfdiDescargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('rfc_emisor', models.CharField(max_length=13)),
                ('nombre_emisor', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc_receptor', models.CharField(max_length=13)),
                ('nombre_receptor', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('tipo_cfdi', models.CharField(choices=[('emitido', 'Emitido'), ('recibido', 'Recibido')], max_length=10)),
                ('uso_cfdi', models.CharField(blank=True, max_length=10, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=5, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(default='vigente', max_length=20)),
                ('xml_raw', models.TextField(blank=True, null=True)),
                ('descargado_en', models.DateTimeField(auto_now_add=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdis', to='sat_client.solicituddescarga')),
            ],
            options={
                'verbose_name': 'CFDI Descargado',
                'verbose_name_plural': 'CFDIs Descargados',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['rfc_emisor', 'fecha_emision'], name='sat_client__rfc_emi_973240_idx'), models.Index(fields=['rfc_receptor', 'fecha_emision'], name='sat_client__rfc_rec_768077_idx'), models.Index(fields=['total', 'fecha_emision'], name='sat_client__total_47e532_idx'), models.Index(fields=['conciliado'], name='sat_client__concili_1a7edf_idx')],
            },
        ),
    ]
