# Generated by Django 5.0.1 on 2026-06-11 18:25

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal
from django.utils import dateparse, timezone
from lxml import etree


def _decimal(value, default="0"):
    return Decimal(value if value not in (None, "") else default)


def _optional_decimal(value):
    if value in (None, ""):
        return None
    return Decimal(value)


def _datetime(value):
    parsed = dateparse.parse_datetime(value or "")
    if parsed is None:
        return None
    if timezone.is_naive(parsed):
        parsed = timezone.make_aware(parsed, timezone.get_current_timezone())
    return parsed


def _children_by_local_name(root, name):
    return [child for child in root.iter() if etree.QName(child).localname == name]


def backfill_pagos_relacionados(apps, schema_editor):
    CfdiDescargado = apps.get_model("sat_client", "CfdiDescargado")
    CfdiPagoRelacionado = apps.get_model("sat_client", "CfdiPagoRelacionado")
    for cfdi in CfdiDescargado.objects.filter(tipo_comprobante="P").exclude(xml_raw__isnull=True).exclude(xml_raw=""):
        try:
            root = etree.fromstring(cfdi.xml_raw.encode("utf-8"))
        except Exception:
            continue
        for pago in _children_by_local_name(root, "Pago"):
            fecha_pago = _datetime(pago.get("FechaPago"))
            if fecha_pago is None:
                continue
            forma_pago = pago.get("FormaDePagoP") or ""
            moneda = pago.get("MonedaP") or "MXN"
            monto_pago = _decimal(pago.get("Monto"))
            for docto in _children_by_local_name(pago, "DoctoRelacionado"):
                uuid_relacionado = (docto.get("IdDocumento") or "").upper()
                if not uuid_relacionado:
                    continue
                CfdiPagoRelacionado.objects.get_or_create(
                    cfdi_pago=cfdi,
                    uuid_relacionado=uuid_relacionado,
                    num_parcialidad=docto.get("NumParcialidad") or "",
                    defaults={
                        "fecha_pago": fecha_pago,
                        "monto": _decimal(docto.get("ImpPagado"), str(monto_pago)),
                        "moneda": docto.get("MonedaDR") or moneda,
                        "forma_pago": forma_pago,
                        "importe_saldo_anterior": _optional_decimal(docto.get("ImpSaldoAnt")),
                        "importe_saldo_insoluto": _optional_decimal(docto.get("ImpSaldoInsoluto")),
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ('sat_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiPagoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_relacionado', models.CharField(db_index=True, max_length=36)),
                ('fecha_pago', models.DateTimeField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('forma_pago', models.CharField(blank=True, max_length=5)),
                ('num_parcialidad', models.CharField(blank=True, max_length=20)),
                ('importe_saldo_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('importe_saldo_insoluto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cfdi_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_detalle', to='sat_client.cfdidescargado')),
            ],
            options={
                'verbose_name': 'Pago relacionado CFDI',
                'verbose_name_plural': 'Pagos relacionados CFDI',
                'ordering': ['fecha_pago', 'uuid_relacionado'],
                'indexes': [models.Index(fields=['fecha_pago', 'monto'], name='sat_client__fecha_p_12fdb4_idx'), models.Index(fields=['uuid_relacionado', 'fecha_pago'], name='sat_client__uuid_re_ddb007_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cfdipagorelacionado',
            constraint=models.UniqueConstraint(fields=('cfdi_pago', 'uuid_relacionado', 'num_parcialidad'), name='uniq_cfdi_pago_docto_parcialidad'),
        ),
        migrations.RunPython(backfill_pagos_relacionados, migrations.RunPython.noop),
    ]
