# Generated by Django 5.0.1 on 2026-07-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_client', '0002_pagos_relacionados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocumentoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('constancia', 'Constancia de situación fiscal'), ('opinion', 'Opinión de cumplimiento'), ('buzon', 'Buzón Tributario')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='sat/documentos/')),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_documentos_sat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud documento SAT',
                'verbose_name_plural': 'Solicitudes documentos SAT',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tipo', 'estado', '-creado_en'], name='sat_client__tipo_d8c018_idx')],
            },
        ),
    ]
