# Generated by Django 5.0.1 on 2026-02-17 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_alter_costoinsumo_options_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('cantidad_sistema', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cantidad_fisica', models.DecimalField(decimal_places=3, max_digits=18)),
                ('motivo', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente aprobación'), ('APLICADO', 'Aplicado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.insumo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ExistenciaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('punto_reorden', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maestros.insumo')),
            ],
            options={
                'verbose_name': 'Existencia de insumo',
                'verbose_name_plural': 'Existencias de insumos',
                'ordering': ['insumo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.insumo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
