# Generated by Django 5.0.1 on 2026-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
