# Generated by Django 5.0.1 on 2026-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario_source_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='existenciainsumo',
            name='consumo_diario_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='existenciainsumo',
            name='dias_llegada_pedido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='existenciainsumo',
            name='inventario_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='existenciainsumo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='existenciainsumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
