# Generated by Django 5.0.1 on 2026-02-19 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_existenciainsumo_consumo_diario_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('DRIVE', 'Google Drive'), ('SCHEDULED', 'Programado')], max_length=12)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error')], default='OK', max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('target_month', models.CharField(blank=True, default='', max_length=7)),
                ('fallback_used', models.BooleanField(default=False)),
                ('downloaded_sources', models.CharField(blank=True, default='', max_length=255)),
                ('rows_stock_read', models.PositiveIntegerField(default=0)),
                ('rows_mov_read', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('unmatched', models.PositiveIntegerField(default=0)),
                ('insumos_created', models.PositiveIntegerField(default=0)),
                ('existencias_updated', models.PositiveIntegerField(default=0)),
                ('movimientos_created', models.PositiveIntegerField(default=0)),
                ('movimientos_skipped_duplicate', models.PositiveIntegerField(default=0)),
                ('aliases_created', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
