# Generated by Django 5.0.1 on 2026-02-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_almacensyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacensyncrun',
            name='pending_preview',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
