# Generated by Django 5.0.1 on 2026-02-20 05:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_almacensyncrun_pending_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_max_diff_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de inventario',
                'verbose_name_plural': 'Configuración de inventario',
            },
        ),
    ]
