# Generated by Django 5.0.1 on 2026-04-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_existenciainsumo_trazabilidad_stock'),
        ('maestros', '0009_fix_colorante_rojo_volume_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoInsumoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('consumo_teorico', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_teorico', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entradas_periodo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stock_inicial', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('stock_final', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('consumo_real', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('diferencia_unidades', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('diferencia_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('diferencia_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('alerta', models.CharField(choices=[('OK', 'Dentro de rango'), ('MERMA', 'Merma excesiva'), ('FALTANTE', 'Consumo mayor al teórico'), ('SIN_DATOS', 'Datos insuficientes')], db_index=True, default='SIN_DATOS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_mensuales', to='maestros.insumo')),
            ],
            options={
                'verbose_name': 'Consumo mensual de insumo',
                'verbose_name_plural': 'Consumos mensuales de insumos',
                'ordering': ['periodo', 'insumo__nombre'],
                'indexes': [models.Index(fields=['periodo', 'alerta'], name='inventario__periodo_7f84d9_idx'), models.Index(fields=['insumo', 'periodo'], name='inventario__insumo__724bb0_idx')],
                'unique_together': {('periodo', 'insumo')},
            },
        ),
    ]
