# Generated by Django 5.0.1 on 2026-04-28 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_consumoinsumomensual'),
        ('maestros', '0009_fix_colorante_rojo_volume_unit'),
        ('recetas', '0028_receta_excluir_cierre_recetaequivalencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoFisicoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('fecha_conteo', models.DateField()),
                ('estatus', models.CharField(choices=[('BORRADOR', 'En captura'), ('REVISION', 'En revisión'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo físico mensual',
                'verbose_name_plural': 'Conteos físicos mensuales',
                'ordering': ['-periodo'],
                'unique_together': {('periodo',)},
            },
        ),
        migrations.CreateModel(
            name='LineaConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=50)),
                ('stock_teorico', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_contado', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ajuste_aplicado', models.BooleanField(default=False)),
                ('observacion_linea', models.TextField(blank=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.conteofisicomensual')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.insumo')),
                ('movimiento_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientoinventario')),
                ('movimiento_producto_cedis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.movimientoproductocedis')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Línea de conteo físico',
                'verbose_name_plural': 'Líneas de conteo físico',
                'ordering': ['conteo', 'nombre'],
                'indexes': [models.Index(fields=['conteo', 'insumo'], name='inventario__conteo__11fc30_idx'), models.Index(fields=['conteo', 'producto'], name='inventario__conteo__d0265f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lineaconteofisico',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('insumo__isnull', False), ('producto__isnull', True)), models.Q(('insumo__isnull', True), ('producto__isnull', False)), _connector='OR'), name='conteo_linea_insumo_o_producto'),
        ),
        migrations.AddConstraint(
            model_name='lineaconteofisico',
            constraint=models.UniqueConstraint(condition=models.Q(('insumo__isnull', False)), fields=('conteo', 'insumo'), name='uniq_conteo_insumo'),
        ),
        migrations.AddConstraint(
            model_name='lineaconteofisico',
            constraint=models.UniqueConstraint(condition=models.Q(('producto__isnull', False)), fields=('conteo', 'producto'), name='uniq_conteo_producto'),
        ),
    ]
