# Generated by Django 5.0.1 on 2026-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_existenciainsumo_almacen_movimientoinventario_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='existenciainsumo',
            options={'ordering': ['almacen', 'insumo__nombre'], 'verbose_name': 'Existencia de insumo', 'verbose_name_plural': 'Existencias de insumos'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.CharField(blank=True, choices=[('ALMACEN_1', 'Almacén 1 (principal)'), ('ALMACEN_CASA_1', 'Almacén Casa 1'), ('ALMACEN_CASA_2', 'Almacén Casa 2'), ('CUARTO_FRIO', 'Cuarto Frío'), ('VELAS', 'Almacén de Velas'), ('LIMPIEZA', 'Almacén de Limpieza'), ('OTRO', 'Otro')], default='ALMACEN_1', max_length=20),
        ),
    ]
