# Generated by Django 5.0.1 on 2026-07-11 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_existencias_por_ubicacion'),
        ('maestros', '0015_insumo_grupo_mano_obra'),
        ('operacion', '0002_expand_bitacoras_trazables'),
        ('recetas', '0041_receta_grupo_mano_obra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='linea_bitacora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='operacion.bitacoraoperativalinea'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='registrado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='trazabilidad',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=120, unique=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=18)),
                ('producido_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('RETENIDO', 'Retenido'), ('CANCELADO', 'Cancelado')], default='DISPONIBLE', max_length=16)),
                ('es_apertura', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='maestros.insumo')),
                ('linea_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lote_generado', to='operacion.bitacoraoperativalinea')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='recetas.receta')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.unidadmedida')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.loteproduccion'),
        ),
    ]
