# Generated by Django 5.0.1 on 2026-09-07 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_usermoduleaccess_module'),
        ('inventario', '0014_lotes_y_origen_movimientos'),
        ('maestros', '0016_alter_insumo_tipo_item'),
        ('pos_bridge', '0021_pointhistoricalinventoryclosing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('capturar', models.BooleanField(default=False)),
                ('revisar', models.BooleanField(default=False)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('CAPTURA', 'Captura'), ('ENVIADO', 'Enviado'), ('RECONTEO', 'Reconteo'), ('ACEPTADO', 'Aceptado'), ('CANCELADO', 'Cancelado')], default='CAPTURA', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('ronda', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('referencia', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos_asignados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='inventario.conteosucursal')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='LineaConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=120)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=60)),
                ('fuente_unidad', models.CharField(max_length=255)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='inventario.conteosucursal')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.insumo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos_bridge.pointproduct')),
            ],
            options={
                'ordering': ['nombre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LecturaConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveIntegerField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('incidencia', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturas', to='inventario.lineaconteosucursal')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionConteoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='inventario.conteosucursal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accesoconteosucursal',
            constraint=models.UniqueConstraint(fields=('user', 'sucursal'), name='cs_acceso_unico'),
        ),
        migrations.AddIndex(
            model_name='conteosucursal',
            index=models.Index(fields=['sucursal', 'fecha', 'estado'], name='inventario__sucursa_4e06e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineaconteosucursal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('insumo__isnull', True), ('producto__isnull', False)), models.Q(('insumo__isnull', False), ('producto__isnull', True)), _connector='OR'), name='cs_linea_fuente_xor'),
        ),
        migrations.AddConstraint(
            model_name='lineaconteosucursal',
            constraint=models.UniqueConstraint(fields=('conteo', 'producto'), name='cs_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='lineaconteosucursal',
            constraint=models.UniqueConstraint(fields=('conteo', 'insumo'), name='cs_insumo_unico'),
        ),
        migrations.AddConstraint(
            model_name='lecturaconteosucursal',
            constraint=models.UniqueConstraint(fields=('linea', 'ronda'), name='cs_lectura_ronda_unica'),
        ),
        migrations.AddConstraint(
            model_name='lecturaconteosucursal',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__isnull', True), ('cantidad__gte', 0), _connector='OR'), name='cs_cantidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='operacionconteosucursal',
            constraint=models.UniqueConstraint(fields=('conteo', 'request_id'), name='cs_operacion_unica'),
        ),
    ]
