# Generated by Django 5.0.1 on 2026-04-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalRentabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes que representa este registro. Ej: 2025-01-01')),
                ('ventas_brutas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('devoluciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_materia_prima', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de ingredientes vendidos (CMV)', max_digits=14)),
                ('empaque', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otros_costos_variables', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('renta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nomina_directa', models.DecimalField(decimal_places=2, default=0, help_text='Nómina de empleados que trabajan directamente en la sucursal', max_digits=12)),
                ('servicios_luz_agua', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gastos_admin_prorrateados', models.DecimalField(decimal_places=2, default=0, help_text='Porción de gastos corporativos (DG, contabilidad, etc.) asignada a esta sucursal', max_digits=12)),
                ('otros_gastos_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inversion_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Inversión total para abrir la sucursal (obra, equipo, inventario inicial, etc.)', max_digits=14)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('subsidio_recibido', models.DecimalField(decimal_places=2, default=0, help_text='Monto que la empresa está poniendo de su propio flujo para sostener esta sucursal este mes', max_digits=12)),
                ('estado', models.CharField(choices=[('SUBSIDIADA', 'Subsidiada'), ('EQUILIBRIO', 'Punto de equilibrio'), ('RECUPERACION', 'En recuperación'), ('RENTABLE', 'Rentable'), ('ESTRELLA', 'Estrella'), ('SIN_DATOS', 'Sin datos suficientes')], db_index=True, default='SIN_DATOS', max_length=20)),
                ('diagnostico_ia', models.TextField(blank=True, default='', help_text='Texto generado por el agente IA explicando el estado de la sucursal')),
                ('recomendaciones_ia', models.JSONField(default=list, help_text='Lista de acciones recomendadas por el agente')),
                ('alerta_nivel', models.IntegerField(default=0, help_text='0=ok, 1=atención, 2=urgente')),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('calculado_por_agente', models.BooleanField(default=False)),
                ('notas_manuales', models.TextField(blank=True, default='')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentabilidad_mensual', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Rentabilidad de sucursal',
                'verbose_name_plural': 'Rentabilidad de sucursales',
                'ordering': ['-periodo', 'sucursal'],
                'unique_together': {('sucursal', 'periodo')},
            },
        ),
    ]
