# Generated by Django 5.0.1 on 2026-04-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalrentabilidad',
            name='costo_reventa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de adquisición de mercancía revendida', max_digits=14),
        ),
    ]
