# Generated by Django 5.0.1 on 2026-05-14 22:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0004_prestamos_contpaq_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBonoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('dias_laborables', models.PositiveSmallIntegerField(default=23)),
                ('monto_hornos', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8)),
                ('monto_embetunado', models.DecimalField(decimal_places=2, default=Decimal('850.00'), max_digits=8)),
                ('monto_armado', models.DecimalField(decimal_places=2, default=Decimal('850.00'), max_digits=8)),
                ('monto_crucero', models.DecimalField(decimal_places=2, default=Decimal('950.00'), max_digits=8)),
                ('pct_produccion', models.DecimalField(decimal_places=2, default=Decimal('65.00'), max_digits=5)),
                ('pct_asistencia', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('pct_puntualidad', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('pct_uniforme', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('premio_embetunado', models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=8)),
                ('limite_uniforme', models.PositiveSmallIntegerField(default=1)),
                ('limite_asistencia', models.PositiveSmallIntegerField(default=2)),
                ('limite_puntualidad', models.PositiveSmallIntegerField(default=2)),
                ('limite_produccion', models.PositiveSmallIntegerField(default=2)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de bono - Producción',
                'verbose_name_plural': 'Configuraciones de bonos - Producción',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='BonoProduccionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('HORNOS', 'Hornos'), ('EMBETUNADO', 'Embetunado'), ('ARMADO', 'Armado'), ('CRUCERO', 'Crucero')], max_length=20)),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('dias_uniforme', models.PositiveSmallIntegerField(default=0)),
                ('dias_puntualidad', models.PositiveSmallIntegerField(default=0)),
                ('dias_asistencia', models.PositiveSmallIntegerField(default=0)),
                ('dias_produccion', models.PositiveSmallIntegerField(default=0)),
                ('total_embetunados', models.PositiveIntegerField(default=0)),
                ('pasa_uniforme', models.BooleanField(default=False)),
                ('pasa_puntualidad', models.BooleanField(default=False)),
                ('pasa_asistencia', models.BooleanField(default=False)),
                ('pasa_produccion', models.BooleanField(default=False)),
                ('gano_premio_embetunado', models.BooleanField(default=False)),
                ('monto_uniforme', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_puntualidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_asistencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_produccion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_premio_embetunado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('ajuste_positivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('ajuste_negativo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('bono_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('desc_ajuste_positivo', models.CharField(blank=True, default='', max_length=200)),
                ('desc_ajuste_negativo', models.CharField(blank=True, default='', max_length=200)),
                ('desc_bono_extra', models.CharField(blank=True, default='', max_length=200)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADO', 'Cerrado'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos_produccion', to='rrhh.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos', to='bonos_produccion.configbonoperiodo')),
            ],
            options={
                'verbose_name': 'Bono de Producción',
                'verbose_name_plural': 'Bonos de Producción',
                'ordering': ['area', 'empleado__nombre'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDiarioProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField()),
                ('tiene_uniforme', models.BooleanField(default=True)),
                ('tiene_puntualidad', models.BooleanField(default=True)),
                ('tiene_asistencia', models.BooleanField(default=True)),
                ('tiene_produccion', models.BooleanField(default=True)),
                ('cantidad_embetunados', models.PositiveSmallIntegerField(default=0)),
                ('observacion', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='bonos_produccion.bonoproduccionempleado')),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('bono', 'dia')},
            },
        ),
    ]
