# Generated by Django 5.0.1 on 2026-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos_produccion', '0005_configbonoperiodo_fecha_inicio_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonoproduccionempleado',
            name='area',
            field=models.CharField(choices=[('HORNOS', 'Hornos'), ('PRODUCCION', 'Embetunado'), ('ARMADO', 'Armado'), ('LOGISTICA', 'Logística'), ('CRUCERO', 'Crucero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configbonoarea',
            name='area',
            field=models.CharField(choices=[('HORNOS', 'Hornos'), ('PRODUCCION', 'Embetunado'), ('ARMADO', 'Armado'), ('LOGISTICA', 'Logística'), ('CRUCERO', 'Crucero')], max_length=20),
        ),
    ]
