# Generated by Django 5.0.1 on 2026-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos_produccion', '0006_area_embetunado_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonoproduccionempleado',
            name='cancela_bono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonoproduccionempleado',
            name='cancela_motivo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
