# Generated by Django 5.0.1 on 2026-09-21 21:28

from decimal import Decimal
from django.db import migrations, models


def copiar_montos_vigentes(apps, schema_editor):
    """Los montos nuevos arrancan igual que el área de la que sale cada persona.

    Preparación recibe a quienes hoy están en Crucero y en Embetunado, y cuartos
    fríos a quienes están en Logística. Copiando el importe vigente de cada
    periodo, la reasignación no le cambia el bono a nadie.
    """
    ConfigBonoPeriodo = apps.get_model("bonos_produccion", "ConfigBonoPeriodo")
    for periodo in ConfigBonoPeriodo.objects.all():
        periodo.monto_preparacion = periodo.monto_crucero
        periodo.monto_cuartos_frios = periodo.monto_logistica
        periodo.save(update_fields=["monto_preparacion", "monto_cuartos_frios"])


def revertir_montos(apps, schema_editor):
    """Nada que deshacer: los campos se eliminan con la migración inversa."""


class Migration(migrations.Migration):

    dependencies = [
        ('bonos_produccion', '0007_bonoproduccionempleado_cancela_bono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbonoperiodo',
            name='monto_cuartos_frios',
            field=models.DecimalField(decimal_places=2, default=Decimal('850.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='configbonoperiodo',
            name='monto_preparacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('850.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='bonoproduccionempleado',
            name='area',
            field=models.CharField(choices=[('HORNOS', 'Hornos'), ('PRODUCCION', 'Embetunado'), ('ARMADO', 'Armado'), ('PREPARACION', 'Preparación'), ('CUARTOS_FRIOS', 'Cuartos fríos'), ('LOGISTICA', 'Logística'), ('CRUCERO', 'Crucero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configbonoarea',
            name='area',
            field=models.CharField(choices=[('HORNOS', 'Hornos'), ('PRODUCCION', 'Embetunado'), ('ARMADO', 'Armado'), ('PREPARACION', 'Preparación'), ('CUARTOS_FRIOS', 'Cuartos fríos'), ('LOGISTICA', 'Logística'), ('CRUCERO', 'Crucero')], max_length=20),
        ),
        migrations.RunPython(copiar_montos_vigentes, revertir_montos),
    ]
