# Generated by Django 5.0.1 on 2026-02-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_lock_auditoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modo_captura_sucursal',
            field=models.BooleanField(default=False),
        ),
    ]
