# Generated by Django 5.0.1 on 2026-03-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_modo_captura_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='fecha_apertura',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
