# Generated by Django 5.0.1 on 2026-05-02 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('logistica', 'Logística'), ('fallas', 'Fallas / Mantenimiento'), ('compras', 'Compras'), ('ventas', 'Ventas'), ('reportes', 'Reportes'), ('produccion', 'Producción'), ('rrhh', 'RRHH'), ('inventario', 'Inventario'), ('recetas', 'Recetas'), ('crm', 'CRM'), ('auditoria', 'Auditoría'), ('maestros', 'Maestros')], max_length=40)),
                ('access', models.CharField(choices=[('none', 'Sin acceso'), ('view', 'Solo ver'), ('manage', 'Ver y editar')], default='none', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_access_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso por módulo',
                'verbose_name_plural': 'Accesos por módulo',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
