# Generated by Django 5.0.1 on 2026-05-04 13:03

from django.db import migrations


SUCURSALES_ESPECIALES = [
    {
        "codigo": "CEDIS",
        "nombre": "CEDIS",
        "activa": False,
    },
    {
        "codigo": "DEVOLUCIONES",
        "nombre": "Devoluciones",
        "activa": False,
    },
]


def crear_sucursales(apps, schema_editor):
    Sucursal = apps.get_model("core", "Sucursal")
    for data in SUCURSALES_ESPECIALES:
        Sucursal.objects.get_or_create(codigo=data["codigo"], defaults=data)


def revertir_sucursales(apps, schema_editor):
    Sucursal = apps.get_model("core", "Sucursal")
    Sucursal.objects.filter(codigo__in=["CEDIS", "DEVOLUCIONES"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_module_access'),
    ]

    operations = [
        migrations.RunPython(crear_sucursales, revertir_sucursales),
    ]
