# Generated by Django 5.0.1 on 2026-05-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mapear_branches_point_cedis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('logistica', 'Logística'), ('fallas', 'Fallas / Mantenimiento'), ('mermas', 'Mermas'), ('compras', 'Compras'), ('ventas', 'Ventas'), ('reportes', 'Reportes'), ('produccion', 'Producción'), ('rrhh', 'RRHH'), ('inventario', 'Inventario'), ('recetas', 'Recetas'), ('crm', 'CRM'), ('auditoria', 'Auditoría'), ('maestros', 'Maestros')], max_length=40),
        ),
    ]
