# Generated by Django 5.0.1 on 2026-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usermoduleaccess_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('logistica', 'Logística'), ('mantenimiento', 'Mantenimiento'), ('seguimiento', 'Seguimiento personal'), ('fallas', 'Fallas / Mantenimiento'), ('mermas', 'Mermas'), ('mermas.captura', 'Mermas - App sucursal'), ('mermas.recepcion', 'Mermas - Recepción CEDIS'), ('mermas.dashboard', 'Mermas - Panel ERP'), ('compras', 'Compras'), ('ventas', 'Ventas'), ('reportes', 'Reportes'), ('produccion', 'Producción'), ('rrhh', 'RRHH'), ('inventario', 'Inventario'), ('recetas', 'Recetas'), ('crm', 'CRM'), ('auditoria', 'Auditoría'), ('maestros', 'Maestros')], max_length=40),
        ),
    ]
