# Generated by Django 5.0.1 on 2026-05-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usermoduleaccess_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permiso', 'Permiso'), ('prestamo', 'Préstamo'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta')], db_index=True, default='normal', max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('objeto_tipo', models.CharField(blank=True, default='', max_length=80)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=80)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['leida', '-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-creado_en'], name='core_notifi_usuario_efc21a_idx'), models.Index(fields=['tipo', 'objeto_tipo', 'objeto_id'], name='core_notifi_tipo_b26861_idx')],
            },
        ),
    ]
