# Generated by Django 5.0.1 on 2026-05-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('permiso', 'Permiso'), ('hora_extra', 'Hora extra'), ('prestamo', 'Préstamo'), ('sistema', 'Sistema'), ('seguimiento', 'Seguimiento')], db_index=True, default='sistema', max_length=20),
        ),
    ]
