# Generated by Django 5.0.1 on 2026-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_usermoduleaccess_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoduleaccess',
            name='module',
            field=models.CharField(choices=[('logistica', 'Logística'), ('mantenimiento', 'Mantenimiento'), ('seguimiento', 'Seguimiento personal'), ('seguimiento.calendario', 'Seguimiento - Calendario'), ('fallas', 'Fallas / Mantenimiento'), ('mermas', 'Mermas'), ('mermas.captura', 'Mermas - App sucursal'), ('mermas.recepcion', 'Mermas - Recepción CEDIS'), ('mermas.dashboard', 'Mermas - Panel ERP'), ('compras', 'Compras'), ('ventas', 'Ventas'), ('reportes', 'Reportes'), ('produccion', 'Producción'), ('rrhh', 'RRHH'), ('rrhh.dashboard', 'RRHH - Indicadores'), ('rrhh.organizacion', 'RRHH - Organización'), ('rrhh.empleados', 'RRHH - Empleados'), ('rrhh.permisos', 'RRHH - Permisos'), ('rrhh.vacaciones', 'RRHH - Vacaciones'), ('rrhh.horas_extra', 'RRHH - Horas extra'), ('rrhh.asistencias', 'RRHH - Asistencias'), ('rrhh.importar_checador', 'RRHH - Checador'), ('rrhh.vacantes', 'RRHH - Vacantes'), ('rrhh.prestamos', 'RRHH - Préstamos'), ('rrhh.nomina', 'RRHH - Nómina'), ('rrhh.asignacion_sucursal', 'RRHH - Asignación sucursal'), ('inventario', 'Inventario'), ('recetas', 'Recetas'), ('crm', 'CRM'), ('auditoria', 'Auditoría'), ('maestros', 'Maestros')], max_length=40),
        ),
    ]
