# Generated by Django 5.0.1 on 2026-04-03 17:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('maestros', '0009_fix_colorante_rojo_volume_unit'),
        ('recetas', '0027_receta_modo_costeo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('event_type', models.CharField(blank=True, default='', max_length=120)),
                ('main_date', models.DateField()),
                ('analysis_start_date', models.DateField()),
                ('analysis_end_date', models.DateField()),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECOPILANDO_DATOS', 'Recopilando datos'), ('EN_MODELADO', 'En modelado'), ('LISTO_PARA_REVISION', 'Listo para revisión'), ('PENDIENTE_DIRECCION', 'Pendiente dirección'), ('APROBADO', 'Aprobado'), ('APROBADO_CON_AJUSTES', 'Aprobado con ajustes'), ('RECHAZADO', 'Rechazado'), ('ENVIADO_A_PRODUCCION', 'Enviado a producción'), ('VALIDADO_POR_PRODUCCION', 'Validado por producción'), ('ENVIADO_A_COMPRAS', 'Enviado a compras'), ('EN_EJECUCION', 'En ejecución'), ('CERRADO', 'Cerrado'), ('EVALUADO_POST_EVENTO', 'Evaluado post-evento')], default='BORRADOR', max_length=32)),
                ('objective_type', models.CharField(blank=True, default='', max_length=80)),
                ('objective_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approval_deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('scenario_focus', models.CharField(choices=[('CONSERVADOR', 'Conservador'), ('BASE', 'Base'), ('AGRESIVO', 'Agresivo')], default='BASE', max_length=20)),
                ('conservative_pct', models.DecimalField(decimal_places=2, default=Decimal('0.90'), max_digits=6)),
                ('aggressive_pct', models.DecimalField(decimal_places=2, default=Decimal('1.10'), max_digits=6)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_rechazados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_events',
                'ordering': ['-main_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=80)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', max_length=200)),
                ('adjustment_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.receta')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_stage', models.CharField(choices=[('DIRECCION', 'Dirección'), ('PRODUCCION', 'Producción'), ('COMPRAS', 'Compras')], max_length=20)),
                ('role_required', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('AJUSTES', 'Ajustes solicitados')], default='PENDIENTE', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requested_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_aprobaciones_pedidas', to=settings.AUTH_USER_MODEL)),
                ('responded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_aprobaciones_resueltas', to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('action_type', models.CharField(max_length=40)),
                ('old_data_json', models.JSONField(blank=True, default=dict)),
                ('new_data_json', models.JSONField(blank=True, default=dict)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaExecutionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('forecast_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('actual_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('forecast_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('variance_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('variance_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.receta')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_metrics', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'event_execution_metrics',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('CONSERVADOR', 'Conservador'), ('BASE', 'Base'), ('AGRESIVO', 'Agresivo')], default='BASE', max_length=20)),
                ('estimated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_cogs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_margin', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('incremental_investment', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('break_even_sales', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sensitivity_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_financials',
                'ordering': ['sales_event', 'scenario'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('base_demand', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('event_uplift', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('trend_adjustment', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('final_forecast', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('conservative_forecast', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('aggressive_forecast', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('model_version', models.CharField(blank=True, default='v1-hybrid', max_length=40)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_event_forecasts', to='core.sucursal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_event_forecasts', to='recetas.receta')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_forecasts',
                'ordering': ['forecast_date', 'branch__codigo', 'product__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Advertencia'), ('CRIT', 'Crítica')], default='INFO', max_length=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LEIDA', 'Leída')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado')], default='BORRADOR', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_produccion_aprobados', to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'production_plans',
                'ordering': ['plan_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('planned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('existing_finished_stock', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('net_qty_to_produce', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('production_day', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_event_production_lines', to='recetas.receta')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ventas.eventoventaproductionplan')),
            ],
            options={
                'db_table': 'production_plan_lines',
                'ordering': ['production_day', 'product__nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaInputRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('on_hand_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('net_shortage_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('unit_cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=10)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_event_requirements', to='maestros.insumo')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_requirements', to='ventas.eventoventa')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_requirements', to='ventas.eventoventaproductionplan')),
            ],
            options={
                'db_table': 'input_requirements',
                'ordering': ['-net_shortage_qty', 'input_item__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AI_SUGGESTED', 'AI sugerido'), ('HISTORICAL', 'Histórico'), ('REPLACEMENT', 'Reemplazo')], default='MANUAL', max_length=20)),
                ('inclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_event_products', to='recetas.receta')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_products',
                'ordering': ['product__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaPurchaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_purchase_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('purchase_deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='ventas.eventoventainputrequirement')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requirements', to='ventas.eventoventa')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.proveedor')),
            ],
            options={
                'db_table': 'purchase_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoVentaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_events', to='core.sucursal')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_branches',
                'ordering': ['branch__codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='eventoventa',
            index=models.Index(fields=['status', 'main_date'], name='sales_events_status_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoventafinancial',
            unique_together={('sales_event', 'scenario')},
        ),
        migrations.AddIndex(
            model_name='eventoventaforecast',
            index=models.Index(fields=['sales_event', 'forecast_date'], name='se_forecast_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoventaforecast',
            index=models.Index(fields=['branch', 'product', 'forecast_date'], name='se_fcst_br_prod_dt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoventaforecast',
            unique_together={('sales_event', 'branch', 'product', 'forecast_date')},
        ),
        migrations.AlterUniqueTogether(
            name='eventoventaproductionplan',
            unique_together={('sales_event', 'plan_date')},
        ),
        migrations.AlterUniqueTogether(
            name='eventoventaproducto',
            unique_together={('sales_event', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='eventoventasucursal',
            unique_together={('sales_event', 'branch')},
        ),
    ]
