# Generated by Django 5.0.1 on 2026-04-03 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0027_receta_modo_costeo'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoventaproductionline',
            name='capacity_gap_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eventoventaproductionline',
            name='capacity_limit_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='eventoventaproductionline',
            name='constraint_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='EventoVentaCapacityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('max_production_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_event_capacity_rules', to='core.sucursal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_event_capacity_rules', to='recetas.receta')),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_rules', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_capacity_rules',
                'ordering': ['capacity_date', 'product__nombre', 'branch__codigo', 'id'],
            },
        ),
    ]
