# Generated by Django 5.0.1 on 2026-04-03 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_eventoventaproductionline_capacity_gap_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVentaProjectionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('SEMANA', 'Proyección semanal'), ('DIA_EXACTO', 'Proyección día exacto'), ('PAQUETE', 'Paquete completo')], max_length=20)),
                ('forecast_version', models.PositiveIntegerField(default=1)),
                ('scope_start', models.DateField(blank=True, null=True)),
                ('scope_end', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_projection_artifacts', to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_artifacts', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_projection_artifacts',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sales_event', 'export_type', 'forecast_version'], name='se_artifact_evt_tp_ver_idx')],
                'unique_together': {('sales_event', 'export_type', 'forecast_version')},
            },
        ),
    ]
