# Generated by Django 5.0.1 on 2026-04-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('ventas', '0003_eventoventaprojectionartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoventa',
            name='guamuchil_comparable_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_comparable_guamuchil', to='core.sucursal'),
        ),
    ]
