# Generated by Django 5.0.1 on 2026-04-04 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('ventas', '0004_eventoventa_guamuchil_comparable_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoventasucursal',
            name='comparable_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_branch_comparable', to='core.sucursal'),
        ),
    ]
