# Generated by Django 5.0.1 on 2026-04-04 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0027_receta_modo_costeo'),
        ('ventas', '0005_eventoventasucursal_comparable_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaAutoritativaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True)),
                ('product_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('point_name', models.CharField(blank=True, default='', max_length=250)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_file', models.CharField(blank=True, default='', max_length=300)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_autoritativas_point', to='core.sucursal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_autoritativas_point', to='recetas.receta')),
            ],
            options={
                'db_table': 'ventas_autoritativas_point',
                'ordering': ['-sale_date', 'branch__codigo', 'point_name'],
                'indexes': [models.Index(fields=['sale_date', 'branch'], name='vap_day_branch_idx'), models.Index(fields=['product', 'sale_date'], name='vap_product_day_idx')],
                'unique_together': {('branch', 'sale_date', 'product_code')},
            },
        ),
    ]
