# Generated by Django 5.0.1 on 2026-04-08 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_ventaautoritativapoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVentaAdjustmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_mode', models.CharField(choices=[('RANGO', 'Rango del evento'), ('DIA', 'Día principal')], default='RANGO', max_length=20)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('forecast_version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('entries_json', models.JSONField(blank=True, default=list)),
                ('preview_json', models.JSONField(blank=True, default=dict)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_borradores_ajuste_creados', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_borradores_ajuste_finalizados', to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_drafts', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_adjustment_drafts',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['sales_event', 'status', 'scope_mode'], name='se_adjdraft_evt_st_scope_idx')],
            },
        ),
    ]
