# Generated by Django 5.0.1 on 2026-04-10 02:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_eventoventaadjustmentdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoventaprojectionartifact',
            name='export_type',
            field=models.CharField(choices=[('SEMANA', 'Proyección semanal'), ('DIA_EXACTO', 'Proyección día exacto'), ('POR_DIA', 'Proyección por día'), ('DASHBOARD', 'Dashboard ejecutivo'), ('PAQUETE', 'Paquete completo')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventoVentaDetailSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_version', models.PositiveIntegerField(default=1)),
                ('source_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_eventos_detail_snapshots', to=settings.AUTH_USER_MODEL)),
                ('sales_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_snapshot', to='ventas.eventoventa')),
            ],
            options={
                'db_table': 'sales_event_detail_snapshots',
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['sales_event', 'snapshot_version'], name='se_detail_snapshot_evt_ver_idx')],
            },
        ),
    ]
