# Generated by Django 5.0.1 on 2026-05-06 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_eventoventasubstitutionweight'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "DROP TABLE IF EXISTS sales_event_adjustments CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_adjustment_drafts CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_approvals CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_audit_log CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_capacity_rules CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_detail_snapshots CASCADE;",
                        "DROP TABLE IF EXISTS event_execution_metrics CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_financials CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_forecasts CASCADE;",
                        "DROP TABLE IF EXISTS input_requirements CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_notifications CASCADE;",
                        "DROP TABLE IF EXISTS production_plan_lines CASCADE;",
                        "DROP TABLE IF EXISTS production_plans CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_products CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_projection_artifacts CASCADE;",
                        "DROP TABLE IF EXISTS purchase_requirements CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_substitution_weights CASCADE;",
                        "DROP TABLE IF EXISTS sales_event_branches CASCADE;",
                        "DROP TABLE IF EXISTS sales_events CASCADE;",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(name='EventoVentaAdjustment'),
                migrations.DeleteModel(name='EventoVentaAdjustmentDraft'),
                migrations.DeleteModel(name='EventoVentaApproval'),
                migrations.DeleteModel(name='EventoVentaAuditLog'),
                migrations.DeleteModel(name='EventoVentaCapacityRule'),
                migrations.DeleteModel(name='EventoVentaDetailSnapshot'),
                migrations.DeleteModel(name='EventoVentaExecutionMetric'),
                migrations.DeleteModel(name='EventoVentaFinancial'),
                migrations.DeleteModel(name='EventoVentaForecast'),
                migrations.DeleteModel(name='EventoVentaInputRequirement'),
                migrations.DeleteModel(name='EventoVentaNotification'),
                migrations.DeleteModel(name='EventoVentaProductionLine'),
                migrations.DeleteModel(name='EventoVentaProductionPlan'),
                migrations.DeleteModel(name='EventoVentaProducto'),
                migrations.DeleteModel(name='EventoVentaProjectionArtifact'),
                migrations.DeleteModel(name='EventoVentaPurchaseRequirement'),
                migrations.DeleteModel(name='EventoVentaSubstitutionWeight'),
                migrations.DeleteModel(name='EventoVentaSucursal'),
                migrations.DeleteModel(name='EventoVenta'),
            ],
        ),
    ]
