# Generated by Django 5.0.1 on 2026-05-06 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mapear_branches_point_cedis'),
        ('ventas', '0011_disable_event_periodic_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PronosticoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('resultado_json', models.JSONField(default=dict)),
                ('total_piezas', models.IntegerField(default=0)),
                ('total_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursales', models.ManyToManyField(blank=True, to='core.sucursal')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
