# Generated by Django 5.0.1 on 2026-02-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costoinsumo',
            options={'ordering': ['-fecha', 'insumo__nombre'], 'verbose_name': 'Costo de insumo', 'verbose_name_plural': 'Costos de insumo'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.RenameIndex(
            model_name='insumo',
            new_name='maestros_in_nombre__aeab9d_idx',
            old_name='maestros_in_nombre_n_3f6c1d_idx',
        ),
    ]
