# Generated by Django 5.0.1 on 2026-02-19 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_costoinsumo_options_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=260, unique=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='maestros.insumo')),
            ],
            options={
                'verbose_name': 'Alias de insumo',
                'verbose_name_plural': 'Aliases de insumos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre_normalizado'], name='maestros_in_nombre__b3860b_idx')],
            },
        ),
    ]
