# Generated by Django 5.0.1 on 2026-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_insumoalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='codigo_point',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombre_point',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
