# Generated by Django 5.0.1 on 2026-02-20 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_insumo_codigo_point_insumo_nombre_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPendingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROVEEDOR', 'Proveedor'), ('INSUMO', 'Insumo'), ('PRODUCTO', 'Producto')], db_index=True, max_length=20)),
                ('point_codigo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('point_nombre', models.CharField(db_index=True, max_length=250)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(blank=True, default='', max_length=32)),
                ('fuzzy_score', models.FloatField(default=0.0)),
                ('fuzzy_sugerencia', models.CharField(blank=True, default='', max_length=250)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pendiente de homologación Point',
                'verbose_name_plural': 'Pendientes de homologación Point',
                'ordering': ['tipo', '-fuzzy_score', 'point_nombre'],
                'indexes': [models.Index(fields=['tipo', 'point_nombre'], name='maestros_po_tipo_1c78e9_idx'), models.Index(fields=['tipo', 'point_codigo'], name='maestros_po_tipo_b91a43_idx')],
                'unique_together': {('tipo', 'point_codigo', 'point_nombre')},
            },
        ),
    ]
