# Generated by Django 5.0.1 on 2026-02-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_pointpendingmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
