# Generated by Django 5.0.1 on 2026-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_purge_legacy_excel_recipe_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='grupo_mano_obra',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
