# Generated by Django 5.0.1 on 2026-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0015_insumo_grupo_mano_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo_item',
            field=models.CharField(choices=[('MATERIA_PRIMA', 'Materia prima (compra directa)'), ('INSUMO_INTERNO', 'Insumo interno (producido)'), ('EMPAQUE', 'Empaque'), ('HERRAMIENTA', 'Herramienta / equipo')], db_index=True, default='MATERIA_PRIMA', max_length=20),
        ),
    ]
