# Generated by Django 5.0.1 on 2026-03-30 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('paused', 'Pausado'), ('retired', 'Retirado')], default='draft', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('allowed_tools_json', models.JSONField(blank=True, default=list)),
                ('allowed_actions_json', models.JSONField(blank=True, default=list)),
                ('requires_human_approval_default', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_agents', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['priority_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_key', models.CharField(max_length=120)),
                ('scope_type', models.CharField(choices=[('read', 'Lectura'), ('analyze', 'Analisis'), ('recommend', 'Recomendacion'), ('request_approval', 'Solicitud de aprobacion'), ('execute_safe_action', 'Ejecucion segura'), ('execute_sensitive_action', 'Ejecucion sensible')], default='read', max_length=32)),
                ('resource_key', models.CharField(max_length=255)),
                ('branch_scope', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='orquestacion.agentdefinition')),
            ],
            options={
                'verbose_name': 'Capacidad de agente',
                'verbose_name_plural': 'Capacidades de agentes',
                'ordering': ['agent__priority_order', 'capability_key', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=80)),
                ('domain', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('high', 'Alta'), ('critical', 'Critica')], default='info', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('recommended_action', models.CharField(blank=True, default='', max_length=255)),
                ('requires_approval', models.BooleanField(default=True)),
                ('decision_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('executed', 'Ejecutada')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_suggestions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_agent_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia de agente',
                'verbose_name_plural': 'Sugerencias de agentes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_mode', models.CharField(max_length=40)),
                ('target_reference', models.CharField(blank=True, default='', max_length=255)),
                ('execution_status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecucion'), ('success', 'Exitosa'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_execution_links', to='core.auditlog')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_executions', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='orquestacion.agentsuggestion')),
            ],
            options={
                'verbose_name': 'Ejecucion ligada a sugerencia',
                'verbose_name_plural': 'Ejecuciones ligadas a sugerencias',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=80)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecucion'), ('blocked', 'Bloqueada'), ('resolved', 'Resuelta'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='orquestacion.agentdefinition')),
                ('assigned_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_tasks', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Tarea de agente',
                'verbose_name_plural': 'Tareas de agentes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agentsuggestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='orquestacion.agenttask'),
        ),
        migrations.CreateModel(
            name='OrchestrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('trigger_type', models.CharField(choices=[('event', 'Evento'), ('schedule', 'Programado'), ('manual', 'Manual'), ('threshold', 'Umbral')], default='event', max_length=24)),
                ('source_event', models.CharField(blank=True, default='', max_length=120)),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('action_mode', models.CharField(choices=[('observe', 'Observar'), ('recommend', 'Recomendar'), ('approval_required', 'Requiere aprobacion')], default='observe', max_length=24)),
                ('cooldown_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_rules', to='orquestacion.agentdefinition')),
                ('secondary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_rules', to='orquestacion.agentdefinition')),
            ],
            options={
                'verbose_name': 'Regla de orquestacion',
                'verbose_name_plural': 'Reglas de orquestacion',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_type', models.CharField(max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('evidence_json', models.JSONField(blank=True, default=dict)),
                ('suggested_agent_name', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('under_review', 'En revision'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('implemented', 'Implementado')], default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_gaps', to=settings.AUTH_USER_MODEL)),
                ('detected_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaps', to='orquestacion.orchestrationrule')),
            ],
            options={
                'verbose_name': 'Hueco de cobertura de agentes',
                'verbose_name_plural': 'Huecos de cobertura de agentes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=120, unique=True)),
                ('trigger_source', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecucion'), ('success', 'Exitoso'), ('partial', 'Parcial'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('result_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_runs', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='orquestacion.orchestrationrule')),
            ],
            options={
                'verbose_name': 'Corrida de orquestacion',
                'verbose_name_plural': 'Corridas de orquestacion',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orquestacion.orchestrationrun'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['status', 'priority_order'], name='orquestacio_status_1a7dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdefinition',
            index=models.Index(fields=['domain', 'status'], name='orquestacio_domain_c16aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcapability',
            index=models.Index(fields=['scope_type', 'active'], name='orquestacio_scope_t_8e61e7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcapability',
            index=models.Index(fields=['capability_key', 'active'], name='orquestacio_capabil_fcea8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentcapability',
            constraint=models.UniqueConstraint(fields=('agent', 'capability_key', 'resource_key'), name='orquestacion_agent_capability_unique_resource'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlink',
            index=models.Index(fields=['execution_status', 'created_at'], name='orquestacio_executi_55e561_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlink',
            index=models.Index(fields=['execution_mode', 'execution_status'], name='orquestacio_executi_907c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['decision_status', 'severity'], name='orquestacio_decisio_5ec94e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsuggestion',
            index=models.Index(fields=['domain', 'decision_status'], name='orquestacio_domain_0a0578_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationrule',
            index=models.Index(fields=['is_active', 'trigger_type'], name='orquestacio_is_acti_cd1f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationrule',
            index=models.Index(fields=['source_event', 'is_active'], name='orquestacio_source__dcff29_idx'),
        ),
        migrations.AddIndex(
            model_name='agentgap',
            index=models.Index(fields=['status', 'created_at'], name='orquestacio_status_063cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentgap',
            index=models.Index(fields=['gap_type', 'status'], name='orquestacio_gap_typ_c724ca_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationrun',
            index=models.Index(fields=['status', 'started_at'], name='orquestacio_status_4d5055_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationrun',
            index=models.Index(fields=['trigger_source', 'started_at'], name='orquestacio_trigger_998be5_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['status', 'priority', 'due_at'], name='orquestacio_status_9675a2_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['agent', 'status'], name='orquestacio_agent_i_d0ea50_idx'),
        ),
    ]
