# Generated by Django 5.0.1 on 2026-04-10 04:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLoopCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveIntegerField(default=1)),
                ('phase', models.CharField(choices=[('load', 'Carga'), ('observe', 'Observa'), ('think', 'Piensa'), ('act', 'Actua'), ('verify', 'Verifica'), ('block', 'Bloquea'), ('complete', 'Cierra')], default='load', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_checkpoints', to='orquestacion.orchestrationrun')),
            ],
            options={
                'verbose_name': 'Checkpoint de loop de agente',
                'verbose_name_plural': 'Checkpoints de loop de agentes',
                'ordering': ['run_id', 'iteration', 'id'],
                'indexes': [models.Index(fields=['run', 'iteration'], name='orquestacio_run_id_02131e_idx'), models.Index(fields=['phase', 'created_at'], name='orquestacio_phase_31b9f3_idx')],
            },
        ),
    ]
