# Generated by Django 5.0.1 on 2026-04-10 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0002_agentloopcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='blocking_rules_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='context_files_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='handoff_targets_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='supported_goal_types_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AgentGoalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=120)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecucion'), ('success', 'Exitosa'), ('blocked', 'Bloqueada'), ('failed', 'Fallida')], default='pending', max_length=16)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_received', to='orquestacion.orchestrationrun')),
                ('child_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_received', to='orquestacion.agenttask')),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_from', to='orquestacion.agentdefinition')),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_sent', to='orquestacion.orchestrationrun')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_sent', to='orquestacion.agenttask')),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations_to', to='orquestacion.agentdefinition')),
            ],
            options={
                'verbose_name': 'Delegacion de goal entre agentes',
                'verbose_name_plural': 'Delegaciones de goals entre agentes',
                'ordering': ['parent_run_id', 'sequence_order', 'id'],
                'indexes': [models.Index(fields=['parent_run', 'sequence_order'], name='orquestacio_parent__434dca_idx'), models.Index(fields=['goal_type', 'status'], name='orquestacio_goal_ty_86b390_idx')],
            },
        ),
    ]
