# Generated by Django 5.0.1 on 2026-04-10 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0003_agentdefinition_blocking_rules_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('proposed', 'Propuesta'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('applied', 'Aplicada')], default='proposed', max_length=16)),
                ('section', models.CharField(choices=[('fact', 'Hecho'), ('error', 'Error'), ('gap', 'Gap')], max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_type', models.CharField(choices=[('agent_runtime', 'Runtime de agente'), ('rule_runner', 'Rule runner'), ('gateway', 'AI Gateway'), ('test_validation', 'Validación'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('detected_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_proposals', to='orquestacion.agentdefinition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memory_proposals', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_proposals', to='orquestacion.orchestrationrun')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_proposals', to='orquestacion.agentsuggestion')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_proposals', to='orquestacion.agenttask')),
            ],
            options={
                'verbose_name': 'Propuesta de memoria',
                'verbose_name_plural': 'Propuestas de memoria',
                'ordering': ['status', '-last_detected_at', '-id'],
                'indexes': [models.Index(fields=['status', 'section'], name='orquestacio_status_1ad1de_idx'), models.Index(fields=['source_type', 'last_detected_at'], name='orquestacio_source__f30ee7_idx'), models.Index(fields=['proposed_by_agent', 'status'], name='orquestacio_propose_ad9f1d_idx')],
            },
        ),
    ]
