# Generated by Django 5.0.1 on 2026-04-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0004_memoryproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryproposal',
            name='approval_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automática')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='memoryproposal',
            name='auto_approval_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memoryproposal',
            name='auto_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryproposal',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
