# Generated by Django 5.0.1 on 2026-04-12 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0005_memoryproposal_approval_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryproposal',
            name='source_type',
            field=models.CharField(choices=[('agent_runtime', 'Runtime de agente'), ('rule_runner', 'Rule runner'), ('gateway', 'AI Gateway'), ('test_validation', 'Validación'), ('quality_guard', 'Quality guard'), ('manual', 'Manual')], default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='QualityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_key', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('architecture_violation', 'Violacion arquitectonica'), ('test_regression', 'Regresion de pruebas'), ('publication_gap', 'Gap de publicacion'), ('runtime_gap', 'Gap de runtime')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Advertencia'), ('high', 'Alta'), ('critical', 'Critica')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('resolved', 'Resuelto'), ('suppressed', 'Suprimido')], default='open', max_length=16)),
                ('source_type', models.CharField(choices=[('guard', 'Guard'), ('test', 'Prueba'), ('runtime', 'Runtime'), ('manual', 'Manual')], default='guard', max_length=24)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('statement', models.TextField()),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('detected_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocking', models.BooleanField(default=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_findings', to='orquestacion.memoryproposal')),
            ],
            options={
                'verbose_name': 'Hallazgo de calidad',
                'verbose_name_plural': 'Hallazgos de calidad',
                'ordering': ['status', '-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemediationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_key', models.CharField(max_length=120, unique=True)),
                ('remediation_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('proposed', 'Propuesta'), ('accepted', 'Aceptada'), ('implemented', 'Implementada'), ('validated', 'Validada'), ('rejected', 'Rechazada')], default='proposed', max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('target_files_json', models.JSONField(blank=True, default=list)),
                ('suggested_tests_json', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='low', max_length=16)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_proposals', to='orquestacion.qualityfinding')),
            ],
            options={
                'verbose_name': 'Propuesta de remediacion',
                'verbose_name_plural': 'Propuestas de remediacion',
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='qualityfinding',
            index=models.Index(fields=['code', 'status'], name='orquestacio_code_5d946f_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfinding',
            index=models.Index(fields=['category', 'status'], name='orquestacio_categor_df6cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityfinding',
            index=models.Index(fields=['source_type', 'last_seen_at'], name='orquestacio_source__83b670_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationproposal',
            index=models.Index(fields=['status', 'risk_level'], name='orquestacio_status_f61ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationproposal',
            index=models.Index(fields=['remediation_type', 'status'], name='orquestacio_remedia_e15c30_idx'),
        ),
        migrations.AddIndex(
            model_name='remediationproposal',
            index=models.Index(fields=['finding', 'status'], name='orquestacio_finding_24c87a_idx'),
        ),
    ]
