# Generated by Django 5.0.1 on 2026-04-15 04:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0006_alter_memoryproposal_source_type_qualityfinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='Nueva conversación', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('archived', 'Archivada')], default='active', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('session_key', models.CharField(blank=True, default='', max_length=80)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación ERP',
                'verbose_name_plural': 'Conversaciones ERP',
                'ordering': ['-last_message_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('context_window_json', models.JSONField(blank=True, default=dict)),
                ('last_compacted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='orquestacion.chatconversation')),
            ],
            options={
                'verbose_name': 'Estado de conversación ERP',
                'verbose_name_plural': 'Estados de conversación ERP',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuario'), ('assistant', 'Asistente'), ('tool', 'Herramienta')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('streaming', 'Transmitiendo'), ('complete', 'Completo'), ('error', 'Error')], default='complete', max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=120)),
                ('tool_display_name', models.CharField(blank=True, default='', max_length=160)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orquestacion.chatconversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de conversación ERP',
                'verbose_name_plural': 'Mensajes de conversación ERP',
                'ordering': ['conversation_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMemoryPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_pins', to='orquestacion.chatconversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_chat_memory_pins', to=settings.AUTH_USER_MODEL)),
                ('memory_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_memory_pins', to='orquestacion.memoryproposal')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_pins', to='orquestacion.chatmessage')),
            ],
            options={
                'verbose_name': 'Memoria fijada en conversación ERP',
                'verbose_name_plural': 'Memorias fijadas en conversaciones ERP',
                'ordering': ['conversation_id', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tool_key', models.CharField(max_length=120)),
                ('tool_name', models.CharField(max_length=120)),
                ('tool_display_name', models.CharField(blank=True, default='', max_length=160)),
                ('arguments_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('complete', 'Completo'), ('approval_requested', 'Aprobación solicitada'), ('error', 'Error')], default='pending', max_length=24)),
                ('requires_approval', models.BooleanField(default=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_tool_calls', to='orquestacion.agentsuggestion')),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='orquestacion.chatmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='orquestacion.chatconversation')),
                ('request_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tool_calls', to='orquestacion.chatmessage')),
            ],
            options={
                'verbose_name': 'Invocación de herramienta en chat ERP',
                'verbose_name_plural': 'Invocaciones de herramientas en chat ERP',
                'ordering': ['conversation_id', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatToolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_error', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='orquestacion.chattoolcall')),
            ],
            options={
                'verbose_name': 'Resultado de herramienta en chat ERP',
                'verbose_name_plural': 'Resultados de herramientas en chat ERP',
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['owner', 'status', 'last_message_at'], name='orquestacio_owner_i_da62b1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status', 'updated_at'], name='orquestacio_status_8bcf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'sequence'], name='orquestacio_convers_7747a8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='orquestacio_role_34a806_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='orquestacion_chat_message_unique_sequence'),
        ),
        migrations.AddIndex(
            model_name='chatmemorypin',
            index=models.Index(fields=['conversation', 'status'], name='orquestacio_convers_6c075b_idx'),
        ),
        migrations.AddIndex(
            model_name='chattoolcall',
            index=models.Index(fields=['conversation', 'created_at'], name='orquestacio_convers_ebfff1_idx'),
        ),
        migrations.AddIndex(
            model_name='chattoolcall',
            index=models.Index(fields=['tool_key', 'status'], name='orquestacio_tool_ke_351bf6_idx'),
        ),
    ]
