# Generated by Django 5.0.1 on 2026-10-07 22:41

import django.db.models.deletion
import django.utils.timezone
import orquestacion.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestacion', '0007_chatconversation_chatconversationstate_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origin_request_id', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('CONSULT_ASSET_MAINTENANCE', 'CONSULT_ASSET_MAINTENANCE')], max_length=40)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('WAITING_INFORMATION', 'WAITING_INFORMATION'), ('WAITING_SELECTION', 'WAITING_SELECTION'), ('READY', 'READY'), ('RUNNING', 'RUNNING'), ('REVALIDATION_REQUIRED', 'REVALIDATION_REQUIRED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state_json', models.JSONField(validators=[orquestacion.models.validate_workflow_state])),
                ('last_request_id', models.UUIDField(blank=True, null=True)),
                ('last_request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_response_json', models.JSONField(default=dict)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('origin_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_workflows', to='orquestacion.chatconversation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status', 'updated_at'], name='orquestacio_owner_i_78d9de_idx'), models.Index(fields=['owner', 'kind', 'status'], name='orquestacio_owner_i_b007ea_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentworkflow',
            constraint=models.CheckConstraint(check=models.Q(('kind', 'CONSULT_ASSET_MAINTENANCE'), ('schema_version', 1)), name='workflow_read_kind_schema'),
        ),
        migrations.AddConstraint(
            model_name='agentworkflow',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('WAITING_INFORMATION', 'WAITING_SELECTION', 'READY', 'RUNNING', 'REVALIDATION_REQUIRED', 'COMPLETED', 'CANCELLED', 'EXPIRED'))), name='workflow_read_status'),
        ),
        migrations.AddConstraint(
            model_name='agentworkflow',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='workflow_positive_version'),
        ),
    ]
