# Generated by Django 5.0.1 on 2026-02-23 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('clave_prefijo', models.CharField(db_index=True, max_length=12, unique=True)),
                ('clave_hash', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integraciones_public_api_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente API pública',
                'verbose_name_plural': 'Clientes API pública',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicApiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=220)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='integraciones.publicapiclient')),
            ],
            options={
                'verbose_name': 'Log API pública',
                'verbose_name_plural': 'Logs API pública',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
