from core.access import (
    _get_role_label,
    can_capture_piso,
    can_manage_orquestacion,
    can_manage_rentabilidad,
    can_view_audit,
    can_view_activos,
    can_view_control,
    can_manage_users,
    can_view_orquestacion,
    can_manage_crm,
    can_manage_compras,
    can_manage_inventario,
    can_manage_logistica,
    can_manage_rrhh,
    can_view_crm,
    can_view_compras,
    can_view_inventario,
    can_view_logistica,
    can_view_maestros,
    can_view_recetas,
    can_view_rrhh,
    can_view_reportes,
    can_view_rentabilidad,
    can_view_sistema,
    can_view_ventas,
    can_view_ventas_eventos,
    can_manage_ventas_eventos,
    can_view_module,
    is_repartidor_only,
    is_branch_capture_only,
)
from core.navigation import build_nav_groups


def ui_access(request):
    user = getattr(request, "user", None)
    current_path = getattr(request, "path", "")
    can_view_fallas = can_view_module(user, "fallas")
    return {
        "ui_access": {
            "can_view_maestros": can_view_maestros(user),
            "can_view_recetas": can_view_recetas(user),
            "can_view_compras": can_view_compras(user),
            "can_manage_compras": can_manage_compras(user),
            "can_view_inventario": can_view_inventario(user),
            "can_manage_inventario": can_manage_inventario(user),
            "can_view_activos": can_view_activos(user),
            "can_view_control": can_view_control(user),
            "can_view_sistema": can_view_sistema(user),
            "can_view_reportes": can_view_reportes(user),
            "can_view_rentabilidad": can_view_rentabilidad(user),
            "can_manage_rentabilidad": can_manage_rentabilidad(user),
            "can_view_audit": can_view_audit(user),
            "can_view_orquestacion": can_view_orquestacion(user),
            "can_manage_orquestacion": can_manage_orquestacion(user),
            "can_manage_users": can_manage_users(user),
            "can_view_crm": can_view_crm(user),
            "can_manage_crm": can_manage_crm(user),
            "can_view_logistica": can_view_logistica(user),
            "can_manage_logistica": can_manage_logistica(user),
            "can_view_rrhh": can_view_rrhh(user),
            "can_manage_rrhh": can_manage_rrhh(user),
            "can_capture_piso": can_capture_piso(user),
            "can_view_ventas": can_view_ventas(user),
            "can_view_ventas_eventos": can_view_ventas_eventos(user),
            "can_manage_ventas_eventos": can_manage_ventas_eventos(user),
            "can_view_fallas": can_view_fallas,
            "branch_capture_only": is_branch_capture_only(user),
            "repartidor_only": is_repartidor_only(user),
            "role_label": _get_role_label(user),
        },
        "ui_nav_groups": build_nav_groups(user, current_path),
    }
