# Generated by Django 5.0.1 on 2026-02-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineareceta',
            options={'ordering': ['receta', 'posicion'], 'verbose_name': 'Línea de receta', 'verbose_name_plural': 'Líneas de receta'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'ordering': ['nombre'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
    ]
