# Generated by Django 5.0.1 on 2026-02-18 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_alter_costoinsumo_options_alter_insumo_options_and_more'),
        ('recetas', '0002_alter_lineareceta_options_alter_receta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='rendimiento_cantidad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='rendimiento_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_rendimiento', to='maestros.unidadmedida'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('PREPARACION', 'Preparación base (pan, betún, crema, relleno)'), ('PRODUCTO_FINAL', 'Producto final de venta')], db_index=True, default='PREPARACION', max_length=20),
        ),
        migrations.CreateModel(
            name='RecetaPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('peso_por_unidad_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unidades_por_batch', models.PositiveIntegerField(blank=True, null=True)),
                ('unidades_por_pastel', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Presentación de receta',
                'verbose_name_plural': 'Presentaciones de receta',
                'ordering': ['receta', 'nombre'],
                'unique_together': {('receta', 'nombre')},
            },
        ),
    ]
