# Generated by Django 5.0.1 on 2026-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_receta_rendimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='usa_presentaciones',
            field=models.BooleanField(default=False),
        ),
    ]
