# Generated by Django 5.0.1 on 2026-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_receta_usa_presentaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineareceta',
            name='etapa',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lineareceta',
            name='tipo_linea',
            field=models.CharField(choices=[('NORMAL', 'Componente principal'), ('SUBSECCION', 'Subsección de componente')], default='NORMAL', max_length=20),
        ),
    ]
