# Generated by Django 5.0.1 on 2026-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_lineareceta_etapa_lineareceta_tipo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetapresentacion',
            name='unidades_por_batch',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='recetapresentacion',
            name='unidades_por_pastel',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
