# Generated by Django 5.0.1 on 2026-02-19 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_recetapresentacion_unidades_por_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('fecha_produccion', models.DateField(default=django.utils.timezone.localdate)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_produccion_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de producción',
                'verbose_name_plural': 'Planes de producción',
                'ordering': ['-fecha_produccion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanProduccionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('notas', models.CharField(blank=True, default='', max_length=160)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recetas.planproduccion')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Renglón de plan de producción',
                'verbose_name_plural': 'Renglones de plan de producción',
                'ordering': ['id'],
            },
        ),
    ]
