# Generated by Django 5.0.1 on 2026-02-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_planproduccion_planproduccionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='codigo_point',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
