# Generated by Django 5.0.1 on 2026-02-21 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_recetacodigopointalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('PRODUCTO', 'Producto'), ('FAMILIA', 'Familia'), ('LOTE', 'Lote'), ('GLOBAL', 'Global')], db_index=True, default='PRODUCTO', max_length=20)),
                ('familia', models.CharField(blank=True, default='', max_length=120)),
                ('familia_normalizada', models.CharField(blank=True, db_index=True, default='', max_length=140)),
                ('lote_desde', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('lote_hasta', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('mo_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('indirecto_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('mo_fijo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('indirecto_fijo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_costeo', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Driver de costeo',
                'verbose_name_plural': 'Drivers de costeo',
                'ordering': ['scope', 'prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecetaCostoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.PositiveIntegerField()),
                ('hash_snapshot', models.CharField(db_index=True, max_length=64)),
                ('lote_referencia', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('driver_scope', models.CharField(blank=True, default='', max_length=20)),
                ('driver_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('mo_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('indirecto_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('mo_fijo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('indirecto_fijo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_mp', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_mo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_indirecto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('rendimiento_cantidad', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('rendimiento_unidad', models.CharField(blank=True, default='', max_length=20)),
                ('costo_por_unidad_rendimiento', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('fuente', models.CharField(blank=True, default='AUTO', max_length=40)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_costo', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Versión de costo de receta',
                'verbose_name_plural': 'Versiones de costo de recetas',
                'ordering': ['receta', '-version_num'],
                'unique_together': {('receta', 'hash_snapshot'), ('receta', 'version_num')},
            },
        ),
    ]
