# Generated by Django 5.0.1 on 2026-02-21 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_costodriver_recetacostoversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PronosticoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuente', models.CharField(blank=True, default='MANUAL', max_length=40)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronosticos', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Pronóstico de venta',
                'verbose_name_plural': 'Pronósticos de venta',
                'ordering': ['-periodo', 'receta__nombre'],
                'unique_together': {('receta', 'periodo')},
            },
        ),
    ]
