# Generated by Codex on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_auditlog_options_alter_departamento_options_and_more"),
        ("recetas", "0011_pronosticoventa"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentaHistorica",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField(db_index=True)),
                ("cantidad", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("tickets", models.PositiveIntegerField(default=0)),
                ("monto_total", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("fuente", models.CharField(blank=True, default="IMPORT_VENTAS", max_length=40)),
                ("creado_en", models.DateTimeField(default=django.utils.timezone.now)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventas_historicas",
                        to="recetas.receta",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta hist\u00f3rica",
                "verbose_name_plural": "Ventas hist\u00f3ricas",
                "ordering": ["-fecha", "receta__nombre"],
            },
        ),
    ]
