# Generated by Django 5.0.1 on 2026-02-22 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_departamento_options_and_more'),
        ('recetas', '0012_ventahistorica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('MES', 'Mes'), ('SEMANA', 'Semana'), ('FIN_SEMANA', 'Fin de semana')], db_index=True, default='MES', max_length=20)),
                ('periodo', models.CharField(blank=True, db_index=True, default='', max_length=7)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuente', models.CharField(blank=True, default='UI_SOL_VENTAS', max_length=40)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_venta', to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud de venta',
                'verbose_name_plural': 'Solicitudes de venta',
                'ordering': ['-fecha_inicio', 'receta__nombre'],
                'unique_together': {('receta', 'sucursal', 'alcance', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
