# Generated by Django 5.0.1 on 2026-02-25 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_lock_auditoria_and_more'),
        ('recetas', '0013_solicitudventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioCedisProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('stock_reservado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_cedis', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Inventario CEDIS de producto',
                'verbose_name_plural': 'Inventario CEDIS de productos',
                'ordering': ['receta__nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudReabastoCedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=24, unique=True)),
                ('fecha_operacion', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_reabasto_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_reabasto', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud sucursal a CEDIS',
                'verbose_name_plural': 'Solicitudes sucursal a CEDIS',
                'ordering': ['-fecha_operacion', '-id'],
                'unique_together': {('fecha_operacion', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='PoliticaStockSucursalProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('stock_objetivo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('dias_cobertura', models.PositiveIntegerField(default=1)),
                ('stock_seguridad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('lote_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('multiplo_empaque', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_stock_sucursal', to='recetas.receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_stock_producto', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Política stock sucursal-producto',
                'verbose_name_plural': 'Políticas stock sucursal-producto',
                'ordering': ['sucursal__codigo', 'receta__nombre'],
                'unique_together': {('sucursal', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudReabastoCedisLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_reportado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('en_transito', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('consumo_proyectado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sugerido', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('solicitado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('justificacion', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_reabasto_lineas', to='recetas.receta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='recetas.solicitudreabastocedis')),
            ],
            options={
                'verbose_name': 'Línea solicitud reabasto CEDIS',
                'verbose_name_plural': 'Líneas solicitud reabasto CEDIS',
                'ordering': ['id'],
                'unique_together': {('solicitud', 'receta')},
            },
        ),
    ]
