# Generated by Django 5.0.1 on 2026-02-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_inventariocedisproducto_solicitudreabastocedis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='receta',
            name='familia',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo',
            field=models.CharField(choices=[('PREPARACION', 'Insumo interno (batida/mezcla, no venta directa)'), ('PRODUCTO_FINAL', 'Producto final de venta (armado)')], db_index=True, default='PREPARACION', max_length=20),
        ),
    ]
