# Generated by Django 5.0.1 on 2026-03-19 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0016_receta_temporalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaPresentacionDerivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_point_derivado', models.CharField(db_index=True, max_length=80)),
                ('nombre_derivado', models.CharField(max_length=250)),
                ('tipo_derivado', models.CharField(choices=[('REBANADA', 'Rebanada')], default='REBANADA', max_length=20)),
                ('unidades_por_padre', models.DecimalField(decimal_places=6, max_digits=18)),
                ('padre_size_hint', models.CharField(blank=True, default='', max_length=40)),
                ('requiere_componentes_directos', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, default='POINT_AUDIT', max_length=40)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta_derivada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentaciones_derivadas_hija', to='recetas.receta')),
                ('receta_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones_derivadas_padre', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Presentación derivada de producto',
                'verbose_name_plural': 'Presentaciones derivadas de producto',
                'ordering': ['receta_padre__nombre', 'nombre_derivado'],
                'unique_together': {('receta_padre', 'codigo_point_derivado')},
            },
        ),
    ]
