# Generated by Django 5.0.1 on 2026-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0017_recetapresentacionderivada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetapresentacionderivada',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recetapresentacionderivada',
            name='codigo_point_derivado',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
