# Generated by Django 5.0.1 on 2026-03-19 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0018_alter_recetapresentacionderivada_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProductoCedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('source_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_cedis', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Movimiento producto CEDIS',
                'verbose_name_plural': 'Movimientos producto CEDIS',
                'ordering': ['-fecha'],
            },
        ),
    ]
