# Generated by Django 5.0.1 on 2026-03-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0019_movimientoproductocedis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planproduccion',
            name='consumo_aplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='consumo_aplicado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='consumo_aplicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_produccion_consumo_aplicado', to=settings.AUTH_USER_MODEL),
        ),
    ]
