# Generated by Django 5.0.1 on 2026-03-19 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0020_planproduccion_consumo_aplicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planproduccion',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_produccion_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONSUMO_APLICADO', 'Consumo aplicado'), ('CERRADO', 'Cerrado')], db_index=True, default='BORRADOR', max_length=20),
        ),
    ]
