# Generated by Django 5.0.1 on 2026-03-23 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0021_planproduccion_cerrado_en_planproduccion_cerrado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaAgrupacionAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_codigo_point', models.CharField(db_index=True, max_length=80)),
                ('addon_nombre_point', models.CharField(max_length=250)),
                ('addon_familia', models.CharField(blank=True, default='', max_length=120)),
                ('addon_categoria', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('POINT_ZERO_REVENUE_ADDON', 'Add-on Point sin ingreso')], default='POINT_ZERO_REVENUE_ADDON', max_length=40)),
                ('status', models.CharField(choices=[('DETECTED', 'Detectado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='DETECTED', max_length=20)),
                ('cooccurrence_days', models.PositiveIntegerField(default=0)),
                ('cooccurrence_branches', models.PositiveIntegerField(default=0)),
                ('cooccurrence_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('addon_receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_addon_para', to='recetas.receta')),
                ('base_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons_aplicados', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Agrupación add-on de receta',
                'verbose_name_plural': 'Agrupaciones add-on de recetas',
                'ordering': ['base_receta__nombre', 'addon_nombre_point'],
                'unique_together': {('base_receta', 'addon_codigo_point')},
            },
        ),
    ]
