# Generated by Django 5.0.1 on 2026-03-24 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0022_recetaagrupacionaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaCostoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('RECIPE', 'Receta'), ('GROUPED_ADDON', 'Receta agrupada con add-on')], db_index=True, max_length=20)),
                ('identity_key', models.CharField(db_index=True, max_length=120)),
                ('label', models.CharField(max_length=260)),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField(db_index=True)),
                ('temporalidad', models.CharField(choices=[('PERMANENTE', 'Permanente'), ('TEMPORAL', 'Temporal'), ('FECHA_ESPECIAL', 'Fecha especial')], db_index=True, default='PERMANENTE', max_length=20)),
                ('temporalidad_detalle', models.CharField(blank=True, default='', max_length=120)),
                ('familia', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('categoria', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('costo_mp', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_mo', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_indirecto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('delta_total', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('delta_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('version_receta', models.PositiveIntegerField(blank=True, null=True)),
                ('version_base', models.PositiveIntegerField(blank=True, null=True)),
                ('version_addon', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('addon_receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_costeo_addon', to='recetas.receta')),
                ('addon_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_costeo_semanal', to='recetas.recetaagrupacionaddon')),
                ('base_receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_costeo_base', to='recetas.receta')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_costeo_semanal', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Snapshot semanal de costeo',
                'verbose_name_plural': 'Snapshots semanales de costeo',
                'ordering': ['-week_start', 'label', 'id'],
                'unique_together': {('identity_key', 'week_start')},
            },
        ),
    ]
