# Generated by Django 5.0.1 on 2026-04-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0012_pointtransferline_is_open'),
        ('recetas', '0028_receta_excluir_cierre_recetaequivalencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planproduccion',
            name='autorizado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='autorizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_produccion_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='planproduccion',
            name='origen_automatizacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='planproduccionitem',
            name='cantidad_autorizada',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='planproduccionitem',
            name='cantidad_sugerida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='planproduccionitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ConsolidadoNocturnoCEDIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(db_index=True, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTO_REVISION', 'Listo para revisión'), ('PLAN_GENERADO', 'Plan generado')], db_index=True, default='BORRADOR', max_length=24)),
                ('sucursales_esperadas', models.PositiveIntegerField(default=0)),
                ('sucursales_con_solicitud', models.PositiveIntegerField(default=0)),
                ('sucursales_sin_solicitud', models.PositiveIntegerField(default=0)),
                ('productos_consolidados', models.PositiveIntegerField(default=0)),
                ('total_sugerido', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_solicitado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_plan_produccion', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados_nocturnos_cedis_creados', to=settings.AUTH_USER_MODEL)),
                ('plan_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados_nocturnos_cedis', to='recetas.planproduccion')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados_nocturnos_cedis', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Consolidado nocturno CEDIS',
                'verbose_name_plural': 'Consolidados nocturnos CEDIS',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
