# Generated by Django 5.0.14 on 2026-05-08 20:00

from django.db import migrations, models


def clasificar_equivalencias(apps, schema_editor):
    RecetaEquivalencia = apps.get_model("recetas", "RecetaEquivalencia")
    # Factor > 1 = conversion real de entero a porcion
    RecetaEquivalencia.objects.filter(factor_conversion__gt=1).update(tipo_relacion="CONVERSION")
    # Factor = 1 = complemento de costeo
    RecetaEquivalencia.objects.filter(factor_conversion=1).update(tipo_relacion="COSTEO")


def revertir(apps, schema_editor):
    RecetaEquivalencia = apps.get_model("recetas", "RecetaEquivalencia")
    RecetaEquivalencia.objects.all().update(tipo_relacion="CONVERSION")


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0032_registrar_equivalencias_rebanadas_faltantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recetaequivalencia",
            name="tipo_relacion",
            field=models.CharField(
                choices=[
                    ("CONVERSION", "Conversión entero→porción"),
                    ("COSTEO", "Complemento de costeo"),
                ],
                db_index=True,
                default="CONVERSION",
                help_text="CONVERSION: rebanada real de entero. COSTEO: complemento para costo total.",
                max_length=20,
            ),
        ),
        migrations.RunPython(clasificar_equivalencias, revertir),
    ]
