# Generated by Django 5.0.14 on 2026-05-08

from django.db import migrations, models


NO_PRODUCTION_CATEGORIES = [
    "Rebanada",
    "Vaso Preparado Mini",
    "Vasos Mini",
    "Vasos Grande",
    "Vasos Preparados Grande",
    "TE",
    "Industrias lec",
    "D-rigaldi",
    "Otros postres",
]
NO_PRODUCTION_NAMES = [
    "Bolitas de Nuez KG",
]


def clasificar_pasa_modulo_produccion(apps, schema_editor):
    Receta = apps.get_model("recetas", "Receta")
    Receta.objects.all().update(pasa_modulo_produccion=True)
    Receta.objects.filter(tipo="PREPARACION").update(pasa_modulo_produccion=False)
    Receta.objects.filter(excluir_cierre=True).update(pasa_modulo_produccion=False)
    Receta.objects.filter(modo_costeo__in=["REVENTA", "SERVICIO_ACCESORIO"]).update(pasa_modulo_produccion=False)
    Receta.objects.filter(categoria__in=NO_PRODUCTION_CATEGORIES).update(pasa_modulo_produccion=False)
    Receta.objects.filter(nombre__in=NO_PRODUCTION_NAMES).update(pasa_modulo_produccion=False)


def revertir(apps, schema_editor):
    Receta = apps.get_model("recetas", "Receta")
    Receta.objects.all().update(pasa_modulo_produccion=True)


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0033_add_tipo_relacion_equivalencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="pasa_modulo_produccion",
            field=models.BooleanField(
                default=True,
                help_text="Indica si la receta debe cuadrar contra el módulo de producción en reportes operativos.",
            ),
        ),
        migrations.RunPython(clasificar_pasa_modulo_produccion, revertir),
    ]
