# Generated by Django 5.0.14 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0034_receta_pasa_modulo_produccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receta",
            name="pasa_modulo_produccion",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Indica si la receta debe cuadrar contra el módulo de producción en reportes operativos.",
            ),
        ),
    ]
