# Generated by Django 5.0.14 on 2026-05-08

from django.db import migrations


def marcar_costeo_como_referencia(apps, schema_editor):
    Receta = apps.get_model("recetas", "Receta")
    RecetaEquivalencia = apps.get_model("recetas", "RecetaEquivalencia")
    costeo_ids = RecetaEquivalencia.objects.filter(
        tipo_relacion="COSTEO",
        activo=True,
    ).values_list("receta_porcion_id", flat=True)
    Receta.objects.filter(id__in=costeo_ids).update(pasa_modulo_produccion=False)


def revertir(apps, schema_editor):
    # La bandera puede haber sido editada manualmente; no se revierte para no pisar criterio operativo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("recetas", "0035_index_receta_pasa_modulo_produccion"),
    ]

    operations = [
        migrations.RunPython(marcar_costeo_como_referencia, revertir),
    ]
