# Generated by Django 5.0.1 on 2026-05-26 22:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alias_pan_arandano_chico'),
        ('recetas', '0036_marcar_costeo_equivalencia_no_produccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosteoProductoDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador')], db_index=True, default='BORRADOR', max_length=20)),
                ('target_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('55.00'), max_digits=8)),
                ('costo_total_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_unitario_resultado_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costeo_producto_drafts_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costeo_producto_drafts_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrador de costeo de producto',
                'verbose_name_plural': 'Borradores de costeo de productos',
                'ordering': ['-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CosteoProductoDraftLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(default=1)),
                ('insumo_nombre_snapshot', models.CharField(max_length=250)),
                ('insumo_codigo_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unidad_codigo_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_total_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('fuente_costo', models.CharField(blank=True, default='', max_length=60)),
                ('unresolved', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='recetas.costeoproductodraft')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.insumo')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Línea de borrador de costeo',
                'verbose_name_plural': 'Líneas de borrador de costeo',
                'ordering': ['draft', 'posicion', 'id'],
            },
        ),
    ]
