# Generated by Django 5.0.1 on 2026-06-12 18:35

from django.db import migrations, models


def crear_politicas_iniciales(apps, schema_editor):
    PoliticaMargenPrecio = apps.get_model('recetas', 'PoliticaMargenPrecio')
    defaults = [
        {
            "fuente_costo": "FAB_COMPLETO",
            "familia_point": "",
            "margen_meta_pct": "55.00",
            "subida_maxima_pct": "25.00",
            "prioridad": 100,
            "notas": "Meta base editable: costo con materia prima, mano de obra, indirectos y empaque.",
        },
        {
            "fuente_costo": "MP_FALLBACK",
            "familia_point": "",
            "margen_meta_pct": "65.00",
            "subida_maxima_pct": "20.00",
            "prioridad": 100,
            "notas": "Meta base editable: solo materia prima; revisar costo completo antes de subir fuerte.",
        },
        {
            "fuente_costo": "REVENTA_HISTORICO",
            "familia_point": "",
            "margen_meta_pct": "30.00",
            "subida_maxima_pct": "15.00",
            "prioridad": 100,
            "notas": "Meta base editable para reventa/accesorios.",
        },
    ]
    for data in defaults:
        PoliticaMargenPrecio.objects.get_or_create(
            fuente_costo=data["fuente_costo"],
            familia_point=data["familia_point"],
            defaults=data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0037_costeo_producto_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaMargenPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_costo', models.CharField(choices=[('TODAS', 'Todas'), ('FAB_COMPLETO', 'Fabricacion completa'), ('MP_FALLBACK', 'Solo materia prima'), ('REVENTA_HISTORICO', 'Reventa')], db_index=True, default='TODAS', max_length=30)),
                ('familia_point', models.CharField(blank=True, db_index=True, default='', help_text='Categoria/familia de Point. Vacio aplica a todas.', max_length=120)),
                ('margen_meta_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subida_maxima_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Si la sugerencia rebasa esta subida vs precio actual, se marca como alto riesgo competitivo.', max_digits=6, null=True)),
                ('precio_max_competitivo', models.DecimalField(blank=True, decimal_places=2, help_text='Tope manual observado de mercado para esta familia/fuente.', max_digits=12, null=True)),
                ('prioridad', models.PositiveIntegerField(db_index=True, default=100)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politica de margen y precio',
                'verbose_name_plural': 'Politicas de margen y precio',
                'ordering': ['prioridad', 'familia_point', 'fuente_costo'],
            },
        ),
        migrations.RunPython(crear_politicas_iniciales, migrations.RunPython.noop),
    ]
