# Generated by Django 5.0.1 on 2026-07-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0040_repoint_legacy_pay_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='grupo_mano_obra',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
