# Generated by Django 5.0.1 on 2026-02-23 14:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, editable=False, max_length=180)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_contrato', models.CharField(choices=[('FIJO', 'Fijo'), ('TEMPORAL', 'Temporal'), ('HONORARIOS', 'Honorarios')], default='FIJO', max_length=20)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('salario_diario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sucursal', models.CharField(blank=True, default='', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NominaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=40, unique=True)),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='QUINCENAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina periodo',
                'verbose_name_plural': 'Nóminas periodos',
                'ordering': ['-fecha_fin', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NominaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('salario_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bonos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('neto_calculado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_nomina', to='rrhh.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='rrhh.nominaperiodo')),
            ],
            options={
                'verbose_name': 'Línea nómina',
                'verbose_name_plural': 'Líneas nómina',
                'ordering': ['empleado__nombre', 'id'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
    ]
