# Generated by Django 5.0.1 on 2026-04-30 18:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='curp',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='ausencias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='horas_dia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='horas_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='incapacidades',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='sbc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Salario base cotización'),
        ),
        migrations.AddField(
            model_name='nominalinea',
            name='sdi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Salario diario integrado'),
        ),
        migrations.CreateModel(
            name='NominaConceptoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERCEPCION', 'Percepción'), ('DEDUCCION', 'Deducción'), ('OBLIGACION', 'Obligación')], max_length=20)),
                ('codigo_concepto', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='rrhh.nominalinea')),
            ],
            options={
                'verbose_name': 'Concepto de línea nómina',
                'verbose_name_plural': 'Conceptos de líneas nómina',
                'ordering': ['linea__empleado__nombre', 'tipo', 'codigo_concepto', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NominaImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_hash', models.CharField(db_index=True, max_length=64)),
                ('estatus', models.CharField(choices=[('SIMULADA', 'Simulada'), ('IMPORTADA', 'Importada'), ('ERROR', 'Error')], default='SIMULADA', max_length=20)),
                ('empleados_detectados', models.PositiveIntegerField(default=0)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomina_importaciones', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to='rrhh.nominaperiodo')),
            ],
            options={
                'verbose_name': 'Importación de nómina',
                'verbose_name_plural': 'Importaciones de nómina',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
