# Generated by Django 5.0.1 on 2026-05-14 00:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usermoduleaccess_module'),
        ('rrhh', '0002_empleado_curp_empleado_nss_empleado_rfc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_minutos', models.PositiveSmallIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_trabajados', models.PositiveIntegerField(default=0)),
                ('fuente', models.CharField(choices=[('hikconnect_api', 'Hik-Connect API'), ('hikconnect_excel', 'Hik-Connect Excel'), ('point', 'PointMeUp'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.empleado')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.turno')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tasa_extra', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Multiplicador sobre salario/hora', max_digits=5)),
                ('monto_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente autorización'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado en nómina')], default='pendiente', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hora_extra', to='rrhh.asistenciaempleado')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extra_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Hora extra',
                'verbose_name_plural': 'Horas extra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionChecador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('api', 'API directa'), ('excel', 'Carga Excel')], max_length=6)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='checador_imports/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación checador',
                'verbose_name_plural': 'Importaciones checador',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PermisoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permiso_hora', 'Permiso por horas'), ('permiso_dia', 'Permiso día completo'), ('salida_personal', 'Salida personal'), ('cita_medica', 'Cita médica'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=12)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='permisos/')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Permiso / Salida',
                'verbose_name_plural': 'Permisos y Salidas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
