# Generated by Django 5.0.1 on 2026-05-14 19:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_capital_humano_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosalida',
            name='goce_sueldo',
            field=models.BooleanField(default=True, help_text='Desmarca si el permiso es sin goce de sueldo', verbose_name='Con goce de sueldo'),
        ),
        migrations.CreateModel(
            name='ImportacionNominaContpaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contpaq_imports/')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('quincena_num', models.PositiveSmallIntegerField(verbose_name='Número de quincena del año')),
                ('empleados_leidos', models.PositiveIntegerField(default=0)),
                ('prestamos_aplicados', models.PositiveIntegerField(default=0)),
                ('prestamos_sin_match', models.PositiveIntegerField(default=0)),
                ('diferencias_detectadas', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación nómina CONTPAQ',
                'verbose_name_plural': 'Importaciones nómina CONTPAQ',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('concepto', models.TextField(verbose_name='Concepto del préstamo')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia electrónica'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo')], default='transferencia', max_length=15)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_deposito', models.DateField(blank=True, null=True, verbose_name='Fecha pactada para depósito')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_quincenas', models.PositiveSmallIntegerField(verbose_name='Número de quincenas')),
                ('descuento_quincenal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento por quincena')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo pendiente')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado por jefe'), ('aprobado', 'Aprobado por dirección'), ('rechazado', 'Rechazado'), ('activo', 'Activo - en descuento'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=12)),
                ('firma_jefe', models.BooleanField(default=False)),
                ('fecha_auth_jefe', models.DateTimeField(blank=True, null=True)),
                ('firma_direccion', models.BooleanField(default=False)),
                ('fecha_auth_dg', models.DateTimeField(blank=True, null=True)),
                ('nota_separacion', models.TextField(blank=True, help_text='En caso de baja, registrar cómo se liquidó el saldo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autorizado_dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_autorizados_dg', to=settings.AUTH_USER_MODEL)),
                ('autorizado_jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_autorizados_jefe', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quincena', models.PositiveSmallIntegerField(verbose_name='Quincena #')),
                ('fecha_quincena', models.DateField(verbose_name='Fecha de la quincena')),
                ('monto_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado'), ('parcial', 'Cobro parcial'), ('omitido', 'Omitido / saltado')], default='pendiente', max_length=10)),
                ('fuente', models.CharField(choices=[('manual', 'Registro manual'), ('contpaq', 'Importación CONTPAQ XLS')], default='manual', max_length=10)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='rrhh.prestamo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota de préstamo',
                'verbose_name_plural': 'Cuotas de préstamo',
                'ordering': ['numero_quincena'],
                'unique_together': {('prestamo', 'numero_quincena')},
            },
        ),
    ]
