# Generated by Django 5.0.1 on 2026-05-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_permiso_preautorizacion_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_contrato', models.CharField(choices=[('FIJO', 'Fijo'), ('TEMPORAL', 'Temporal'), ('HONORARIOS', 'Honorarios')], default='FIJO', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_baja', models.DateField()),
                ('motivo', models.CharField(choices=[('abandono', 'Abandono laboral'), ('mejor_oportunidad', 'Mejor oportunidad de empleo'), ('cambio_domicilio', 'Cambio de domicilio'), ('ambiente', 'Mal ambiente laboral'), ('remuneracion', 'Baja remuneración'), ('no_apto', 'No apto'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('observacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bajas_rrhh', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Baja de empleado',
                'verbose_name_plural': 'Bajas de empleados',
                'ordering': ['-fecha_baja', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VacanteRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=120)),
                ('puesto', models.CharField(max_length=120)),
                ('fecha_solicitada', models.DateField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=16)),
                ('fecha_cubierta', models.DateField(blank=True, null=True)),
                ('motivo_no_cubierta', models.TextField(blank=True, default='')),
                ('sugerencias', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado_cubrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_cubiertas', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Vacante RRHH',
                'verbose_name_plural': 'Vacantes RRHH',
                'ordering': ['-fecha_solicitada', 'area', 'puesto'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, help_text='Vacío aplica como plantilla base anual', null=True)),
                ('area', models.CharField(max_length=120)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla autorizada',
                'verbose_name_plural': 'Plantillas autorizadas',
                'ordering': ['-anio', '-mes', 'area', 'puesto'],
                'unique_together': {('anio', 'mes', 'area', 'puesto')},
            },
        ),
    ]
