# Generated by Django 5.0.1 on 2026-05-26 21:21

import django.db.models.deletion
import unicodedata
from django.conf import settings
from django.db import migrations, models


def _key(value):
    value = unicodedata.normalize("NFKD", value or "")
    value = "".join(char for char in value if not unicodedata.combining(char))
    return " ".join(value.upper().split())


def _inferir_puesto_operativo(empleado):
    area = (empleado.area or "").upper()
    puesto = (empleado.puesto or "").upper()
    texto = f"{area} {puesto}"
    if "HORNO" in texto:
        return "HORNOS"
    if "ARMADO" in texto:
        return "ARMADO"
    if "CRUCERO" in puesto and "VENTAS" not in area:
        return "CRUCERO"
    if "ENVIO" in texto or "ENVÍO" in texto or "SUCURSAL" in texto:
        return "ENVIO_SUCURSAL"
    if "REPART" in texto:
        return "REPARTIDOR"
    if "CALL" in texto:
        return "CALL_CENTER"
    if "AFAN" in texto or "LIMPIEZA" in texto:
        return "LIMPIEZA"
    if "ALMACEN" in texto or "ALMACÉN" in texto:
        return "ALMACEN"
    if "PRODUCCION" in area or "PRODUCCIÓN" in area:
        return "PRODUCCION"
    return ""


def aplicar_organizacion_inicial(apps, schema_editor):
    Empleado = apps.get_model("rrhh", "Empleado")
    empleados = {_key(empleado.nombre): empleado for empleado in Empleado.objects.all()}
    yesenia = empleados.get(_key("SOTO INZUNZA YESENIA"))
    johana = empleados.get(_key("LOPEZ PALOS JOHANA ADELIN"))
    carolina = empleados.get(_key("CAYETANO VALENZUELA CAROLINA"))
    roxana = empleados.get(_key("RIVAS SOLIS ROXANA"))
    reglas = {
        _key("SOTO INZUNZA YESENIA"): {
            "departamento": "ADMINISTRACION",
            "puesto": "Jefe de Administración",
            "puesto_operativo": "JEFATURA",
        },
        _key("LOPEZ PALOS JOHANA ADELIN"): {
            "departamento": "VENTAS",
            "puesto": "Jefe de Ventas",
            "puesto_operativo": "JEFATURA",
        },
        _key("CAYETANO VALENZUELA CAROLINA"): {
            "departamento": "PRODUCCION",
            "puesto": "Jefe de Producción",
            "puesto_operativo": "JEFATURA",
        },
        _key("LUGO ESPINOZA PAULA ELIZABETH"): {
            "departamento": "RRHH",
            "puesto": "Jefe de Recursos Humanos",
            "puesto_operativo": "RRHH",
        },
        _key("RIVAS SOLIS ROXANA"): {
            "departamento": "PRODUCCION",
            "puesto": "Supervisora de Producción",
            "puesto_operativo": "SUPERVISION_PRODUCCION",
            "jefe_directo": carolina,
        },
        _key("ANGULO PARRA JULISSA"): {
            "departamento": "PRODUCCION",
            "puesto": "Encargada de Producción",
            "puesto_operativo": "ENCARGADA_PRODUCCION",
            "jefe_directo": carolina,
        },
        _key("PEREZ VALENZUELA JORGE ISAAC"): {
            "departamento": "MANTENIMIENTO",
            "puesto": "Mantenimiento",
            "puesto_operativo": "MANTENIMIENTO",
            "jefe_directo": yesenia,
        },
    }
    for empleado in Empleado.objects.all():
        data = dict(reglas.get(_key(empleado.nombre), {}))
        if not data:
            area = (empleado.area or "").upper().strip()
            puesto_operativo = _inferir_puesto_operativo(empleado)
            data = {
                "tipo_personal": "POLLYANA",
                "puesto_operativo": puesto_operativo,
                "participa_bonos_ventas": False,
                "participa_bonos_produccion": False,
            }
            if "MARKETING" in area:
                data["departamento"] = "MARKETING"
                data["tipo_personal"] = "EXTERNO"
            elif "REPART" in area or puesto_operativo == "REPARTIDOR":
                data["departamento"] = "VENTAS"
                data["puesto"] = "Repartidor"
                data["jefe_directo"] = johana
                data["participa_bonos_ventas"] = True
            elif "VENTAS" in area:
                data["departamento"] = "VENTAS"
                data["jefe_directo"] = johana
                data["participa_bonos_ventas"] = True
            elif "HORNOS" in area or "PRODUCCION" in area or "PRODUCCIÓN" in area:
                data["departamento"] = "PRODUCCION"
                data["jefe_directo"] = carolina
                data["participa_bonos_produccion"] = True
            elif "LOGISTICA" in area and puesto_operativo == "ENVIO_SUCURSAL":
                data["departamento"] = "PRODUCCION"
                data["jefe_directo"] = roxana or carolina
                data["participa_bonos_produccion"] = True
            elif "AFAN" in area or "LIMPIEZA" in area:
                data["departamento"] = "ADMINISTRACION"
                data["puesto"] = "Limpieza"
                data["puesto_operativo"] = "LIMPIEZA"
                data["jefe_directo"] = yesenia
            elif "ALMACEN" in area or "ALMACÉN" in area:
                data["departamento"] = "ADMINISTRACION"
                data["puesto_operativo"] = puesto_operativo or "ALMACEN"
                data["jefe_directo"] = yesenia
            elif "ADMIN" in area:
                data["departamento"] = "ADMINISTRACION"
                data["jefe_directo"] = yesenia

        for field, value in data.items():
            if value is not None:
                setattr(empleado, field, value)
        empleado.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_prestamos_jefe_directo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores_directos', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='participa_bonos_produccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='participa_bonos_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto_operativo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_personal',
            field=models.CharField(choices=[('POLLYANA', "Pollyana's Dolce"), ('EXTERNO', 'Externo / apoyo')], db_index=True, default='POLLYANA', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario_erp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(aplicar_organizacion_inicial, noop),
    ]
