# Generated by Django 5.0.1 on 2026-05-26 22:03

from django.db import migrations, models


def backfill_departamento_origen(apps, schema_editor):
    Empleado = apps.get_model("rrhh", "Empleado")
    for empleado in Empleado.objects.all():
        area = (empleado.area or "").upper()
        puesto = (empleado.puesto or "").upper()
        puesto_operativo = (empleado.puesto_operativo or "").upper()
        update_fields = []

        if "REPART" in area or puesto_operativo == "REPARTIDOR":
            empleado.departamento_origen = "LOGISTICA"
            empleado.departamento = "VENTAS"
            empleado.puesto_operativo = "REPARTIDOR"
            empleado.participa_bonos_ventas = True
            update_fields = ["departamento_origen", "departamento", "puesto_operativo", "participa_bonos_ventas"]
        elif "ENVIO" in area or "ENVÍO" in area or "ENVIO" in puesto or "SUCURSAL" in area or puesto_operativo == "ENVIO_SUCURSAL":
            empleado.departamento_origen = "LOGISTICA"
            empleado.departamento = "PRODUCCION"
            empleado.puesto_operativo = "ENVIO_SUCURSAL"
            empleado.participa_bonos_produccion = True
            update_fields = ["departamento_origen", "departamento", "puesto_operativo", "participa_bonos_produccion"]
        elif not empleado.departamento_origen and empleado.departamento:
            empleado.departamento_origen = empleado.departamento
            update_fields = ["departamento_origen"]

        if update_fields:
            empleado.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_organizacion_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento_origen',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40),
        ),
        migrations.RunPython(backfill_departamento_origen, migrations.RunPython.noop),
    ]
