# Generated by Django 5.0.1 on 2026-05-27 02:53

import django.db.models.deletion
import unicodedata
from django.conf import settings
from django.db import migrations, models


def normalizar(value):
    value = unicodedata.normalize("NFKD", value or "")
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    return " ".join(value.upper().split())


def clasificar_permisos_direccion(apps, schema_editor):
    PermisoSalida = apps.get_model("rrhh", "PermisoSalida")
    deps_direccion = {"ADMINISTRACION", "VENTAS", "PRODUCCION", "RRHH", "COMPRAS", "LOGISTICA"}
    nombres_direccion = {
        normalizar("YESENIA SOTO INZUNZA"),
        normalizar("JOHANA LOPEZ"),
        normalizar("JOHANA LOPEZ LOPEZ"),
        normalizar("CAROLINA CAYETANO"),
        normalizar("PAULA"),
        normalizar("PAULA LUGO"),
    }
    puesto_keywords = ("JEFE", "ENCARGAD", "RESPONSABLE", "COORDINADOR", "LIDER")

    permisos = PermisoSalida.objects.select_related("empleado").filter(estado="solicitado")
    for permiso in permisos.iterator():
        empleado = permiso.empleado
        nombre = normalizar(empleado.nombre)
        departamento = (empleado.departamento or empleado.departamento_origen or "").upper()
        puesto = f"{empleado.puesto or ''} {empleado.puesto_operativo or ''} {empleado.area or ''}".upper()
        requiere = (
            nombre in nombres_direccion
            or any(nombre.startswith(item) for item in nombres_direccion if len(item) > 5)
            or (
                departamento in deps_direccion
                and (
                    any(keyword in puesto for keyword in puesto_keywords)
                    or departamento in {"COMPRAS", "LOGISTICA"} and not empleado.jefe_directo_id
                )
            )
        )
        if requiere:
            permiso.requiere_direccion = True
            permiso.estado_direccion = "pendiente"
            permiso.save(update_fields=["requiere_direccion", "estado_direccion"])


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_organizacion_departamento_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permisosalida',
            name='autorizado_direccion_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_autorizados_direccion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisosalida',
            name='estado_direccion',
            field=models.CharField(choices=[('no_requiere', 'No requiere Dirección'), ('pendiente', 'Pendiente Dirección'), ('autorizado', 'Autorizado por Dirección'), ('rechazado', 'Rechazado por Dirección')], default='no_requiere', max_length=16),
        ),
        migrations.AddField(
            model_name='permisosalida',
            name='fecha_autorizacion_direccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisosalida',
            name='requiere_direccion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento_origen',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40),
        ),
        migrations.RunPython(clasificar_permisos_direccion, migrations.RunPython.noop),
    ]
