# Generated by Django 5.0.1 on 2026-05-27 05:09

from django.db import migrations, models


def seed_bonos_esquemas(apps, schema_editor):
    BonoEsquema = apps.get_model("rrhh", "BonoEsquema")
    Empleado = apps.get_model("rrhh", "Empleado")
    ventas, _ = BonoEsquema.objects.get_or_create(
        codigo="VENTAS",
        defaults={
            "nombre": "Ventas",
            "departamento": "VENTAS",
            "area": "VENTAS",
            "descripcion": "Esquema base usado por el módulo de bonos de ventas.",
        },
    )
    produccion, _ = BonoEsquema.objects.get_or_create(
        codigo="PRODUCCION",
        defaults={
            "nombre": "Producción",
            "departamento": "PRODUCCION",
            "area": "PRODUCCION",
            "descripcion": "Esquema base usado por el módulo de bonos de producción.",
        },
    )
    for empleado in Empleado.objects.filter(participa_bonos_ventas=True).iterator():
        empleado.bonos_esquemas.add(ventas)
    for empleado in Empleado.objects.filter(participa_bonos_produccion=True).iterator():
        empleado.bonos_esquemas.add(produccion)


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_permisos_direccion_autorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonoEsquema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('departamento', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('area', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Esquema de bono',
                'verbose_name_plural': 'Esquemas de bono',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='bonos_esquemas',
            field=models.ManyToManyField(blank=True, related_name='empleados', to='rrhh.bonoesquema'),
        ),
        migrations.RunPython(seed_bonos_esquemas, migrations.RunPython.noop),
    ]
