# Generated by Django 5.0.1 on 2026-05-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def poblar_jefe_directo_horas_extra(apps, schema_editor):
    HoraExtra = apps.get_model("rrhh", "HoraExtra")
    Empleado = apps.get_model("rrhh", "Empleado")
    empleados = (
        Empleado.objects.select_related("jefe_directo__usuario_erp")
        .filter(jefe_directo__usuario_erp__isnull=False)
        .values_list("id", "jefe_directo__usuario_erp_id")
    )
    jefe_por_empleado = {empleado_id: user_id for empleado_id, user_id in empleados}
    for hora_extra in HoraExtra.objects.filter(jefe_directo__isnull=True).only("id", "empleado_id"):
        jefe_user_id = jefe_por_empleado.get(hora_extra.empleado_id)
        if jefe_user_id:
            HoraExtra.objects.filter(pk=hora_extra.pk).update(jefe_directo_id=jefe_user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_bonos_esquemas_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='fecha_autorizacion_jefe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_extra_por_autorizar', to=settings.AUTH_USER_MODEL, verbose_name='Jefe directo / autorizador'),
        ),
        migrations.RunPython(poblar_jefe_directo_horas_extra, migrations.RunPython.noop),
    ]
