# Generated by Django 5.0.1 on 2026-05-28 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_vacantes_solicitud(apps, schema_editor):
    VacanteRRHH = apps.get_model("rrhh", "VacanteRRHH")
    VacanteMovimiento = apps.get_model("rrhh", "VacanteMovimiento")
    for vacante in VacanteRRHH.objects.order_by("id"):
        update_fields = []
        if not vacante.folio:
            fecha = vacante.fecha_solicitada or django.utils.timezone.localdate()
            base = f"VAC-{fecha.strftime('%y%m')}"
            folio = f"{base}-{vacante.id:04d}"
            suffix = 1
            while VacanteRRHH.objects.filter(folio=folio).exclude(pk=vacante.pk).exists():
                suffix += 1
                folio = f"{base}-{vacante.id:04d}-{suffix}"
            vacante.folio = folio[:20]
            update_fields.append("folio")
        if not vacante.solicitado_por_id and vacante.creado_por_id:
            vacante.solicitado_por_id = vacante.creado_por_id
            update_fields.append("solicitado_por")
        if not vacante.cantidad_solicitada:
            vacante.cantidad_solicitada = 1
            update_fields.append("cantidad_solicitada")
        if update_fields:
            vacante.save(update_fields=update_fields)
        if not VacanteMovimiento.objects.filter(vacante_id=vacante.id).exists():
            VacanteMovimiento.objects.create(
                vacante_id=vacante.id,
                estado_anterior="",
                estado_nuevo=vacante.estado,
                actor_id=vacante.creado_por_id,
                comentario="Registro histórico migrado a flujo de solicitud.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificacion_tipo'),
        ('rrhh', '0012_horaextra_fecha_autorizacion_jefe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanterrhh',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='cantidad_solicitada',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='departamento',
            field=models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='fecha_necesaria',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='fecha_validacion_rrhh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='folio',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='motivo_solicitud',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='prioridad',
            field=models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_rrhh', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='tipo_solicitud',
            field=models.CharField(choices=[('reemplazo', 'Reemplazo'), ('nueva_posicion', 'Nueva posición'), ('temporal', 'Temporal')], default='reemplazo', max_length=20),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='validado_rrhh_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_validadas_rrhh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacanterrhh',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente Dirección'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=24),
        ),
        migrations.CreateModel(
            name='VacanteMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=24)),
                ('estado_nuevo', models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente Dirección'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], max_length=24)),
                ('comentario', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='rrhh.vacanterrhh')),
            ],
            options={
                'verbose_name': 'Movimiento de vacante',
                'verbose_name_plural': 'Movimientos de vacante',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VacanteCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobertura', models.DateField(default=django.utils.timezone.localdate)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacantes_cobertura', to='rrhh.empleado')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='rrhh.vacanterrhh')),
            ],
            options={
                'verbose_name': 'Cobertura de vacante',
                'verbose_name_plural': 'Coberturas de vacante',
                'ordering': ['fecha_cobertura', 'id'],
                'unique_together': {('vacante', 'empleado')},
            },
        ),
        migrations.RunPython(backfill_vacantes_solicitud, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vacanterrhh',
            name='folio',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
