# Generated by Django 5.0.1 on 2026-05-28 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_vacanterrhh_autorizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacanterrhh',
            name='autorizador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_por_autorizar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='requiere_direccion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vacanterrhh',
            name='tipo_autorizacion',
            field=models.CharField(choices=[('jefe_directo', 'Jefe directo'), ('direccion_general', 'Dirección General')], db_index=True, default='jefe_directo', max_length=24),
        ),
        migrations.AlterField(
            model_name='vacantemovimiento',
            name='estado_nuevo',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente autorización'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], max_length=24),
        ),
        migrations.AlterField(
            model_name='vacanterrhh',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente autorización'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=24),
        ),
    ]
