# Generated by Django 5.0.1 on 2026-05-28 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0014_vacanterrhh_autorizador_asignado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantemovimiento',
            name='estado_nuevo',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente autorización'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('devuelta_correccion', 'Devuelta a corrección'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], max_length=24),
        ),
        migrations.AlterField(
            model_name='vacanterrhh',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('revision_rrhh', 'En revisión RRHH'), ('pendiente_direccion', 'Pendiente autorización'), ('autorizada', 'Autorizada'), ('reclutamiento', 'En reclutamiento'), ('cubierta', 'Cubierta'), ('pausada', 'Pausada'), ('devuelta_correccion', 'Devuelta a corrección'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=24),
        ),
        migrations.CreateModel(
            name='VacanteSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('comentario', 'Comentario'), ('busqueda', 'Búsqueda'), ('contacto', 'Contacto'), ('entrevista', 'Entrevista'), ('prueba', 'Prueba'), ('oferta', 'Oferta'), ('contratado', 'Contratado'), ('descartado', 'Descartado')], default='comentario', max_length=20)),
                ('candidato', models.CharField(blank=True, default='', max_length=180)),
                ('comentario', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='rrhh.vacanterrhh')),
            ],
            options={
                'verbose_name': 'Seguimiento de vacante',
                'verbose_name_plural': 'Seguimientos de vacante',
                'ordering': ['-fecha', '-creado_en', '-id'],
            },
        ),
    ]
