# Generated by Django 5.0.1 on 2026-06-04 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0015_alter_vacantemovimiento_estado_nuevo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cuenta_clabe',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_cuenta',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacanteseguimiento',
            name='etapa',
            field=models.CharField(choices=[('postulante', 'Candidatos recibidos'), ('entrevista_tel', '1ra entrevista (telefónica)'), ('filtro', 'Filtro / preselección'), ('entrevista_pres', '2da entrevista (presencial)'), ('seleccionado', 'Candidato seleccionado'), ('documentos', 'Solicitud de documentos'), ('prueba', 'Periodo de prueba'), ('contratado', 'Contratado'), ('descartado', 'Descartado'), ('comentario', 'Nota / comentario'), ('busqueda', 'Búsqueda (legacy)'), ('contacto', 'Contacto (legacy)'), ('entrevista', 'Entrevista (legacy)'), ('oferta', 'Oferta (legacy)')], default='comentario', max_length=20),
        ),
        migrations.CreateModel(
            name='EmpleadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nss', 'NSS'), ('fiscal', 'Constancia de situación fiscal'), ('ine', 'INE'), ('curp', 'CURP'), ('acta', 'Acta de nacimiento'), ('domicilio', 'Comprobante de domicilio'), ('estudios', 'Constancia de estudios'), ('carta_laboral', 'Carta laboral'), ('banco', 'Cuenta bancaria'), ('otro', 'Otro')], db_index=True, max_length=20)),
                ('archivo', models.FileField(blank=True, help_text='PDF o imagen del documento', null=True, upload_to='rrhh/documentos/')),
                ('valor_texto', models.CharField(blank=True, default='', help_text='NSS, CURP, RFC u otro dato de texto', max_length=200)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rrhh.empleado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de empleado',
                'verbose_name_plural': 'Documentos de empleados',
                'ordering': ['empleado', 'tipo', '-creado_en'],
            },
        ),
    ]
