# Generated by Django 5.0.1 on 2026-06-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_documentos_empleado_pipeline_vacantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaempleado',
            name='minutos_comida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asistenciaempleado',
            name='regreso_comida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistenciaempleado',
            name='salida_comida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
