# Generated by Django 5.0.1 on 2026-06-05 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0016_documentos_empleado_pipeline_vacantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanteseguimiento',
            name='etapa',
            field=models.CharField(choices=[('entrevista_pres', 'Entrevista presencial'), ('seleccionado', 'Candidato seleccionado'), ('documentos', 'Solicitud de documentos'), ('prueba', 'Periodo de prueba'), ('contratado', 'Contratado'), ('descartado', 'Descartado'), ('comentario', 'Nota'), ('postulante', 'Candidatos recibidos (legacy)'), ('entrevista_tel', '1ra entrevista tel. (legacy)'), ('filtro', 'Filtro preselección (legacy)'), ('busqueda', 'Búsqueda (legacy)'), ('contacto', 'Contacto (legacy)'), ('entrevista', 'Entrevista (legacy)'), ('oferta', 'Oferta (legacy)')], default='comentario', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidatoVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fuente', models.CharField(choices=[('referencia', 'Referencia interna'), ('bolsa', 'Bolsa de trabajo'), ('redes', 'Redes sociales'), ('otro', 'Otro')], default='referencia', max_length=20)),
                ('etapa_actual', models.CharField(choices=[('entrevista_pres', 'Entrevista presencial'), ('seleccionado', 'Candidato seleccionado'), ('documentos', 'Solicitud de documentos'), ('prueba', 'Periodo de prueba'), ('contratado', 'Contratado'), ('descartado', 'Descartado')], default='entrevista_pres', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatura', to='rrhh.empleado')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='rrhh.vacanterrhh')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['etapa_actual', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='vacanteseguimiento',
            name='candidato_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='rrhh.candidatovacante'),
        ),
    ]
