# Generated by Django 5.0.1 on 2026-06-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0019_empleado_identidad_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nivel_organizacional',
            field=models.CharField(blank=True, choices=[('COLABORADOR', 'Colaborador'), ('ENCARGADA', 'Encargada / encargado'), ('SUPERVISION', 'Supervisión'), ('JEFATURA', 'Jefatura'), ('DIRECCION', 'Dirección')], db_index=True, default='', max_length=20),
        ),
    ]
