# Generated by Django 5.0.1 on 2026-06-09 02:43

from django.db import migrations, models


FUNCIONES_BASE = (
    ("HORNOS", "Hornos", "PRODUCCION", "PRODUCCION", "HORNOS", "COLABORADOR"),
    ("EMBETUNADO", "Embetunado", "PRODUCCION", "PRODUCCION", "EMBETUNADO", "COLABORADOR"),
    ("ARMADO", "Armado", "PRODUCCION", "PRODUCCION", "ARMADO", "COLABORADOR"),
    ("CRUCERO", "Crucero", "PRODUCCION", "PRODUCCION", "CRUCERO", "COLABORADOR"),
    ("ENVIO A SUCURSAL", "Envío a sucursal", "LOGISTICA", "PRODUCCION", "ENVIO_SUCURSAL", "COLABORADOR"),
    ("CAJAS", "Cajas", "VENTAS", "VENTAS", "CAJAS", "COLABORADOR"),
    ("AUXILIAR CAJAS", "Auxiliar cajas", "VENTAS", "VENTAS", "AUXILIAR_CAJAS", "COLABORADOR"),
    ("CALL CENTER", "Call center", "VENTAS", "VENTAS", "CALL_CENTER", "COLABORADOR"),
    ("REPARTIDORES", "Repartidores", "LOGISTICA", "VENTAS", "REPARTIDOR", "COLABORADOR"),
    ("COMPRAS", "Compras", "COMPRAS", "COMPRAS", "COMPRAS", "COLABORADOR"),
    ("ALMACEN", "Almacén", "ADMINISTRACION", "ADMINISTRACION", "ALMACEN", "COLABORADOR"),
    ("LIMPIEZA", "Limpieza / afanadoras", "ADMINISTRACION", "ADMINISTRACION", "LIMPIEZA", "COLABORADOR"),
    ("AUXILIAR CONTABLE", "Auxiliar contable", "ADMINISTRACION", "ADMINISTRACION", "AUXILIAR_CONTABLE", "COLABORADOR"),
    ("RRHH", "Recursos Humanos", "RRHH", "RRHH", "RRHH", "COLABORADOR"),
    ("MANTENIMIENTO", "Mantenimiento", "MANTENIMIENTO", "MANTENIMIENTO", "MANTENIMIENTO", "COLABORADOR"),
    ("MARKETING", "Marketing externo", "MARKETING", "MARKETING", "MARKETING", "COLABORADOR"),
)


def seed_funciones_operativas(apps, schema_editor):
    CatalogoFuncionOperativa = apps.get_model("rrhh", "CatalogoFuncionOperativa")
    for codigo, etiqueta, departamento_origen, departamento_actual, puesto_operativo, nivel in FUNCIONES_BASE:
        CatalogoFuncionOperativa.objects.update_or_create(
            codigo=codigo,
            defaults={
                "etiqueta": etiqueta,
                "departamento_origen": departamento_origen,
                "departamento_actual": departamento_actual,
                "puesto_operativo": puesto_operativo,
                "nivel_organizacional": nivel,
                "activo": True,
                "sistema": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0021_permisosalida_cambio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoFuncionOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=80, unique=True)),
                ('etiqueta', models.CharField(max_length=120)),
                ('departamento_origen', models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40)),
                ('departamento_actual', models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], db_index=True, default='', max_length=40)),
                ('puesto_operativo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('nivel_organizacional', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('ENCARGADA', 'Encargada / encargado'), ('SUPERVISION', 'Supervisión'), ('JEFATURA', 'Jefatura'), ('DIRECCION', 'Dirección')], db_index=True, default='COLABORADOR', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('sistema', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Función operativa',
                'verbose_name_plural': 'Funciones operativas',
                'ordering': ['departamento_actual', 'etiqueta', 'codigo'],
            },
        ),
        migrations.RunPython(seed_funciones_operativas, migrations.RunPython.noop),
    ]
