# Generated by Django 5.0.1 on 2026-06-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_vacaciones_reglamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaPendienteEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('convertida', 'Convertida a empleado'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('sucursal', models.CharField(blank=True, default='', max_length=120)),
                ('departamento', models.CharField(blank=True, choices=[('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('PRODUCCION', 'Producción'), ('RRHH', 'Recursos Humanos'), ('COMPRAS', 'Compras'), ('MANTENIMIENTO', 'Mantenimiento'), ('LOGISTICA', 'Logística'), ('MARKETING', 'Marketing')], default='', max_length=40)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('puesto', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_ingreso_sugerida', models.DateField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('convertida_en', models.DateTimeField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_pendientes', to='rrhh.candidatovacante')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_pendientes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_desde_vacante', to='rrhh.empleado')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altas_pendientes', to='rrhh.vacanterrhh')),
            ],
            options={
                'verbose_name': 'Alta pendiente de empleado',
                'verbose_name_plural': 'Altas pendientes de empleados',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='altapendienteempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('candidato',), name='rrhh_alta_pendiente_unica_por_candidato'),
        ),
    ]
