# Generated by Django 5.0.1 on 2026-06-10 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0023_vacaciones_reglamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('uso_tolerancia', 'Uso de tolerancia'), ('retardo', 'Retardo'), ('retardo_tolerancia', 'Retardo por tolerancia recurrente'), ('falta', 'Falta'), ('falta_retardos', 'Falta por retardos'), ('jornada_incompleta', 'Jornada incompleta'), ('hora_extra_pendiente', 'Hora extra pendiente'), ('aviso_baja_faltas', 'Aviso por faltas'), ('posible_rescision', 'Posible rescision por faltas')], db_index=True, max_length=32)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliado', 'Conciliado'), ('resuelto', 'Resuelto')], db_index=True, default='pendiente', max_length=16)),
                ('severidad', models.CharField(choices=[('info', 'Informativa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=12)),
                ('minutos', models.IntegerField(default=0)),
                ('goce_sueldo', models.BooleanField(blank=True, null=True)),
                ('ventana_inicio', models.DateField(blank=True, null=True)),
                ('ventana_fin', models.DateField(blank=True, null=True)),
                ('conteo_retardos_15d', models.PositiveSmallIntegerField(default=0)),
                ('conteo_faltas_30d', models.PositiveSmallIntegerField(default=0)),
                ('detalle', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='rrhh.asistenciaempleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_asistencia', to='rrhh.empleado')),
                ('hora_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asistencia', to='rrhh.horaextra')),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asistencia', to='rrhh.permisosalida')),
                ('solicitud_vacaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asistencia', to='rrhh.solicitudvacaciones')),
            ],
            options={
                'verbose_name': 'Incidencia de asistencia',
                'verbose_name_plural': 'Incidencias de asistencia',
                'ordering': ['-fecha', 'empleado__nombre', 'tipo'],
                'unique_together': {('empleado', 'fecha', 'tipo')},
            },
        ),
    ]
