# Generated by Django 5.0.1 on 2026-06-11 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_incidenciaasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciaasistencia',
            name='editado_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidenciaasistencia',
            name='tipo',
            field=models.CharField(choices=[('uso_tolerancia', 'Uso de tolerancia'), ('retardo', 'Retardo'), ('retardo_tolerancia', 'Retardo por tolerancia recurrente'), ('falta', 'Falta'), ('falta_retardos', 'Falta por retardos'), ('jornada_incompleta', 'Jornada incompleta'), ('hora_extra_pendiente', 'Hora extra pendiente'), ('comida_excedida', 'Comida excedida'), ('suspension', 'Suspensión'), ('aviso_baja_faltas', 'Aviso por faltas'), ('baja_faltas', 'Baja por faltas')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='IncidenciaAsistenciaBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=80)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='rrhh.incidenciaasistencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de incidencia de asistencia',
                'verbose_name_plural': 'Bitácora de incidencias de asistencia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
