# Generated by Django 5.0.1 on 2026-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0024_altapendienteempleado_and_more'),
        ('rrhh', '0026_suspensionempleado'),
    ]

    operations = [
    ]
