# Generated by Django 5.0.1 on 2026-06-15 18:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0028_horaextra_cancelado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenominaEquivalenciaCONTPAQi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento_erp', models.CharField(db_index=True, max_length=32, unique=True)),
                ('clave_contpaqi', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=180)),
                ('aplica_valor', models.BooleanField(default=False)),
                ('aplica_horas', models.BooleanField(default=False)),
                ('aplica_importe', models.BooleanField(default=False)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equivalencia CONTPAQi prenomina',
                'verbose_name_plural': 'Equivalencias CONTPAQi prenomina',
                'ordering': ['tipo_movimiento_erp'],
            },
        ),
        migrations.CreateModel(
            name='AjusteAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo_ajuste', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('salida_comida', 'Salida comida'), ('regreso_comida', 'Regreso comida'), ('turno', 'Turno'), ('observacion', 'Observacion')], db_index=True, max_length=24)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('APLICADO', 'Aplicado')], db_index=True, default='PENDIENTE', max_length=16)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_propuestos', models.JSONField(blank=True, default=dict)),
                ('valores_aplicados', models.JSONField(blank=True, default=dict)),
                ('motivo', models.TextField()),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_asistencia_aplicados', to=settings.AUTH_USER_MODEL)),
                ('asistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='rrhh.asistenciaempleado')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_asistencia_autorizados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_asistencia', to='rrhh.empleado')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_asistencia_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de asistencia',
                'verbose_name_plural': 'Ajustes de asistencia',
                'ordering': ['-fecha', 'empleado__nombre', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrenominaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=40, unique=True)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('fecha_corte', models.DateField(db_index=True)),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('RANGO', 'Rango manual')], default='QUINCENAL', max_length=20)),
                ('sucursal', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('LISTO', 'Listo'), ('EXPORTADO', 'Exportado'), ('CERRADO', 'Cerrado')], db_index=True, default='BORRADOR', max_length=20)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prenomina_cortes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corte de prenomina',
                'verbose_name_plural': 'Cortes de prenomina',
                'ordering': ['-fecha_fin', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrenominaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo_movimiento_erp', models.CharField(choices=[('FALTA', 'Falta'), ('SUSPENSION', 'Suspension'), ('HORA_EXTRA', 'Hora extra'), ('INCAPACIDAD', 'Incapacidad')], db_index=True, max_length=32)),
                ('clave_contpaqi', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE_CONFIGURACION', 'Pendiente configuracion'), ('LISTO', 'Listo'), ('BLOQUEADO', 'Bloqueado'), ('EXPORTADO', 'Exportado')], db_index=True, default='PENDIENTE_CONFIGURACION', max_length=32)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuente', models.CharField(blank=True, default='', max_length=80)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='rrhh.prenominacorte')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_prenomina', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Movimiento de prenomina',
                'verbose_name_plural': 'Movimientos de prenomina',
                'ordering': ['empleado__nombre', 'fecha', 'tipo_movimiento_erp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrenominaEmpleadoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_periodo', models.PositiveSmallIntegerField(default=0)),
                ('dias_laborables', models.PositiveSmallIntegerField(default=0)),
                ('dias_no_laborados_pre_ingreso', models.PositiveSmallIntegerField(default=0)),
                ('dias_asistencia', models.PositiveSmallIntegerField(default=0)),
                ('faltas', models.PositiveSmallIntegerField(default=0)),
                ('retardos', models.PositiveSmallIntegerField(default=0)),
                ('suspensiones', models.PositiveSmallIntegerField(default=0)),
                ('permisos', models.PositiveSmallIntegerField(default=0)),
                ('vacaciones', models.PositiveSmallIntegerField(default=0)),
                ('horas_extra_autorizadas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('ajustes_pendientes', models.PositiveSmallIntegerField(default=0)),
                ('alertas_bloqueantes', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('LISTO', 'Listo'), ('REVISAR', 'Revisar'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='LISTO', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='rrhh.prenominacorte')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_prenomina', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Resumen de empleado en prenomina',
                'verbose_name_plural': 'Resumenes de empleados en prenomina',
                'ordering': ['empleado__nombre', 'id'],
                'unique_together': {('corte', 'empleado')},
            },
        ),
    ]
