# Generated by Django 5.0.1 on 2026-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0029_prenominaequivalenciacontpaqi_ajusteasistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenominamovimiento',
            name='fuente_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='prenominamovimiento',
            name='fuente_modelo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='prenominamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('fuente_id__gt', ''), ('fuente_modelo__gt', '')), fields=('corte', 'fuente_modelo', 'fuente_id', 'tipo_movimiento_erp'), name='rrhh_prenomina_movimiento_fuente_unica'),
        ),
    ]
