# Generated by Django 5.0.1 on 2026-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0030_prenominamovimiento_fuente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteasistencia',
            name='comentario_autorizacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
