# Generated by Django 5.0.1 on 2026-06-17 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0031_ajusteasistencia_comentario_autorizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prenominaempleadoresumen',
            name='incapacidades',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IncapacidadEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('enfermedad_general', 'Enfermedad general'), ('riesgo_trabajo', 'Riesgo de trabajo'), ('maternidad', 'Maternidad'), ('otro', 'Otro')], db_index=True, default='enfermedad_general', max_length=24)),
                ('folio', models.CharField(blank=True, default='', max_length=80)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], db_index=True, default='activa', max_length=12)),
                ('notas', models.TextField(blank=True, default='')),
                ('comentario_cancelacion', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incapacidades', to='rrhh.empleado')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incapacidades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='incapacidadempleado',
            constraint=models.UniqueConstraint(condition=models.Q(('folio', ''), _negated=True), fields=('empleado', 'folio'), name='rrhh_incapacidad_folio_unico_empleado'),
        ),
    ]
