# Generated by Django 5.0.1 on 2026-06-17 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0032_incapacidad_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incapacidadempleado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='rrhh_incapacidad_fecha_fin_gte_inicio'),
        ),
    ]
