# Generated by Django 5.0.1 on 2026-07-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('rrhh', '0033_incapacidad_fecha_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sucursal_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.sucursal'),
        ),
    ]
