# Generated by Django 5.0.1 on 2026-07-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0035_backfill_empleado_sucursal_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniversario', models.DateField()),
                ('fecha_limite', models.DateField()),
                ('antiguedad_anios', models.PositiveSmallIntegerField()),
                ('dias_generados', models.DecimalField(decimal_places=2, max_digits=6)),
                ('origen', models.CharField(default='calculado', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_vacacionales', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Periodo vacacional',
                'verbose_name_plural': 'Periodos vacacionales',
                'ordering': ['aniversario', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionGoceVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('consumida', 'Consumida'), ('liberada', 'Liberada'), ('revertida', 'Revertida')], db_index=True, max_length=16)),
                ('excepcion_fifo', models.BooleanField(default=False)),
                ('motivo_excepcion', models.CharField(blank=True, default='', max_length=220)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_goce', to='rrhh.solicitudvacaciones')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_goce', to='rrhh.periodovacacional')),
            ],
            options={
                'verbose_name': 'Aplicación de goce vacacional',
                'verbose_name_plural': 'Aplicaciones de goce vacacional',
                'ordering': ['periodo__aniversario', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodovacacional',
            constraint=models.UniqueConstraint(fields=('empleado', 'aniversario'), name='uq_periodo_vac_aniversario'),
        ),
        migrations.AddConstraint(
            model_name='periodovacacional',
            constraint=models.CheckConstraint(check=models.Q(('dias_generados__gte', 0)), name='ck_periodo_vac_dias_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='aplicaciongocevacaciones',
            constraint=models.UniqueConstraint(fields=('solicitud', 'periodo'), name='uq_aplicacion_goce_periodo'),
        ),
        migrations.AddConstraint(
            model_name='aplicaciongocevacaciones',
            constraint=models.CheckConstraint(check=models.Q(('dias__gt', 0)), name='ck_aplicacion_goce_dias_pos'),
        ),
    ]
