# Generated by Django 5.0.1 on 2026-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0036_periodo_vacacional_aplicacion_goce'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='exento_checador',
            field=models.BooleanField(default=False, help_text='No genera falta automática cuando no hay checada (remoto, oficina sin checador).'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='exento_checador_motivo',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
