# Generated by Django 5.0.1 on 2026-07-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0038_backfill_asistencia_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoHikCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(db_index=True, max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('codigo_externo', models.CharField(db_index=True, max_length=80)),
                ('ocurrido_en', models.DateTimeField(db_index=True)),
                ('tipo_evento', models.CharField(max_length=20)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('estado', models.CharField(choices=[('received', 'Recibido'), ('accepted', 'Aceptado'), ('deferred', 'Diferido'), ('rejected', 'Rechazado')], db_index=True, default='received', max_length=20)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('retryable', models.BooleanField(default=False)),
                ('projection_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('effects_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=1)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_hik_cloud', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Evento crudo de Hik-Connect',
                'verbose_name_plural': 'Eventos crudos de Hik-Connect',
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventohikcloud',
            constraint=models.UniqueConstraint(fields=('fuente', 'event_id'), name='uniq_evento_hik_cloud_fuente_event_id'),
        ),
    ]
