# Generated by Django 5.0.1 on 2026-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0039_eventohikcloud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoIntegracionHik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='hikconnect_cloud', max_length=40, unique=True)),
                ('estado', models.CharField(choices=[('healthy', 'Al día'), ('recovering', 'Recuperándose'), ('action_required', 'Requiere acción')], db_index=True, default='recovering', max_length=24)),
                ('ultimo_ciclo_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_exito_en', models.DateTimeField(blank=True, null=True)),
                ('ultima_marca_cloud_en', models.DateTimeField(blank=True, null=True)),
                ('outbox_pending', models.PositiveIntegerField(default=0)),
                ('identity_deferred', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('incident_key', models.CharField(blank=True, default='', max_length=128)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('reportado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de integración Hik-Connect',
                'verbose_name_plural': 'Estados de integración Hik-Connect',
            },
        ),
    ]
