# Generated by Django 5.0.1 on 2026-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0040_estadointegracionhik'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventohikcloud',
            name='conflict_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventohikcloud',
            name='effects_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventohikcloud',
            name='last_conflict_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='eventohikcloud',
            name='projection_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
