# Generated by Django 5.0.1 on 2026-09-10 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0043_permisosalida_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncapacidadCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('editar', 'Corrección'), ('cancelar', 'Cancelación')], db_index=True, max_length=12)),
                ('motivo', models.TextField()),
                ('cambios', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('incapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='rrhh.incapacidadempleado')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incapacidades_cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de incapacidad',
                'verbose_name_plural': 'Cambios de incapacidades',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
