# Generated by Django 5.0.1 on 2026-09-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0044_incapacidadcambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidadcambio',
            name='empleado_nombre',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='incapacidadcambio',
            name='resumen',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='incapacidadcambio',
            name='accion',
            field=models.CharField(choices=[('editar', 'Corrección'), ('cancelar', 'Cancelación'), ('eliminar', 'Eliminación')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='incapacidadcambio',
            name='incapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios', to='rrhh.incapacidadempleado'),
        ),
    ]
