# Generated by Django 5.0.1 on 2026-09-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cumpleanos_activos_y_avisos'),
        ('rrhh', '0045_incapacidadcambio_empleado_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AvisoCumpleanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hoy', 'Hoy'), ('anticipado', 'Tres días antes'), ('semanal', 'Resumen semanal')], max_length=12)),
                ('fecha_referencia', models.DateField()),
                ('estado_correo', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('enviado', 'Aceptado por correo'), ('fallido', 'Falló'), ('incierto', 'Resultado incierto'), ('sin_contacto', 'Sin correo de trabajo'), ('omitido', 'Omitido')], default='pendiente', max_length=12)),
                ('correo_destino', models.EmailField(blank=True, default='', max_length=254)),
                ('error_correo', models.CharField(blank=True, default='', max_length=400)),
                ('referencia_correo', models.CharField(blank=True, default='', max_length=200)),
                ('clave_correo', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='avisocumpleanos',
            constraint=models.UniqueConstraint(fields=('usuario', 'tipo', 'fecha_referencia'), name='rrhh_cumple_aviso_unico'),
        ),
    ]
