# Generated by Django 5.0.1 on 2026-09-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0046_cumpleanos_activos_y_avisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='modalidad_marcaje',
            field=models.CharField(choices=[('AUTO', 'Automática según puesto y fuente'), ('CUATRO_MARCAS', 'Cuatro marcas'), ('DOS_MARCAS', 'Dos marcas'), ('RUTA', 'Trabajo en ruta')], db_index=True, default='AUTO', help_text='Define las marcas esperadas; Automática usa puesto y fuente de asistencia.', max_length=20),
        ),
    ]
