# Generated by Django 5.0.1 on 2026-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0047_empleado_modalidad_marcaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciaasistencia',
            name='tipo',
            field=models.CharField(choices=[('uso_tolerancia', 'Uso de tolerancia'), ('retardo', 'Retardo'), ('retardo_tolerancia', 'Retardo por tolerancia recurrente'), ('falta', 'Falta'), ('falta_retardos', 'Falta por retardos'), ('jornada_incompleta', 'Jornada incompleta'), ('hora_extra_pendiente', 'Hora extra pendiente'), ('extra_no_calculable', 'Hora extra no calculable'), ('marcaje_incompleto', 'Marcaje incompleto'), ('comida_excedida', 'Comida excedida'), ('suspension', 'Suspensión'), ('aviso_baja_faltas', 'Aviso por faltas'), ('baja_faltas', 'Baja por faltas')], db_index=True, max_length=32),
        ),
    ]
