# Generated by Django 5.0.1 on 2026-09-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0048_incidencia_asistencia_tipos_marcaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='deteccion_por_checada',
            field=models.BooleanField(default=True, help_text='Permite inferir este turno por la hora de entrada cuando no hay horario asignado al empleado.'),
        ),
        migrations.CreateModel(
            name='AsignacionTurnoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('proteger_reingesta_historica', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_asignados', to='rrhh.empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_empleado', to='rrhh.turno')),
            ],
            options={
                'ordering': ['empleado__nombre', '-fecha_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionturnoempleado',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_inicio'), name='rrhh_turno_empleado_inicio_unico'),
        ),
        migrations.AddConstraint(
            model_name='asignacionturnoempleado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='rrhh_turno_empleado_rango_valido'),
        ),
    ]
