# Generated by Django 5.0.1 on 2026-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0049_turno_deteccion_por_checada_asignacionturnoempleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='ajuste_autorizacion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
