# Generated by Django 5.0.1 on 2026-09-24 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0050_horaextra_ajuste_justificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=240)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionJornadaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('proteger_reingesta_historica', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_empleado_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas_asignadas', to='rrhh.empleado')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='rrhh.jornadasemanal')),
            ],
            options={
                'ordering': ['-fecha_inicio', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='JornadaSemanalDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='rrhh.jornadasemanal')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jornadas_dia', to='rrhh.turno')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asignacionjornadaempleado',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha_inicio'), name='rrhh_jornada_empleado_inicio_unico'),
        ),
        migrations.AddConstraint(
            model_name='asignacionjornadaempleado',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='rrhh_jornada_empleado_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='jornadasemanaldia',
            constraint=models.UniqueConstraint(fields=('jornada', 'dia_semana'), name='rrhh_jornada_dia_unico'),
        ),
        migrations.AddConstraint(
            model_name='jornadasemanaldia',
            constraint=models.CheckConstraint(check=models.Q(('dia_semana__gte', 0), ('dia_semana__lte', 6)), name='rrhh_jornada_dia_valido'),
        ),
    ]
