# Generated by Django 5.0.1 on 2026-09-30 21:24

from django.db import migrations, models


def proteger_historico_horas_extra(apps, schema_editor):
    HoraExtra = apps.get_model("rrhh", "HoraExtra")
    HoraExtra.objects.exclude(estado="pendiente").update(
        requiere_aplicacion_prenomina=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0052_nominalinea_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='requiere_aplicacion_prenomina',
            field=models.BooleanField(db_index=True, default=True, help_text='Incluye esta solicitud en el control de cortes de prenómina.'),
        ),
        migrations.RunPython(
            proteger_historico_horas_extra,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='prenominamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('fuente_id__gt', ''), ('fuente_modelo', 'rrhh.HoraExtra'), ('tipo_movimiento_erp', 'HORA_EXTRA')), fields=('fuente_modelo', 'fuente_id', 'tipo_movimiento_erp'), name='rrhh_prenomina_hora_extra_fuente_unica'),
        ),
    ]
