CHECKLIST_BASE = [
    ("orden_limpieza", "Orden y limpieza", "Pisos limpios, lustrados y libres de mal olor."),
    ("orden_limpieza", "Orden y limpieza", "Cristales limpios y sin marcas."),
    ("orden_limpieza", "Orden y limpieza", "Paredes limpias y sin manchas."),
    ("orden_limpieza", "Orden y limpieza", "Botes de basura limpios y libres de olores."),
    ("orden_limpieza", "Orden y limpieza", "Vitrinas limpias y libres de malos olores."),
    ("orden_limpieza", "Orden y limpieza", "Refrigeradores limpios y libres de malos olores."),
    ("orden_limpieza", "Orden y limpieza", "Puntos de venta limpios y sin polvo."),
    ("equipos", "Funcionamiento de equipos", "Caja, computadora, impresora y terminales funcionan."),
    ("equipos", "Funcionamiento de equipos", "Aires acondicionados funcionan."),
    ("equipos", "Funcionamiento de equipos", "Iluminación enciende y no presenta fallas."),
    ("equipos", "Funcionamiento de equipos", "Teléfonos en función y con línea."),
    ("equipos", "Funcionamiento de equipos", "Internet y videovigilancia funcionando."),
    ("personal", "Personal", "Uniforme limpio y planchado."),
    ("personal", "Personal", "Uñas cortas y limpias."),
    ("personal", "Personal", "Zapatos limpios."),
    ("personal", "Personal", "Cofia y cubrebocas disponibles cuando aplica."),
    ("actividades", "Actividades del día", "Incidencias y sucesos relevantes registrados."),
    ("actividades", "Actividades del día", "Inventarios diarios registrados."),
    ("actividades", "Actividades del día", "Checklists COFEPRIS en proceso."),
    ("actividades", "Actividades del día", "Plan de mantenimiento del día revisado."),
]
