# Generated by Django 5.0.1 on 2026-04-29 21:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('core', '0005_sucursal_fecha_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('equipo', 'Equipo y Maquinaria'), ('instalacion', 'Instalaciones'), ('mobiliario', 'Mobiliario y Decoración'), ('otro', 'Otro')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría de falla',
                'verbose_name_plural': 'Categorías de fallas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica - Operación detenida')], default='media', max_length=10)),
                ('foto_evidencia', models.ImageField(help_text='Foto obligatoria tomada desde cámara del dispositivo', upload_to='fallas/evidencias/%Y/%m/')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('en_revision', 'En revisión'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=15)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor_servicio', models.CharField(blank=True, max_length=200)),
                ('notas_internas', models.TextField(blank=True)),
                ('activo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas', to='activos.activo', verbose_name='Activo relacionado (opcional)')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='fallas.categoriafalla')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Reporte de falla',
                'verbose_name_plural': 'Reportes de fallas',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_anterior', models.CharField(blank=True, max_length=15)),
                ('estatus_nuevo', models.CharField(blank=True, max_length=15)),
                ('comentario', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='fallas.reportefalla')),
            ],
            options={
                'verbose_name': 'Bitácora de falla',
                'verbose_name_plural': 'Bitácora de fallas',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='reportefalla',
            index=models.Index(fields=['sucursal', 'estatus'], name='fallas_repo_sucursa_ed2620_idx'),
        ),
        migrations.AddIndex(
            model_name='reportefalla',
            index=models.Index(fields=['estatus', 'prioridad'], name='fallas_repo_estatus_2aad6a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportefalla',
            index=models.Index(fields=['fecha_reporte'], name='fallas_repo_fecha_r_3b9720_idx'),
        ),
    ]
