# Generated by Django 5.0.1 on 2026-05-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0002_grupos_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='area',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('produccion', 'Producción'), ('general', 'General')], default='general', help_text='Área responsable de dar seguimiento al reporte', max_length=15, verbose_name='Área'),
        ),
    ]
