# Generated by Django 5.0.1 on 2026-06-09 03:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0004_grupos_ventas_produccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaSeguimientoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='fallas/seguimiento/%Y/%m/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='fallas.bitacorafalla')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de seguimiento de falla',
                'verbose_name_plural': 'Evidencias de seguimiento de fallas',
                'ordering': ['creado_en'],
            },
        ),
    ]
