# Generated by Django 5.0.1 on 2026-07-22 15:08

from django.db import migrations, models


def clasificar_reportes_historicos(apps, schema_editor):
    ReporteFalla = apps.get_model('fallas', 'ReporteFalla')
    ReporteFalla.objects.filter(activo_relacionado__isnull=True).update(
        tipo_objetivo='INSTALACION',
        area_instalacion='Sucursal',
    )
    ReporteFalla.objects.filter(foto_evidencia='').update(
        justificacion_sin_foto='Reporte histórico anterior a la evidencia opcional.',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0006_reclasificar_cerrado_como_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='area_instalacion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='justificacion_sin_foto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportefalla',
            name='tipo_objetivo',
            field=models.CharField(choices=[('EQUIPO', 'Equipo registrado'), ('INSTALACION', 'Instalación de sucursal')], default='EQUIPO', max_length=16),
        ),
        migrations.AlterField(
            model_name='reportefalla',
            name='foto_evidencia',
            field=models.ImageField(blank=True, help_text='Foto opcional; si falta debe registrarse una justificación', null=True, upload_to='fallas/evidencias/%Y/%m/'),
        ),
        migrations.RunPython(clasificar_reportes_historicos, migrations.RunPython.noop),
    ]
