# Generated by Django 5.0.1 on 2026-09-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_trazabilidad_mantenimiento'),
        ('core', '0022_conteos_sucursales_access'),
        ('fallas', '0007_objetivo_instalacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefalla',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, help_text='Reporte principal que ya atiende este mismo problema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='fallas.reportefalla', verbose_name='Duplicado de'),
        ),
        migrations.AddIndex(
            model_name='reportefalla',
            index=models.Index(fields=['duplicado_de'], name='fallas_repo_duplica_f2d443_idx'),
        ),
    ]
