from decimal import Decimal

from django.db import migrations, models


CONCEPTOS_BASE = [
    {
        "codigo": "VENTA_EFECTIVO_SUCURSAL",
        "nombre": "Venta en efectivo por sucursal",
        "descripcion": (
            "Depositos de efectivo en ventanilla contra CFDI emitidos al publico "
            "en general por sucursal."
        ),
        "familia": "venta",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "forma_pago_esperada": "01",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["deposito en efectivo", "ventanilla"],
        "evidencia_requerida": ["cfdi_emitido", "sucursal", "fecha_venta", "ficha_deposito"],
        "prioridad": 10,
    },
    {
        "codigo": "VENTA_TARJETA_DEBITO",
        "nombre": "Venta con tarjeta de debito",
        "descripcion": "Depositos de adquirente contra CFDI emitidos con forma de pago 28.",
        "familia": "tarjeta",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "forma_pago_esperada": "28",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["negocios afiliados", "tpv", "debito"],
        "evidencia_requerida": ["cfdi_emitido", "liquidacion_adquirente", "terminal_o_afiliacion"],
        "prioridad": 20,
    },
    {
        "codigo": "VENTA_TARJETA_CREDITO",
        "nombre": "Venta con tarjeta de credito",
        "descripcion": "Depositos de adquirente contra CFDI emitidos con forma de pago 04.",
        "familia": "tarjeta",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "forma_pago_esperada": "04",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["negocios afiliados", "tpv", "credito"],
        "evidencia_requerida": ["cfdi_emitido", "liquidacion_adquirente", "terminal_o_afiliacion"],
        "prioridad": 21,
    },
    {
        "codigo": "VENTA_TARJETA_SERVICIOS",
        "nombre": "Venta con tarjeta de servicios",
        "descripcion": "Depositos de adquirente contra CFDI emitidos con forma de pago 29.",
        "familia": "tarjeta",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "forma_pago_esperada": "29",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["amex", "optblue", "negocios afiliados"],
        "evidencia_requerida": ["cfdi_emitido", "liquidacion_adquirente", "terminal_o_afiliacion"],
        "prioridad": 22,
    },
    {
        "codigo": "COMISION_TPV",
        "nombre": "Comision de terminal bancaria",
        "descripcion": "Cargo por comisiones de adquirente; debe respaldarse con CFDI recibido si existe.",
        "familia": "gasto",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "recibido",
        "requiere_cfdi_recibido": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["comision", "tasas de descuento", "tpv", "optblue"],
        "evidencia_requerida": ["cfdi_recibido", "estado_cuenta", "liquidacion_adquirente"],
        "prioridad": 30,
    },
    {
        "codigo": "IVA_COMISION_TPV",
        "nombre": "IVA de comision bancaria",
        "descripcion": "IVA trasladado por comisiones de adquirente o banco.",
        "familia": "gasto",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "recibido",
        "requiere_cfdi_recibido": True,
        "afecta_iva": True,
        "palabras_clave": ["iva", "comision", "tpv"],
        "evidencia_requerida": ["cfdi_recibido", "estado_cuenta"],
        "prioridad": 31,
    },
    {
        "codigo": "TRANSFERENCIA_CLIENTE_CFDI",
        "nombre": "Transferencia de cliente con CFDI",
        "descripcion": "Pago por transferencia SPEI de cliente contra CFDI emitido.",
        "familia": "transferencia",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "forma_pago_esperada": "03",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["spei", "transferencia", "cliente"],
        "evidencia_requerida": ["cfdi_emitido", "cep", "ordenante", "referencia_bancaria"],
        "prioridad": 40,
    },
    {
        "codigo": "PAGO_PARCIAL_CLIENTE_REP",
        "nombre": "Pago parcial o diferido con REP",
        "descripcion": "Cobro de CFDI PPD que requiere complemento de pago.",
        "familia": "transferencia",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "pago",
        "forma_pago_esperada": "03",
        "requiere_rep": True,
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["spei", "ppd", "complemento de pago"],
        "evidencia_requerida": ["cfdi_emitido_ppd", "rep", "cep"],
        "prioridad": 41,
    },
    {
        "codigo": "ANTICIPO_CLIENTE",
        "nombre": "Anticipo de cliente",
        "descripcion": "Entrada de dinero de cliente pendiente de aplicacion contra pedido o CFDI.",
        "familia": "transferencia",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "emitido",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["anticipo", "apartado", "pedido"],
        "evidencia_requerida": ["pedido", "cfdi_anticipo", "comprobante_pago"],
        "prioridad": 42,
    },
    {
        "codigo": "DEVOLUCION_SAT_IVA",
        "nombre": "Devolucion SAT IVA",
        "descripcion": "Abono de autoridad fiscal por devolucion de IVA; no es venta.",
        "familia": "fiscal",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_flujo": True,
        "palabras_clave": ["sat", "tesofe", "devolucion iva", "shcp"],
        "evidencia_requerida": ["acuse_sat", "resolucion_sat", "declaracion"],
        "prioridad": 50,
    },
    {
        "codigo": "DEVOLUCION_SAT_ISR",
        "nombre": "Devolucion SAT ISR",
        "descripcion": "Abono de autoridad fiscal por devolucion de ISR; no es venta.",
        "familia": "fiscal",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "afecta_isr": True,
        "afecta_flujo": True,
        "palabras_clave": ["sat", "tesofe", "devolucion isr", "shcp"],
        "evidencia_requerida": ["acuse_sat", "resolucion_sat", "declaracion"],
        "prioridad": 51,
    },
    {
        "codigo": "PAGO_NOMINA_TIMBRADA",
        "nombre": "Pago de nomina timbrada",
        "descripcion": "Salida bancaria contra CFDI de nomina timbrada y dispersion.",
        "familia": "nomina",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "nomina",
        "requiere_evidencia_externa": True,
        "afecta_isr": True,
        "palabras_clave": ["nomina", "dispersion", "sueldos"],
        "evidencia_requerida": ["cfdi_nomina", "dispersion_bancaria", "periodo_nomina"],
        "prioridad": 60,
    },
    {
        "codigo": "PAGO_PTU",
        "nombre": "Pago de PTU",
        "descripcion": "Salida bancaria por reparto de utilidades contra timbrado o soporte laboral.",
        "familia": "nomina",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "nomina",
        "requiere_evidencia_externa": True,
        "afecta_isr": True,
        "palabras_clave": ["ptu", "utilidades"],
        "evidencia_requerida": ["cfdi_nomina", "calculo_ptu", "dispersion_bancaria"],
        "prioridad": 61,
    },
    {
        "codigo": "PAGO_RENTA_CFDI",
        "nombre": "Pago de renta con CFDI",
        "descripcion": "Cargo de renta o arrendamiento contra CFDI recibido.",
        "familia": "gasto",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "recibido",
        "requiere_cfdi_recibido": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["renta", "arrendamiento"],
        "evidencia_requerida": ["cfdi_recibido", "contrato", "comprobante_pago"],
        "prioridad": 70,
    },
    {
        "codigo": "PAGO_IMPUESTOS",
        "nombre": "Pago de impuestos",
        "descripcion": "Cargo por pago de impuestos federales o estatales; no se concilia contra venta.",
        "familia": "fiscal",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "afecta_iva": True,
        "afecta_isr": True,
        "palabras_clave": ["sat", "impuestos", "linea de captura", "tesoreria"],
        "evidencia_requerida": ["linea_captura", "acuse_pago", "declaracion"],
        "prioridad": 71,
    },
    {
        "codigo": "TRASPASO_ENTRE_CUENTAS",
        "nombre": "Traspaso entre cuentas propias",
        "descripcion": "Movimiento de balance entre cuentas propias; no representa venta ni gasto.",
        "familia": "balance",
        "tipo_movimiento": "ambos",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "afecta_flujo": False,
        "palabras_clave": ["traspaso", "cuenta propia", "transferencia interna"],
        "evidencia_requerida": ["cuenta_origen", "cuenta_destino", "referencia_bancaria"],
        "prioridad": 80,
    },
    {
        "codigo": "PRESTAMO_RECIBIDO",
        "nombre": "Prestamo recibido",
        "descripcion": "Entrada de financiamiento o prestamo; no es venta.",
        "familia": "balance",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "palabras_clave": ["prestamo", "financiamiento", "credito"],
        "evidencia_requerida": ["contrato", "tabla_amortizacion", "referencia_bancaria"],
        "prioridad": 81,
    },
    {
        "codigo": "PRESTAMO_PAGADO",
        "nombre": "Pago de prestamo",
        "descripcion": "Salida por amortizacion de financiamiento o prestamo.",
        "familia": "balance",
        "tipo_movimiento": "cargo",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "palabras_clave": ["prestamo", "amortizacion", "credito"],
        "evidencia_requerida": ["contrato", "tabla_amortizacion", "referencia_bancaria"],
        "prioridad": 82,
    },
    {
        "codigo": "REEMBOLSO_PROVEEDOR",
        "nombre": "Reembolso de proveedor",
        "descripcion": "Entrada por reembolso, bonificacion o devolucion de proveedor.",
        "familia": "balance",
        "tipo_movimiento": "abono",
        "cfdi_esperado": "egreso",
        "requiere_evidencia_externa": True,
        "palabras_clave": ["reembolso", "bonificacion", "devolucion proveedor"],
        "evidencia_requerida": ["cfdi_egreso_o_nota_credito", "comprobante_pago", "proveedor"],
        "prioridad": 83,
    },
    {
        "codigo": "PENDIENTE_ORIGEN",
        "nombre": "Pendiente de clasificar",
        "descripcion": "Movimiento sin evidencia suficiente para clasificar o conciliar.",
        "familia": "pendiente",
        "tipo_movimiento": "ambos",
        "cfdi_esperado": "ninguno",
        "requiere_evidencia_externa": True,
        "palabras_clave": [],
        "evidencia_requerida": ["revision_administracion"],
        "prioridad": 999,
    },
]


def seed_conceptos(apps, schema_editor):
    concepto_model = apps.get_model("conciliacion", "ConceptoConciliacion")
    for item in CONCEPTOS_BASE:
        defaults = {
            "nombre": item["nombre"],
            "descripcion": item.get("descripcion", ""),
            "familia": item["familia"],
            "tipo_movimiento": item["tipo_movimiento"],
            "cfdi_esperado": item["cfdi_esperado"],
            "forma_pago_esperada": item.get("forma_pago_esperada", ""),
            "requiere_rep": item.get("requiere_rep", False),
            "requiere_cfdi_recibido": item.get("requiere_cfdi_recibido", False),
            "requiere_evidencia_externa": item.get("requiere_evidencia_externa", False),
            "afecta_iva": item.get("afecta_iva", False),
            "afecta_isr": item.get("afecta_isr", False),
            "afecta_flujo": item.get("afecta_flujo", True),
            "permite_conciliacion_automatica": item.get("permite_conciliacion_automatica", False),
            "tolerancia_monto": Decimal(str(item.get("tolerancia_monto", "0.00"))),
            "tolerancia_porcentaje": Decimal(str(item.get("tolerancia_porcentaje", "0.0000"))),
            "cuenta_contable_sugerida": item.get("cuenta_contable_sugerida", ""),
            "palabras_clave": item.get("palabras_clave", []),
            "evidencia_requerida": item.get("evidencia_requerida", []),
            "prioridad": item.get("prioridad", 100),
            "activo": item.get("activo", True),
        }
        concepto_model.objects.update_or_create(codigo=item["codigo"], defaults=defaults)


def unseed_conceptos(apps, schema_editor):
    concepto_model = apps.get_model("conciliacion", "ConceptoConciliacion")
    concepto_model.objects.filter(codigo__in=[item["codigo"] for item in CONCEPTOS_BASE]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("conciliacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoConciliacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=160)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "familia",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                            ("gasto", "Gasto"),
                            ("nomina", "Nomina"),
                            ("fiscal", "Fiscal"),
                            ("balance", "Balance"),
                            ("pendiente", "Pendiente"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[("abono", "Abono"), ("cargo", "Cargo"), ("ambos", "Ambos")],
                        max_length=10,
                    ),
                ),
                (
                    "cfdi_esperado",
                    models.CharField(
                        choices=[
                            ("emitido", "CFDI emitido"),
                            ("recibido", "CFDI recibido"),
                            ("nomina", "Nomina timbrada"),
                            ("pago", "Complemento de pago"),
                            ("egreso", "CFDI de egreso"),
                            ("ninguno", "Sin CFDI esperado"),
                            ("opcional", "CFDI opcional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("forma_pago_esperada", models.CharField(blank=True, max_length=2)),
                ("requiere_rep", models.BooleanField(default=False)),
                ("requiere_cfdi_recibido", models.BooleanField(default=False)),
                ("requiere_evidencia_externa", models.BooleanField(default=False)),
                ("afecta_iva", models.BooleanField(default=False)),
                ("afecta_isr", models.BooleanField(default=False)),
                ("afecta_flujo", models.BooleanField(default=True)),
                ("permite_conciliacion_automatica", models.BooleanField(default=False)),
                ("tolerancia_monto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tolerancia_porcentaje", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("cuenta_contable_sugerida", models.CharField(blank=True, max_length=120)),
                ("palabras_clave", models.JSONField(blank=True, default=list)),
                ("evidencia_requerida", models.JSONField(blank=True, default=list)),
                ("prioridad", models.PositiveIntegerField(default=100)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Concepto de conciliacion",
                "verbose_name_plural": "Conceptos de conciliacion",
                "ordering": ["prioridad", "codigo"],
            },
        ),
        migrations.AddIndex(
            model_name="conceptoconciliacion",
            index=models.Index(fields=["familia", "activo"], name="conciliacio_familia_637665_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptoconciliacion",
            index=models.Index(fields=["tipo_movimiento", "activo"], name="conciliacio_tipo_mo_030851_idx"),
        ),
        migrations.AddIndex(
            model_name="conceptoconciliacion",
            index=models.Index(fields=["cfdi_esperado"], name="conciliacio_cfdi_es_72a172_idx"),
        ),
        migrations.RunPython(seed_conceptos, unseed_conceptos),
    ]
