# Generated by Django 5.0.1 on 2026-06-11 14:31

import django.db.models.deletion
from django.db import migrations, models


IDENTIFICADORES_BASE = [
    ("MATRIZ", "VENTAS DEL DIA(?!.*SUC)", "regex", "Factura global sin marca de sucursal", 40),
    ("PAYAN", "SUC PAYAN", "texto", "Factura global Payan", 10),
    ("PAYAN", "PAYAN", "texto", "Referencia Payan", 30),
    ("LAS_GLORIAS", "SUC GLORIAS", "texto", "Factura global Las Glorias", 10),
    ("LAS_GLORIAS", "LAS GLORIAS", "texto", "Referencia Las Glorias", 20),
    ("LAS_GLORIAS", "GLORIAS", "texto", "Referencia Glorias", 30),
    ("LEYVA", "SUC LEYVA", "texto", "Factura global Leyva", 10),
    ("LEYVA", "LEYVA", "texto", "Referencia Leyva", 30),
    ("CRUCERO", "SUC CRUCERO", "texto", "Factura global Crucero", 10),
    ("CRUCERO", "CRUCERO", "texto", "Referencia Crucero", 30),
    ("PLAZA_NIO", "SUC PLAZA NIO", "texto", "Factura global Plaza Nio", 10),
    ("PLAZA_NIO", "PLAZA NIO", "texto", "Referencia Plaza Nio", 20),
    ("COLOSIO", "SUC COLOSIO", "texto", "Factura global Colosio", 10),
    ("COLOSIO", "COLOSIO", "texto", "Referencia Colosio", 30),
    ("GUAMUCHIL", "SUC GUAMUCHIL", "texto", "Factura global Guamuchil", 10),
    ("GUAMUCHIL", "GUAMUCHIL", "texto", "Referencia Guamuchil", 30),
    ("EL_TUNEL", "SUC TUNEL", "texto", "Factura global El Tunel", 10),
    ("EL_TUNEL", "SUC EL TUNEL", "texto", "Factura global El Tunel", 10),
    ("EL_TUNEL", "EL TUNEL", "texto", "Referencia El Tunel", 20),
    ("EL_TUNEL", "TUNEL", "texto", "Referencia Tunel", 30),
]


def seed_identificadores(apps, schema_editor):
    sucursal_model = apps.get_model("core", "Sucursal")
    identificador_model = apps.get_model("conciliacion", "SucursalIdentificadorFiscal")
    sucursales = {sucursal.codigo: sucursal for sucursal in sucursal_model.objects.filter(activa=True)}

    for codigo, patron, tipo, descripcion, prioridad in IDENTIFICADORES_BASE:
        sucursal = sucursales.get(codigo)
        if sucursal is None:
            continue
        identificador_model.objects.update_or_create(
            sucursal=sucursal,
            patron=patron,
            tipo=tipo,
            defaults={
                "descripcion": descripcion,
                "prioridad": prioridad,
                "activo": True,
            },
        )


def unseed_identificadores(apps, schema_editor):
    identificador_model = apps.get_model("conciliacion", "SucursalIdentificadorFiscal")
    identificador_model.objects.filter(patron__in=[item[1] for item in IDENTIFICADORES_BASE]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0002_conceptoconciliacion'),
        ('core', '0017_alter_usermoduleaccess_module'),
        ('sat_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfdiSucursalResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('xml_concepto', 'Concepto XML'), ('manual', 'Manual'), ('sin_coincidencia', 'Sin coincidencia'), ('ambigua', 'Ambigua')], max_length=30)),
                ('confianza', models.PositiveSmallIntegerField(default=0)),
                ('texto_detectado', models.CharField(blank=True, max_length=255)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('revisado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cfdi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion_sucursal', to='sat_client.cfdidescargado')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfdi_resueltos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Resolucion de sucursal CFDI',
                'verbose_name_plural': 'Resoluciones de sucursal CFDI',
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['sucursal', 'confianza'], name='conciliacio_sucursa_ee728e_idx'), models.Index(fields=['fuente'], name='conciliacio_fuente_4b4b58_idx'), models.Index(fields=['revisado'], name='conciliacio_revisad_588822_idx')],
            },
        ),
        migrations.CreateModel(
            name='SucursalIdentificadorFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('regex', 'Regex')], default='texto', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=180)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identificadores_fiscales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Identificador fiscal de sucursal',
                'verbose_name_plural': 'Identificadores fiscales de sucursal',
                'ordering': ['prioridad', 'sucursal__codigo', 'patron'],
                'indexes': [models.Index(fields=['activo', 'prioridad'], name='conciliacio_activo_cd7e81_idx'), models.Index(fields=['tipo', 'activo'], name='conciliacio_tipo_15be25_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sucursalidentificadorfiscal',
            constraint=models.UniqueConstraint(fields=('sucursal', 'patron', 'tipo'), name='uniq_identificador_fiscal_sucursal'),
        ),
        migrations.RunPython(seed_identificadores, unseed_identificadores),
    ]
