# Generated by Django 5.0.1 on 2026-06-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0003_cfdisucursalresolucion_sucursalidentificadorfiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionbancaria',
            name='fuente',
            field=models.CharField(choices=[('manual_csv', 'Carga manual CSV'), ('manual_excel', 'Carga manual Excel'), ('manual_pdf', 'Carga manual PDF')], max_length=20),
        ),
    ]
