# Generated by Django 5.0.1 on 2026-06-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0004_alter_importacionbancaria_fuente'),
        ('syncfy_client', '0004_alter_movimientobancario_tipo_conciliacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContableConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('capital', 'Capital'), ('ingreso', 'Ingreso'), ('costo', 'Costo'), ('gasto', 'Gasto'), ('orden', 'Orden')], max_length=20)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], max_length=20)),
                ('agrupador_sat', models.CharField(blank=True, max_length=20)),
                ('cuenta_contpaqi', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable de conciliacion',
                'verbose_name_plural': 'Cuentas contables de conciliacion',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['tipo', 'activa'], name='conciliacio_tipo_ae6f31_idx'), models.Index(fields=['agrupador_sat'], name='conciliacio_agrupad_64287d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancariaPropia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('empresa_rfc', models.CharField(blank=True, max_length=13)),
                ('clabe', models.CharField(blank=True, max_length=18)),
                ('ultimos_digitos', models.CharField(blank=True, max_length=8)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_bancaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='catalogo_conciliacion', to='syncfy_client.cuentabancaria')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='conciliacion.cuentacontableconciliacion')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria propia',
                'verbose_name_plural': 'Cuentas bancarias propias',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ContraparteConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('banco', 'Banco'), ('sat', 'SAT'), ('cuenta_propia', 'Cuenta propia'), ('tarjeta_credito', 'Tarjeta de credito'), ('linea_credito', 'Linea de credito'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('palabras_clave', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrapartes', to='conciliacion.cuentacontableconciliacion')),
            ],
            options={
                'verbose_name': 'Contraparte de conciliacion',
                'verbose_name_plural': 'Contrapartes de conciliacion',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoFinancieroConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de credito'), ('linea_credito', 'Linea de credito')], max_length=30)),
                ('nombre', models.CharField(max_length=160)),
                ('institucion', models.CharField(max_length=120)),
                ('numero_referencia', models.CharField(blank=True, max_length=60)),
                ('patrones_descripcion', models.JSONField(blank=True, default=list)),
                ('evidencia_requerida', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contraparte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos', to='conciliacion.contraparteconciliacion')),
                ('cuenta_bancaria_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos_pagados', to='conciliacion.cuentabancariapropia')),
                ('cuenta_contable_intereses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos_intereses', to='conciliacion.cuentacontableconciliacion')),
                ('cuenta_contable_pasivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instrumentos_pasivo', to='conciliacion.cuentacontableconciliacion')),
            ],
            options={
                'verbose_name': 'Instrumento financiero de conciliacion',
                'verbose_name_plural': 'Instrumentos financieros de conciliacion',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReglaClasificacionMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo_movimiento', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono'), ('ambos', 'Ambos')], default='ambos', max_length=10)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('patrones_descripcion', models.JSONField(blank=True, default=list)),
                ('contraparte_tipo', models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('banco', 'Banco'), ('sat', 'SAT'), ('cuenta_propia', 'Cuenta propia'), ('tarjeta_credito', 'Tarjeta de credito'), ('linea_credito', 'Linea de credito'), ('otro', 'Otro')], max_length=30)),
                ('instrumento_tipo', models.CharField(blank=True, choices=[('tarjeta_credito', 'Tarjeta de credito'), ('linea_credito', 'Linea de credito')], max_length=30)),
                ('requiere_cuenta_propia_destino', models.BooleanField(default=False)),
                ('evidencia_requerida', models.JSONField(blank=True, default=list)),
                ('confianza_base', models.PositiveSmallIntegerField(default=70)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_clasificacion', to='conciliacion.conceptoconciliacion')),
                ('cuenta_debe_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_debe', to='conciliacion.cuentacontableconciliacion')),
                ('cuenta_haber_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_haber', to='conciliacion.cuentacontableconciliacion')),
            ],
            options={
                'verbose_name': 'Regla de clasificacion bancaria',
                'verbose_name_plural': 'Reglas de clasificacion bancaria',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentabancariapropia',
            index=models.Index(fields=['empresa_rfc', 'activa'], name='conciliacio_empresa_d1aac4_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentabancariapropia',
            index=models.Index(fields=['ultimos_digitos'], name='conciliacio_ultimos_0517e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentabancariapropia',
            index=models.Index(fields=['clabe'], name='conciliacio_clabe_476e52_idx'),
        ),
        migrations.AddIndex(
            model_name='contraparteconciliacion',
            index=models.Index(fields=['tipo', 'activa'], name='conciliacio_tipo_aac0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='contraparteconciliacion',
            index=models.Index(fields=['rfc'], name='conciliacio_rfc_b26d78_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentofinancieroconciliacion',
            index=models.Index(fields=['tipo', 'activo'], name='conciliacio_tipo_e9872c_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentofinancieroconciliacion',
            index=models.Index(fields=['institucion'], name='conciliacio_institu_eb3484_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaclasificacionmovimiento',
            index=models.Index(fields=['tipo_movimiento', 'activa'], name='conciliacio_tipo_mo_83f77d_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaclasificacionmovimiento',
            index=models.Index(fields=['prioridad', 'activa'], name='conciliacio_priorid_651a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaclasificacionmovimiento',
            index=models.Index(fields=['contraparte_tipo'], name='conciliacio_contrap_ce3a58_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaclasificacionmovimiento',
            index=models.Index(fields=['instrumento_tipo'], name='conciliacio_instrum_890763_idx'),
        ),
    ]
