# Generated by Django 5.0.1 on 2026-05-14 22:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_usermoduleaccess_module'),
        ('rrhh', '0004_prestamos_contpaq_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBonoVentasPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('dias_laborables', models.PositiveSmallIntegerField(default=23)),
                ('bono_base', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=8)),
                ('pct_uniforme', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('pct_asistencia', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5)),
                ('pct_puntualidad', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('limite_uniforme', models.PositiveSmallIntegerField(default=1)),
                ('limite_asistencia', models.PositiveSmallIntegerField(default=2)),
                ('limite_puntualidad', models.PositiveSmallIntegerField(default=2)),
                ('bono_ventas_adicional', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=8)),
                ('umbral_crecimiento_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('peso_grande', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('peso_mediano', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5)),
                ('peso_chico', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('peso_mini', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('peso_velas_accesorios', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('peso_vasos', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de bono - Ventas',
                'verbose_name_plural': 'Configuraciones de bonos - Ventas',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='BonoVentasEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('dias_asistencia', models.PositiveSmallIntegerField(default=0)),
                ('dias_uniforme', models.PositiveSmallIntegerField(default=0)),
                ('dias_puntualidad', models.PositiveSmallIntegerField(default=0)),
                ('pasa_uniforme', models.BooleanField(default=False)),
                ('pasa_asistencia', models.BooleanField(default=False)),
                ('pasa_puntualidad', models.BooleanField(default=False)),
                ('monto_uniforme', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_asistencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('monto_puntualidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('sub1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('bono_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pasa_bono_ventas', models.BooleanField(default=False)),
                ('ajuste_positivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('ajuste_negativo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('bono_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('desc_ajuste_positivo', models.CharField(blank=True, default='', max_length=200)),
                ('desc_ajuste_negativo', models.CharField(blank=True, default='', max_length=200)),
                ('desc_bono_extra', models.CharField(blank=True, default='', max_length=200)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADO', 'Cerrado'), ('PAGADO', 'Pagado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos_ventas', to='rrhh.empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonos', to='bonos_ventas.configbonoventasperiodo')),
            ],
            options={
                'verbose_name': 'Bono de Ventas',
                'verbose_name_plural': 'Bonos de Ventas',
                'ordering': ['sucursal__nombre', 'empleado__nombre'],
                'unique_together': {('periodo', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDiarioVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField()),
                ('tiene_uniforme', models.BooleanField(default=True)),
                ('tiene_puntualidad', models.BooleanField(default=True)),
                ('tiene_asistencia', models.BooleanField(default=True)),
                ('puntos_de_vista', models.CharField(blank=True, default='', max_length=500)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='bonos_ventas.bonoventasempleado')),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('bono', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='VentaCategoriaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('GRANDE', 'Grande'), ('MEDIANO', 'Mediano'), ('CHICO', 'Chico'), ('MINI', 'Mini'), ('VELAS_ACCESORIOS', 'Velas/Accesorios'), ('VASOS', 'Vasos')], max_length=30)),
                ('cantidad_actual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('cantidad_anterior', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('pct_crecimiento', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('activo_bono', models.BooleanField(default=False)),
                ('monto_bono_categoria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('POS_BRIDGE', 'pos_bridge')], default='MANUAL', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_categoria', to='bonos_ventas.configbonoventasperiodo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
            ],
            options={
                'ordering': ['sucursal__nombre', 'categoria'],
                'unique_together': {('periodo', 'sucursal', 'categoria')},
            },
        ),
    ]
