# Generated by Django 5.0.1 on 2026-05-28 18:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonos_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonoventasempleado',
            name='dias_con_bitacora',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonoventasempleado',
            name='monto_bono_entregas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='bonoventasempleado',
            name='pct_efectividad_entrega',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='configbonoventasperiodo',
            name='bono_repartidor_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='configbonoventasperiodo',
            name='umbral_efectividad_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5),
        ),
    ]
