# Generated by Django 5.0.1 on 2026-05-11 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_usermoduleaccess_module'),
        ('logistica', '0002_unidad_repartidor_bitacorarepartidor_reporteunidad'),
        ('recetas', '0036_marcar_costeo_equivalencia_no_produccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=40, unique=True)),
                ('ticket_point', models.CharField(blank=True, default='', max_length=80)),
                ('estatus', models.CharField(choices=[('CAPTURA', 'En captura'), ('ENVIADO_CEDIS', 'Enviado a CEDIS'), ('RECIBIDO_OK', 'Recibido sin diferencia'), ('RECIBIDO_DIFERENCIA', 'Recibido con diferencia'), ('CANCELADO', 'Cancelado')], db_index=True, default='CAPTURA', max_length=24)),
                ('iniciado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('enviado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recibido_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repartidor_confirmado', models.BooleanField(default=False)),
                ('nota_sucursal', models.TextField(blank=True, default='')),
                ('nota_recepcion', models.TextField(blank=True, default='')),
                ('alerta_ventas', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_registradas', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_transportadas', to='logistica.repartidor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Registro de merma',
                'verbose_name_plural': 'Registros de merma',
                'ordering': ['-iniciado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MermaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_texto', models.CharField(blank=True, default='', max_length=220)),
                ('cantidad_enviada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('conforme', models.BooleanField(blank=True, null=True)),
                ('nota_recepcion', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recetas.receta')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='mermas.mermaregistro')),
            ],
            options={
                'verbose_name': 'Producto de merma',
                'verbose_name_plural': 'Productos de merma',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MermaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TICKET', 'Ticket Point'), ('PRODUCTO_SUCURSAL', 'Producto en sucursal'), ('PRODUCTO_CEDIS', 'Producto recibido CEDIS')], db_index=True, max_length=24)),
                ('archivo', models.ImageField(upload_to='mermas/evidencias/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_evidencias', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='mermas.mermaregistro')),
            ],
            options={
                'verbose_name': 'Evidencia de merma',
                'verbose_name_plural': 'Evidencias de merma',
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
