# Generated by Django 5.0.1 on 2026-05-12 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usermoduleaccess_module'),
        ('mermas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEnviosSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_envios_sucursales', to='core.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_envios_sucursales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Envíos a Sucursales',
                'verbose_name_plural': 'Personal Envíos a Sucursales',
                'ordering': ['user__first_name', 'user__last_name', 'user__username'],
            },
        ),
    ]
