# Generated by Django 5.0.1 on 2026-05-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_reporte_reafirmacion_resumen'),
        ('mermas', '0002_personalenviossucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermaregistro',
            name='repartidor_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_entregadas_cedis', to='logistica.repartidor'),
        ),
    ]
