# Generated by Django 5.0.1 on 2026-07-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('maestros', '0016_alter_insumo_tipo_item'),
        ('mermas', '0003_mermaregistro_repartidor_entrega'),
        ('rrhh', '0037_empleado_exento_checador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_point', models.CharField(db_index=True, max_length=80)),
                ('nombre_point', models.CharField(max_length=250)),
                ('unidad_point', models.CharField(max_length=40)),
                ('cantidad_reportada', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('motivo', models.CharField(max_length=80)),
                ('comentario', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='mermas/insumos/%Y/%m/')),
                ('justificacion_sin_foto', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('SIN_RESPONSABLE', 'Sin responsable'), ('EN_ACLARACION', 'En aclaración'), ('RECHAZADA', 'Rechazada'), ('APROBADA', 'Aprobada'), ('EJECUTANDO', 'Ejecutando'), ('APLICADA', 'Aplicada'), ('REQUIERE_REVISION', 'Requiere revisión'), ('INTERVENCION_TECNICA', 'Intervención técnica')], db_index=True, default='BORRADOR', max_length=32)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_sucursal', to='maestros.insumo')),
                ('jefe_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_insumos_por_aprobar', to='rrhh.empleado')),
                ('jefe_inmediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_insumos_asignadas', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_insumos_reportadas', to=settings.AUTH_USER_MODEL)),
                ('reportante_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_insumos_reportadas', to='rrhh.empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_insumos', to='core.sucursal')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MermaInsumoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=32)),
                ('estado_nuevo', models.CharField(max_length=32)),
                ('motivo', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('merma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='mermas.mermainsumo')),
            ],
            options={
                'ordering': ['creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenAjustePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_point', models.CharField(max_length=80)),
                ('unidad_point', models.CharField(max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SIMULADA', 'Simulada'), ('EJECUTANDO', 'Ejecutando'), ('APLICADA', 'Aplicada'), ('REQUIERE_REVISION', 'Requiere revisión'), ('INTERVENCION_TECNICA', 'Intervención técnica')], db_index=True, default='PENDIENTE', max_length=32)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('existencia_antes', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('existencia_despues', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('referencia_point', models.CharField(blank=True, default='', max_length=120)),
                ('evidencia_tecnica', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('merma', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_point', to='mermas.mermainsumo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_ajuste_point', to='core.sucursal')),
            ],
        ),
        migrations.AddIndex(
            model_name='mermainsumo',
            index=models.Index(fields=['sucursal', 'estatus'], name='merma_ins_suc_est_idx'),
        ),
        migrations.AddIndex(
            model_name='mermainsumo',
            index=models.Index(fields=['jefe_inmediato', 'estatus'], name='merma_ins_jefe_est_idx'),
        ),
    ]
