# Generated by Django 5.0.1 on 2026-07-25 22:08

from django.db import migrations, models
from django.utils import timezone


def backfill_costos_historicos(apps, schema_editor):
    MermaInsumo = apps.get_model("mermas", "MermaInsumo")
    CostoInsumo = apps.get_model("maestros", "CostoInsumo")
    resolved_at = timezone.now()
    for merma in MermaInsumo.objects.all().iterator(chunk_size=500):
        costo = None
        if merma.insumo_id:
            costo = (
                CostoInsumo.objects.filter(
                    insumo_id=merma.insumo_id,
                    fecha__lte=merma.creado_en.date(),
                )
                .order_by("-fecha", "-id")
                .first()
            )
        if costo:
            merma.costo_unitario_historico = costo.costo_unitario
            merma.costo_moneda = costo.moneda
            merma.costo_fecha = costo.fecha
            merma.costo_fuente_id = str(costo.id)
            merma.estado_valorizacion = "CON_COSTO"
        else:
            merma.estado_valorizacion = "SIN_COSTO"
        merma.costo_resuelto_en = resolved_at
        merma.save(update_fields=[
            "costo_unitario_historico", "costo_moneda", "costo_fecha",
            "costo_fuente_id", "estado_valorizacion", "costo_resuelto_en",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('mermas', '0004_merma_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermainsumo',
            name='costo_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='costo_fuente_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='costo_moneda',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='costo_resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='costo_unitario_historico',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='estado_valorizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CON_COSTO', 'Con costo'), ('SIN_COSTO', 'Sin costo')], db_index=True, default='PENDIENTE', max_length=16),
        ),
        migrations.RunPython(backfill_costos_historicos, migrations.RunPython.noop),
    ]
