# Generated by Django 5.0.1 on 2026-09-04 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_usermoduleaccess_module'),
        ('mermas', '0005_merma_insumo_costo_historico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaSucursalAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_captura_mermas', to='core.sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas_sucursales_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal adicional para captura de merma',
                'verbose_name_plural': 'Sucursales adicionales para captura de merma',
            },
        ),
        migrations.AddConstraint(
            model_name='mermasucursalacceso',
            constraint=models.UniqueConstraint(fields=('user', 'sucursal'), name='mermas_acceso_usuario_sucursal_unico'),
        ),
    ]
