# Generated by Django 5.0.1 on 2026-10-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mermas', '0006_mermasucursalacceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermainsumo',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mermainsumo',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mermaregistro',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mermaregistro',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
