# Generated by Django 5.0.1 on 2026-03-29 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0026_alter_productomonthclosure_opening_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('capa_objetivo', models.CharField(choices=[('FABRICACION', 'Fabricación'), ('SUCURSAL', 'Sucursal'), ('EMPRESA', 'Empresa')], db_index=True, max_length=20)),
                ('bucket', models.CharField(choices=[('MANO_OBRA_PROD', 'Mano de obra producción'), ('INDIRECTO_PROD', 'Indirecto producción'), ('EMPAQUE_PROD', 'Empaque producción'), ('COMERCIAL_SUCURSAL', 'Comercial sucursal'), ('CORPORATIVO', 'Corporativo'), ('LOGISTICA', 'Logística'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=30)),
                ('impacta_costo_producto', models.BooleanField(default=False)),
                ('impacta_contribucion_sucursal', models.BooleanField(default=False)),
                ('impacta_utilidad_empresa', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de gasto',
                'verbose_name_plural': 'Categorías de gasto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaResultadoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True, unique=True)),
                ('venta_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('costo_fabricacion_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('margen_bruto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gasto_comercial_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contribucion_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gasto_corporativo_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('utilidad_operativa_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resultado mensual empresa',
                'verbose_name_plural': 'Resultados mensuales empresa',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('PRODUCCION', 'Producción'), ('SUCURSAL_VENTA', 'Sucursal venta'), ('CORPORATIVO', 'Corporativo'), ('LOGISTICA', 'Logística'), ('CEDIS', 'CEDIS')], db_index=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ReglaAsignacionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('base_reparto', models.CharField(choices=[('NONE', 'Sin reparto'), ('VENTAS', 'Por ventas'), ('UNIDADES', 'Por unidades'), ('COSTO_MP', 'Por costo MP')], default='NONE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_asignacion', to='reportes.categoriagasto')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_asignacion', to='reportes.centrocosto')),
            ],
            options={
                'verbose_name': 'Regla de asignación de gasto',
                'verbose_name_plural': 'Reglas de asignación de gasto',
                'ordering': ['prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GastoOperativoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fuente', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTADA', 'Importada')], default='MANUAL', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('archivo_soporte', models.CharField(blank=True, default='', max_length=300)),
                ('es_estimado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_operativos_capturados', to=settings.AUTH_USER_MODEL)),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_mensuales', to='reportes.categoriagasto')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_mensuales', to='reportes.centrocosto')),
            ],
            options={
                'verbose_name': 'Gasto operativo mensual',
                'verbose_name_plural': 'Gastos operativos mensuales',
                'ordering': ['-periodo', 'centro_costo__codigo', 'categoria_gasto__codigo', 'id'],
                'indexes': [models.Index(fields=['periodo', 'centro_costo'], name='rgasto_periodo_centro_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoCostoOperativoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('unidades_base', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('venta_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('asp', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_mp_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('mano_obra_prod_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('indirecto_prod_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('empaque_prod_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_fabricacion_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_operativos_mensuales', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Costo operativo mensual por producto',
                'verbose_name_plural': 'Costos operativos mensuales por producto',
                'ordering': ['-periodo', 'receta__nombre'],
                'unique_together': {('periodo', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='ProductoPricingDecisionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('asp_actual', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_fabricacion_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('contribucion_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('margen_bruto_pct', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('margen_contribucion_pct', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio_objetivo_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('precio_objetivo_contribucion', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('gap_precio', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('impacto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accion_sugerida', models.CharField(choices=[('DEFENDER', 'Defender'), ('PROMOVER', 'Promover'), ('CORREGIR_COSTO', 'Corregir costo'), ('SUBIR_PRECIO', 'Subir precio'), ('GANCHO', 'Gancho'), ('REFORMULAR', 'Reformular')], db_index=True, default='DEFENDER', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_decisions_mensuales', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Decisión mensual de pricing',
                'verbose_name_plural': 'Decisiones mensuales de pricing',
                'ordering': ['-periodo', 'accion_sugerida', '-impacto_estimado', 'receta__nombre'],
                'unique_together': {('periodo', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='ProductoSucursalContribucionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('unidades_vendidas', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('venta_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('asp', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_producto_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_producto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gasto_comercial_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('gasto_comercial_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contribucion_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contribucion_unit', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('margen_contribucion_pct', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones_mensuales', to='recetas.receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuciones_producto_mensuales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Contribución mensual por producto y sucursal',
                'verbose_name_plural': 'Contribuciones mensuales por producto y sucursal',
                'ordering': ['-periodo', 'sucursal__codigo', 'receta__nombre'],
                'unique_together': {('periodo', 'receta', 'sucursal')},
            },
        ),
    ]
