# Generated by Django 5.0.1 on 2026-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastooperativomensual',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True),
        ),
    ]
