# Generated by Django 5.0.1 on 2026-03-30 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_gastooperativomensual_external_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GENERAL', 'General consolidado')], db_index=True, default='GENERAL', max_length=20)),
                ('fuente_nombre', models.CharField(db_index=True, max_length=220)),
                ('archivo_ruta', models.CharField(max_length=500)),
                ('archivo_hash', models.CharField(db_index=True, max_length=64)),
                ('sheet_name', models.CharField(default='GENERAL', max_length=120)),
                ('titulo', models.CharField(blank=True, default='', max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Importación de presupuesto',
                'verbose_name_plural': 'Importaciones de presupuesto',
                'ordering': ['-created_at', 'fuente_nombre'],
                'unique_together': {('tipo', 'fuente_nombre', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoLineaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(db_index=True, max_length=180, unique=True)),
                ('period', models.DateField(db_index=True)),
                ('account_code', models.CharField(blank=True, default='', max_length=80)),
                ('concept', models.CharField(db_index=True, max_length=220)),
                ('annual_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('annual_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('annual_variance', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monthly_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monthly_variance', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_mensuales', to='reportes.presupuestoimport')),
            ],
            options={
                'verbose_name': 'Línea mensual de presupuesto',
                'verbose_name_plural': 'Líneas mensuales de presupuesto',
                'ordering': ['-period', 'concept', 'row_index'],
                'indexes': [models.Index(fields=['period', 'concept'], name='rpresu_period_concept_idx')],
            },
        ),
    ]
