# Generated by Django 5.0.1 on 2026-03-30 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_presupuestoimport_presupuestolineamensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('GLOBAL', 'Global'), ('FUENTE', 'Por fuente')], db_index=True, max_length=20)),
                ('fuente_nombre', models.CharField(blank=True, db_index=True, default='', max_length=220)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_variance', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen mensual de presupuesto',
                'verbose_name_plural': 'Resumenes mensuales de presupuesto',
                'ordering': ['-period', 'tipo', 'fuente_nombre'],
                'unique_together': {('period', 'tipo', 'fuente_nombre')},
            },
        ),
    ]
