# Generated by Django 5.0.1 on 2026-03-30 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_pointpendingmatch_visibility_and_classification'),
        ('recetas', '0026_alter_productomonthclosure_opening_source'),
        ('reportes', '0004_presupuestoresumenmensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoCostoHistoricoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metodo', models.CharField(choices=[('MONTHLY_WEIGHTED', 'Promedio ponderado mensual'), ('ROLLED_FORWARD', 'Arrastre último costo'), ('POINT_EXISTENCIA', 'Costo Point existencia')], db_index=True, max_length=30)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('weighted_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_historicos_mensuales', to='maestros.insumo')),
            ],
            options={
                'verbose_name': 'Costo histórico mensual de insumo',
                'verbose_name_plural': 'Costos históricos mensuales de insumos',
                'ordering': ['-periodo', 'insumo__nombre'],
                'unique_together': {('periodo', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='RecetaCostoHistoricoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('costo_total', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('costo_por_unidad_rendimiento', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('lineas_costeadas', models.PositiveIntegerField(default=0)),
                ('lineas_totales', models.PositiveIntegerField(default=0)),
                ('coverage_pct', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_historicos_mensuales', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Costo histórico mensual de receta',
                'verbose_name_plural': 'Costos históricos mensuales de recetas',
                'ordering': ['-periodo', 'receta__nombre'],
                'unique_together': {('periodo', 'receta')},
            },
        ),
    ]
