# Generated by Django 5.0.1 on 2026-03-30 22:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_pointpendingmatch_visibility_and_classification'),
        ('reportes', '0005_insumocostohistoricomensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumocostohistoricomensual',
            name='metodo',
            field=models.CharField(choices=[('MONTHLY_WEIGHTED', 'Promedio ponderado mensual'), ('ROLLED_FORWARD', 'Arrastre último costo'), ('POINT_EXISTENCIA', 'Costo Point existencia'), ('ALIAS_RULE', 'Equivalencia histórica'), ('NEXT_KNOWN', 'Primer costo posterior')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ReglaCostoHistoricoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('ALIAS_INSUMO', 'Equivalencia con otro insumo'), ('NEXT_KNOWN_COST', 'Usar primer costo posterior')], db_index=True, max_length=30)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_costo_historico_origen', to='maestros.insumo')),
                ('insumo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_costo_historico_referencia', to='maestros.insumo')),
            ],
            options={
                'verbose_name': 'Regla de costo histórico por insumo',
                'verbose_name_plural': 'Reglas de costo histórico por insumo',
                'ordering': ['prioridad', 'id'],
                'unique_together': {('insumo_origen', 'metodo', 'insumo_referencia')},
            },
        ),
    ]
