# Generated by Django 5.0.1 on 2026-04-06 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_corteoficialdiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('classification', models.CharField(choices=[('REVENTA', 'Reventa'), ('ACCESORIO', 'Accesorio'), ('SERVICIO', 'Servicio'), ('FABRICADO', 'Fabricado')], db_index=True, max_length=20)),
                ('is_fixed', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de negocio por producto',
                'verbose_name_plural': 'Reglas de negocio por producto',
                'ordering': ['product_name'],
            },
        ),
    ]
