# Generated by Django 5.0.1 on 2026-04-06 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_proyectoinversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinversion',
            name='discount_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='cash_on_cash',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='confidence_score',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='data_source',
            field=models.CharField(choices=[('FACT', 'Fact'), ('FALLBACK', 'Fallback'), ('ESTIMATED', 'Estimado')], db_index=True, default='ESTIMATED', max_length=20),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='fecha_estimada_recuperacion_forecast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='flujo_libre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='flujo_operativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='flujo_para_recuperacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='health_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='health_status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], default='RED', max_length=10),
        ),
        migrations.AddField(
            model_name='proyectoinversionsnapshotmensual',
            name='payback_forecast_meses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ProyectoInversionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('PAYBACK_RISK', 'Payback en riesgo'), ('LOW_ROI', 'ROI bajo'), ('NEGATIVE_FREE_CASHFLOW', 'Flujo libre negativo'), ('CAPEX_OVERRUN', 'Sobreinversión')], db_index=True, max_length=40)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=10)),
                ('titulo', models.CharField(max_length=140)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='reportes.proyectoinversion')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='reportes.proyectoinversionsnapshotmensual')),
            ],
            options={
                'verbose_name': 'Alerta de proyecto de inversión',
                'verbose_name_plural': 'Alertas de proyectos de inversión',
                'ordering': ['-activa', '-last_detected_at', '-id'],
                'indexes': [models.Index(fields=['proyecto', 'activa'], name='rpinvalert_proj_active_idx'), models.Index(fields=['codigo', 'activa'], name='rpinvalert_code_active_idx')],
            },
        ),
    ]
