# Generated by Django 5.0.1 on 2026-04-06 18:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_proyectoinversion_discount_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpansionPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Política expansión activa', max_length=120)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('min_free_cashflow_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_debt_to_income_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.40'), max_digits=8)),
                ('max_average_payback_months', models.DecimalField(decimal_places=2, default=Decimal('24'), max_digits=8)),
                ('max_projects_in_risk', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política global de expansión',
                'verbose_name_plural': 'Políticas globales de expansión',
                'ordering': ['-activa', '-actualizado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpansionZoneScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(db_index=True, max_length=120)),
                ('zona', models.CharField(db_index=True, max_length=120)),
                ('score_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ventas_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('densidad', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('competencia', models.CharField(blank=True, default='', max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score de zona de expansión',
                'verbose_name_plural': 'Scores de zonas de expansión',
                'ordering': ['-score_estimado', 'ciudad', 'zona'],
                'unique_together': {('ciudad', 'zona')},
            },
        ),
    ]
