# Generated by Django 5.0.1 on 2026-04-06 19:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0027_receta_modo_costeo'),
        ('reportes', '0017_dashboardfullsnapshot_mv_dashboard_full'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('recomendado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('producido_real', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('vendido_real', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('merma', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('desviacion', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_execution_logs', to='recetas.receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_execution_logs', to='core.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de ejecución de producción',
                'verbose_name_plural': 'Bitácoras de ejecución de producción',
                'ordering': ['-fecha', 'sucursal__codigo', 'receta__nombre', '-id'],
                'indexes': [models.Index(fields=['fecha', 'sucursal'], name='rprodexec_day_branch_idx'), models.Index(fields=['fecha', 'receta'], name='rprodexec_day_recipe_idx')],
                'unique_together': {('fecha', 'receta', 'sucursal')},
            },
        ),
    ]
