# Generated by Django 5.0.1 on 2026-04-06 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('reportes', '0018_alter_presupuestoimport_tipo_productionexecutionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionexecutionlog',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productionexecutionlog',
            name='decision_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='productionexecutionlog',
            name='recommendation_version',
            field=models.CharField(blank=True, default='v1', max_length=40),
        ),
        migrations.AddField(
            model_name='productionexecutionlog',
            name='stock_visible',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='ForecastCalibrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(db_index=True)),
                ('familia', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('weekly_pattern', models.CharField(choices=[('MON_WED', 'Lunes-Miércoles'), ('THU_SUN', 'Jueves-Domingo')], db_index=True, max_length=16)),
                ('rotation_band', models.CharField(choices=[('HIGH', 'Alta rotación'), ('LOW', 'Baja rotación')], db_index=True, max_length=16)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('wape_before_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wape_after_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bias_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hit_rate_before_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hit_rate_after_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('volatility_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recent_weight', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('mid_weight', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('older_weight', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('bias_adjustment', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('buffer_multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('execution_gap_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_calibration_profiles', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Perfil de calibración de forecast',
                'verbose_name_plural': 'Perfiles de calibración de forecast',
                'ordering': ['-reference_date', 'sucursal__codigo', 'familia', 'weekly_pattern', 'rotation_band'],
                'indexes': [models.Index(fields=['reference_date', 'sucursal', 'weekly_pattern', 'rotation_band'], name='rfcstcal_ref_branch_idx'), models.Index(fields=['reference_date', 'familia', 'weekly_pattern', 'rotation_band'], name='rfcstcal_ref_family_idx')],
                'unique_together': {('reference_date', 'sucursal', 'familia', 'weekly_pattern', 'rotation_band')},
            },
        ),
    ]
