# Generated by Django 5.0.1 on 2026-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0019_productionexecutionlog_comentario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastooperativomensual",
            name="tipo_dato",
            field=models.CharField(
                choices=[("REAL", "Real"), ("PRESUPUESTO", "Presupuesto")],
                db_index=True,
                default="REAL",
                max_length=20,
            ),
        ),
    ]
