# Generated by Django 5.0.1 on 2026-04-06 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0027_receta_modo_costeo'),
        ('reportes', '0020_gastooperativomensual_tipo_dato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionexecutionlog',
            name='aprobado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PROPOSED', 'Propuesta'), ('APPROVED', 'Aprobada'), ('RELEASED', 'Liberada'), ('EXECUTED', 'Ejecutada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PROPOSED', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automática')], db_index=True, default='AUTO', max_length=20)),
                ('recommendation_version', models.CharField(blank=True, db_index=True, default='v1', max_length=40)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'ordering': ['-fecha', 'sucursal__codigo', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recomendada', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cantidad_aprobada', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('decision_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('riesgo_merma', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=16)),
                ('motivo', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reportes.productionorder')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_lines', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Línea de orden de producción',
                'verbose_name_plural': 'Líneas de orden de producción',
                'ordering': ['-decision_score', 'receta__nombre', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['fecha', 'status'], name='rprodord_day_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['fecha', 'sucursal'], name='rprodord_day_branch_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorder',
            unique_together={('fecha', 'sucursal')},
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['order', 'decision_score'], name='rprodline_order_score_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorderline',
            index=models.Index(fields=['receta', 'created_at'], name='rprodline_recipe_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderline',
            unique_together={('order', 'receta')},
        ),
    ]
