# Generated by Django 5.0.1 on 2026-04-06 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0020_gastooperativomensual_tipo_dato"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaGastoOperativoArchivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_filename", models.CharField(db_index=True, max_length=255)),
                ("stored_file_path", models.CharField(max_length=500, unique=True)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[("WEB", "Web"), ("DROPBOX", "Carpeta monitoreada"), ("COMMAND", "Comando")],
                        db_index=True,
                        default="WEB",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSING", "Procesando"),
                            ("SUCCESS", "Exitosa"),
                            ("ERROR", "Error"),
                            ("DUPLICATE", "Duplicada"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("target_year", models.PositiveSmallIntegerField(default=2026)),
                ("uploaded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("loaded_rows", models.PositiveIntegerField(default=0)),
                ("created_rows", models.PositiveIntegerField(default=0)),
                ("updated_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("project_refresh_count", models.PositiveIntegerField(default=0)),
                ("affected_branches", models.JSONField(blank=True, default=list)),
                ("covered_periods", models.JSONField(blank=True, default=list)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas_gasto_operativo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga de gasto operativo",
                "verbose_name_plural": "Cargas de gasto operativo",
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="cargagastooperativoarchivo",
            index=models.Index(fields=["status", "uploaded_at"], name="rgopexload_status_uploaded_idx"),
        ),
        migrations.AddIndex(
            model_name="cargagastooperativoarchivo",
            index=models.Index(fields=["file_hash", "status"], name="rgopexload_hash_status_idx"),
        ),
    ]
