# Generated by Django 5.0.1 on 2026-04-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0021_cargagastooperativoarchivo"),
        ("reportes", "0021_productionexecutionlog_aprobado_and_more"),
    ]

    operations = []
