# Generated by Django 5.0.1 on 2026-04-06 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('maestros', '0009_fix_colorante_rojo_volume_unit'),
        ('recetas', '0027_receta_modo_costeo'),
        ('reportes', '0022_merge_20260406_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('adoption_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('approval_deviation_avg', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('execution_deviation_avg', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('merma_total', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('impacto_economico_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snapshot de métricas operativas',
                'verbose_name_plural': 'Snapshots de métricas operativas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(db_index=True, max_length=180, unique=True)),
                ('tipo', models.CharField(choices=[('MERMA', 'Riesgo de merma'), ('DESVIACION', 'Desviación de ejecución'), ('OPORTUNIDAD', 'Oportunidad de venta'), ('STOCK', 'Stock crítico')], db_index=True, max_length=20)),
                ('severidad', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], db_index=True, max_length=20)),
                ('entidad', models.CharField(db_index=True, max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('impacto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fecha', models.DateField(db_index=True)),
                ('resuelta', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_alerts', to='maestros.insumo')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_alerts', to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_alerts', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Alerta operativa',
                'verbose_name_plural': 'Alertas operativas',
                'ordering': ['resuelta', '-impacto_estimado', '-created_at', '-id'],
                'indexes': [models.Index(fields=['fecha', 'resuelta', 'severidad'], name='ralert_day_state_sev_idx'), models.Index(fields=['tipo', 'fecha'], name='ralert_type_day_idx')],
            },
        ),
    ]
