# Generated by Django 5.0.1 on 2026-04-06 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_solicitudcompra_cotizaciones_recibidas_and_more'),
        ('core', '0005_sucursal_fecha_apertura'),
        ('maestros', '0009_fix_colorante_rojo_volume_unit'),
        ('reportes', '0024_proyectoinversionescenario_simulacion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_report_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationsmetricsnapshot',
            name='adopcion_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='operationsmetricsnapshot',
            name='desviacion_impacto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operationsmetricsnapshot',
            name='efectividad_recomendaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='operationsmetricsnapshot',
            name='impacto_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='AutoControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('max_variacion_produccion_pct', models.DecimalField(decimal_places=2, default=30, max_digits=8)),
                ('max_compra_diaria', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('min_stock_seguridad', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('enable_auto_purchase', models.BooleanField(default=True)),
                ('enable_alerts', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_control_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control global de automatización',
                'verbose_name_plural': 'Control global de automatización',
            },
        ),
        migrations.CreateModel(
            name='AutoPurchaseRequestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('fecha_sugerida_compra', models.DateField(blank=True, db_index=True, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('stock_objetivo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('faltante_inmediato', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('faltante_objetivo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cantidad_sugerida', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('purchase_priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('lead_time_dias', models.PositiveIntegerField(default=0)),
                ('frecuencia_pedido_dias', models.PositiveIntegerField(default=0)),
                ('lote_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_purchase_snapshots', to='maestros.insumo')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_snapshots', to='reportes.productionorder')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_purchase_snapshots', to='maestros.proveedor')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_purchase_snapshot', to='compras.solicitudcompra')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_purchase_snapshots', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Snapshot de compra automática',
                'verbose_name_plural': 'Snapshots de compra automática',
                'ordering': ['fecha', '-purchase_priority_score', 'sucursal__codigo', 'insumo__nombre'],
                'indexes': [models.Index(fields=['fecha', 'sucursal'], name='rautopurch_day_branch_idx'), models.Index(fields=['fecha', 'purchase_priority_score'], name='rautopurch_day_score_idx'), models.Index(fields=['fecha_sugerida_compra', 'fecha'], name='rautopurch_suggest_day_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierLeadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time_dias', models.PositiveIntegerField(default=0)),
                ('frecuencia_pedido_dias', models.PositiveIntegerField(default=7)),
                ('lote_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_lead_times', to='maestros.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_lead_times', to='maestros.proveedor')),
            ],
            options={
                'verbose_name': 'Lead time por proveedor',
                'verbose_name_plural': 'Lead times por proveedor',
                'ordering': ['insumo__nombre', 'proveedor__nombre', '-activo', 'id'],
                'indexes': [models.Index(fields=['insumo', 'activo'], name='rsupplt_insumo_active_idx'), models.Index(fields=['proveedor', 'activo'], name='rsupplt_prov_active_idx')],
                'unique_together': {('insumo', 'proveedor')},
            },
        ),
    ]
