# Generated by Django 5.0.1 on 2026-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0025_alert_resolution_note_alert_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoimport',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'General consolidado'), ('DETALLE', 'Detalle confiable')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
