# Generated by Django 5.0.1 on 2026-04-25 01:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0011_pointmonthlysummary'),
        ('reportes', '0026_alter_presupuestoimport_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoReventaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('fecha_vigencia', models.DateField(db_index=True)),
                ('fuente', models.CharField(choices=[('POINT_ALMACEN', 'Point ALMACEN'), ('POINT_PRODUCT_HISTORY', 'Historial producto Point'), ('MANUAL', 'Manual')], db_index=True, default='POINT_ALMACEN', max_length=40)),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('unidad', models.CharField(blank=True, default='', max_length=40)),
                ('cantidad_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('source_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_reventa', to='pos_bridge.pointproduct')),
            ],
            options={
                'verbose_name': 'Costo de producto de reventa',
                'verbose_name_plural': 'Costos de productos de reventa',
                'ordering': ['-fecha_vigencia', 'producto_point__name'],
                'indexes': [models.Index(fields=['producto_point', 'fecha_vigencia'], name='reportes_pr_product_6e4e84_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoReventaCostoHistoricoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('costo_promedio', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metodo', models.CharField(choices=[('MONTHLY_WEIGHTED', 'Promedio ponderado mensual'), ('ROLLED_FORWARD', 'Arrastre último costo'), ('POINT_ALMACEN', 'Costo Point ALMACEN')], db_index=True, default='MONTHLY_WEIGHTED', max_length=30)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('weighted_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_reventa_historicos_mensuales', to='pos_bridge.pointproduct')),
            ],
            options={
                'verbose_name': 'Costo histórico mensual de producto de reventa',
                'verbose_name_plural': 'Costos históricos mensuales de productos de reventa',
                'ordering': ['-periodo', 'producto_point__name'],
                'unique_together': {('periodo', 'producto_point')},
            },
        ),
    ]
