# Generated by Django 5.0.1 on 2026-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0027_productoreventacosto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaresultadomensual',
            name='costo_materia_prima_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='empresaresultadomensual',
            name='costo_reventa_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='empresaresultadomensual',
            name='empaque_prod_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='empresaresultadomensual',
            name='indirecto_prod_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='empresaresultadomensual',
            name='mano_obra_prod_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
