# Generated by Django 5.0.1 on 2026-04-27 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('reportes', '0028_empresaresultadomensual_costo_materia_prima_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Área de presupuesto',
                'verbose_name_plural': 'Áreas de presupuesto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RubroPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('codigo_cuenta', models.CharField(blank=True, default='', max_length=50)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('COSTO', 'Costo'), ('CAPEX', 'Capex')], db_index=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubros', to='reportes.areapresupuesto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_presupuesto', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Rubro de presupuesto',
                'verbose_name_plural': 'Rubros de presupuesto',
                'ordering': ['area__orden', 'area__nombre', 'concepto', 'sucursal__codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineaPresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('version', models.CharField(choices=[('ORIGINAL', 'Original'), ('REVISADO', 'Revisado')], db_index=True, default='ORIGINAL', max_length=20)),
                ('monto_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fuente_real', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_mensuales', to='reportes.rubropresupuesto')),
            ],
            options={
                'verbose_name': 'Línea de presupuesto mensual',
                'verbose_name_plural': 'Líneas de presupuesto mensual',
                'ordering': ['-periodo', 'rubro__area__orden', 'rubro__concepto'],
            },
        ),
        migrations.AddIndex(
            model_name='rubropresupuesto',
            index=models.Index(fields=['area', 'tipo'], name='rubro_presu_area_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='rubropresupuesto',
            index=models.Index(fields=['codigo_cuenta'], name='rubro_presu_cuenta_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubropresupuesto',
            constraint=models.UniqueConstraint(fields=('area', 'concepto', 'codigo_cuenta', 'sucursal'), name='uniq_rubro_presu_area_concept_suc'),
        ),
        migrations.AddIndex(
            model_name='lineapresupuestomensual',
            index=models.Index(fields=['periodo', 'version'], name='linea_presu_period_ver_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lineapresupuestomensual',
            unique_together={('rubro', 'periodo', 'version')},
        ),
    ]
