# Generated by Django 5.0.1 on 2026-04-27 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('pos_bridge', '0011_pointmonthlysummary'),
        ('reportes', '0029_presupuesto_maestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMensualSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('stock_apertura', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('stock_cierre', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuente_apertura', models.DateTimeField()),
                ('fuente_cierre', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_mensual_sucursal', to='pos_bridge.pointproduct')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_mensual_producto', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Stock mensual por sucursal',
                'verbose_name_plural': 'Stocks mensuales por sucursal',
                'ordering': ['-periodo', 'sucursal__codigo', 'producto__name'],
                'indexes': [models.Index(fields=['periodo', 'sucursal'], name='rstock_mes_branch_idx'), models.Index(fields=['periodo', 'producto'], name='rstock_mes_product_idx')],
                'unique_together': {('periodo', 'sucursal', 'producto')},
            },
        ),
    ]
