# Generated by Django 5.0.1 on 2026-07-03 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0040_repoint_legacy_pay_ingredients'),
        ('reportes', '0031_dgoperacionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoManoObraDiarioArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('area', models.CharField(choices=[('HORNOS', 'Hornos'), ('ARMADO', 'Armado'), ('EMBETUNADO', 'Embetunado')], db_index=True, max_length=20)),
                ('nomina_dia_area', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidades_producidas', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('costo_unidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('es_dia_laborable_esperado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costo de mano de obra diario por área',
                'verbose_name_plural': 'Costos de mano de obra diarios por área',
                'ordering': ['-fecha', 'area'],
            },
        ),
        migrations.CreateModel(
            name='RecetaAreaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('area', models.CharField(choices=[('HORNOS', 'Hornos'), ('ARMADO', 'Armado'), ('EMBETUNADO', 'Embetunado')], db_index=True, max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Área de producción por receta/familia',
                'verbose_name_plural': 'Áreas de producción por receta/familia',
            },
        ),
        migrations.AddConstraint(
            model_name='costomanoobradiarioarea',
            constraint=models.UniqueConstraint(fields=('fecha', 'area'), name='cmoda_fecha_area_unico'),
        ),
        migrations.AddField(
            model_name='recetaareaproduccion',
            name='receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_produccion', to='recetas.receta'),
        ),
        migrations.AddConstraint(
            model_name='recetaareaproduccion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('familia__gt', ''), ('receta__isnull', True)), models.Q(('familia', ''), ('receta__isnull', False)), _connector='OR'), name='rap_familia_xor_receta'),
        ),
        migrations.AddConstraint(
            model_name='recetaareaproduccion',
            constraint=models.UniqueConstraint(fields=('familia', 'area'), name='rap_familia_area_unico'),
        ),
        migrations.AddConstraint(
            model_name='recetaareaproduccion',
            constraint=models.UniqueConstraint(fields=('receta', 'area'), name='rap_receta_area_unico'),
        ),
    ]
