# Generated by Django 5.0.1 on 2026-07-04 15:52

from django.db import migrations, models

# Únicas 2 fusiones de familia confirmadas por Mauricio (ver PR #867 /
# specs/mano-obra-minutos-estandar.md) — se siembran ya fusionadas para no
# perder esa decisión de negocio al migrar del diccionario fijo a esta tabla.
_FUSIONES_CONFIRMADAS = {
    "Pastel Chico": "Pastel",
    "Pastel Grande": "Pastel",
    "Pastel Mediano": "Pastel",
    "Pastel Mini": "Pastel",
    "Betún y Rellenos": "Betún, Cremas, Rellenos (INSUMO PRODUCIDO)",
}


def sembrar_familia_grupo(apps, schema_editor):
    FamiliaGrupoManoObra = apps.get_model("reportes", "FamiliaGrupoManoObra")
    Receta = apps.get_model("recetas", "Receta")
    Insumo = apps.get_model("maestros", "Insumo")

    familias_reales = set(
        Receta.objects.exclude(familia="").values_list("familia", flat=True).distinct()
    ) | set(
        Insumo.objects.filter(tipo_item="INSUMO_INTERNO")
        .exclude(categoria="")
        .values_list("categoria", flat=True)
        .distinct()
    )
    for familia_real in familias_reales:
        FamiliaGrupoManoObra.objects.get_or_create(
            familia_real=familia_real,
            defaults={"grupo": _FUSIONES_CONFIRMADAS.get(familia_real, familia_real)},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0032_costomanoobradiarioarea_recetaareaproduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaGrupoManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia_real', models.CharField(db_index=True, max_length=120, unique=True)),
                ('grupo', models.CharField(db_index=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Grupo de familia para mano de obra',
                'verbose_name_plural': 'Grupos de familia para mano de obra',
            },
        ),
        migrations.RemoveField(
            model_name='costomanoobradiarioarea',
            name='costo_unidad',
        ),
        migrations.AddField(
            model_name='costomanoobradiarioarea',
            name='costo_minuto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costomanoobradiarioarea',
            name='minutos_demandados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='costomanoobradiarioarea',
            name='minutos_disponibles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='recetaareaproduccion',
            name='lote_minutos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recetaareaproduccion',
            name='lote_personas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recetaareaproduccion',
            name='lote_piezas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(sembrar_familia_grupo, migrations.RunPython.noop),
    ]
