# Generated by Django 5.0.1 on 2026-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0040_repoint_legacy_pay_ingredients'),
        ('reportes', '0033_minutos_estandar_grupo_familia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recetaareaproduccion',
            name='rap_familia_area_unico',
        ),
        migrations.AddField(
            model_name='recetaareaproduccion',
            name='es_grupo_insumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='recetaareaproduccion',
            constraint=models.UniqueConstraint(fields=('familia', 'area', 'es_grupo_insumo'), name='rap_familia_area_unico'),
        ),
    ]
