# Generated by Django 5.0.1 on 2026-07-07 02:58

from django.db import migrations

# Únicas 2 fusiones de familia confirmadas por Mauricio (PR #867/#870) que
# se migran al nuevo campo Receta.grupo_mano_obra, para no perder esas
# decisiones de negocio ya tomadas.
_FUSIONES_CONFIRMADAS = {
    "Pastel Chico": "Pastel",
    "Pastel Grande": "Pastel",
    "Pastel Mediano": "Pastel",
    "Pastel Mini": "Pastel",
    "Betún y Rellenos": "Betún, Cremas, Rellenos (INSUMO PRODUCIDO)",
}


def sembrar_grupo_mano_obra(apps, schema_editor):
    Receta = apps.get_model("recetas", "Receta")
    for familia, grupo in _FUSIONES_CONFIRMADAS.items():
        Receta.objects.filter(familia=familia).update(grupo_mano_obra=grupo)


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0034_remove_recetaareaproduccion_rap_familia_area_unico_and_more'),
        ('recetas', '0041_receta_grupo_mano_obra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamiliaGrupoManoObra',
        ),
        migrations.AlterModelOptions(
            name='recetaareaproduccion',
            options={'verbose_name': 'Área de producción por grupo de mano de obra', 'verbose_name_plural': 'Áreas de producción por grupo de mano de obra'},
        ),
        migrations.RemoveConstraint(
            model_name='recetaareaproduccion',
            name='rap_familia_xor_receta',
        ),
        migrations.RemoveConstraint(
            model_name='recetaareaproduccion',
            name='rap_receta_area_unico',
        ),
        migrations.RemoveField(
            model_name='recetaareaproduccion',
            name='receta',
        ),
        migrations.RunPython(sembrar_grupo_mano_obra, migrations.RunPython.noop),
    ]
