# Generated by Django 5.0.1 on 2026-07-14 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('reportes', '0035_delete_familiagrupomanoobra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaFuenteRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fuente', models.CharField(choices=[('GASTO_OPERATIVO', 'Gasto operativo mensual'), ('NOMINA', 'Nómina RRHH'), ('BONO_PRODUCCION', 'Bonos producción'), ('BONO_VENTAS', 'Bonos ventas'), ('VENTA_POS', 'Ventas POS Point'), ('CONSUMO_MP', 'Consumo materia prima'), ('MANUAL', 'Captura manual')], db_index=True, max_length=30)),
                ('filtros', models.JSONField(blank=True, default=dict, help_text='Parámetros por fuente, p.ej. {"departamento": "VENTAS", "campo_monto": "salario_base", "categoria_pos": "BOLLO", "producto_pos": "CHOCOLATE", "centro_tipo": "CORPORATIVO"}')),
                ('signo', models.SmallIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('origen', models.CharField(choices=[('SEED', 'Seed automático'), ('ADMIN', 'Ajuste manual')], db_index=True, default='ADMIN', max_length=10)),
                ('notas', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria_gasto', models.ForeignKey(blank=True, help_text='Para GASTO_OPERATIVO: categoría a agregar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_fuente_rubro', to='reportes.categoriagasto')),
                ('centro_costo', models.ForeignKey(blank=True, help_text='Para GASTO_OPERATIVO: centro explícito (si no, se usa la sucursal).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglas_fuente_rubro', to='reportes.centrocosto')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_fuente', to='reportes.rubropresupuesto')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Dimensión sucursal; si es nula se usa la del rubro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_fuente_rubro', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Regla de fuente de rubro',
                'verbose_name_plural': 'Reglas de fuente de rubro',
                'ordering': ['rubro__area__orden', 'rubro__concepto', 'tipo_fuente'],
                'indexes': [models.Index(fields=['rubro', 'tipo_fuente'], name='regla_fuente_rubro_tipo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reglafuenterubro',
            constraint=models.CheckConstraint(check=models.Q(('signo__in', (1, -1))), name='regla_fuente_rubro_signo_valido'),
        ),
    ]
