# Generated by Django 5.0.1 on 2026-07-15 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0036_reglafuenterubro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPresupuestoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_capturar', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='reportes.areapresupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_presupuesto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de área de presupuesto',
                'verbose_name_plural': 'Responsables de área de presupuesto',
            },
        ),
        migrations.AddConstraint(
            model_name='areapresupuestoresponsable',
            constraint=models.UniqueConstraint(fields=('area', 'usuario'), name='uniq_area_presu_responsable'),
        ),
    ]
