# Generated by Django 5.0.1 on 2026-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0038_alter_reglafuenterubro_tipo_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglafuenterubro',
            name='tipo_fuente',
            field=models.CharField(choices=[('GASTO_OPERATIVO', 'Gasto operativo mensual'), ('NOMINA', 'Nómina RRHH'), ('BONO_PRODUCCION', 'Bonos producción'), ('BONO_VENTAS', 'Bonos ventas'), ('VENTA_POS', 'Ventas POS Point'), ('CONSUMO_MP', 'Consumo materia prima'), ('MANTENIMIENTO_UNIDAD', 'Mantenimiento de unidad vehicular'), ('COMBUSTIBLE_UNIDAD', 'Combustible de unidad vehicular'), ('MANTENIMIENTO_EQUIPO', 'Mantenimiento de equipos (activos)'), ('MANUAL', 'Captura manual')], db_index=True, max_length=30),
        ),
    ]
