# Generated by Django 5.0.1 on 2026-07-31 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0042_proyectoinversiongasto_tipo_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='reportes.areapresupuesto')),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='reportes.categoriagasto')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='reportes.centrocosto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_recurrentes_creados', to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_recurrentes', to='reportes.rubropresupuesto')),
            ],
            options={
                'verbose_name': 'Gasto recurrente',
                'verbose_name_plural': 'Gastos recurrentes',
                'ordering': ['area__orden', 'concepto', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GastoRecurrenteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia_inicio', models.DateField(db_index=True)),
                ('vigencia_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=1)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('metodo_pago_previsto', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='', max_length=20)),
                ('tipo_credito', models.CharField(blank=True, choices=[('UNICO', 'Un solo vencimiento'), ('DIFERIDO', 'Diferido')], default='', max_length=10)),
                ('plazo_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('plazo_unidad', models.CharField(blank=True, choices=[('DIAS', 'Días'), ('MESES', 'Meses')], default='', max_length=10)),
                ('numero_parcialidades', models.PositiveSmallIntegerField(default=1)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_gasto_recurrente_creadas', to=settings.AUTH_USER_MODEL)),
                ('gasto_recurrente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='reportes.gastorecurrente')),
            ],
            options={
                'verbose_name': 'Versión de gasto recurrente',
                'verbose_name_plural': 'Versiones de gastos recurrentes',
                'ordering': ['-vigencia_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ObligacionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('VARIABLE', 'Variable'), ('RECURRENTE', 'Recurrente')], db_index=True, max_length=12)),
                ('concepto', models.CharField(max_length=200)),
                ('proveedor', models.CharField(blank=True, default='', max_length=200)),
                ('periodo', models.DateField(db_index=True)),
                ('fecha_gasto', models.DateField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('monto_reconocido', models.DecimalField(decimal_places=2, max_digits=18)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10)),
                ('metodo_pago_previsto', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='', max_length=20)),
                ('tipo_credito', models.CharField(blank=True, choices=[('UNICO', 'Un solo vencimiento'), ('DIFERIDO', 'Diferido')], default='', max_length=10)),
                ('plazo_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('plazo_unidad', models.CharField(blank=True, choices=[('DIAS', 'Días'), ('MESES', 'Meses')], default='', max_length=10)),
                ('numero_parcialidades', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('archivo_soporte', models.CharField(blank=True, default='', max_length=300)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_gasto', to='reportes.areapresupuesto')),
                ('categoria_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_gasto', to='reportes.categoriagasto')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_gasto', to='reportes.centrocosto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligaciones_gasto_creadas', to=settings.AUTH_USER_MODEL)),
                ('gasto_operativo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligacion_gasto', to='reportes.gastooperativomensual')),
                ('gasto_recurrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='reportes.gastorecurrente')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_gasto', to='reportes.rubropresupuesto')),
                ('version_recurrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='reportes.gastorecurrenteversion')),
            ],
            options={
                'verbose_name': 'Obligación de gasto',
                'verbose_name_plural': 'Obligaciones de gasto',
                'ordering': ['-periodo', 'fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParcialidadObligacionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcialidades', to='reportes.obligaciongasto')),
            ],
            options={
                'verbose_name': 'Parcialidad de obligación',
                'verbose_name_plural': 'Parcialidades de obligaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoObligacionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(db_index=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=160)),
                ('notas', models.TextField(blank=True, default='')),
                ('registrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reportes.obligaciongasto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_obligacion_registrados', to=settings.AUTH_USER_MODEL)),
                ('parcialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reportes.parcialidadobligaciongasto')),
            ],
            options={
                'verbose_name': 'Pago de obligación',
                'verbose_name_plural': 'Pagos de obligaciones',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='gastorecurrente',
            index=models.Index(fields=['area', 'activo'], name='gasto_rec_area_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='gastorecurrenteversion',
            constraint=models.UniqueConstraint(fields=('gasto_recurrente', 'vigencia_inicio'), name='uniq_gasto_rec_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='gastorecurrenteversion',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='gasto_rec_version_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='gastorecurrenteversion',
            constraint=models.CheckConstraint(check=models.Q(('dia_vencimiento__gte', 1), ('dia_vencimiento__lte', 31)), name='gasto_rec_dia_vencimiento_valido'),
        ),
        migrations.AddIndex(
            model_name='obligaciongasto',
            index=models.Index(fields=['area', 'periodo'], name='obligacion_area_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='obligaciongasto',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='obligacion_estado_vence_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligaciongasto',
            constraint=models.UniqueConstraint(condition=models.Q(('gasto_recurrente__isnull', False)), fields=('gasto_recurrente', 'periodo'), name='uniq_obligacion_recurrente_periodo'),
        ),
        migrations.AddConstraint(
            model_name='obligaciongasto',
            constraint=models.CheckConstraint(check=models.Q(('monto_reconocido__gt', 0)), name='obligacion_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcialidadobligaciongasto',
            constraint=models.UniqueConstraint(fields=('obligacion', 'numero'), name='uniq_obligacion_parcialidad'),
        ),
        migrations.AddConstraint(
            model_name='parcialidadobligaciongasto',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='parcialidad_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagoobligaciongasto',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='pago_obligacion_positivo'),
        ),
    ]
