# Generated by Django 5.0.1 on 2026-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('reportes', '0044_obligacion_gasto_fuente_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglafuenterubro',
            name='clave_fuente',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Huella estable del origen económico para impedir doble conteo.', max_length=64),
        ),
        migrations.AddField(
            model_name='reglafuenterubro',
            name='modo_asignacion',
            field=models.CharField(choices=[('CANONICA', 'Fuente canónica'), ('CONTROL', 'Espejo de control (no sumable)'), ('DISTRIBUCION', 'Distribución porcentual')], db_index=True, default='CANONICA', max_length=20),
        ),
        migrations.AlterField(
            model_name='reglafuenterubro',
            name='tipo_fuente',
            field=models.CharField(choices=[('GASTO_OPERATIVO', 'Gasto operativo mensual'), ('OBLIGACION_GASTO', 'Obligaciones de gasto por rubro'), ('NOMINA', 'Nómina RRHH'), ('NOMINA_CONCEPTO', 'Concepto de nómina RRHH'), ('BONO_PRODUCCION', 'Bonos producción'), ('BONO_VENTAS', 'Bonos ventas'), ('VENTA_POS', 'Ventas POS Point'), ('CONSUMO_MP', 'Consumo materia prima'), ('MANTENIMIENTO_UNIDAD', 'Mantenimiento de unidad vehicular'), ('COMBUSTIBLE_UNIDAD', 'Combustible de unidad vehicular'), ('MANTENIMIENTO_EQUIPO', 'Mantenimiento de equipos (activos)'), ('COSTO_REVENTA', 'Costo de reventa de complementos'), ('MERMA_PRODUCTO', 'Merma física de producto (módulo mermas)'), ('MANUAL', 'Captura manual')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='reglafuenterubro',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('modo_asignacion', 'CANONICA'), models.Q(('clave_fuente', ''), _negated=True)), fields=('clave_fuente',), name='uniq_fuente_canonica_presupuesto'),
        ),
    ]
