# Generated by Django 5.0.1 on 2026-09-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0047_cobertura_gastos_recurrentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastorecurrenteversion',
            name='archivo_soporte',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
