# Generated by Django 5.0.1 on 2026-09-20 19:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cumpleanos_activos_y_avisos'),
        ('reportes', '0048_gastorecurrenteversion_archivo_soporte'),
        ('rrhh', '0046_cumpleanos_activos_y_avisos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteCedulaIMSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral')], max_length=12)),
                ('periodo', models.DateField(db_index=True)),
                ('registro_patronal', models.CharField(db_index=True, max_length=20)),
                ('razon_social', models.CharField(blank=True, default='', max_length=200)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('VALIDO', 'Válido'), ('APLICADO', 'Aplicado'), ('DISCREPANCIA', 'Discrepancia')], max_length=16)),
                ('total_patronal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('trabajadores', models.PositiveIntegerField(default=0)),
                ('cruzados', models.PositiveIntegerField(default=0)),
                ('sin_cruce', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_cedula_imss_aplicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente de cédula IMSS',
                'verbose_name_plural': 'Expedientes de cédulas IMSS',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCedulaIMSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('SUA_XLS', 'SUA XLS'), ('EMA_PDF', 'EMA PDF'), ('EBA_PDF', 'EBA PDF')], max_length=12)),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='reportes/cedulas-imss/%Y/%m/')),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('tamano', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('total_visible', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='reportes.expedientecedulaimss')),
            ],
            options={
                'verbose_name': 'Documento de cédula IMSS',
                'verbose_name_plural': 'Documentos de cédula IMSS',
            },
        ),
        migrations.CreateModel(
            name='DetalleCedulaIMSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(db_index=True, max_length=11)),
                ('nombre_origen', models.CharField(max_length=200)),
                ('dias', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('sdi', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('retiro', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cesantia_patronal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('aportacion_vivienda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cuota_patronal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_codigo', models.CharField(blank=True, default='', max_length=50)),
                ('cruce_estado', models.CharField(choices=[('CRUZADO', 'Cruzado'), ('SIN_CRUCE', 'Sin cruce')], max_length=16)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cedula_imss', to='rrhh.empleado')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cedula_imss', to='core.sucursal')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='reportes.documentocedulaimss')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='reportes.expedientecedulaimss')),
            ],
            options={
                'verbose_name': 'Detalle de cédula IMSS',
                'verbose_name_plural': 'Detalles de cédula IMSS',
            },
        ),
        migrations.AddIndex(
            model_name='expedientecedulaimss',
            index=models.Index(fields=['registro_patronal', 'periodo'], name='cedula_imss_reg_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='expedientecedulaimss',
            constraint=models.UniqueConstraint(fields=('tipo', 'periodo', 'registro_patronal', 'revision'), name='uniq_cedula_imss_revision'),
        ),
        migrations.AddConstraint(
            model_name='expedientecedulaimss',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'APLICADO')), fields=('tipo', 'periodo', 'registro_patronal'), name='uniq_cedula_imss_aplicada'),
        ),
        migrations.AddIndex(
            model_name='detallecedulaimss',
            index=models.Index(fields=['empleado', 'expediente'], name='cedula_imss_emp_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='detallecedulaimss',
            constraint=models.UniqueConstraint(fields=('documento', 'nss'), name='uniq_cedula_imss_nss'),
        ),
        migrations.AddConstraint(
            model_name='detallecedulaimss',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cruce_estado', 'CRUZADO'), ('empleado__isnull', False)), models.Q(('cruce_estado', 'SIN_CRUCE'), ('empleado__isnull', True)), _connector='OR'), name='cedula_imss_cruce_coherente'),
        ),
    ]
