# Generated by Django 5.0.1 on 2026-09-21 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0049_expediente_cedula_imss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gastorecurrenteversion',
            name='gasto_rec_periodicidad_valida',
        ),
        migrations.AlterField(
            model_name='gastorecurrenteversion',
            name='periodicidad_meses',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mensual'), (2, 'Bimestral'), (3, 'Trimestral'), (6, 'Semestral'), (12, 'Anual')], default=1),
        ),
        migrations.AddConstraint(
            model_name='gastorecurrenteversion',
            constraint=models.CheckConstraint(check=models.Q(('periodicidad_meses__in', (1, 2, 3, 6, 12))), name='gasto_rec_periodicidad_valida'),
        ),
    ]
