# Generated by Django 5.0.1 on 2026-09-24 18:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cumpleanos_activos_y_avisos'),
        ('reportes', '0051_documentocedulaimss_sipare_pdf'),
        ('rrhh', '0051_jornadas_semanales'),
        ('sat_client', '0004_documento_sat_pending_connector_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglafuenterubro',
            name='tipo_fuente',
            field=models.CharField(choices=[('GASTO_OPERATIVO', 'Gasto operativo mensual'), ('OBLIGACION_GASTO', 'Obligaciones de gasto por rubro'), ('NOMINA', 'Nómina RRHH'), ('NOMINA_CONCEPTO', 'Concepto de nómina RRHH'), ('BONO_PRODUCCION', 'Bonos producción'), ('BONO_VENTAS', 'Bonos ventas'), ('VENTA_POS', 'Ventas POS Point'), ('CONSUMO_MP', 'Consumo materia prima'), ('MANTENIMIENTO_UNIDAD', 'Mantenimiento de unidad vehicular'), ('COMBUSTIBLE_UNIDAD', 'Combustible de unidad vehicular'), ('MANTENIMIENTO_EQUIPO', 'Mantenimiento de equipos (activos)'), ('COSTO_REVENTA', 'Costo de reventa de complementos'), ('MERMA_PRODUCTO', 'Merma física de producto (módulo mermas)'), ('ISN_CFDI', 'ISN desde CFDI estatal'), ('MANUAL', 'Captura manual')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ExpedienteISN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_gravada_calculada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_declarada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('VALIDO', 'Valido'), ('APLICADO', 'Aplicado'), ('REEMPLAZADO', 'Reemplazado'), ('DISCREPANCIA', 'Discrepancia')], max_length=16)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_isn_aplicados', to=settings.AUTH_USER_MODEL)),
                ('cfdi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expediente_isn', to='sat_client.cfdidescargado')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionISNEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_gravada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_isn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('area_codigo', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_isn', to='rrhh.empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_isn', to='core.sucursal')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='reportes.expedienteisn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.UniqueConstraint(fields=('periodo', 'revision'), name='uniq_isn_periodo_revision'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'APLICADO')), fields=('periodo',), name='uniq_isn_aplicado_periodo'),
        ),
        migrations.AddConstraint(
            model_name='distribucionisnempleado',
            constraint=models.UniqueConstraint(fields=('expediente', 'empleado'), name='uniq_isn_expediente_empleado'),
        ),
    ]
