# Generated by Django 5.0.1 on 2026-09-24 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cumpleanos_activos_y_avisos'),
        ('reportes', '0052_expediente_isn'),
        ('rrhh', '0051_jornadas_semanales'),
        ('sat_client', '0004_documento_sat_pending_connector_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='distribucionisnempleado',
            constraint=models.CheckConstraint(check=models.Q(('base_gravada__gte', 0)), name='isn_dist_base_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='distribucionisnempleado',
            constraint=models.CheckConstraint(check=models.Q(('monto_isn__gte', 0)), name='isn_dist_monto_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('periodo__day', 1)), name='isn_periodo_primer_dia'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='isn_revision_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('importe_pagado__gt', 0)), name='isn_importe_pagado_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('base_gravada_calculada__gte', 0)), name='isn_base_calculada_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('base_declarada__isnull', True), ('base_declarada__gte', 0), _connector='OR'), name='isn_base_declarada_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ('VALIDO', 'APLICADO', 'REEMPLAZADO', 'DISCREPANCIA'))), name='isn_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('aplicado_en__isnull', False), ('estado', 'APLICADO')), models.Q(models.Q(('estado', 'APLICADO'), _negated=True), ('aplicado_en__isnull', True)), _connector='OR'), name='isn_aplicacion_fecha_coherente'),
        ),
    ]
