# Generated by Django 5.0.1 on 2026-09-24 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0053_integridad_expediente_isn'),
        ('sat_client', '0004_documento_sat_pending_connector_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expedienteisn',
            name='isn_aplicacion_fecha_coherente',
        ),
        migrations.AddConstraint(
            model_name='expedienteisn',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('aplicado_en__isnull', False), ('estado__in', ('APLICADO', 'REEMPLAZADO'))), models.Q(models.Q(('estado__in', ('APLICADO', 'REEMPLAZADO')), _negated=True), ('aplicado_en__isnull', True)), _connector='OR'), name='isn_aplicacion_fecha_coherente'),
        ),
    ]
