# Generated by Django 5.0.1 on 2026-09-28 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0021_pointhistoricalinventoryclosing_and_more'),
        ('reportes', '0054_estado_aplicacion_isn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('READY', 'Lista'), ('SOURCE_INCOMPLETE', 'Fuente incompleta')], default='READY', max_length=24)),
                ('source_issues', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('calculation_fingerprint', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('rebuilt_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_rebuild_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corrida de auditoría de inventario',
                'verbose_name_plural': 'Corridas de auditoría de inventario',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryAuditCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('opening_point', models.DecimalField(decimal_places=4, max_digits=18)),
                ('production', models.DecimalField(decimal_places=4, max_digits=18)),
                ('sales', models.DecimalField(decimal_places=4, max_digits=18)),
                ('waste', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transfer_in', models.DecimalField(decimal_places=4, max_digits=18)),
                ('transfer_out', models.DecimalField(decimal_places=4, max_digits=18)),
                ('conversion_in', models.DecimalField(decimal_places=4, max_digits=18)),
                ('conversion_out', models.DecimalField(decimal_places=4, max_digits=18)),
                ('identified_adjustment', models.DecimalField(decimal_places=4, max_digits=18)),
                ('expected_closing', models.DecimalField(decimal_places=4, max_digits=18)),
                ('point_closing', models.DecimalField(decimal_places=4, max_digits=18)),
                ('difference', models.DecimalField(decimal_places=4, max_digits=18)),
                ('point_closing_status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('PROTECTED', 'Protegido')], default='AVAILABLE', max_length=16)),
                ('movement_status', models.CharField(choices=[('BALANCED', 'Conciliado'), ('NEEDS_EXPLANATION', 'Pendiente de explicación'), ('PENDING_APPROVAL', 'Explicación pendiente de aprobación'), ('RESOLVED', 'Resuelto y aprobado'), ('SOURCE_INCOMPLETE', 'Fuente incompleta')], default='NEEDS_EXPLANATION', max_length=24)),
                ('physical_status', models.CharField(choices=[('NOT_AVAILABLE', 'Sin conteo manual')], default='NOT_AVAILABLE', max_length=20)),
                ('issue_codes', models.JSONField(blank=True, default=list)),
                ('source_trace', models.JSONField(blank=True, default=dict)),
                ('calculation_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('rebuilt_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_cases', to='pos_bridge.pointbranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_cases', to='pos_bridge.pointproduct')),
            ],
            options={
                'verbose_name': 'Caso de auditoría de inventario',
                'verbose_name_plural': 'Casos de auditoría de inventario',
                'ordering': ['month', 'branch_id', 'product_id'],
                'permissions': [('approve_product_inventory_audit', 'Puede aprobar auditorías de inventario')],
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('EXPLAIN', 'Explicar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('REOPEN', 'Reabrir')], max_length=12)),
                ('reason_code', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='reportes/inventory-audit/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inventory_audit_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reportes.productinventoryauditcase')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_events', to='reportes.productinventoryauditevent')),
            ],
            options={
                'verbose_name': 'Evento de auditoría de inventario',
                'verbose_name_plural': 'Eventos de auditoría de inventario',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditrun',
            constraint=models.CheckConstraint(check=models.Q(('month__day', 1)), name='inv_audit_run_month_day_1'),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='reportes.productinventoryauditrun'),
        ),
        migrations.AddIndex(
            model_name='productinventoryauditevent',
            index=models.Index(fields=['case', 'created_at'], name='inv_audit_event_case_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventoryauditcase',
            index=models.Index(fields=['month', 'movement_status'], name='inv_audit_month_move_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventoryauditcase',
            index=models.Index(fields=['month', 'branch'], name='inv_audit_month_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventoryauditcase',
            index=models.Index(fields=['month', 'point_closing_status'], name='inv_audit_month_point_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditcase',
            constraint=models.CheckConstraint(check=models.Q(('month__day', 1)), name='inv_audit_case_month_day_1'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditcase',
            constraint=models.UniqueConstraint(fields=('month', 'branch', 'product'), name='uniq_inv_audit_month_branch_product'),
        ),
    ]
