# Generated by Django 5.0.1 on 2026-09-28 16:44

import reportes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0055_productinventoryauditrun_productinventoryauditcase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventoryauditevent',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['created_at', 'id'], 'verbose_name': 'Evento de auditoría de inventario', 'verbose_name_plural': 'Eventos de auditoría de inventario'},
        ),
        migrations.AlterField(
            model_name='productinventoryauditrun',
            name='summary',
            field=models.JSONField(blank=True, default=reportes.models.default_product_inventory_audit_summary),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('action__in', ('APPROVE', 'REJECT')), _negated=True), ('related_event__isnull', False), _connector='OR'), name='inv_audit_review_has_explain'),
        ),
    ]
