# Generated by Django 5.0.1 on 2026-09-28 16:53

from django.db import migrations


CREATE_EVENT_GUARD_SQL = """
CREATE FUNCTION reportes_guard_product_inventory_audit_event()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    related_action varchar;
    related_case_id bigint;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Los eventos de auditoría de inventario son inmutables.'
            USING ERRCODE = '23000';
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.actor_id IS NOT NULL
           AND NEW.actor_id IS NULL
           AND (to_jsonb(OLD) - 'actor_id') = (to_jsonb(NEW) - 'actor_id') THEN
            RETURN NEW;
        END IF;

        RAISE EXCEPTION 'Los eventos de auditoría de inventario son inmutables.'
            USING ERRCODE = '23000';
    END IF;

    IF NEW.action IN ('APPROVE', 'REJECT') THEN
        IF NEW.related_event_id IS NULL THEN
            RAISE EXCEPTION 'La revisión requiere una explicación relacionada.'
                USING ERRCODE = '23514';
        END IF;

        SELECT action, case_id
        INTO related_action, related_case_id
        FROM reportes_productinventoryauditevent
        WHERE id = NEW.related_event_id;

        IF NOT FOUND
           OR related_action <> 'EXPLAIN'
           OR related_case_id <> NEW.case_id THEN
            RAISE EXCEPTION 'La revisión debe referenciar una explicación del mismo caso.'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER reportes_product_inventory_audit_event_guard
BEFORE INSERT OR UPDATE OR DELETE
ON reportes_productinventoryauditevent
FOR EACH ROW
EXECUTE FUNCTION reportes_guard_product_inventory_audit_event();

CREATE FUNCTION reportes_guard_inventory_audit_actor_clear()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.actor_id IS NOT NULL
       AND NEW.actor_id IS NULL
       AND EXISTS (SELECT 1 FROM auth_user WHERE id = OLD.actor_id) THEN
        RAISE EXCEPTION 'actor_id solo puede limpiarse al eliminar al usuario.'
            USING ERRCODE = '23503';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER reportes_inventory_audit_actor_clear_guard
AFTER UPDATE
ON reportes_productinventoryauditevent
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
WHEN (OLD.actor_id IS DISTINCT FROM NEW.actor_id)
EXECUTE FUNCTION reportes_guard_inventory_audit_actor_clear();
"""


DROP_EVENT_GUARD_SQL = """
DROP TRIGGER IF EXISTS reportes_inventory_audit_actor_clear_guard
ON reportes_productinventoryauditevent;
DROP TRIGGER IF EXISTS reportes_product_inventory_audit_event_guard
ON reportes_productinventoryauditevent;
DROP FUNCTION IF EXISTS reportes_guard_inventory_audit_actor_clear();
DROP FUNCTION IF EXISTS reportes_guard_product_inventory_audit_event();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0056_alter_productinventoryauditevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventoryauditevent',
            options={'default_manager_name': 'objects', 'ordering': ['created_at', 'id'], 'verbose_name': 'Evento de auditoría de inventario', 'verbose_name_plural': 'Eventos de auditoría de inventario'},
        ),
        migrations.RunSQL(
            sql=CREATE_EVENT_GUARD_SQL,
            reverse_sql=DROP_EVENT_GUARD_SQL,
        ),
    ]
