# Generated by Django 5.0.1 on 2026-09-28 17:09

from django.conf import settings
from django.db import migrations, models


CREATE_AUDIT_CONTRACT_GUARDS_SQL = """
ALTER TABLE reportes_productinventoryauditevent
ADD CONSTRAINT inv_audit_event_metadata_object
CHECK (jsonb_typeof(metadata) = 'object');

CREATE FUNCTION reportes_guard_inventory_audit_case_month()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    run_month date;
BEGIN
    SELECT month
    INTO run_month
    FROM reportes_productinventoryauditrun
    WHERE id = NEW.run_id;

    IF NOT FOUND OR NEW.month IS DISTINCT FROM run_month THEN
        RAISE EXCEPTION 'El mes del caso debe coincidir con el mes de la corrida.'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER reportes_inventory_audit_case_month_guard
BEFORE INSERT OR UPDATE OF month, run_id
ON reportes_productinventoryauditcase
FOR EACH ROW
EXECUTE FUNCTION reportes_guard_inventory_audit_case_month();

CREATE FUNCTION reportes_guard_inventory_audit_run_month()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.month IS DISTINCT FROM OLD.month
       AND EXISTS (
           SELECT 1
           FROM reportes_productinventoryauditcase
           WHERE run_id = OLD.id
       ) THEN
        RAISE EXCEPTION 'No puede cambiarse el mes de una corrida con casos.'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER reportes_inventory_audit_run_month_guard
BEFORE UPDATE OF month
ON reportes_productinventoryauditrun
FOR EACH ROW
EXECUTE FUNCTION reportes_guard_inventory_audit_run_month();
"""


DROP_AUDIT_CONTRACT_GUARDS_SQL = """
DROP TRIGGER IF EXISTS reportes_inventory_audit_run_month_guard
ON reportes_productinventoryauditrun;
DROP TRIGGER IF EXISTS reportes_inventory_audit_case_month_guard
ON reportes_productinventoryauditcase;
DROP FUNCTION IF EXISTS reportes_guard_inventory_audit_run_month();
DROP FUNCTION IF EXISTS reportes_guard_inventory_audit_case_month();
ALTER TABLE reportes_productinventoryauditevent
DROP CONSTRAINT IF EXISTS inv_audit_event_metadata_object;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0021_pointhistoricalinventoryclosing_and_more'),
        ('reportes', '0057_alter_productinventoryauditevent_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productinventoryauditcase',
            constraint=models.CheckConstraint(check=models.Q(('point_closing_status__in', ('AVAILABLE', 'PROTECTED'))), name='inv_audit_point_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditcase',
            constraint=models.CheckConstraint(check=models.Q(('movement_status__in', ('BALANCED', 'NEEDS_EXPLANATION', 'PENDING_APPROVAL', 'RESOLVED', 'SOURCE_INCOMPLETE'))), name='inv_audit_move_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditcase',
            constraint=models.CheckConstraint(check=models.Q(('physical_status', 'NOT_AVAILABLE')), name='inv_audit_physical_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditevent',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ('EXPLAIN', 'APPROVE', 'REJECT', 'REOPEN'))), name='inv_audit_event_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditevent',
            constraint=models.CheckConstraint(check=models.Q(('reason_code__regex', '^\\s*$'), _negated=True), name='inv_audit_event_reason_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='productinventoryauditrun',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('READY', 'SOURCE_INCOMPLETE'))), name='inv_audit_run_status_valid'),
        ),
        migrations.RunSQL(
            sql=CREATE_AUDIT_CONTRACT_GUARDS_SQL,
            reverse_sql=DROP_AUDIT_CONTRACT_GUARDS_SQL,
        ),
    ]
