# Generated by Django 5.0.1 on 2026-09-28 17:19

from django.db import migrations


LOCK_RUN_WHILE_VALIDATING_CASE_SQL = """
CREATE OR REPLACE FUNCTION reportes_guard_inventory_audit_case_month()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    run_month date;
BEGIN
    SELECT month
    INTO run_month
    FROM reportes_productinventoryauditrun
    WHERE id = NEW.run_id
    FOR SHARE;

    IF NOT FOUND OR NEW.month IS DISTINCT FROM run_month THEN
        RAISE EXCEPTION 'El mes del caso debe coincidir con el mes de la corrida.'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
"""


RESTORE_UNLOCKED_CASE_MONTH_GUARD_SQL = """
CREATE OR REPLACE FUNCTION reportes_guard_inventory_audit_case_month()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    run_month date;
BEGIN
    SELECT month
    INTO run_month
    FROM reportes_productinventoryauditrun
    WHERE id = NEW.run_id;

    IF NOT FOUND OR NEW.month IS DISTINCT FROM run_month THEN
        RAISE EXCEPTION 'El mes del caso debe coincidir con el mes de la corrida.'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0058_productinventoryauditcase_inv_audit_point_status_valid_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=LOCK_RUN_WHILE_VALIDATING_CASE_SQL,
            reverse_sql=RESTORE_UNLOCKED_CASE_MONTH_GUARD_SQL,
        ),
    ]
