# Generated by Django 5.0.1 on 2026-09-28 23:05

import reportes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0059_lock_inventory_audit_case_run_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventoryauditevent',
            name='evidence',
            field=models.FileField(blank=True, null=True, storage=reportes.storage.InventoryAuditEvidenceStorage(), upload_to=''),
        ),
    ]
