# Generated by Django 5.0.1 on 2026-09-29 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0060_private_inventory_audit_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='assignment_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='attention_level',
            field=models.CharField(choices=[('GROUPED', 'Agrupado para revisión'), ('NORMAL', 'Revisión normal'), ('HIGH', 'Atención inmediata')], db_index=True, default='GROUPED', max_length=12),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='investigated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='investigation_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='investigation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='last_notified_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='productinventoryauditcase',
            name='responsible_area',
            field=models.CharField(choices=[('LOGISTICS', 'Logística'), ('SALES', 'Ventas'), ('PRODUCTION', 'Producción / CEDIS'), ('ADMINISTRATION', 'Administración')], db_index=True, default='ADMINISTRATION', max_length=20),
        ),
    ]
