# Generated by Django 5.0.1 on 2026-10-07 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0023_enforce_open_transfer_snapshot_append_only'),
        ('reportes', '0061_inventory_audit_investigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryDocumentaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('action', models.CharField(choices=[('CLOSE', 'Cierre documental'), ('REOPEN', 'Reabrir cierre documental')], max_length=8)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_bridge.pointbranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos_bridge.pointproduct')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['month', 'branch', 'product', '-id'], name='inv_doc_pair_latest_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productinventorydocumentaryevent',
            constraint=models.CheckConstraint(check=models.Q(('month__day', 1)), name='inv_doc_month_day_1'),
        ),
        migrations.AddConstraint(
            model_name='productinventorydocumentaryevent',
            constraint=models.CheckConstraint(check=models.Q(('action__in', ('CLOSE', 'REOPEN'))), name='inv_doc_action_valid'),
        ),
    ]
