# Generated by Django 5.0.1 on 2026-10-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0062_productinventorydocumentaryevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventoryauditrun',
            name='partial_published',
            field=models.BooleanField(default=False),
        ),
    ]
