# Generated by Django 5.0.1 on 2026-06-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_solicitudcancelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre del contacto')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('especialidad', models.CharField(blank=True, default='', help_text='Ej. Refrigeración, Electricidad, Mecánica general', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor de servicio',
                'verbose_name_plural': 'Proveedores de servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
