# Generated by Django 5.0.1 on 2026-07-22 17:13

import django.db.models.deletion
import django.utils.timezone
import mantenimiento.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_trazabilidad_mantenimiento'),
        ('core', '0019_alter_usermoduleaccess_module'),
        ('logistica', '0042_serviciorealizadounidad_anulacion'),
        ('maestros', '0016_alter_insumo_tipo_item'),
        ('mantenimiento', '0005_proveedorservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default=mantenimiento.models._folio_servicio_mantenimiento, editable=False, max_length=24, unique=True)),
                ('fecha_servicio', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('responsable', models.CharField(blank=True, default='', max_length=120)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=80, verbose_name='Factura / nota / remisión')),
                ('documento', models.FileField(blank=True, help_text='PDF o imagen de la factura, nota o remisión.', null=True, upload_to='mantenimiento/servicios/%Y/%m/')),
                ('descripcion_general', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('metodo_distribucion', models.CharField(choices=[('SIN_DESGLOSE', 'Sin desglose por objetivo'), ('DESGLOSE_REAL', 'Desglose indicado por el proveedor'), ('PRORRATEO', 'Prorrateo administrativo')], default='SIN_DESGLOSE', max_length=16)),
                ('clave_origen', models.CharField(blank=True, help_text='Clave idempotente para importaciones históricas.', max_length=160, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_mantenimiento_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_mantenimiento_agrupados', to='maestros.proveedor')),
            ],
            options={
                'verbose_name': 'Servicio de mantenimiento',
                'verbose_name_plural': 'Servicios de mantenimiento',
                'ordering': ['-fecha_servicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objetivo', models.CharField(choices=[('ACTIVO', 'Equipo / activo'), ('UNIDAD', 'Unidad logística'), ('INSTALACION', 'Trabajo en instalaciones')], max_length=16)),
                ('instalacion_categoria', models.CharField(blank=True, default='', max_length=120)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=160)),
                ('trabajo_realizado', models.TextField()),
                ('costo_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('costo_estimado', models.BooleanField(default=False)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio_mantenimiento', to='activos.activo')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_instalaciones_mantenimiento', to='core.sucursal')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_servicio_mantenimiento', to='logistica.unidad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.serviciomantenimiento')),
            ],
            options={
                'verbose_name': 'Alcance de servicio de mantenimiento',
                'verbose_name_plural': 'Alcances de servicio de mantenimiento',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviciomantenimiento',
            constraint=models.CheckConstraint(check=models.Q(('costo_total__gte', 0)), name='servicio_mant_costo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalleserviciomantenimiento',
            constraint=models.CheckConstraint(check=models.Q(('costo_asignado__isnull', True), ('costo_asignado__gte', 0), _connector='OR'), name='detalle_servicio_costo_no_negativo'),
        ),
    ]
