# Generated by Django 5.0.1 on 2026-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_proveedorservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorservicio',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp / celular'),
        ),
    ]
