# Generated by Django 5.0.1 on 2026-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_trazabilidad_mantenimiento'),
        ('core', '0019_alter_usermoduleaccess_module'),
        ('logistica', '0042_serviciorealizadounidad_anulacion'),
        ('mantenimiento', '0006_serviciomantenimiento_detalleserviciomantenimiento_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleserviciomantenimiento',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activo__isnull', False), ('instalacion_categoria', ''), ('sucursal__isnull', True), ('tipo_objetivo', 'ACTIVO'), ('unidad__isnull', True)), models.Q(('activo__isnull', True), ('instalacion_categoria', ''), ('sucursal__isnull', True), ('tipo_objetivo', 'UNIDAD'), ('unidad__isnull', False)), models.Q(('activo__isnull', True), ('instalacion_categoria__gt', ''), ('sucursal__isnull', False), ('tipo_objetivo', 'INSTALACION'), ('unidad__isnull', True)), _connector='OR'), name='detalle_servicio_objetivo_coherente'),
        ),
    ]
