# Generated by Django 5.0.1 on 2026-10-02 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        ('fallas', '0008_reportefalla_duplicado_de_and_more'),
        ('mantenimiento', '0006_proveedorservicio_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoAtencionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(max_length=2000)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_atencion_creados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_atencion', to='activos.ordenmantenimiento')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_atencion', to='fallas.reportefalla')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='vinculoatencionequipo',
            constraint=models.UniqueConstraint(fields=('orden', 'reporte'), name='mantenimiento_vinculo_orden_reporte_uniq'),
        ),
    ]
