# Generated by Django 5.0.1 on 2026-10-02 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        ('mantenimiento', '0007_vinculoatencionequipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCapturaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(max_length=32)),
                ('clave', models.UUIDField()),
                ('huella', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.ordenmantenimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='comprobantecapturaequipo',
            constraint=models.UniqueConstraint(fields=('usuario', 'operacion', 'clave'), name='mant_captura_usuario_op_clave_uniq'),
        ),
    ]
