# Generated by Django 5.0.1 on 2026-07-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('mantenimiento', '0007_detalleserviciomantenimiento_detalle_servicio_objetivo_coherente'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomantenimiento',
            name='sucursal_cargo',
            field=models.ForeignKey(blank=True, help_text='Centro de costo del documento cuando no existe desglose por alcance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_mantenimiento_cargados', to='core.sucursal'),
        ),
    ]
