# Generated by Django 5.0.1 on 2026-10-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0016_alter_insumo_tipo_item'),
        ('mantenimiento', '0009_comprobanteconfiguracionplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoProveedorDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_original_id', models.PositiveBigIntegerField(editable=False)),
                ('proveedor_original_id', models.PositiveBigIntegerField(editable=False)),
                ('motivo', models.TextField()),
                ('evidencia', models.TextField()),
                ('autor_original_id', models.PositiveBigIntegerField(editable=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_proveedores_confirmados', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_documentales', to='mantenimiento.proveedorservicio')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinculos_tecnicos_documentales', to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='vinculoproveedordocumental',
            constraint=models.UniqueConstraint(fields=('perfil_original_id', 'proveedor_original_id'), name='mant_vinculo_proveedor_par_unico'),
        ),
    ]
