# Generated by Django 5.0.1 on 2026-10-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        ('fallas', '0008_reportefalla_duplicado_de_and_more'),
        ('mantenimiento', '0010_vinculo_proveedor_documental'),
        ('reportes', '0061_inventory_audit_investigation'),
        ('sat_client', '0004_documento_sat_pending_connector_state'),
        ('syncfy_client', '0004_alter_movimientobancario_tipo_conciliacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFinancieroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.CharField(choices=[('orden', 'Orden'), ('falla', 'Incidencia')], max_length=8)),
                ('trabajo_original_id', models.PositiveBigIntegerField(editable=False)),
                ('tipo_documento', models.CharField(choices=[('obligacion', 'Obligación'), ('gasto', 'Gasto'), ('cfdi', 'CFDI'), ('movimiento', 'Movimiento')], max_length=12)),
                ('documento_original_id', models.PositiveBigIntegerField(editable=False)),
                ('orden_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('falla_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('obligacion_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('gasto_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('cfdi_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('movimiento_original_id', models.PositiveBigIntegerField(editable=False, null=True)),
                ('motivo', models.TextField(max_length=2000)),
                ('evidencia', models.TextField(max_length=4000)),
                ('autor_original_id', models.PositiveBigIntegerField(editable=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_trabajo_confirmados', to=settings.AUTH_USER_MODEL)),
                ('cfdi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_documentados', to='sat_client.cfdidescargado')),
                ('falla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_financieros', to='fallas.reportefalla')),
                ('gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_documentados', to='reportes.gastooperativomensual')),
                ('movimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_documentados', to='syncfy_client.movimientobancario')),
                ('obligacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_documentados', to='reportes.obligaciongasto')),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_financieros', to='activos.ordenmantenimiento')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.UniqueConstraint(fields=('tipo_trabajo', 'trabajo_original_id', 'tipo_documento', 'documento_original_id'), name='mant_trabajo_documento_unico'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('gasto_original_id__isnull', False)), fields=('tipo_trabajo', 'trabajo_original_id', 'gasto_original_id'), name='mant_trabajo_gasto_unico'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('falla_original_id__isnull', True), ('orden_original_id', models.F('trabajo_original_id')), ('orden_original_id__isnull', False), ('tipo_trabajo', 'orden')), models.Q(('falla_original_id', models.F('trabajo_original_id')), ('falla_original_id__isnull', False), ('orden_original_id__isnull', True), ('tipo_trabajo', 'falla')), _connector='OR'), name='mant_documento_trabajo_tipo'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cfdi_original_id__isnull', True), ('movimiento_original_id__isnull', True), ('obligacion_original_id', models.F('documento_original_id')), ('obligacion_original_id__isnull', False), ('tipo_documento', 'obligacion')), models.Q(('cfdi_original_id__isnull', True), ('gasto_original_id', models.F('documento_original_id')), ('gasto_original_id__isnull', False), ('movimiento_original_id__isnull', True), ('obligacion_original_id__isnull', True), ('tipo_documento', 'gasto')), models.Q(('cfdi_original_id', models.F('documento_original_id')), ('cfdi_original_id__isnull', False), ('gasto_original_id__isnull', True), ('movimiento_original_id__isnull', True), ('obligacion_original_id__isnull', True), ('tipo_documento', 'cfdi')), models.Q(('cfdi_original_id__isnull', True), ('gasto_original_id__isnull', True), ('movimiento_original_id', models.F('documento_original_id')), ('movimiento_original_id__isnull', False), ('obligacion_original_id__isnull', True), ('tipo_documento', 'movimiento')), _connector='OR'), name='mant_documento_fuente_tipo'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('orden__isnull', True), models.Q(('orden_id', models.F('orden_original_id')), ('orden_original_id__isnull', False)), _connector='OR'), name='mant_doc_orden_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('falla__isnull', True), models.Q(('falla_id', models.F('falla_original_id')), ('falla_original_id__isnull', False)), _connector='OR'), name='mant_doc_falla_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('obligacion__isnull', True), models.Q(('obligacion_id', models.F('obligacion_original_id')), ('obligacion_original_id__isnull', False)), _connector='OR'), name='mant_doc_obligacion_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('gasto__isnull', True), models.Q(('gasto_id', models.F('gasto_original_id')), ('gasto_original_id__isnull', False)), _connector='OR'), name='mant_doc_gasto_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('cfdi__isnull', True), models.Q(('cfdi_id', models.F('cfdi_original_id')), ('cfdi_original_id__isnull', False)), _connector='OR'), name='mant_doc_cfdi_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('movimiento__isnull', True), models.Q(('movimiento_id', models.F('movimiento_original_id')), ('movimiento_original_id__isnull', False)), _connector='OR'), name='mant_doc_movimiento_original'),
        ),
        migrations.AddConstraint(
            model_name='documentofinancierotrabajo',
            constraint=models.CheckConstraint(check=models.Q(('autor__isnull', True), models.Q(('autor_id', models.F('autor_original_id')), ('autor_original_id__isnull', False)), _connector='OR'), name='mant_doc_autor_original'),
        ),
    ]
