# Generated by Django 5.0.1 on 2026-04-28 06:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('recetas', '0028_receta_excluir_cierre_recetaequivalencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('venta_proyectada', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('unidades_proyectadas', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('unidades_proyectadas_ajustadas', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('factor_merma', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('factor_devolucion', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('metodo', models.CharField(default='PROMEDIO_MOVIL_7D', max_length=50)),
                ('confianza', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=10)),
                ('dias_historial', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecciones_produccion', to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones_produccion', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Proyección de producción',
                'verbose_name_plural': 'Proyecciones de producción',
                'ordering': ['periodo', 'sucursal__codigo', 'receta__nombre'],
                'indexes': [models.Index(fields=['periodo', 'sucursal'], name='proy_prod_period_suc_idx'), models.Index(fields=['periodo', 'receta'], name='proy_prod_period_rec_idx')],
                'unique_together': {('periodo', 'receta', 'sucursal')},
            },
        ),
    ]
