# Generated by Django 5.0.1 on 2026-04-28 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastQuincenalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTO_REVISION', 'Listo para revisión'), ('APROBADO', 'Aprobado')], db_index=True, default='BORRADOR', max_length=24)),
                ('recetas_proyectadas', models.PositiveIntegerField(default=0)),
                ('registros_generados', models.PositiveIntegerField(default=0)),
                ('recetas_anomalas', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_quincenal_runs_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrida forecast quincenal',
                'verbose_name_plural': 'Corridas forecast quincenal',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
    ]
