from __future__ import annotations


AGENTS = [
    {
        "code": "director_operativo",
        "name": "Director Operativo",
        "domain": "operaciones",
        "status": "active",
        "description": "Coordina prioridades, escala riesgos y consolida el estado operativo.",
        "owner_department_code": "OPS",
        "system_prompt_version": "v1",
        "allowed_tools_json": [
            "api.reportes_bi_dashboard",
            "api.audit_logs",
            "api.integraciones_point_resumen",
            "api.pos_bridge_sync_jobs",
        ],
        "allowed_actions_json": [
            "delegate",
            "summarize",
            "request_approval",
        ],
        "supported_goal_types_json": [
            "operational_chain_review",
        ],
        "context_files_json": [
            ".agent/skills/60-automation-ops/skill-agent-runtime-foundation/SKILL.md",
            ".agent/skills/60-automation-ops/skill-sales-event-publication-guard/SKILL.md",
        ],
        "blocking_rules_json": [
            "no_missing_context",
            "no_invalid_handoff",
        ],
        "handoff_targets_json": [
            "agente_publicacion_eventos_ventas",
            "agente_produccion",
            "agente_compras",
            "agente_conciliacion",
        ],
        "requires_human_approval_default": True,
        "priority_order": 10,
    },
    {
        "code": "agente_demanda_ventas",
        "name": "Agente de Demanda y Ventas",
        "domain": "ventas",
        "status": "active",
        "description": "Analiza demanda, forecast, estacionalidad y stock minimo de arranque por sucursal.",
        "owner_department_code": "VENTAS",
        "system_prompt_version": "v1",
        "allowed_tools_json": [
            "api.pos_bridge_sales_summary",
            "api.pos_bridge_sales_branch",
            "api.pos_bridge_sales_product",
            "api.ventas_historial",
            "api.ventas_pronostico",
        ],
        "allowed_actions_json": [
            "forecast_review",
            "seasonality_alert",
            "product_special_request",
        ],
        "supported_goal_types_json": [],
        "context_files_json": [],
        "blocking_rules_json": [],
        "handoff_targets_json": [],
        "requires_human_approval_default": True,
        "priority_order": 20,
    },
    {
        "code": "agente_produccion",
        "name": "Agente de Produccion",
        "domain": "produccion",
        "status": "active",
        "description": "Traduce demanda validada a necesidades de produccion, revisando capacidad y vida util.",
        "owner_department_code": "PROD",
        "system_prompt_version": "v1",
        "allowed_tools_json": [
            "api.mrp_explode",
            "api.mrp_requerimientos",
            "api.mrp_planes",
            "api.recetas_versiones",
        ],
        "allowed_actions_json": [
            "build_production_recommendation",
            "capacity_alert",
            "recipe_gap_review",
        ],
        "supported_goal_types_json": [
            "production_readiness_guard",
        ],
        "context_files_json": [
            ".agent/skills/60-automation-ops/skill-agent-runtime-foundation/SKILL.md",
        ],
        "blocking_rules_json": [
            "event_not_ready_for_production",
            "production_plan_missing",
        ],
        "handoff_targets_json": [
            "agente_compras",
        ],
        "requires_human_approval_default": True,
        "priority_order": 30,
    },
    {
        "code": "agente_compras",
        "name": "Agente de Compras",
        "domain": "compras",
        "status": "active",
        "description": "Convierte plan validado en necesidades de insumo y prioriza abastecimiento.",
        "owner_department_code": "COMPRAS",
        "system_prompt_version": "v1",
        "allowed_tools_json": [
            "api.inventario_sugerencias_compra",
            "api.pos_bridge_inventory_low_stock",
            "api.compras_solicitudes",
            "api.compras_ordenes",
        ],
        "allowed_actions_json": [
            "purchase_request_recommendation",
            "supplier_risk_alert",
            "inventory_refresh_request",
        ],
        "supported_goal_types_json": [
            "purchase_review_guard",
        ],
        "context_files_json": [
            ".agent/skills/60-automation-ops/skill-agent-runtime-foundation/SKILL.md",
        ],
        "blocking_rules_json": [
            "event_not_validated_by_production",
            "input_requirements_missing",
            "purchase_requirements_missing",
        ],
        "handoff_targets_json": [
            "agente_conciliacion",
        ],
        "requires_human_approval_default": True,
        "priority_order": 40,
    },
    {
        "code": "agente_conciliacion",
        "name": "Agente de Conciliacion",
        "domain": "conciliacion",
        "status": "active",
        "description": "Detecta desviaciones entre Point, ERP, ventas, produccion e inventario.",
        "owner_department_code": "ADMIN",
        "system_prompt_version": "v1",
        "allowed_tools_json": [
            "api.control_discrepancias",
            "api.integraciones_point_historial",
            "api.pos_bridge_sync_jobs",
            "api.audit_logs",
        ],
        "allowed_actions_json": [
            "reconciliation_review",
            "retry_sync_request",
            "issue_escalation",
        ],
        "supported_goal_types_json": [
            "reconciliation_guard",
        ],
        "context_files_json": [
            ".agent/skills/60-automation-ops/skill-agent-runtime-foundation/SKILL.md",
        ],
        "blocking_rules_json": [
            "artifact_disk_db_mismatch",
            "financial_publication_mismatch",
        ],
        "handoff_targets_json": [],
        "requires_human_approval_default": True,
        "priority_order": 50,
    },
    {
        "code": "agente_publicacion_eventos_ventas",
        "name": "Agente de Publicacion de Eventos de Ventas",
        "domain": "ventas",
        "status": "active",
        "description": (
            "Valida taxonomia, workflow, artifacts y consistencia financiera antes de permitir "
            "publicacion de paquetes comerciales."
        ),
        "owner_department_code": "VENTAS",
        "system_prompt_version": "v1-agent-runtime",
        "allowed_tools_json": [
            "skill.sales_event_publication_guard",
            "python.ventas.publication_guard",
            "orm.ventas.sales_event",
            "orm.ventas.projection_artifacts",
        ],
        "allowed_actions_json": [
            "review_publication",
            "publish_if_safe",
            "block_publication",
        ],
        "supported_goal_types_json": [
            "sales_event_publication_guard",
        ],
        "context_files_json": [
            ".agent/skills/60-automation-ops/skill-agent-runtime-foundation/SKILL.md",
            ".agent/skills/60-automation-ops/skill-sales-event-publication-guard/SKILL.md",
        ],
        "blocking_rules_json": [
            "workflow_gate_not_ready",
            "unknown_base_methods",
            "mature_branch_without_base",
            "financials_missing",
        ],
        "handoff_targets_json": [
            "agente_produccion",
        ],
        "requires_human_approval_default": True,
        "priority_order": 25,
    },
]


CAPABILITIES = [
    {
        "agent_code": "director_operativo",
        "capability_key": "reporting.read.executive_dashboard",
        "scope_type": "read",
        "resource_key": "GET /api/reportes/bi/dashboard/",
    },
    {
        "agent_code": "director_operativo",
        "capability_key": "audit.read.logs",
        "scope_type": "read",
        "resource_key": "GET /api/audit/logs/",
    },
    {
        "agent_code": "director_operativo",
        "capability_key": "integrations.read.point_summary",
        "scope_type": "read",
        "resource_key": "GET /api/integraciones/point/resumen/",
    },
    {
        "agent_code": "director_operativo",
        "capability_key": "integrations.execute.pos_sync_refresh",
        "scope_type": "execute_safe_action",
        "resource_key": "POST /api/pos-bridge/sync-jobs/trigger/",
    },
    {
        "agent_code": "director_operativo",
        "capability_key": "runtime.execute.operational_chain_review",
        "scope_type": "execute_safe_action",
        "resource_key": "PYTHON orquestacion.services.agent_runtime operational_chain_review",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.read.summary",
        "scope_type": "read",
        "resource_key": "GET /api/pos-bridge/sales/summary/",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.analyze.by_branch",
        "scope_type": "analyze",
        "resource_key": "GET /api/pos-bridge/sales/by-branch/",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.analyze.trends",
        "scope_type": "analyze",
        "resource_key": "GET /api/pos-bridge/sales/trends/",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.read.forecast",
        "scope_type": "read",
        "resource_key": "GET /api/ventas/pronostico/",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.analyze.forecast_insights",
        "scope_type": "analyze",
        "resource_key": "GET /api/ventas/pronostico-insights/",
    },
    {
        "agent_code": "agente_demanda_ventas",
        "capability_key": "sales.analyze.day_close_measure",
        "scope_type": "analyze",
        "resource_key": "COMMAND python manage.py measure_sales_day_close",
    },
    {
        "agent_code": "agente_publicacion_eventos_ventas",
        "capability_key": "sales.read.event_publication_state",
        "scope_type": "read",
        "resource_key": "ORM ventas.EventoVenta + ventas.EventoVentaProjectionArtifact",
    },
    {
        "agent_code": "agente_publicacion_eventos_ventas",
        "capability_key": "sales.analyze.publication_guard",
        "scope_type": "analyze",
        "resource_key": "PYTHON orquestacion.services.sales_event_publication_guard",
    },
    {
        "agent_code": "agente_publicacion_eventos_ventas",
        "capability_key": "sales.execute.publish_if_safe",
        "scope_type": "execute_safe_action",
        "resource_key": "PYTHON ventas.views._persist_projection_artifacts",
    },
    {
        "agent_code": "agente_produccion",
        "capability_key": "mrp.analyze.explode",
        "scope_type": "analyze",
        "resource_key": "POST /api/mrp/explode/",
    },
    {
        "agent_code": "agente_produccion",
        "capability_key": "mrp.analyze.production_readiness_guard",
        "scope_type": "analyze",
        "resource_key": "PYTHON orquestacion.services.multi_agent_guards.observe_production_readiness",
    },
    {
        "agent_code": "agente_produccion",
        "capability_key": "mrp.analyze.requirements",
        "scope_type": "analyze",
        "resource_key": "POST /api/mrp/calcular-requerimientos/",
    },
    {
        "agent_code": "agente_produccion",
        "capability_key": "mrp.recommend.plan_from_forecast",
        "scope_type": "recommend",
        "resource_key": "POST /api/mrp/generar-plan-pronostico/",
    },
    {
        "agent_code": "agente_produccion",
        "capability_key": "recipes.analyze.gap_audit",
        "scope_type": "analyze",
        "resource_key": "COMMAND python manage.py run_recipe_gap_audit",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "inventory.analyze.purchase_review_guard",
        "scope_type": "analyze",
        "resource_key": "PYTHON orquestacion.services.multi_agent_guards.observe_purchase_review",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "inventory.read.purchase_suggestions",
        "scope_type": "read",
        "resource_key": "GET /api/inventario/sugerencias-compra/",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "inventory.analyze.low_stock",
        "scope_type": "analyze",
        "resource_key": "GET /api/pos-bridge/inventory/low-stock/",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "inventory.read.current",
        "scope_type": "read",
        "resource_key": "GET /api/pos-bridge/inventory/current/",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "purchasing.read.requests",
        "scope_type": "read",
        "resource_key": "GET /api/compras/solicitudes/",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "purchasing.recommend.request_create",
        "scope_type": "recommend",
        "resource_key": "POST /api/compras/solicitud/",
    },
    {
        "agent_code": "agente_compras",
        "capability_key": "inventory.execute.refresh_sync",
        "scope_type": "execute_safe_action",
        "resource_key": "COMMAND python manage.py run_inventory_sync",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "control.analyze.reconciliation_guard",
        "scope_type": "analyze",
        "resource_key": "PYTHON orquestacion.services.multi_agent_guards.observe_reconciliation_guard",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "control.read.discrepancies",
        "scope_type": "read",
        "resource_key": "GET /api/control/discrepancias/",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "integrations.read.operations_history",
        "scope_type": "read",
        "resource_key": "GET /api/integraciones/point/operaciones/historial/",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "integrations.read.sync_jobs",
        "scope_type": "read",
        "resource_key": "GET /api/pos-bridge/sync-jobs/",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "integrations.execute.retry_failed_jobs",
        "scope_type": "execute_safe_action",
        "resource_key": "COMMAND python manage.py retry_failed_jobs",
    },
    {
        "agent_code": "agente_conciliacion",
        "capability_key": "integrations.analyze.reconcile_sales_report",
        "scope_type": "analyze",
        "resource_key": "COMMAND python manage.py reconcile_sales_report",
    },
]


RULES = [
    {
        "code": "stock_arranque_branch_risk",
        "name": "Riesgo de stock de arranque por sucursal",
        "trigger_type": "threshold",
        "source_event": "inventory.low_stock_detected",
        "condition_json": {
            "requires": ["low_stock", "expected_demand", "delivery_window"],
            "logic": "expected_demand_gt_start_stock",
        },
        "primary_agent_code": "agente_demanda_ventas",
        "secondary_agent_code": "agente_compras",
        "action_mode": "approval_required",
        "cooldown_minutes": 120,
        "is_active": True,
    },
    {
        "code": "seasonal_peak_detection",
        "name": "Deteccion de fecha fuerte",
        "trigger_type": "schedule",
        "source_event": "sales.seasonality_review",
        "condition_json": {
            "lookahead_days": 45,
            "requires": ["sales_history", "forecast", "commercial_calendar"],
        },
        "primary_agent_code": "agente_demanda_ventas",
        "secondary_agent_code": "agente_produccion",
        "action_mode": "recommend",
        "cooldown_minutes": 1440,
        "is_active": True,
    },
    {
        "code": "integration_job_failure_review",
        "name": "Revision de job fallido de integracion",
        "trigger_type": "event",
        "source_event": "integration.job_failed",
        "condition_json": {
            "requires": ["sync_job_status", "job_type"],
            "logic": "status_failed",
        },
        "primary_agent_code": "agente_conciliacion",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 30,
        "is_active": True,
    },
    {
        "code": "production_weekly_purchase_request_deadline",
        "name": "Solicitud semanal de compras de Produccion fuera de horario",
        "trigger_type": "schedule",
        "source_event": "purchasing.production_weekly_request_review",
        "condition_json": {
            "schedule": {
                "weekday": "monday",
                "cutoff_local_time": "12:00",
            },
            "policy": {
                "horizon_days": 15,
                "required_source_department": "PROD",
            },
            "requires": ["purchase_requests", "request_created_at", "requested_delivery_date"],
        },
        "primary_agent_code": "agente_compras",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 1440,
        "is_active": True,
    },
    {
        "code": "purchase_exception_requires_dg_approval",
        "name": "Excepcion de compra que requiere aprobacion DG",
        "trigger_type": "threshold",
        "source_event": "purchasing.request_exception_detected",
        "condition_json": {
            "requires": ["purchase_request_total", "catalog_status", "budget_status"],
            "logic": {
                "any_of": [
                    {"field": "purchase_request_total", "operator": "gt", "value": 5000},
                    {"field": "catalog_status", "operator": "eq", "value": "out_of_catalog"},
                    {"field": "budget_status", "operator": "eq", "value": "over_budget"},
                ]
            },
            "approval_owner": "DG",
        },
        "primary_agent_code": "agente_compras",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 240,
        "is_active": True,
    },
    {
        "code": "inventory_adjustment_authorization_guard",
        "name": "Ajuste de inventario sin autorizacion requerida",
        "trigger_type": "event",
        "source_event": "inventory.adjustment_requested",
        "condition_json": {
            "requires": ["adjustment_request", "approval_status", "requested_by"],
            "logic": "missing_required_authorization",
            "approval_owner": "ADMIN",
            "stale_pending_hours": 4,
            "integrity_checks": [
                "applied_without_approval_actor",
                "applied_without_approval_timestamp",
                "rejected_without_approval_actor",
                "rejected_without_approval_timestamp",
            ],
        },
        "primary_agent_code": "agente_conciliacion",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 60,
        "is_active": True,
    },
    {
        "code": "near_expiry_or_low_rotation_review",
        "name": "Revision de baja rotacion o proximidad a caducidad",
        "trigger_type": "threshold",
        "source_event": "inventory.expiry_or_rotation_review",
        "condition_json": {
            "requires": ["stock_actual", "rotation_index", "expiry_date"],
            "logic": "near_expiry_or_low_rotation_detected",
            "scope": {
                "allowed_item_types": ["MATERIA_PRIMA"],
                "excluded_category_keywords": ["DESECHABLE", "EMPAQUE"],
            },
            "thresholds": {
                "min_stock_actual": 1,
                "days_of_cover_gte": 30,
                "stock_vs_min_factor_gte": "1.50",
                "stock_vs_avg_factor_gte": "1.10",
                "zero_consumption_requires_review": True,
                "zero_consumption_stock_vs_min_factor_gte": "3.00",
                "zero_consumption_stock_vs_avg_factor_gte": "3.00",
                "zero_consumption_min_stock_absolute": "10",
            },
            "data_gaps": {
                "expiry_date_source": "missing_in_erp_inventory_lot_model",
            },
        },
        "primary_agent_code": "agente_conciliacion",
        "secondary_agent_code": "agente_compras",
        "action_mode": "recommend",
        "cooldown_minutes": 720,
        "is_active": True,
    },
    {
        "code": "branch_capacity_below_threshold",
        "name": "Sucursal por debajo del umbral minimo de capacidad",
        "trigger_type": "threshold",
        "source_event": "logistics.branch_capacity_review",
        "condition_json": {
            "requires": ["branch_capacity_pct", "expected_demand", "delivery_window"],
            "logic": {
                "field": "branch_capacity_pct",
                "operator": "lt",
                "value": 30,
            },
            "policy": {
                "unit": "percent",
                "priority": "high",
            },
        },
        "primary_agent_code": "agente_demanda_ventas",
        "secondary_agent_code": "agente_compras",
        "action_mode": "recommend",
        "cooldown_minutes": 180,
        "is_active": True,
    },
    {
        "code": "cold_chain_temperature_breach",
        "name": "Desviacion de cadena fria en entregas a sucursales",
        "trigger_type": "threshold",
        "source_event": "logistics.cold_chain_temperature_review",
        "condition_json": {
            "requires": ["transport_temperature_c", "route_id", "branch_code"],
            "logic": {
                "outside_range_c": [3, 5],
            },
            "policy": {
                "unit": "celsius",
                "escalate_immediately": True,
            },
        },
        "primary_agent_code": "agente_conciliacion",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 30,
        "is_active": True,
    },
    {
        "code": "daily_production_plan_missing",
        "name": "Plan diario de Produccion no cargado en sistema",
        "trigger_type": "schedule",
        "source_event": "production.daily_plan_review",
        "condition_json": {
            "schedule": {
                "frequency": "daily",
                "cutoff_local_time": "09:00",
            },
            "requires": ["production_plan", "plan_created_at", "production_date"],
            "logic": "missing_daily_production_plan",
        },
        "primary_agent_code": "agente_produccion",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 720,
        "is_active": True,
    },
    {
        "code": "plan_demand_production_purchase_chain",
        "name": "Cadena demanda a produccion y compras del plan",
        "trigger_type": "manual",
        "source_event": "production.plan_chain_review",
        "condition_json": {
            "requires": [
                "production_plan",
                "sales_history",
                "sales_request",
                "forecast",
                "inventory_current",
                "recipe_lines",
            ],
            "plan_scope": "same_day_latest_plan",
            "lookback_days": 60,
            "thresholds": {
                "demand_min_historico_days_warning": 7,
                "demand_min_historico_days_success": 28,
                "purchase_shortage_ratio_warning": "0.05",
            },
            "known_gaps": [
                "branch_delivery_windows_not_modeled",
                "session_forecast_preview_not_available_in_background",
            ],
        },
        "primary_agent_code": "agente_demanda_ventas",
        "secondary_agent_code": "director_operativo",
        "action_mode": "approval_required",
        "cooldown_minutes": 180,
        "is_active": True,
    },
    {
        "code": "sales_event_operational_chain_review",
        "name": "Cadena operativa multi-agente del evento comercial",
        "trigger_type": "manual",
        "source_event": "sales.event_operational_chain_review",
        "condition_json": {
            "requires": [
                "sales_event",
                "forecast_week",
                "financials",
                "production_plan",
                "input_requirements",
                "purchase_requirements",
            ],
            "entity_scope": "ventas.EventoVenta",
            "goal_type": "operational_chain_review",
            "handoff_sequence": [
                "sales_event_publication_guard",
                "production_readiness_guard",
                "purchase_review_guard",
            ],
        },
        "primary_agent_code": "director_operativo",
        "secondary_agent_code": "agente_conciliacion",
        "action_mode": "approval_required",
        "cooldown_minutes": 60,
        "is_active": True,
    },
    {
        "code": "production_checklist_below_target",
        "name": "Checklist de Produccion por debajo de meta",
        "trigger_type": "threshold",
        "source_event": "production.checklist_review",
        "condition_json": {
            "requires": ["checklist_score_pct", "production_line", "production_date"],
            "logic": {
                "field": "checklist_score_pct",
                "operator": "lt",
                "value": 95,
            },
            "policy": {
                "unit": "percent",
                "target": 95,
            },
        },
        "primary_agent_code": "agente_produccion",
        "secondary_agent_code": "director_operativo",
        "action_mode": "recommend",
        "cooldown_minutes": 1440,
        "is_active": True,
    },
]
