# Generated by Django 5.0.1 on 2026-04-16 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudHorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('raw_command', models.TextField()),
                ('source_channel', models.CharField(choices=[('WEB', 'ERP Web'), ('API', 'API'), ('IA_PRIVADA', 'IA privada')], default='WEB', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('canonical_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('APROBADO', 'Aprobado'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], db_index=True, default='BORRADOR', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('execution_summary_json', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_aprobados', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_ejecutados', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'special_hours_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('closed_all_day', models.BooleanField(default=False)),
                ('time_windows_json', models.JSONField(blank=True, default=list)),
                ('execution_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('validation_errors_json', models.JSONField(blank=True, default=list)),
                ('platform_payload_json', models.JSONField(blank=True, default=dict)),
                ('published_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios_especiales_detalle', to='core.sucursal')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='horarios_especiales.solicitudhorarioespecial')),
            ],
            options={
                'db_table': 'special_hours_request_details',
                'ordering': ['target_date', 'sucursal__codigo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecialBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('EXECUTION_REQUESTED', 'Execution requested'), ('EXECUTION_SUCCESS', 'Execution success'), ('EXECUTION_FAILED', 'Execution failed'), ('RETRY_REQUESTED', 'Retry requested'), ('CANCELLED', 'Cancelled')], max_length=40)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='horarios_especiales.horarioespecialdetalle')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='horarios_especiales.solicitudhorarioespecial')),
            ],
            options={
                'db_table': 'special_hours_audit_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SucursalAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('alias_normalizado', models.CharField(blank=True, db_index=True, default='', max_length=140)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTED', 'Importado'), ('AI_SUGGESTED', 'Sugerido IA')], default='MANUAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_aliases_creados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aliases', to='core.sucursal')),
            ],
            options={
                'db_table': 'special_hours_branch_aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SucursalPlataformaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GOOGLE_BUSINESS_PROFILE', 'Google Business Profile')], default='GOOGLE_BUSINESS_PROFILE', max_length=40)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_location_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_location_name', models.CharField(blank=True, default='', max_length=160)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas_horario', to='core.sucursal')),
            ],
            options={
                'db_table': 'special_hours_platform_configs',
                'ordering': ['platform', 'sucursal__codigo'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecialIntentoPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GOOGLE_BUSINESS_PROFILE', 'Google Business Profile')], default='GOOGLE_BUSINESS_PROFILE', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload_json', models.JSONField(blank=True, default=dict)),
                ('response_payload_json', models.JSONField(blank=True, default=dict)),
                ('error_payload_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('external_operation_id', models.CharField(blank=True, default='', max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_attempts', to='horarios_especiales.horarioespecialdetalle')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_especiales_intentos_ejecutados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'special_hours_publication_attempts',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['platform', 'status'], name='he_attempt_platform_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='horarioespecialintentopublicacion',
            constraint=models.UniqueConstraint(fields=('detail', 'platform', 'attempt_no'), name='he_publication_attempt_unique'),
        ),
        migrations.AddIndex(
            model_name='solicitudhorarioespecial',
            index=models.Index(fields=['status', 'created_at'], name='he_request_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='horarioespecialdetalle',
            index=models.Index(fields=['target_date', 'execution_status'], name='he_detail_date_exec_idx'),
        ),
        migrations.AddConstraint(
            model_name='horarioespecialdetalle',
            constraint=models.UniqueConstraint(fields=('request', 'sucursal', 'target_date'), name='he_request_detail_unique'),
        ),
        migrations.AddIndex(
            model_name='horarioespecialbitacora',
            index=models.Index(fields=['request', 'created_at'], name='he_audit_request_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sucursalalias',
            index=models.Index(fields=['sucursal', 'is_active'], name='he_alias_branch_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='sucursalalias',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('alias_normalizado',), name='he_branch_alias_active_unique'),
        ),
        migrations.AddIndex(
            model_name='sucursalplataformaexterna',
            index=models.Index(fields=['platform', 'is_active'], name='he_platform_config_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sucursalplataformaexterna',
            constraint=models.UniqueConstraint(fields=('sucursal', 'platform'), name='he_platform_config_branch_unique'),
        ),
        migrations.AddConstraint(
            model_name='sucursalplataformaexterna',
            constraint=models.UniqueConstraint(condition=models.Q(('external_location_name', ''), _negated=True), fields=('platform', 'external_location_name'), name='he_platform_config_location_unique'),
        ),
    ]
