# Generated by Django 5.0.1 on 2026-02-23 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, editable=False, max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tipo_cliente', models.CharField(blank=True, default='', max_length=40)),
                ('sucursal_referencia', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('sucursal', models.CharField(blank=True, default='', max_length=120)),
                ('estatus', models.CharField(choices=[('NUEVO', 'Nuevo'), ('COTIZADO', 'Cotizado'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En producción'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('canal', models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('OTRO', 'Otro')], default='MOSTRADOR', max_length=20)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='crm.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('estatus_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('estatus_nuevo', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('COTIZADO', 'Cotizado'), ('CONFIRMADO', 'Confirmado'), ('EN_PRODUCCION', 'En producción'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='', max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_seguimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='crm.pedidocliente')),
            ],
            options={
                'ordering': ['-fecha_evento', '-id'],
            },
        ),
    ]
