# Generated by Django 5.0.1 on 2026-03-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_modo_captura_sucursal'),
        ('crm', '0001_initial'),
        ('recetas', '0016_receta_temporalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='sucursal_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_pedidos', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='PickupReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], db_index=True, default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('WEB', 'Web')], default='WEB', max_length=20)),
                ('source_client_prefix', models.CharField(blank=True, default='', max_length=12)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('client_name', models.CharField(blank=True, default='', max_length=180)),
                ('snapshot_stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reserved_qty_at_creation', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('buffer_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('available_to_promise', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('snapshot_captured_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_reservations', to='recetas.receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_reservations', to='core.sucursal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='pickup_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='crm.pickupreservation'),
        ),
        migrations.AddIndex(
            model_name='pickupreservation',
            index=models.Index(fields=['status', 'expires_at'], name='crm_pickup_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='pickupreservation',
            index=models.Index(fields=['receta', 'sucursal', 'status'], name='crm_pickup_recipe_branch_idx'),
        ),
    ]
