# Generated by Django 5.0.1 on 2026-07-27 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('crm', '0006_pedidocliente_tracking_ownership'),
        ('integraciones', '0003_publicapiclient_repartidores_logistica_autorizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='point_note_fetched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='point_note_folio',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='point_note_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='point_note_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='social_reference',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='pedidocliente',
            name='canal',
            field=models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('OTRO', 'Otro')], default='MOSTRADOR', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pedidocliente',
            constraint=models.UniqueConstraint(condition=models.Q(('point_note_id', ''), _negated=True), fields=('point_note_id',), name='crm_pedido_point_note_unico'),
        ),
    ]
