# Generated by Django 5.0.1 on 2026-07-27 23:43

from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_datetime


def backfill_point_indexed_facts(apps, schema_editor):
    PedidoCliente = apps.get_model("crm", "PedidoCliente")
    for order in PedidoCliente.objects.exclude(point_note_id="").iterator(
        chunk_size=500,
    ):
        snapshot = order.point_note_snapshot
        if not isinstance(snapshot, dict):
            continue
        updates = []
        raw_sold_at = snapshot.get("sold_at")
        if raw_sold_at and order.point_note_sold_at is None:
            parsed = parse_datetime(str(raw_sold_at).strip())
            if parsed is not None:
                if timezone.is_naive(parsed):
                    parsed = timezone.make_aware(
                        parsed,
                        timezone.get_current_timezone(),
                    )
                order.point_note_sold_at = parsed
                updates.append("point_note_sold_at")
        branch = str(snapshot.get("branch_name") or "").strip()
        if branch and not str(order.sucursal or "").strip():
            order.sucursal = branch[:120]
            updates.append("sucursal")
        if updates:
            order.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_pedidocliente_point_note_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='point_link_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='pedidocliente',
            name='point_note_sold_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocliente',
            name='sucursal',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.RunPython(
            backfill_point_indexed_facts,
            migrations.RunPython.noop,
        ),
    ]
