# Generated by Django 5.0.1 on 2026-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_point_link_fingerprint_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocliente',
            name='canal',
            field=models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('OTRO', 'Otro'), ('POR_CONFIRMAR', 'Canal por confirmar')], default='MOSTRADOR', max_length=20),
        ),
    ]
