# Generated by Django 5.0.1 on 2026-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_pedidocliente_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='point_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('point_customer_id', ''), _negated=True), fields=('point_customer_id',), name='crm_cliente_point_id_unico'),
        ),
    ]
