# Generated by Django 5.0.1 on 2026-10-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_cliente_point_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NOTE', 'Nota de venta'), ('SPECIAL', 'Pedido especial')], max_length=10)),
                ('point_id', models.CharField(max_length=120)),
                ('snapshot', models.JSONField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='point_order_link', to='crm.pedidocliente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pointorderlink',
            constraint=models.UniqueConstraint(fields=('kind', 'point_id'), name='crm_point_document_unique'),
        ),
    ]
