# Generated by Django 5.0.1 on 2026-02-23 14:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('fecha_ruta', models.DateField(default=django.utils.timezone.localdate)),
                ('chofer', models.CharField(blank=True, default='', max_length=120)),
                ('unidad', models.CharField(blank=True, default='', max_length=120)),
                ('estatus', models.CharField(choices=[('PLANEADA', 'Planeada'), ('EN_RUTA', 'En ruta'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PLANEADA', max_length=20)),
                ('km_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('total_entregas', models.PositiveIntegerField(default=0)),
                ('entregas_completadas', models.PositiveIntegerField(default=0)),
                ('entregas_incidencia', models.PositiveIntegerField(default=0)),
                ('monto_estimado_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistica_rutas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ruta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntregaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=180)),
                ('direccion', models.CharField(blank=True, default='', max_length=250)),
                ('contacto', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('ventana_inicio', models.DateTimeField(blank=True, null=True)),
                ('ventana_fin', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En camino'), ('ENTREGADA', 'Entregada'), ('INCIDENCIA', 'Incidencia'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('comentario', models.TextField(blank=True, default='')),
                ('evidencia_url', models.URLField(blank=True, default='')),
                ('entregado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_logistica', to='crm.pedidocliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='logistica.rutaentrega')),
            ],
            options={
                'ordering': ['secuencia', 'id'],
            },
        ),
    ]
