# Generated by Django 5.0.1 on 2026-04-28 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sucursal_fecha_apertura'),
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=180)),
                ('placa', models.CharField(blank=True, default='', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_logistica', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Unidad logística',
                'verbose_name_plural': 'Unidades logísticas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartidores_logistica', to='core.sucursal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor_logistica', to=settings.AUTH_USER_MODEL)),
                ('unidad_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartidores_asignados', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraRepartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('km_inicio', models.PositiveIntegerField()),
                ('km_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('novedades', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='logistica.repartidor')),
            ],
            options={
                'verbose_name': 'Bitácora de repartidor',
                'verbose_name_plural': 'Bitácoras de repartidores',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('repartidor', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ReporteUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falla', 'Falla mecánica'), ('mantenimiento', 'Mantenimiento preventivo'), ('accidente', 'Accidente'), ('llanta', 'Llanta'), ('documentos', 'Documentos'), ('otro', 'Otro')], max_length=30)),
                ('severidad', models.CharField(choices=[('informativo', 'Informativo'), ('urgente', 'Urgente'), ('critico', 'Crítico')], default='informativo', max_length=20)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='logistica/reportes/')),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('programado', 'Programado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('proveedor_servicio', models.CharField(blank=True, default='', max_length=180)),
                ('fecha_servicio_programado', models.DateTimeField(blank=True, null=True)),
                ('costo_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas_compras', models.TextField(blank=True, default='')),
                ('notificacion_escalada', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_logistica_asignados', to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_unidad', to='logistica.repartidor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Reporte de unidad',
                'verbose_name_plural': 'Reportes de unidad',
                'ordering': ['-fecha_reporte', '-id'],
                'indexes': [models.Index(fields=['estatus', 'severidad', 'fecha_reporte'], name='logistica_r_estatus_e6e728_idx'), models.Index(fields=['unidad', 'fecha_reporte'], name='logistica_r_unidad__d020e0_idx')],
            },
        ),
    ]
