# Generated by Django 5.0.1 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0002_unidad_repartidor_bitacorarepartidor_reporteunidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporteunidad",
            name="ip_reporte",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
