# Generated by Django 5.0.1 on 2026-04-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_reporteunidad_ip_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSalidaLlegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('folio', models.CharField(blank=True, max_length=20)),
                ('hora_salida', models.DateTimeField(auto_now_add=True)),
                ('km_salida', models.PositiveIntegerField()),
                ('nivel_gas_salida', models.CharField(choices=[('vacio', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('lleno', 'Lleno')], max_length=10)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('km_llegada', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_gas_llegada', models.CharField(blank=True, choices=[('vacio', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('lleno', 'Lleno')], max_length=10)),
                ('litros_cargados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('costo_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ip_registro', models.GenericIPAddressField(null=True)),
                ('latitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.repartidor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Bitácora salida/llegada',
                'verbose_name_plural': 'Bitácoras salida/llegada',
                'ordering': ['-fecha', '-hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('km_entrada', models.PositiveIntegerField()),
                ('km_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_gas_entrada', models.CharField(choices=[('vacio', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('lleno', 'Lleno')], max_length=10)),
                ('nivel_gas_salida', models.CharField(blank=True, choices=[('vacio', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('lleno', 'Lleno')], max_length=10)),
                ('ext_llanta_refaccion', models.BooleanField(default=False)),
                ('ext_gato', models.BooleanField(default=False)),
                ('ext_llave_rueda', models.BooleanField(default=False)),
                ('ext_rines', models.BooleanField(default=False)),
                ('ext_aire_neumaticos', models.BooleanField(default=False)),
                ('ext_claxon', models.BooleanField(default=False)),
                ('ext_limpiaparabrisas', models.BooleanField(default=False)),
                ('ext_luces', models.BooleanField(default=False)),
                ('ext_direccionales', models.BooleanField(default=False)),
                ('ext_control_llave', models.BooleanField(default=False)),
                ('ext_antena', models.BooleanField(default=False)),
                ('ext_tapon_gas', models.BooleanField(default=False)),
                ('int_espejos', models.BooleanField(default=False)),
                ('int_encendedor', models.BooleanField(default=False)),
                ('int_luz_interior', models.BooleanField(default=False)),
                ('int_ac', models.BooleanField(default=False)),
                ('int_radio', models.BooleanField(default=False)),
                ('int_botones_radio', models.BooleanField(default=False)),
                ('int_rejillas_ac', models.BooleanField(default=False)),
                ('int_tapetes', models.BooleanField(default=False)),
                ('int_cinturones', models.BooleanField(default=False)),
                ('int_tarjeta_circulacion', models.BooleanField(default=False)),
                ('niv_aceite', models.BooleanField(default=False)),
                ('niv_frenos', models.BooleanField(default=False)),
                ('niv_bateria', models.BooleanField(default=False)),
                ('niv_agua_limpiadores', models.BooleanField(default=False)),
                ('niv_agua_radiador', models.BooleanField(default=False)),
                ('est_asientos_delanteros', models.BooleanField(default=False)),
                ('est_asientos_traseros', models.BooleanField(default=False)),
                ('est_cajuela', models.BooleanField(default=False)),
                ('est_tablero', models.BooleanField(default=False)),
                ('est_panel_puertas', models.BooleanField(default=False)),
                ('est_visera', models.BooleanField(default=False)),
                ('tiene_golpes', models.BooleanField(default=False)),
                ('descripcion_golpes', models.TextField(blank=True)),
                ('foto_golpes', models.ImageField(blank=True, null=True, upload_to='inspecciones/')),
                ('observaciones', models.TextField(blank=True)),
                ('ip_registro', models.GenericIPAddressField(null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.repartidor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Inspección de vehículo',
                'verbose_name_plural': 'Inspecciones de vehículo',
                'ordering': ['-fecha'],
            },
        ),
    ]
