# Generated by Django 5.0.1 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistica", "0004_bitacora_salida_inspeccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidad",
            name="folio_consecutivo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bitacorasalidallegada",
            name="folio",
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name="bitacorasalidallegada",
            name="hora_salida",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bitacorasalidallegada",
            name="cerrada",
            field=models.BooleanField(default=False),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="bitacorasalidallegada",
                    name="foto_tablero_salida",
                    field=models.ImageField(blank=True, null=True, upload_to="bitacora/"),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="bitacorasalidallegada",
                    name="foto_tablero_salida",
                    field=models.ImageField(upload_to="bitacora/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bitacorasalidallegada",
            name="foto_tablero_llegada",
            field=models.ImageField(blank=True, null=True, upload_to="bitacora/"),
        ),
    ]
