# Generated by Django 5.0.1 on 2026-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_bitacora_folio_fotos_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='marca',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
