# Generated by Django 5.0.1 on 2026-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_unidad_marca_modelo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacorasalidallegada',
            name='foto_ticket_combustible',
            field=models.ImageField(blank=True, null=True, upload_to='bitacora/combustible/'),
        ),
    ]
