# Generated by Django 5.0.1 on 2026-05-01 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_bitacora_ticket_combustible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicioUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_intervalo', models.CharField(choices=[('km', 'Por kilómetros'), ('tiempo', 'Por tiempo'), ('ambos', 'Kilómetros o tiempo (lo que ocurra primero)')], max_length=10)),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True)),
                ('intervalo_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('aplica_todas_unidades', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfigAlertaFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documento_vencimiento', 'Vencimiento de documento'), ('servicio_proximo', 'Servicio próximo'), ('lavado_pendiente', 'Lavado pendiente')], max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('dias_anticipacion_1', models.PositiveIntegerField(default=30)),
                ('dias_anticipacion_2', models.PositiveIntegerField(default=15)),
                ('dias_anticipacion_3', models.PositiveIntegerField(default=0)),
                ('destinatarios', models.ManyToManyField(related_name='alertas_flota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de alerta de flota',
                'verbose_name_plural': 'Configuraciones de alertas de flota',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_circulacion', 'Tarjeta de circulación'), ('seguro', 'Seguro vehicular'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('aseguradora', models.CharField(blank=True, max_length=100)),
                ('archivo', models.FileField(upload_to='documentos_unidad/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Documento de unidad',
                'verbose_name_plural': 'Documentos de unidades',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='LavadoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lavados', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Lavado de unidad',
                'verbose_name_plural': 'Lavados de unidades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReparacionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('descripcion_falla', models.TextField()),
                ('descripcion_reparacion', models.TextField(blank=True)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='reparaciones_unidad/')),
                ('foto_nota', models.ImageField(blank=True, null=True, upload_to='reparaciones_unidad/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reporte_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='logistica.reporteunidad')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Reparación de unidad',
                'verbose_name_plural': 'Reparaciones de unidades',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ServicioRealizadoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('km_al_servicio', models.PositiveIntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='servicios_unidad/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('proximos_km', models.PositiveIntegerField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='logistica.unidad')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.tiposerviciounidad')),
            ],
            options={
                'verbose_name': 'Servicio realizado',
                'verbose_name_plural': 'Servicios realizados',
                'ordering': ['-fecha_servicio'],
            },
        ),
    ]
