# Generated by Django 5.0.1 on 2026-05-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_gestion_flota'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('aceite_ok', models.BooleanField(default=False)),
                ('refrigerante_ok', models.BooleanField(default=False)),
                ('liquido_frenos_ok', models.BooleanField(default=False)),
                ('limpiaparabrisas_ok', models.BooleanField(default=False)),
                ('presion_llantas_ok', models.BooleanField(default=False)),
                ('desgaste_llantas_ok', models.BooleanField(default=False)),
                ('luces_ok', models.BooleanField(default=False)),
                ('escobillas_ok', models.BooleanField(default=False)),
                ('bateria_ok', models.BooleanField(default=False)),
                ('tablero_ok', models.BooleanField(default=False)),
                ('documentos_ok', models.BooleanField(default=False)),
                ('licencia_ok', models.BooleanField(default=False)),
                ('kit_emergencia_ok', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('tiene_fallas', models.BooleanField(default=False)),
                ('ip_registro', models.GenericIPAddressField(null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_diarias', to='logistica.repartidor')),
                ('reporte_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspeccion_origen', to='logistica.reporteunidad')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_diarias', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Inspección diaria',
                'verbose_name_plural': 'Inspecciones diarias',
                'ordering': ['-hora'],
                'unique_together': {('unidad', 'fecha')},
            },
        ),
    ]
