# Generated by Django 5.0.1 on 2026-05-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_inspeccion_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='archivo_licencia',
            field=models.FileField(blank=True, null=True, upload_to='licencias_repartidores/'),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='licencia_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='licencia_expiracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='numero_licencia',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
