# Generated by Django 5.0.1 on 2026-05-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_repartidor_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUnidadReafirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reafirmaciones_reporte', to='logistica.repartidor')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reafirmaciones', to='logistica.reporteunidad')),
            ],
            options={
                'verbose_name': 'Reafirmación de reporte',
                'verbose_name_plural': 'Reafirmaciones de reportes',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['reporte', 'creado_en'], name='logistica_r_reporte_fd0a66_idx'), models.Index(fields=['repartidor', 'creado_en'], name='logistica_r_reparti_5dcfa1_idx')],
            },
        ),
    ]
