# Generated by Django 5.0.1 on 2026-05-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_reporte_reafirmacion_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustibleUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_gas_despues', models.CharField(blank=True, choices=[('vacio', 'Vacío'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('lleno', 'Lleno')], max_length=10)),
                ('foto_ticket', models.ImageField(upload_to='bitacora/combustible/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_registro', models.GenericIPAddressField(null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='logistica.bitacorasalidallegada')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='logistica.repartidor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Carga de combustible',
                'verbose_name_plural': 'Cargas de combustible',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
