# Generated by Django 5.0.1 on 2026-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_carga_combustible_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadounidad',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='lavados_unidad/'),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='tipo_lavado',
            field=models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('caja_refrigerada', 'Caja refrigerada'), ('completo', 'Completo')], default='completo', max_length=30),
        ),
    ]
