# Generated by Django 5.0.1 on 2026-05-14 23:52

from django.db import migrations, models


def migrar_tipo_lavado_a_partes(apps, schema_editor):
    LavadoUnidad = apps.get_model("logistica", "LavadoUnidad")
    for lavado in LavadoUnidad.objects.all().iterator():
        updates = {
            "lavado_exterior": False,
            "lavado_interior": False,
            "lavado_caja_refrigerada": False,
        }
        if lavado.tipo_lavado == "exterior":
            updates["lavado_exterior"] = True
        elif lavado.tipo_lavado == "interior":
            updates["lavado_interior"] = True
        elif lavado.tipo_lavado == "caja_refrigerada":
            updates["lavado_caja_refrigerada"] = True
        elif lavado.tipo_lavado == "completo":
            updates["lavado_exterior"] = True
            updates["lavado_interior"] = True
            updates["lavado_caja_refrigerada"] = True
        LavadoUnidad.objects.filter(pk=lavado.pk).update(**updates)


def revertir_partes_a_tipo_lavado(apps, schema_editor):
    LavadoUnidad = apps.get_model("logistica", "LavadoUnidad")
    for lavado in LavadoUnidad.objects.all().iterator():
        if lavado.lavado_exterior and lavado.lavado_interior and lavado.lavado_caja_refrigerada:
            tipo = "completo"
        elif lavado.lavado_caja_refrigerada:
            tipo = "caja_refrigerada"
        elif lavado.lavado_interior:
            tipo = "interior"
        elif lavado.lavado_exterior:
            tipo = "exterior"
        else:
            tipo = lavado.tipo_lavado
        LavadoUnidad.objects.filter(pk=lavado.pk).update(tipo_lavado=tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_lavado_pwa_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadounidad',
            name='lavado_caja_refrigerada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='lavado_exterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lavadounidad',
            name='lavado_interior',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrar_tipo_lavado_a_partes, revertir_partes_a_tipo_lavado),
    ]
