# Generated by Django 5.0.1 on 2026-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_lavado_partes_multiples'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='autorizado_por',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='empresa_externa',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='motivo_autorizacion',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='notas_identidad',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='tipo_identidad',
            field=models.CharField(choices=[('empleado_dolce', 'Empleado Dolce'), ('externo_autorizado', 'Externo autorizado'), ('cuenta_tecnica', 'Cuenta técnica')], default='empleado_dolce', max_length=30),
        ),
    ]
