# Generated by Django 5.0.1 on 2026-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_merge_0016_duplicados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='tipo_identidad',
            field=models.CharField(choices=[('empleado_dolce', 'Empleado Dolce'), ('empleado_conductor_ocasional', 'Empleado conductor ocasional'), ('externo_autorizado', 'Externo autorizado'), ('cuenta_tecnica', 'Cuenta técnica')], default='empleado_dolce', max_length=30),
        ),
    ]
