# Generated by Django 5.0.1 on 2026-06-12 22:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_usermoduleaccess_module'),
        ('logistica', '0018_repartidor_conductor_occasional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida'), ('LLEGADA_GEOFENCE', 'Llegada a geocerca'), ('DESVIO', 'Desvío'), ('PARADA_LARGA', 'Parada larga'), ('GPS_PERDIDO', 'GPS perdido'), ('INCIDENCIA_MANUAL', 'Incidencia manual'), ('CIERRE', 'Cierre')], max_length=30)),
                ('severidad', models.CharField(choices=[('info', 'Informativo'), ('ok', 'Cumplimiento'), ('alerta', 'Alerta'), ('critica', 'Crítica')], default='info', max_length=10)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distancia_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Evento de ruta',
                'verbose_name_plural': 'Eventos de ruta',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('punto_nombre_snapshot', models.CharField(blank=True, default='', editable=False, max_length=160)),
                ('latitud_geocerca', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('longitud_geocerca', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('radio_geocerca_metros', models.PositiveIntegerField(editable=False)),
                ('hora_estimada', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('hora_salida_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VISITADA', 'Visitada'), ('OMITIDA', 'Omitida'), ('FUERA_RADIO', 'Fuera de radio')], default='PENDIENTE', max_length=20)),
                ('distancia_llegada_metros', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parada de ruta',
                'verbose_name_plural': 'Paradas de ruta',
                'ordering': ['ruta', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PuntoLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('CEDIS', 'CEDIS'), ('SUCURSAL', 'Sucursal'), ('PROVEEDOR', 'Proveedor'), ('TALLER', 'Taller'), ('BANCO', 'Banco'), ('AUTORIZADO', 'Punto autorizado')], default='SUCURSAL', max_length=20)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_geocerca_metros', models.PositiveIntegerField(default=80)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punto logístico',
                'verbose_name_plural': 'Puntos logísticos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bateria_porcentaje', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp_dispositivo', models.DateTimeField(blank=True, null=True)),
                ('timestamp_servidor', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('fuera_de_geocerca', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ubicación de ruta',
                'verbose_name_plural': 'Ubicaciones de ruta',
                'ordering': ['-timestamp_servidor', '-id'],
            },
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='bitacora_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_operativas', to='logistica.bitacorasalidallegada'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='cumplimiento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='hora_cierre_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='hora_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to='logistica.repartidor'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='unidad_operativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_asignadas', to='logistica.unidad'),
        ),
        migrations.AddIndex(
            model_name='rutaentrega',
            index=models.Index(fields=['estatus', 'fecha_ruta'], name='logistica_r_estatus_eda88b_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaentrega',
            index=models.Index(fields=['repartidor', 'estatus'], name='logistica_r_reparti_f70c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='rutaentrega',
            index=models.Index(fields=['unidad_operativa', 'estatus'], name='logistica_r_unidad__e3b792_idx'),
        ),
        migrations.AddConstraint(
            model_name='rutaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'EN_RUTA'), ('repartidor__isnull', False)), fields=('repartidor',), name='rutaentrega_unica_en_ruta_repartidor'),
        ),
        migrations.AddConstraint(
            model_name='rutaentrega',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'EN_RUTA'), ('unidad_operativa__isnull', False)), fields=('unidad_operativa',), name='rutaentrega_unica_en_ruta_unidad'),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_ruta_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='logistica.rutaentrega'),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='logistica.rutaentrega'),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='logistica.paradaruta'),
        ),
        migrations.AddField(
            model_name='puntologistico',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_logisticos', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_ruta', to='logistica.puntologistico'),
        ),
        migrations.AddField(
            model_name='ubicacionruta',
            name='repartidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_ruta', to='logistica.repartidor'),
        ),
        migrations.AddField(
            model_name='ubicacionruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='logistica.rutaentrega'),
        ),
        migrations.AddField(
            model_name='ubicacionruta',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_ruta', to='logistica.unidad'),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='logistica.ubicacionruta'),
        ),
        migrations.AddIndex(
            model_name='puntologistico',
            index=models.Index(fields=['tipo', 'activo'], name='logistica_p_tipo_a05938_idx'),
        ),
        migrations.AddIndex(
            model_name='puntologistico',
            index=models.Index(fields=['sucursal', 'activo'], name='logistica_p_sucursa_4c0116_idx'),
        ),
        migrations.AddConstraint(
            model_name='puntologistico',
            constraint=models.CheckConstraint(check=models.Q(('latitud__gte', Decimal('-90')), ('latitud__lte', Decimal('90'))), name='puntologistico_latitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='puntologistico',
            constraint=models.CheckConstraint(check=models.Q(('longitud__gte', Decimal('-180')), ('longitud__lte', Decimal('180'))), name='puntologistico_longitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='puntologistico',
            constraint=models.CheckConstraint(check=models.Q(('radio_geocerca_metros__gte', 20), ('radio_geocerca_metros__lte', 1000)), name='puntologistico_radio_rango'),
        ),
        migrations.AddConstraint(
            model_name='puntologistico',
            constraint=models.CheckConstraint(check=models.Q(('latitud', Decimal('0')), ('longitud', Decimal('0')), _negated=True), name='puntologistico_no_cero_cero'),
        ),
        migrations.AddIndex(
            model_name='paradaruta',
            index=models.Index(fields=['ruta', 'estado'], name='logistica_p_ruta_id_cb64a1_idx'),
        ),
        migrations.AddIndex(
            model_name='paradaruta',
            index=models.Index(fields=['punto', 'estado'], name='logistica_p_punto_i_04ce93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paradaruta',
            unique_together={('ruta', 'orden')},
        ),
        migrations.AddIndex(
            model_name='ubicacionruta',
            index=models.Index(fields=['ruta', 'timestamp_servidor'], name='logistica_u_ruta_id_dfc9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionruta',
            index=models.Index(fields=['repartidor', 'timestamp_servidor'], name='logistica_u_reparti_ddf341_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionruta',
            index=models.Index(fields=['fuera_de_geocerca', 'timestamp_servidor'], name='logistica_u_fuera_d_6e39ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionruta',
            constraint=models.CheckConstraint(check=models.Q(('latitud__gte', Decimal('-90')), ('latitud__lte', Decimal('90'))), name='ubicacionruta_latitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionruta',
            constraint=models.CheckConstraint(check=models.Q(('longitud__gte', Decimal('-180')), ('longitud__lte', Decimal('180'))), name='ubicacionruta_longitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionruta',
            constraint=models.CheckConstraint(check=models.Q(('latitud', Decimal('0')), ('longitud', Decimal('0')), _negated=True), name='ubicacionruta_no_cero_cero'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionruta',
            constraint=models.CheckConstraint(check=models.Q(('precision_metros__isnull', True), ('precision_metros__gte', Decimal('0')), _connector='OR'), name='ubicacionruta_precision_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionruta',
            constraint=models.CheckConstraint(check=models.Q(('velocidad_kmh__isnull', True), ('velocidad_kmh__gte', Decimal('0')), _connector='OR'), name='ubicacionruta_velocidad_no_negativa'),
        ),
        migrations.AddIndex(
            model_name='eventoruta',
            index=models.Index(fields=['ruta', 'tipo', 'creado_en'], name='logistica_e_ruta_id_b9c665_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoruta',
            index=models.Index(fields=['severidad', 'creado_en'], name='logistica_e_severid_dc4107_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoruta',
            constraint=models.CheckConstraint(check=models.Q(('latitud__isnull', True), models.Q(('latitud__gte', Decimal('-90')), ('latitud__lte', Decimal('90'))), _connector='OR'), name='eventoruta_latitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='eventoruta',
            constraint=models.CheckConstraint(check=models.Q(('longitud__isnull', True), models.Q(('longitud__gte', Decimal('-180')), ('longitud__lte', Decimal('180'))), _connector='OR'), name='eventoruta_longitud_rango'),
        ),
        migrations.AddConstraint(
            model_name='eventoruta',
            constraint=models.CheckConstraint(check=models.Q(('latitud__isnull', True), ('longitud__isnull', True), models.Q(('latitud', Decimal('0')), ('longitud', Decimal('0')), _negated=True), _connector='OR'), name='eventoruta_no_cero_cero'),
        ),
    ]
