# Generated by Django 5.0.1 on 2026-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_eventoruta_paradaruta_puntologistico_ubicacionruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_programada_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_programada_distancia_metros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_programada_duracion_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_programada_fuente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_programada_polyline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
