# Generated by Django 5.0.1 on 2026-06-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_rutaentrega_ruta_programada_actualizada_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoruta',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida'), ('LLEGADA_GEOFENCE', 'Llegada a geocerca'), ('DESVIO', 'Desvío'), ('PARADA_LARGA', 'Parada larga'), ('GPS_PERDIDO', 'GPS perdido'), ('GPS_PRECISION_BAJA', 'GPS con precisión baja'), ('UBICACION_TARDIA', 'Ubicación tardía'), ('SALTO_IMPOSIBLE', 'Salto GPS imposible'), ('INCIDENCIA_MANUAL', 'Incidencia manual'), ('CIERRE', 'Cierre')], max_length=30),
        ),
    ]
