# Generated by Django 5.0.1 on 2026-06-14 04:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_usermoduleaccess_module'),
        ('logistica', '0021_alter_eventoruta_tipo'),
        ('pos_bridge', '0017_alter_pointsyncjob_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaCargaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('CONFIRMADA', 'Carga confirmada'), ('CON_INCIDENCIA', 'Con incidencia'), ('BLOQUEADA', 'Bloqueada')], default='PENDIENTE', max_length=20)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_override', models.CharField(blank=True, default='', max_length=240)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_carga_confirmados', to=settings.AUTH_USER_MODEL)),
                ('point_sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_carga_ruta', to='pos_bridge.pointsyncjob')),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_carga', to='logistica.rutaentrega')),
            ],
            options={
                'verbose_name': 'Checklist de carga de ruta',
                'verbose_name_plural': 'Checklists de carga de ruta',
                'ordering': ['-ruta__fecha_ruta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RutaCargaChecklistLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_external_id', models.CharField(db_index=True, max_length=40)),
                ('detail_external_id', models.CharField(db_index=True, max_length=40)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('item_code', models.CharField(blank=True, default='', max_length=80)),
                ('item_name', models.CharField(max_length=250)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('cantidad_enviada_esperada', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('cantidad_cargada', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADA', 'Cargada'), ('PARCIAL', 'Parcial'), ('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=20)),
                ('motivo_diferencia', models.CharField(blank=True, choices=[('stock_limitado', 'Stock limitado'), ('sin_stock', 'No hay stock'), ('produccion_no_lista', 'Producción aún no está lista'), ('producto_danado', 'Producto dañado'), ('cambio_autorizado', 'Cambio autorizado'), ('otro', 'Otro')], default='', max_length=40)),
                ('notas', models.TextField(blank=True, default='')),
                ('client_event_id', models.CharField(blank=True, default='', max_length=80)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='logistica.rutacargachecklist')),
                ('erp_destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_carga_destino', to='core.sucursal')),
                ('erp_origin_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_carga_origen', to='core.sucursal')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_carga', to='logistica.paradaruta')),
                ('point_transfer_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_checklist_carga', to='pos_bridge.pointtransferline')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_carga_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Línea de checklist de carga',
                'verbose_name_plural': 'Líneas de checklist de carga',
                'ordering': ['parada__orden', 'item_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParadaEntregaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOTO_ENTREGA', 'Foto de entrega'), ('INCIDENCIA', 'Incidencia'), ('ENTREGA_PARCIAL', 'Entrega parcial'), ('CONFIRMACION', 'Confirmación')], default='CONFIRMACION', max_length=30)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='logistica/evidencias_entrega/')),
                ('comentario', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('client_event_id', models.CharField(blank=True, default='', max_length=80)),
                ('capturado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_entrega_capturadas', to=settings.AUTH_USER_MODEL)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_entrega', to='logistica.paradaruta')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_entrega', to='logistica.rutaentrega')),
                ('linea_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_entrega', to='logistica.rutacargachecklistlinea')),
            ],
            options={
                'verbose_name': 'Evidencia de entrega por parada',
                'verbose_name_plural': 'Evidencias de entrega por parada',
                'ordering': ['-capturado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='rutacargachecklist',
            index=models.Index(fields=['estatus', 'sincronizado_en'], name='logistica_r_estatus_7bd705_idx'),
        ),
        migrations.AddIndex(
            model_name='rutacargachecklistlinea',
            index=models.Index(fields=['checklist', 'estatus'], name='logistica_r_checkli_dc244e_idx'),
        ),
        migrations.AddIndex(
            model_name='rutacargachecklistlinea',
            index=models.Index(fields=['parada', 'estatus'], name='logistica_r_parada__7dc983_idx'),
        ),
        migrations.AddIndex(
            model_name='rutacargachecklistlinea',
            index=models.Index(fields=['source_hash'], name='logistica_r_source__58949f_idx'),
        ),
        migrations.AddConstraint(
            model_name='rutacargachecklistlinea',
            constraint=models.UniqueConstraint(fields=('checklist', 'source_hash'), name='rutacarga_linea_source_unica'),
        ),
        migrations.AddConstraint(
            model_name='rutacargachecklistlinea',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('checklist', 'client_event_id'), name='rutacarga_linea_evento_cliente_unico'),
        ),
        migrations.AddIndex(
            model_name='paradaentregaevidencia',
            index=models.Index(fields=['ruta', 'capturado_en'], name='logistica_p_ruta_id_71b7da_idx'),
        ),
        migrations.AddIndex(
            model_name='paradaentregaevidencia',
            index=models.Index(fields=['parada', 'capturado_en'], name='logistica_p_parada__fb6c40_idx'),
        ),
        migrations.AddConstraint(
            model_name='paradaentregaevidencia',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id', ''), _negated=True), fields=('ruta', 'capturado_por', 'client_event_id'), name='paradaevidencia_evento_cliente_unico'),
        ),
    ]
