# Generated by Django 5.0.1 on 2026-06-14 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0022_rutacargachecklist_rutacargachecklistlinea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paradaruta',
            name='entrega_confirmada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='entrega_confirmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_logistica_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='entrega_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('CON_DIFERENCIA', 'Con diferencia'), ('NO_ENTREGADA', 'No entregada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='entrega_notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
