# Generated by Django 5.0.1 on 2026-06-14 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_usermoduleaccess_module'),
        ('logistica', '0023_paradaruta_entrega_confirmada_en_and_more'),
        ('pos_bridge', '0017_alter_pointsyncjob_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rutacargachecklistlinea',
            constraint=models.UniqueConstraint(condition=models.Q(('source_hash', ''), _negated=True), fields=('source_hash',), name='rutacarga_linea_source_global_unica'),
        ),
    ]
