# Generated by Django 5.0.1 on 2026-06-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0026_punto_logistico_cedis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='auditoria_analizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='auditoria_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('ok', 'OK'), ('revision', 'Revisar'), ('alto_riesgo', 'Alto riesgo'), ('error', 'Error IA')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='auditoria_ia',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='auditoria_motivos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='auditoria_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargacombustibleunidad',
            name='ticket_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
