# Generated by Django 5.0.1 on 2026-07-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0028_rename_auditoria_ia_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommerce_order_id', models.PositiveIntegerField()),
                ('ecommerce_order_number', models.CharField(blank=True, default='', max_length=60)),
                ('ecommerce_task_id', models.PositiveIntegerField()),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=160)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('driver_access_token', models.CharField(max_length=64)),
                ('driver_url', models.URLField(max_length=300)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_ecommerce', to='logistica.repartidor')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_ecommerce', to='logistica.rutaentrega')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_ecommerce', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Entrega e-commerce',
                'verbose_name_plural': 'Entregas e-commerce',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='entregaecommerce',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'PENDIENTE')), fields=('ecommerce_order_id',), name='entregaecommerce_unica_pendiente_por_pedido'),
        ),
    ]
