# Generated by Django 5.0.1 on 2026-07-04 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pedidocliente_sucursal_ref_pickupreservation_and_more'),
        ('logistica', '0029_entregaecommerce_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=160)),
                ('cliente_telefono', models.CharField(blank=True, default='', max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('canal_origen', models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('OTRO', 'Otro')], default='TELEFONO', max_length=20)),
                ('canal_detalle', models.CharField(blank=True, default='', max_length=60)),
                ('notas', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignado_en', models.DateTimeField(blank=True, null=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_domicilio_creadas', to=settings.AUTH_USER_MODEL)),
                ('pedido_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_domicilio', to='crm.pedidocliente')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_domicilio', to='logistica.repartidor')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_domicilio', to='logistica.unidad')),
            ],
            options={
                'verbose_name': 'Solicitud de domicilio',
                'verbose_name_plural': 'Solicitudes de domicilio',
                'ordering': ['-created_at'],
            },
        ),
    ]
