# Generated by Django 5.0.1 on 2026-07-11 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0030_solicituddomicilio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_causa',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_datos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_estado',
            field=models.CharField(choices=[('NO_REQUERIDA', 'No requerida'), ('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='NO_REQUERIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_revisada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paradaruta',
            name='revision_entrega_revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_logistica_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoruta',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida'), ('LLEGADA_GEOFENCE', 'Llegada a geocerca'), ('DESVIO', 'Desvío'), ('PARADA_LARGA', 'Parada larga'), ('GPS_PERDIDO', 'GPS perdido'), ('GPS_PRECISION_BAJA', 'GPS con precisión baja'), ('UBICACION_TARDIA', 'Ubicación tardía'), ('SALTO_IMPOSIBLE', 'Salto GPS imposible'), ('INCIDENCIA_MANUAL', 'Incidencia manual'), ('CIERRE', 'Cierre'), ('ENTREGA', 'Entrega'), ('ENTREGA_EXCEPCIONAL', 'Entrega excepcional'), ('ENTREGA_AUTORIZADA', 'Entrega excepcional autorizada'), ('ENTREGA_RECHAZADA', 'Entrega excepcional rechazada'), ('INCONSISTENCIA_ENTREGA', 'Inconsistencia de entrega')], max_length=30),
        ),
    ]
