# Generated by Django 5.0.1 on 2026-07-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0031_paradaruta_revision_entrega_causa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoruta',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida'), ('LLEGADA_GEOFENCE', 'Llegada a geocerca'), ('DESVIO', 'Desvío'), ('PARADA_LARGA', 'Parada larga'), ('GPS_PERDIDO', 'GPS perdido'), ('GPS_PRECISION_BAJA', 'GPS con precisión baja'), ('UBICACION_TARDIA', 'Ubicación tardía'), ('SALTO_IMPOSIBLE', 'Salto GPS imposible'), ('INCIDENCIA_MANUAL', 'Incidencia manual'), ('CIERRE', 'Cierre'), ('ENTREGA', 'Entrega'), ('ENTREGA_EXCEPCIONAL', 'Entrega excepcional'), ('ENTREGA_AUTORIZADA', 'Entrega excepcional autorizada'), ('ENTREGA_RECHAZADA', 'Entrega excepcional rechazada'), ('INCONSISTENCIA_ENTREGA', 'Inconsistencia de entrega'), ('RECARGA_CEDIS', 'Recarga CEDIS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rutacargachecklistlinea',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADA', 'Cargada'), ('PARCIAL', 'Parcial'), ('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante'), ('NO_APLICA', 'No aplica'), ('ZERO_EXPECTED', 'Enviado cero')], default='PENDIENTE', max_length=20),
        ),
    ]
