# Generated by Django 5.0.1 on 2026-07-11 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0035_paradaruta_revision_corregida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEntregaCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='entregas_ruta', max_length=40, unique=True)),
                ('ultima_fecha_exitosa', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='revision_alerta_estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTA', 'Resuelta')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='revision_alerta_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='revision_alerta_resuelta_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoruta',
            name='revision_alerta_resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_logistica_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoruta',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida'), ('LLEGADA_GEOFENCE', 'Llegada a geocerca'), ('DESVIO', 'Desvío'), ('PARADA_LARGA', 'Parada larga'), ('GPS_PERDIDO', 'GPS perdido'), ('GPS_PRECISION_BAJA', 'GPS con precisión baja'), ('UBICACION_TARDIA', 'Ubicación tardía'), ('SALTO_IMPOSIBLE', 'Salto GPS imposible'), ('INCIDENCIA_MANUAL', 'Incidencia manual'), ('CIERRE', 'Cierre'), ('ENTREGA', 'Entrega'), ('ENTREGA_EXCEPCIONAL', 'Entrega excepcional'), ('ENTREGA_AUTORIZADA', 'Entrega excepcional autorizada'), ('ENTREGA_RECHAZADA', 'Entrega excepcional rechazada'), ('ENTREGA_CORREGIDA', 'Entrega excepcional corregida'), ('INCONSISTENCIA_ENTREGA', 'Inconsistencia de entrega'), ('RECARGA_CEDIS', 'Recarga CEDIS')], max_length=30),
        ),
    ]
