# Generated by Django 5.0.1 on 2026-07-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0037_reporteunidad_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutacargachecklistlinea',
            name='superada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='logistica.rutacargachecklistlinea'),
        ),
        migrations.AlterField(
            model_name='rutacargachecklistlinea',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CARGADA', 'Cargada'), ('PARCIAL', 'Parcial'), ('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante'), ('NO_APLICA', 'No aplica'), ('ZERO_EXPECTED', 'Enviado cero'), ('SUPERADA', 'Superada')], default='PENDIENTE', max_length=20),
        ),
    ]
