# Generated by Django 5.0.1 on 2026-07-16 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0038_rutacargachecklistlinea_superada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaCargaSucursalEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_event_id', models.CharField(max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('contexto_version', models.CharField(max_length=64)),
                ('respuesta', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_carga_sucursal_creados', to=settings.AUTH_USER_MODEL)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_carga_sucursal', to='logistica.paradaruta')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_carga_sucursal', to='logistica.rutaentrega')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepanciaLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('CARGA_CEDIS', 'Carga en CEDIS'), ('RECEPCION_SUCURSAL', 'Recepción en sucursal')], max_length=30)),
                ('cantidad_enviada', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cantidad_cargada', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('motivo', models.CharField(max_length=40)),
                ('notas', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE_JEFE', 'Pendiente del jefe'), ('VALIDADA_REAL', 'Validada como real'), ('MARCADA_INCORRECTA', 'Marcada como incorrecta'), ('ACLARACION_SOLICITADA', 'Aclaración solicitada')], default='PENDIENTE_JEFE', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, default='')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_logistica_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias_logistica_creadas', to=settings.AUTH_USER_MODEL)),
                ('linea_carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias', to='logistica.rutacargachecklistlinea')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias', to='logistica.paradaruta')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancias_logistica_revisadas', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias', to='logistica.rutaentrega')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['asignado_a', 'estado', 'creado_en'], name='logistica_d_asignad_912a7e_idx'), models.Index(fields=['ruta', 'parada', 'origen'], name='logistica_d_ruta_id_09d0b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discrepancialogistica',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE_JEFE', 'ACLARACION_SOLICITADA'])), fields=('linea_carga', 'origen'), name='discrepancia_logistica_abierta_unica'),
        ),
        migrations.AddConstraint(
            model_name='rutacargasucursalevento',
            constraint=models.UniqueConstraint(fields=('ruta', 'client_event_id'), name='carga_sucursal_evento_unico'),
        ),
    ]
