# Generated by Django 5.0.1 on 2026-07-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0003_publicapiclient_repartidores_logistica_autorizados'),
        ('logistica', '0043_solicituddomicilio_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddomicilio',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SolicitudDomicilioStatusOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('requested_status', models.CharField(max_length=20)),
                ('final_status', models.CharField(max_length=20)),
                ('actor_id', models.CharField(max_length=64)),
                ('actor_nombre', models.CharField(max_length=120)),
                ('result_snapshot', models.JSONField(default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistica_status_operations', to='integraciones.publicapiclient')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_status_operations', to='logistica.repartidor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_operations', to='logistica.solicituddomicilio')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='solicituddomiciliostatusoperation',
            constraint=models.UniqueConstraint(fields=('solicitud', 'operation_id'), name='logistica_status_operation_unica'),
        ),
    ]
