# Generated by Django 5.0.1 on 2026-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0044_solicituddomicilio_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddomicilio',
            name='canal_origen',
            field=models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('OTRO', 'Otro')], default='TELEFONO', max_length=20),
        ),
    ]
