# Generated by Django 5.0.1 on 2026-07-27 21:10

from django.db import migrations, models


def migrate_delivery_states(apps, schema_editor):
    SolicitudDomicilio = apps.get_model("logistica", "SolicitudDomicilio")
    solicitudes = SolicitudDomicilio._base_manager

    # Los terminales preceden este contrato: no se inventan motivo, GPS ni
    # evidencia. Se preservan como históricos, incluso si tenían nota Point.
    solicitudes.filter(
        estatus__in=["ENTREGADO", "CANCELADO"],
    ).update(legacy_without_point=True)

    linked_to_point = solicitudes.filter(
        pedido_cliente__point_note_id__gt="",
    )
    linked_to_point.filter(estatus="PENDIENTE").update(estatus="CONFIRMADO")
    linked_assigned = linked_to_point.filter(estatus="ASIGNADO")
    linked_assigned.filter(
        direccion_cliente__latitud__isnull=False,
        direccion_cliente__longitud__isnull=False,
    ).update(estatus="LISTO")
    linked_assigned.filter(
        models.Q(direccion_cliente__latitud__isnull=True)
        | models.Q(direccion_cliente__longitud__isnull=True)
    ).update(estatus="CONFIRMADO")
    linked_to_point.filter(estatus="EN_RUTA").filter(
        models.Q(repartidor__isnull=True)
        | models.Q(direccion_cliente__latitud__isnull=True)
        | models.Q(direccion_cliente__longitud__isnull=True)
    ).update(estatus="CONFIRMADO")

    without_point = solicitudes.exclude(
        pedido_cliente__point_note_id__gt="",
    )
    without_point.exclude(estatus__in=["ENTREGADO", "CANCELADO"]).update(
        estatus="PENDIENTE_POINT",
    )


def reverse_delivery_states(apps, schema_editor):
    # Rollback deliberadamente lossy: los estados nuevos se colapsan a los dos
    # estados activos que entendía 0045; los terminales conservan su valor.
    SolicitudDomicilio = apps.get_model("logistica", "SolicitudDomicilio")
    solicitudes = SolicitudDomicilio._base_manager
    solicitudes.filter(estatus="CONFIRMADO").update(estatus="PENDIENTE")
    solicitudes.filter(
        estatus__in=["PREPARANDO", "LISTO"],
    ).update(estatus="ASIGNADO")
    solicitudes.filter(estatus="PENDIENTE_POINT").update(
        estatus="PENDIENTE",
    )
    solicitudes.update(legacy_without_point=False)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_pedidocliente_point_note_fetched_at_and_more'),
        ('logistica', '0045_alter_solicituddomicilio_canal_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddomicilio',
            name='cancelacion_motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='solicituddomicilio',
            name='instrucciones_entrega',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='solicituddomicilio',
            name='legacy_without_point',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='solicituddomicilio',
            name='ventana_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicituddomicilio',
            name='ventana_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_delivery_states, reverse_delivery_states),
        migrations.AlterField(
            model_name='solicituddomicilio',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE_POINT', 'Pendiente de Point'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_POINT', max_length=20),
        ),
    ]
