# Generated by Django 5.0.1 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integraciones", "0003_publicapiclient_repartidores_logistica_autorizados"),
        ("logistica", "0047_solicituddomicilio_pedido_unico"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicituddomicilio",
            name="incidencia_motivo",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="solicituddomicilio",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_POINT", "Pendiente de Point"),
                    ("CONFIRMADO", "Confirmado"),
                    ("PREPARANDO", "Preparando"),
                    ("LISTO", "Listo"),
                    ("EN_RUTA", "En ruta"),
                    ("ENTREGADO", "Entregado"),
                    ("INCIDENCIA", "Incidencia"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE_POINT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="solicituddomiciliostatusoperation",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="SolicitudDomicilioLocationOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_id", models.UUIDField()),
                (
                    "latitud",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "longitud",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "accuracy_m",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("captured_at", models.DateTimeField()),
                ("actor_id", models.CharField(max_length=64)),
                ("actor_nombre", models.CharField(max_length=120)),
                (
                    "result_snapshot",
                    models.JSONField(default=dict, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistica_location_operations",
                        to="integraciones.publicapiclient",
                    ),
                ),
                (
                    "repartidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domicilio_location_operations",
                        to="logistica.repartidor",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_operations",
                        to="logistica.solicituddomicilio",
                    ),
                ),
            ],
            options={"ordering": ["-captured_at", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="solicituddomiciliolocationoperation",
            constraint=models.UniqueConstraint(
                fields=("solicitud", "operation_id"),
                name="logistica_location_operation_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicituddomiciliolocationoperation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("latitud__gte", -90),
                    ("latitud__lte", 90),
                ),
                name="logistica_location_latitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicituddomiciliolocationoperation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("longitud__gte", -180),
                    ("longitud__lte", 180),
                ),
                name="logistica_location_longitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicituddomiciliolocationoperation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("accuracy_m__gte", 0),
                    ("accuracy_m__lte", 500),
                ),
                name="logistica_location_precision_rango",
            ),
        ),
    ]
