# Generated by Django 5.0.1 on 2026-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0050_domicilio_route_stop_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddomicilio',
            name='canal_origen',
            field=models.CharField(choices=[('MOSTRADOR', 'Mostrador'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('WEB', 'Web'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('OTRO', 'Otro'), ('POR_CONFIRMAR', 'Canal por confirmar')], default='TELEFONO', max_length=20),
        ),
    ]
