# Generated by Django 5.0.1 on 2026-09-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0051_alter_solicituddomicilio_canal_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteunidad',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, help_text='Reporte principal que ya atiende este mismo desperfecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='logistica.reporteunidad', verbose_name='Duplicado de'),
        ),
        migrations.AddIndex(
            model_name='reporteunidad',
            index=models.Index(fields=['duplicado_de'], name='logistica_r_duplica_603baa_idx'),
        ),
    ]
