# Generated by Django 5.0.1 on 2026-10-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0052_reporteunidad_duplicado_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddomiciliostatusoperation',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domicilio_status_operations', to='logistica.repartidor'),
        ),
    ]
