# Generated by Django 5.0.1 on 2026-05-22 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_permiso_preautorizacion_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MINUTA', 'Minuta'), ('PROYECTO', 'Proyecto'), ('COMPROMISO', 'Compromiso')], db_index=True, max_length=20)),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('entregable_esperado', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_limite', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('EN_REVISION', 'En revisión'), ('COMPLETADO', 'Completado'), ('BLOQUEADO', 'Bloqueado'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('requiere_aprobacion', models.BooleanField(default=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, default='ERP', max_length=80)),
                ('referencia_externa', models.CharField(blank=True, default='', max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_items_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_items_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_items', to='rrhh.empleado')),
                ('responsable_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['estatus', 'fecha_limite', '-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='seguimiento/evidencias/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('SUBIDA', 'Subida'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='SUBIDA', max_length=20)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_evidencias_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento_evidencias', to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='seguimiento.seguimientoitem')),
            ],
            options={
                'verbose_name': 'Evidencia de seguimiento',
                'verbose_name_plural': 'Evidencias de seguimiento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FEEDBACK', 'Retroalimentación del colaborador'), ('REVISION_DG', 'Revisión DG'), ('BLOQUEO', 'Bloqueo')], default='FEEDBACK', max_length=20)),
                ('comentario', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento_comentarios', to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='seguimiento.seguimientoitem')),
            ],
            options={
                'verbose_name': 'Comentario de seguimiento',
                'verbose_name_plural': 'Comentarios de seguimiento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(db_index=True, default=False)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_checks_completados', to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='seguimiento.seguimientoitem')),
            ],
            options={
                'verbose_name': 'Checklist de seguimiento',
                'verbose_name_plural': 'Checklist de seguimiento',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='seguimientoitem',
            index=models.Index(fields=['responsable_user', 'estatus', 'fecha_limite'], name='seg_item_resp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoitem',
            index=models.Index(fields=['tipo', 'estatus'], name='seg_item_tipo_status_idx'),
        ),
    ]
