# Generated by Django 5.0.1 on 2026-05-23 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_permiso_preautorizacion_jefe'),
        ('seguimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoitem',
            name='participantes_empleado',
            field=models.ManyToManyField(blank=True, related_name='seguimiento_participaciones', to='rrhh.empleado'),
        ),
        migrations.AddField(
            model_name='seguimientoitem',
            name='participantes_user',
            field=models.ManyToManyField(blank=True, related_name='seguimiento_participaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
