# Generated by Django 5.0.1 on 2026-05-23 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_seguimientoitem_participantes_empleado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoProrrogaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateField()),
                ('motivo', models.TextField()),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_prorrogas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogas', to='seguimiento.seguimientoitem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento_prorrogas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de prórroga',
                'verbose_name_plural': 'Solicitudes de prórroga',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['seguimiento', 'estatus'], name='seg_prorroga_item_status_idx'), models.Index(fields=['usuario', 'estatus'], name='seg_prorroga_user_status_idx')],
            },
        ),
    ]
