# Generated by Django 5.0.1 on 2026-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_aprobacion_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='aprobador_nombre',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='entregable',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='estatus_origen',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='prioridad',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='requiere_aprobacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='responsable_nombre',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='sub_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='vence',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
