# Generated by Django 5.0.1 on 2026-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_seguimientochecklistitem_aprobador_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='origen_step_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
