# Generated by Django 5.0.1 on 2026-06-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_seguimientochecklistitem_origen_step_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientochecklistitem',
            name='aprobador_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_pasos_a_aprobar', to=settings.AUTH_USER_MODEL),
        ),
    ]
