# Generated by Django 5.0.1 on 2026-06-11 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_seguimientochecklistitem_aprobador_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de calendario',
                'verbose_name_plural': 'Actividades de calendario',
                'ordering': ['fecha', 'hora_inicio', 'id'],
                'indexes': [models.Index(fields=['usuario', 'fecha', 'activo'], name='seg_act_cal_user_fecha_idx')],
            },
        ),
    ]
