# Generated by Codex on 2026-06-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguimiento", "0008_actividadcalendario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadcalendario",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_calendario_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actividadcalendario",
            name="direccion_general",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="actividadcalendario",
            name="invitado_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_calendario_invitado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actividadcalendario",
            name="tipo",
            field=models.CharField(
                choices=[("ACTIVIDAD", "Actividad"), ("REUNION", "Reunión")],
                db_index=True,
                default="ACTIVIDAD",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="actividadcalendario",
            index=models.Index(fields=["creado_por", "fecha", "activo"], name="seg_act_cal_creador_fecha_idx"),
        ),
        migrations.AddIndex(
            model_name="actividadcalendario",
            index=models.Index(fields=["invitado_user", "fecha", "activo"], name="seg_act_cal_inv_fecha_idx"),
        ),
    ]
