from django.urls import path
from . import views

app_name = "recetas"

urlpatterns = [
    path("", views.recetas_list, name="recetas_list"),
    path("recetas/", views.recetas_list, name="recetas_list_legacy"),
    path("recetas/nueva/", views.receta_create, name="receta_create"),
    path("drivers/", views.drivers_costeo, name="drivers_costeo_legacy"),
    path("pronosticos/", views.plan_produccion, name="pronosticos_legacy"),
    path("recetas/<int:pk>/", views.receta_detail, name="receta_detail"),
    path("recetas/<int:pk>/aprobar-sugeridos/", views.receta_aprobar_sugeridos, name="receta_aprobar_sugeridos"),
    path("recetas/<int:pk>/sync-point/", views.receta_sync_point, name="receta_sync_point"),
    path("recetas/<int:pk>/normalizar-canonicidad/", views.receta_repoint_canonical, name="receta_repoint_canonical"),
    path("recetas/<int:pk>/aplicar-derivados-sugeridos/", views.receta_apply_direct_base_replacements, name="receta_apply_direct_base_replacements"),
    path("recetas/<int:pk>/sync-derivados/", views.receta_sync_derivados, name="receta_sync_derivados"),
    path("recetas/<int:pk>/versiones/export/", views.receta_versiones_export, name="receta_versiones_export"),
    path("recetas/<int:pk>/actualizar/", views.receta_update, name="receta_update"),
    path("recetas/<int:pk>/eliminar/", views.receta_delete, name="receta_delete"),
    path("recetas/<int:pk>/copiar-lineas/", views.receta_copy_lineas, name="receta_copy_lineas"),
    path("drivers-costeo/", views.drivers_costeo, name="drivers_costeo"),
    path("costeo/", views.costeo_dashboard, name="costeo_dashboard"),
    path("costeo/snapshot/", views.costeo_dashboard_snapshot, name="costeo_dashboard_snapshot"),
    path("recetas/sync/grupo/", views.recetas_sync_group, name="recetas_sync_group"),
    path("recetas/sync/todo/", views.recetas_sync_all, name="recetas_sync_all"),
    path("recetas/sync/nuevos/", views.recetas_sync_new, name="recetas_sync_new"),
    path("drivers-costeo/importar/", views.drivers_costeo_importar, name="drivers_costeo_importar"),
    path("drivers-costeo/plantilla/", views.drivers_costeo_plantilla, name="drivers_costeo_plantilla"),
    path("drivers-costeo/<int:driver_id>/eliminar/", views.drivers_costeo_delete, name="drivers_costeo_delete"),
    path("recetas/<int:pk>/presentaciones/nueva/", views.presentacion_create, name="presentacion_create"),
    path("recetas/<int:pk>/presentaciones/<int:presentacion_id>/editar/", views.presentacion_edit, name="presentacion_edit"),
    path("recetas/<int:pk>/presentaciones/<int:presentacion_id>/eliminar/", views.presentacion_delete, name="presentacion_delete"),
    path("recetas/<int:pk>/lineas/nueva/", views.linea_create, name="linea_create"),
    path("recetas/<int:pk>/lineas/<int:linea_id>/editar/", views.linea_edit, name="linea_edit"),
    path("recetas/<int:pk>/lineas/<int:linea_id>/eliminar/", views.linea_delete, name="linea_delete"),
    path("recetas/<int:pk>/lineas/<int:linea_id>/aplicar-derivado/", views.linea_apply_direct_base_replacement, name="linea_apply_direct_base_replacement"),
    path("matching/pendientes/", views.matching_pendientes, name="matching_pendientes"),
    path("matching/insumos/search.json", views.matching_insumos_search, name="matching_insumos_search"),
    path("matching/aprobar/<int:linea_id>/", views.aprobar_matching, name="aprobar_matching"),
    path("matching/aprobar-sugerido/<int:linea_id>/", views.aprobar_matching_sugerido, name="aprobar_matching_sugerido"),
    path("matching/normalizar-linea/<int:linea_id>/", views.linea_repoint_canonical, name="linea_repoint_canonical"),
    path("matching/aprobar-sugerido-lote/", views.aprobar_matching_sugerido_lote, name="aprobar_matching_sugerido_lote"),
    path("plan-produccion/", views.plan_produccion, name="plan_produccion"),
    path("dg-operacion/", views.dg_operacion_dashboard, name="dg_operacion_dashboard"),
    path("produccion-cedis/semanal/", views.produccion_cedis_weekly_dashboard, name="produccion_cedis_weekly_dashboard"),
    path("dg-operacion/exportar/", views.dg_operacion_dashboard_export, name="dg_operacion_dashboard_export"),
    path("plan-produccion/dg/", views.plan_produccion_dg_dashboard, name="plan_produccion_dg_dashboard"),
    path("plan-produccion/nuevo/", views.plan_produccion_create, name="plan_produccion_create"),
    path("plan-produccion/<int:plan_id>/eliminar/", views.plan_produccion_delete, name="plan_produccion_delete"),
    path("plan-produccion/<int:plan_id>/exportar/", views.plan_produccion_export, name="plan_produccion_export"),
    path("plan-produccion/periodo/exportar/", views.plan_produccion_periodo_export, name="plan_produccion_periodo_export"),
    path("plan-produccion/estado/exportar/", views.plan_produccion_estado_dashboard_export, name="plan_produccion_estado_dashboard_export"),
    path("plan-produccion/<int:plan_id>/solicitud-imprimir/", views.plan_produccion_solicitud_print, name="plan_produccion_solicitud_print"),
    path("plan-produccion/<int:plan_id>/solicitud-compras-imprimir/", views.plan_produccion_solicitud_compras_print, name="plan_produccion_solicitud_compras_print"),
    path("plan-produccion/<int:plan_id>/generar-solicitudes/", views.plan_produccion_generar_solicitudes, name="plan_produccion_generar_solicitudes"),
    path("plan-produccion/<int:plan_id>/aplicar-consumo/", views.plan_produccion_aplicar_consumo, name="plan_produccion_aplicar_consumo"),
    path("plan-produccion/<int:plan_id>/cerrar/", views.plan_produccion_cerrar, name="plan_produccion_cerrar"),
    path("plan-produccion/<int:plan_id>/items/nuevo/", views.plan_produccion_item_create, name="plan_produccion_item_create"),
    path("plan-produccion/<int:plan_id>/items/<int:item_id>/eliminar/", views.plan_produccion_item_delete, name="plan_produccion_item_delete"),
    path("plan-produccion/pronosticos/plantilla/", views.pronosticos_descargar_plantilla, name="pronosticos_plantilla"),
    path("plan-produccion/pronosticos/importar/", views.pronosticos_importar, name="pronosticos_importar"),
    path(
        "plan-produccion/ventas-historicas/plantilla/",
        views.ventas_historicas_descargar_plantilla,
        name="ventas_historicas_plantilla",
    ),
    path(
        "plan-produccion/ventas-historicas/importar/",
        views.ventas_historicas_importar,
        name="ventas_historicas_importar",
    ),
    path(
        "plan-produccion/solicitud-ventas/plantilla/",
        views.solicitud_ventas_descargar_plantilla,
        name="solicitud_ventas_plantilla",
    ),
    path(
        "plan-produccion/solicitud-ventas/guardar/",
        views.solicitud_ventas_guardar,
        name="solicitud_ventas_guardar",
    ),
    path(
        "plan-produccion/solicitud-ventas/importar/",
        views.solicitud_ventas_importar,
        name="solicitud_ventas_importar",
    ),
    path(
        "plan-produccion/solicitud-ventas/aplicar-forecast/",
        views.solicitud_ventas_aplicar_desde_forecast,
        name="solicitud_ventas_aplicar_desde_forecast",
    ),
    path(
        "plan-produccion/pronosticos/estadistico/",
        views.pronostico_estadistico_desde_historial,
        name="pronostico_estadistico_desde_historial",
    ),
    path(
        "plan-produccion/pronosticos/preview/export/",
        views.forecast_preview_export,
        name="forecast_preview_export",
    ),
    path(
        "plan-produccion/pronosticos/vs-solicitud/export/",
        views.forecast_vs_solicitud_export,
        name="forecast_vs_solicitud_export",
    ),
    path(
        "plan-produccion/pronosticos/backtest/export/",
        views.forecast_backtest_export,
        name="forecast_backtest_export",
    ),
    path(
        "plan-produccion/pronosticos/generar-plan/",
        views.plan_produccion_generar_desde_pronostico,
        name="plan_produccion_generar_desde_pronostico",
    ),
    path("reabasto-cedis/", views.reabasto_cedis, name="reabasto_cedis"),
    path("reabasto-cedis/captura/", views.reabasto_cedis_captura, name="reabasto_cedis_captura"),
    path("reabasto-cedis/politicas/guardar/", views.reabasto_cedis_politica_guardar, name="reabasto_cedis_politica_guardar"),
    path("reabasto-cedis/inventario/guardar/", views.reabasto_cedis_inventario_guardar, name="reabasto_cedis_inventario_guardar"),
    path("reabasto-cedis/lineas/guardar/", views.reabasto_cedis_linea_guardar, name="reabasto_cedis_linea_guardar"),
    path("reabasto-cedis/cierre/guardar/", views.reabasto_cedis_cierre_guardar, name="reabasto_cedis_cierre_guardar"),
    path("reabasto-cedis/lineas/<int:linea_id>/eliminar/", views.reabasto_cedis_linea_eliminar, name="reabasto_cedis_linea_eliminar"),
    path("reabasto-cedis/solicitudes/<int:solicitud_id>/estado/", views.reabasto_cedis_estado_guardar, name="reabasto_cedis_estado_guardar"),
    path("reabasto-cedis/importar/", views.reabasto_cedis_importar, name="reabasto_cedis_importar"),
    path("reabasto-cedis/export/", views.reabasto_cedis_consolidado_export, name="reabasto_cedis_consolidado_export"),
    path("reabasto-cedis/generar-plan/", views.reabasto_cedis_generar_plan, name="reabasto_cedis_generar_plan"),
    path("reabasto-cedis/generar-compras/", views.reabasto_cedis_generar_compras, name="reabasto_cedis_generar_compras"),
    path("mrp/", views.mrp_form, name="mrp_form"),
]
