from django.urls import path
from . import views

app_name = "recetas"

urlpatterns = [
    path("", views.recetas_list, name="recetas_list"),
    path("recetas/", views.recetas_list, name="recetas_list_legacy"),
    path("drivers/", views.drivers_costeo, name="drivers_costeo_legacy"),
    path("pronosticos/", views.plan_produccion, name="pronosticos_legacy"),
    path("recetas/<int:pk>/", views.receta_detail, name="receta_detail"),
    path("recetas/<int:pk>/versiones/export/", views.receta_versiones_export, name="receta_versiones_export"),
    path("recetas/<int:pk>/actualizar/", views.receta_update, name="receta_update"),
    path("drivers-costeo/", views.drivers_costeo, name="drivers_costeo"),
    path("drivers-costeo/importar/", views.drivers_costeo_importar, name="drivers_costeo_importar"),
    path("drivers-costeo/plantilla/", views.drivers_costeo_plantilla, name="drivers_costeo_plantilla"),
    path("drivers-costeo/<int:driver_id>/eliminar/", views.drivers_costeo_delete, name="drivers_costeo_delete"),
    path("recetas/<int:pk>/presentaciones/nueva/", views.presentacion_create, name="presentacion_create"),
    path("recetas/<int:pk>/presentaciones/<int:presentacion_id>/editar/", views.presentacion_edit, name="presentacion_edit"),
    path("recetas/<int:pk>/presentaciones/<int:presentacion_id>/eliminar/", views.presentacion_delete, name="presentacion_delete"),
    path("recetas/<int:pk>/lineas/nueva/", views.linea_create, name="linea_create"),
    path("recetas/<int:pk>/lineas/<int:linea_id>/editar/", views.linea_edit, name="linea_edit"),
    path("recetas/<int:pk>/lineas/<int:linea_id>/eliminar/", views.linea_delete, name="linea_delete"),
    path("matching/pendientes/", views.matching_pendientes, name="matching_pendientes"),
    path("matching/insumos/search.json", views.matching_insumos_search, name="matching_insumos_search"),
    path("matching/aprobar/<int:linea_id>/", views.aprobar_matching, name="aprobar_matching"),
    path("plan-produccion/", views.plan_produccion, name="plan_produccion"),
    path("plan-produccion/nuevo/", views.plan_produccion_create, name="plan_produccion_create"),
    path("plan-produccion/<int:plan_id>/eliminar/", views.plan_produccion_delete, name="plan_produccion_delete"),
    path("plan-produccion/<int:plan_id>/exportar/", views.plan_produccion_export, name="plan_produccion_export"),
    path("plan-produccion/periodo/exportar/", views.plan_produccion_periodo_export, name="plan_produccion_periodo_export"),
    path("plan-produccion/<int:plan_id>/solicitud-imprimir/", views.plan_produccion_solicitud_print, name="plan_produccion_solicitud_print"),
    path("plan-produccion/<int:plan_id>/solicitud-compras-imprimir/", views.plan_produccion_solicitud_compras_print, name="plan_produccion_solicitud_compras_print"),
    path("plan-produccion/<int:plan_id>/generar-solicitudes/", views.plan_produccion_generar_solicitudes, name="plan_produccion_generar_solicitudes"),
    path("plan-produccion/<int:plan_id>/items/nuevo/", views.plan_produccion_item_create, name="plan_produccion_item_create"),
    path("plan-produccion/<int:plan_id>/items/<int:item_id>/eliminar/", views.plan_produccion_item_delete, name="plan_produccion_item_delete"),
    path("plan-produccion/pronosticos/plantilla/", views.pronosticos_descargar_plantilla, name="pronosticos_plantilla"),
    path("plan-produccion/pronosticos/importar/", views.pronosticos_importar, name="pronosticos_importar"),
    path(
        "plan-produccion/ventas-historicas/plantilla/",
        views.ventas_historicas_descargar_plantilla,
        name="ventas_historicas_plantilla",
    ),
    path(
        "plan-produccion/ventas-historicas/importar/",
        views.ventas_historicas_importar,
        name="ventas_historicas_importar",
    ),
    path(
        "plan-produccion/solicitud-ventas/plantilla/",
        views.solicitud_ventas_descargar_plantilla,
        name="solicitud_ventas_plantilla",
    ),
    path(
        "plan-produccion/solicitud-ventas/guardar/",
        views.solicitud_ventas_guardar,
        name="solicitud_ventas_guardar",
    ),
    path(
        "plan-produccion/solicitud-ventas/importar/",
        views.solicitud_ventas_importar,
        name="solicitud_ventas_importar",
    ),
    path(
        "plan-produccion/solicitud-ventas/aplicar-forecast/",
        views.solicitud_ventas_aplicar_desde_forecast,
        name="solicitud_ventas_aplicar_desde_forecast",
    ),
    path(
        "plan-produccion/pronosticos/estadistico/",
        views.pronostico_estadistico_desde_historial,
        name="pronostico_estadistico_desde_historial",
    ),
    path(
        "plan-produccion/pronosticos/generar-plan/",
        views.plan_produccion_generar_desde_pronostico,
        name="plan_produccion_generar_desde_pronostico",
    ),
    path("mrp/", views.mrp_form, name="mrp_form"),
]
