# Generated by Django 5.0.1 on 2026-07-01 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_alter_usermoduleaccess_module'),
        ('recetas', '0040_repoint_legacy_pay_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALIDAS_CFP1', 'Salidas CFP1 a sucursales'), ('INVENTARIO_CFP1', 'Inventario Diario CFP1'), ('PLAGAS', 'Registro de control de plagas'), ('CFP11', 'Control de Inventario Diario CFP 1.1'), ('ROTACION', 'Rotación de producto bitácora'), ('REBANADO', 'Producto Rebanado')], max_length=32)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=16)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraOperativaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='operacion.bitacoraoperativa')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
