# Generated by Django 5.0.1 on 2026-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraoperativa',
            name='tipo',
            field=models.CharField(choices=[('SALIDAS_CFP1', 'Salidas CFP1 a sucursales'), ('INVENTARIO_CFP1', 'Inventario Diario CFP1'), ('PLAGAS', 'Registro de control de plagas'), ('HORNOS', 'Control producción - Hornos'), ('CFP11', 'Control de Inventario Diario CFP 1.1'), ('ARMADO', 'Control producción - Armado'), ('ROTACION', 'Rotación de producto bitácora'), ('REBANADO', 'Producto Rebanado')], max_length=32),
        ),
    ]
