# Generated by Django 5.0.1 on 2026-07-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0015_insumo_grupo_mano_obra'),
        ('operacion', '0003_corte_ciego'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraoperativalinea',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_bitacora_operativa', to='maestros.insumo'),
        ),
    ]
