# Generated by Django 5.0.1 on 2026-07-30 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_trazabilidad_mantenimiento'),
        ('core', '0019_alter_usermoduleaccess_module'),
        ('fallas', '0007_objetivo_instalacion'),
        ('operacion', '0004_linea_insumo_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHigiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLORO_PH', 'Niveles de cloro y pH'), ('LIMPIEZA', 'Programa de limpieza'), ('BANOS', 'Limpieza de baños')], db_index=True, max_length=16)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('clave_instancia', models.CharField(help_text='Identifica la toma, ronda o programa dentro del día.', max_length=80)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('plantilla_version', models.CharField(max_length=20)),
                ('plantilla_snapshot', models.JSONField(blank=True, default=dict)),
                ('tipo_bano', models.CharField(blank=True, default='', max_length=16)),
                ('uso_bano', models.CharField(blank=True, default='', max_length=16)),
                ('notas', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(default='CERRADO', max_length=16)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_higiene_creados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_higiene', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Registro diario de higiene',
                'verbose_name_plural': 'Registros diarios de higiene',
                'ordering': ['-fecha', '-hora', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaHigiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_clave', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=80)),
                ('punto_revision', models.CharField(max_length=240)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('respuesta', models.CharField(blank=True, choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No cumple'), ('NA', 'No aplica')], default='', max_length=16)),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='operacion/higiene/evidencias/%Y/%m/')),
                ('corregido_en_momento', models.BooleanField(default=False)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('tipo_objetivo', models.CharField(blank=True, default='', max_length=16)),
                ('area_instalacion', models.CharField(blank=True, default='', max_length=120)),
                ('activo_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_higiene', to='activos.activo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='operacion.registrohigiene')),
                ('reporte_falla', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origen_higiene', to='fallas.reportefalla')),
            ],
            options={
                'verbose_name': 'Respuesta de higiene',
                'verbose_name_plural': 'Respuestas de higiene',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='registrohigiene',
            index=models.Index(fields=['sucursal', 'fecha', 'tipo'], name='operacion_r_sucursa_fb0b0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrohigiene',
            constraint=models.UniqueConstraint(fields=('sucursal', 'fecha', 'tipo', 'clave_instancia'), name='operacion_higiene_instancia_diaria_unica'),
        ),
        migrations.AddConstraint(
            model_name='respuestahigiene',
            constraint=models.UniqueConstraint(fields=('registro', 'punto_clave'), name='operacion_higiene_respuesta_punto_unica'),
        ),
    ]
