# Generated by Django 5.0.1 on 2026-09-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallas', '0008_reportefalla_duplicado_de_and_more'),
        ('operacion', '0005_higiene_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestahigiene',
            name='continuidad_falla',
            field=models.CharField(blank=True, choices=[('INICIAL', 'Detección inicial'), ('IGUAL', 'Sigue igual'), ('CAMBIO', 'Cambió o empeoró'), ('CORRECCION_PENDIENTE', 'Corrección pendiente de validar')], db_index=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='respuestahigiene',
            name='reporte_falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constataciones_higiene', to='fallas.reportefalla'),
        ),
    ]
