# Generated by Django 5.0.1 on 2026-02-23 08:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0006_insumo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=160)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En mantenimiento'), ('FUERA_SERVICIO', 'Fuera de servicio')], default='OPERATIVO', max_length=20)),
                ('criticidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_reposicion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('vida_util_meses', models.PositiveIntegerField(default=60)),
                ('horas_uso_promedio_mes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_mantenimiento', to='maestros.proveedor')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=24, unique=True)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='PREVENTIVO', max_length=16)),
                ('prioridad', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=16)),
                ('fecha_programada', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('costo_otros', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_mantenimiento', to='activos.activo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de mantenimiento',
                'verbose_name_plural': 'Órdenes de mantenimiento',
                'ordering': ['-fecha_programada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(max_length=80)),
                ('comentario', models.TextField(blank=True, default='')),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='activos.ordenmantenimiento')),
            ],
            options={
                'verbose_name': 'Bitácora de mantenimiento',
                'verbose_name_plural': 'Bitácoras de mantenimiento',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CALIBRACION', 'Calibración'), ('LIMPIEZA', 'Limpieza'), ('INSPECCION', 'Inspección')], default='PREVENTIVO', max_length=16)),
                ('frecuencia_dias', models.PositiveIntegerField(default=30)),
                ('tolerancia_dias', models.PositiveIntegerField(default=0)),
                ('ultima_ejecucion', models.DateField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=120)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado')], default='ACTIVO', max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='activos.activo')),
            ],
            options={
                'verbose_name': 'Plan de mantenimiento',
                'verbose_name_plural': 'Planes de mantenimiento',
                'ordering': ['proxima_ejecucion', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='plan_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_generadas', to='activos.planmantenimiento'),
        ),
    ]
