# Generated by Django 5.0.1 on 2026-05-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('core', '0006_user_module_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde está físicamente el activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='core.sucursal', verbose_name='Sucursal'),
        ),
    ]
