# Generated by Django 5.0.1 on 2026-06-02 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_activo_add_sucursal_fk'),
        ('maestros', '0010_alias_pan_arandano_chico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='origen',
            field=models.CharField(choices=[('PLAN', 'Plan de mantenimiento'), ('SOLICITUD', 'Solicitud de falla'), ('EMERGENCIA', 'Emergencia no reportada'), ('INICIATIVA', 'Iniciativa del técnico')], default='PLAN', max_length=16),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='proveedor_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento', to='maestros.proveedor', verbose_name='Proveedor del servicio'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='proxima_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisión'),
        ),
        migrations.CreateModel(
            name='EvidenciaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='activos/evidencias/%Y/%m/')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento / PDF')], default='FOTO', max_length=16)),
                ('descripcion', models.CharField(blank=True, default='', max_length=240)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='activos.ordenmantenimiento')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de orden',
                'verbose_name_plural': 'Evidencias de orden',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=24, unique=True)),
                ('descripcion', models.TextField()),
                ('urgencia', models.CharField(choices=[('CRITICA', 'Crítica — equipo detenido'), ('ALTA', 'Alta — falla visible'), ('MEDIA', 'Media — funciona con problema'), ('BAJA', 'Baja — detallar para seguimiento')], default='MEDIA', max_length=10)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=16)),
                ('nombre_reportante', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_falla', to='activos.activo')),
                ('orden_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_atendidas', to='activos.ordenmantenimiento')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_falla_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de falla',
                'verbose_name_plural': 'Solicitudes de falla',
                'ordering': ['-fecha_reporte', '-id'],
            },
        ),
    ]
