# Generated by Django 5.0.1 on 2026-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_solicitudfalla_evidenciaorden_campos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='factura_archivo',
            field=models.FileField(blank=True, help_text='PDF o foto de la factura / nota de remisión del proveedor', null=True, upload_to='activos/facturas/%Y/%m/', verbose_name='Archivo de factura'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='nota_trabajo',
            field=models.TextField(blank=True, default='', verbose_name='Nota del trabajo realizado'),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='numero_factura',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Número de factura / remisión'),
        ),
    ]
