# Generated by Django 5.0.1 on 2026-07-10 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_orden_factura_nota_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='ejecutado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento_ejecutadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='responsable_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
