# Generated by Django 5.0.1 on 2026-10-05 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenImportacionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_sha256', models.CharField(max_length=64)),
                ('hoja', models.CharField(max_length=31)),
                ('fila', models.PositiveIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('huella_revision', models.CharField(max_length=64)),
                ('fuente', models.JSONField()),
                ('decision', models.JSONField()),
                ('autor_original_id', models.PositiveBigIntegerField()),
                ('activo_original_id', models.PositiveBigIntegerField()),
                ('orden_original_id', models.PositiveBigIntegerField(null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origenes_bitacora', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origenes_importacion', to='activos.ordenmantenimiento')),
            ],
            options={'default_permissions': ()},
        ),
        migrations.AddConstraint(
            model_name='origenimportacionbitacora',
            constraint=models.UniqueConstraint(fields=('archivo_sha256', 'hoja', 'fila', 'slot'), name='origen_bitacora_global_unique'),
        ),
        migrations.AddConstraint(
            model_name='origenimportacionbitacora',
            constraint=models.CheckConstraint(check=models.Q(('slot__in', [1, 2])), name='origen_bitacora_slot_valido'),
        ),
    ]
