# Generated by Django 5.0.1 on 2026-02-17 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_alter_costoinsumo_options_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('PARCIAL', 'Parcial'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.localdate)),
                ('conformidad_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DIFERENCIAS', 'Con diferencias'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.ordencompra')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('area', models.CharField(max_length=120)),
                ('solicitante', models.CharField(max_length=120)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('fecha_requerida', models.DateField(default=django.utils.timezone.localdate)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maestros.insumo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.solicitudcompra'),
        ),
    ]
