# Generated by Django 5.0.1 on 2026-02-19 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('maestros', '0002_alter_costoinsumo_options_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='proveedor_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sugeridas', to='maestros.proveedor'),
        ),
    ]
