# Generated by Django 5.0.1 on 2026-02-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_solicitudcompra_proveedor_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
