# Generated by Django 5.0.1 on 2026-02-20 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra_referencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCompraPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_tipo', models.CharField(choices=[('mes', 'Mensual'), ('q1', '1ra quincena'), ('q2', '2da quincena')], max_length=10)),
                ('periodo_mes', models.CharField(max_length=7)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_compras_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo_mes', 'periodo_tipo'],
                'unique_together': {('periodo_tipo', 'periodo_mes')},
            },
        ),
    ]
