# Generated by Django 5.0.1 on 2026-02-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_presupuestocompraperiodo'),
        ('maestros', '0005_pointpendingmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCompraProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_compras_proveedor_actualizados', to=settings.AUTH_USER_MODEL)),
                ('presupuesto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_proveedor', to='compras.presupuestocompraperiodo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_compra', to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-presupuesto_periodo_id', 'proveedor_id'],
                'unique_together': {('presupuesto_periodo', 'proveedor')},
            },
        ),
    ]
