# Generated by Django 5.0.1 on 2026-02-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_presupuestocompraproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCompraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=120)),
                ('categoria_normalizada', models.CharField(db_index=True, max_length=140)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_compras_categoria_actualizados', to=settings.AUTH_USER_MODEL)),
                ('presupuesto_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_categoria', to='compras.presupuestocompraperiodo')),
            ],
            options={
                'ordering': ['-presupuesto_periodo_id', 'categoria'],
                'unique_together': {('presupuesto_periodo', 'categoria_normalizada')},
            },
        ),
    ]
