# Generated by Django 5.0.1 on 2026-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_presupuestocompracategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='cotizaciones_recibidas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='cotizaciones_requeridas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fuera_de_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='justificacion_excepcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
