# Generated by Django 5.0.1 on 2026-08-03 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compras_read_indexes'),
        ('maestros', '0016_alter_insumo_tipo_item'),
        ('reportes', '0045_fuente_unica_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unidad', models.CharField(default='pieza', max_length=30)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=12)),
                ('consecuencia_posponer', models.TextField(blank=True, default='')),
                ('costo_unitario_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='compras/departamentales/%Y/%m/')),
                ('estado', models.CharField(choices=[('POR_REVISAR', 'Por revisar'), ('POR_COTIZAR', 'Por cotizar'), ('COTIZANDO', 'Cotizando'), ('ESPERANDO_AREA', 'Esperando información del área'), ('ESPERANDO_DG', 'Esperando autorización de Dirección General'), ('POSPUESTO', 'Pospuesto'), ('FINANCIAMIENTO', 'Evaluando financiamiento'), ('AUTORIZADO', 'Autorizado'), ('ORDENADO', 'Ordenado'), ('RECIBIDO_PARCIAL', 'Recibido parcialmente'), ('PENDIENTE_CONFIRMACION', 'Comprado, pendiente de confirmación'), ('RECIBIDO_CONFORME', 'Recibido conforme'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], db_index=True, default='POR_REVISAR', max_length=30)),
                ('siguiente_responsable', models.CharField(choices=[('AREA', 'Área solicitante'), ('COMPRAS', 'Compras'), ('DG', 'Dirección General'), ('NADIE', 'Sin acción pendiente')], default='COMPRAS', max_length=12)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('comentario_reciente', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_compra_departamental', to='reportes.rubropresupuesto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to='compras/cotizaciones/%Y/%m/')),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('cantidad_ofertada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('envio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('instalacion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('otros_cargos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('garantia_observaciones', models.TextField(blank=True, default='')),
                ('seleccionada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_departamentales', to='maestros.proveedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='compras.itemcompradepartamental')),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('liberado_en', models.DateTimeField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.cotizacioncompradepartamental')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compromiso', to='compras.itemcompradepartamental')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=24, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('PARCIAL', 'Parcial'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_departamentales', to='maestros.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='LineaOrdenCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.cotizacioncompradepartamental')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='linea_orden', to='compras.itemcompradepartamental')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.ordencompradepartamental')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionItemDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=3, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('recibido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('linea_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.lineaordencompradepartamental')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=24, unique=True)),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('EXTRAORDINARIA', 'Extraordinaria'), ('EMERGENCIA', 'Emergencia')], default='MENSUAL', max_length=20)),
                ('periodo', models.DateField(help_text='Primer día del mes planeado')),
                ('motivo', models.TextField(blank=True, default='')),
                ('justificacion_extraordinaria', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada a Compras'), ('EN_ATENCION', 'En atención'), ('PARCIAL', 'Parcialmente atendida'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra_departamentales', to='reportes.areapresupuesto')),
                ('comprador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_departamentales_asignadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_compra_departamentales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'permissions': [('decidir_exceso_compra_departamental', 'Puede decidir excesos de compras departamentales')],
            },
        ),
        migrations.AddField(
            model_name='itemcompradepartamental',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudcompradepartamental'),
        ),
        migrations.CreateModel(
            name='EventoCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('detalle', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compras.itemcompradepartamental')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='compras.solicitudcompradepartamental')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudcompradepartamental',
            index=models.Index(fields=['area', 'periodo', 'estado'], name='comp_dept_area_per_est_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcompradepartamental',
            index=models.Index(fields=['estado', 'siguiente_responsable'], name='comp_dept_item_flow_idx'),
        ),
    ]
