# Generated by Django 5.0.1 on 2026-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_itemcompradepartamental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompradepartamental',
            name='monto_gastado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Importe reconocido por la fuente financiera; no se llena al solicitar, cotizar ni ordenar.', max_digits=14),
        ),
    ]
