# Generated by Django 5.0.1 on 2026-08-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_itemcompradepartamental_monto_gastado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisocompradepartamental',
            name='formalizado_en',
            field=models.DateTimeField(blank=True, help_text='Se llena al generar la orden; antes de eso el monto es una reserva presupuestal.', null=True),
        ),
    ]
