# Generated by Django 5.0.1 on 2026-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_compromisocompradepartamental_formalizado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncompradepartamental',
            name='enlace_producto',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='cotizacioncompradepartamental',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('', 'Compra directa'), ('AMAZON', 'Amazon'), ('MERCADO_LIBRE', 'Mercado Libre'), ('OTRA', 'Otra tienda en línea')], default='', max_length=20),
        ),
    ]
