# Generated by Django 5.0.1 on 2026-09-10 01:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_cotizacioncompradepartamental_enlace_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncompradepartamental',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcompradepartamental',
            name='estado',
            field=models.CharField(choices=[('POR_REVISAR', 'Por revisar'), ('POR_COTIZAR', 'Por cotizar'), ('COTIZANDO', 'Cotizando'), ('ESPERANDO_AREA', 'Esperando información del área'), ('ESPERANDO_DG', 'Esperando autorización de Dirección General'), ('POSPUESTO', 'Pospuesto'), ('FINANCIAMIENTO', 'Evaluando financiamiento'), ('AUTORIZADO', 'Autorizado'), ('ORDENADO', 'Ordenado'), ('COMPRADO', 'Comprado, pendiente de entrega'), ('RECIBIDO_PARCIAL', 'Recibido parcialmente'), ('PENDIENTE_CONFIRMACION', 'Comprado, pendiente de confirmación'), ('RECIBIDO_CONFORME', 'Recibido conforme'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], db_index=True, default='POR_REVISAR', max_length=30),
        ),
        migrations.CreateModel(
            name='CompraRealizadaDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('importe_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_pedido', models.CharField(blank=True, default='', max_length=160)),
                ('comprobante', models.FileField(upload_to='compras/cotizaciones/compras/%Y/%m/')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.cotizacioncompradepartamental')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra_realizada', to='compras.itemcompradepartamental')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCotizacionDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antes', models.JSONField()),
                ('despues', models.JSONField()),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='compras.cotizacioncompradepartamental')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
    ]
