# Generated by Django 5.0.1 on 2026-09-10 17:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_edicion_cotizacion_compra_realizada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('CORREO', 'Correo'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('destino', models.CharField(blank=True, default='', help_text='Correo o teléfono realmente usado.', max_length=160)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido'), ('SIN_CONTACTO', 'Sin contacto'), ('INCIERTO', 'Resultado incierto'), ('SIN_CANAL', 'Canal no disponible')], db_index=True, default='PENDIENTE', max_length=20)),
                ('detalle', models.TextField(blank=True, default='', help_text='Motivo del último resultado.')),
                ('referencia_externa', models.CharField(blank=True, default='', help_text='Id del mensaje devuelto por el proveedor.', max_length=160)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='compras.comprarealizadadepartamental')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_compra_departamental', to=settings.AUTH_USER_MODEL)),
                ('ultimo_intento_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_compra_departamental_reintentados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['canal'],
            },
        ),
        migrations.AddConstraint(
            model_name='avisocompradepartamental',
            constraint=models.UniqueConstraint(fields=('compra', 'canal'), name='aviso_compra_canal_unico'),
        ),
    ]
