# Generated by Django 5.0.1 on 2026-09-10 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_avisocompradepartamental_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprarealizadadepartamental',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HistorialCompraDepartamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antes', models.JSONField()),
                ('despues', models.JSONField()),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='compras.comprarealizadadepartamental')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
    ]
