# Generated by Django 5.0.1 on 2026-09-29 21:11

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_intentos_compra_reembolsos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentocompradepartamental',
            name='reembolso_cargos_adicionales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='intentocompradepartamental',
            constraint=models.CheckConstraint(check=models.Q(('reembolso_cargos_adicionales__gte', 0)), name='comp_dept_reembolso_cargos_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='intentocompradepartamental',
            constraint=models.CheckConstraint(check=models.Q(('reembolso_solicitado__isnull', False), ('reembolso_cargos_adicionales', 0), _connector='OR'), name='comp_dept_reembolso_cargos_requieren_total'),
        ),
        migrations.AddConstraint(
            model_name='intentocompradepartamental',
            constraint=models.CheckConstraint(check=models.Q(('reembolso_solicitado__isnull', True), ('reembolso_cargos_adicionales__lte', models.F('reembolso_solicitado')), _connector='OR'), name='comp_dept_reembolso_cargos_hasta_total'),
        ),
    ]
