# Generated by Django 5.0.1 on 2026-10-05 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        ('compras', '0017_intento_reembolso_cargos_adicionales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoCompraDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Equipo'), ('ORDEN', 'Trabajo')], max_length=6)),
                ('item_original_id', models.PositiveBigIntegerField(editable=False)),
                ('destino_original_id', models.PositiveBigIntegerField(editable=False)),
                ('autor_original_id', models.PositiveBigIntegerField(editable=False)),
                ('motivo', models.TextField()),
                ('evidencia', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_documentales', to='activos.activo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_compra_confirmados', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_documentales', to='compras.itemcompradepartamental')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_documentales', to='activos.ordenmantenimiento')),
            ],
            options={
                'ordering': ['-creado_en', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.UniqueConstraint(fields=('item_original_id', 'tipo', 'destino_original_id'), name='comp_destino_par_original_unico'),
        ),
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('orden__isnull', True), ('tipo', 'ACTIVO')), models.Q(('activo__isnull', True), ('tipo', 'ORDEN')), _connector='OR'), name='comp_destino_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('motivo', ''), _negated=True), models.Q(('evidencia', ''), _negated=True)), name='comp_destino_documentado'),
        ),
    ]
