# Generated by Django 5.0.1 on 2026-10-05 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_activo_pasaporte_qr'),
        ('compras', '0018_destinos_documentales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.CheckConstraint(check=models.Q(('item__isnull', True), ('item_id', models.F('item_original_id')), _connector='OR'), name='comp_destino_item_original'),
        ),
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.CheckConstraint(check=models.Q(('autor__isnull', True), ('autor_id', models.F('autor_original_id')), _connector='OR'), name='comp_destino_autor_original'),
        ),
        migrations.AddConstraint(
            model_name='destinocompradocumental',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('activo__isnull', True), ('activo_id', models.F('destino_original_id')), _connector='OR'), models.Q(('orden__isnull', True), ('orden_id', models.F('destino_original_id')), _connector='OR')), name='comp_destino_fuente_original'),
        ),
    ]
