# Generated by Django 5.0.1 on 2026-10-05 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activos", "0006_activo_pasaporte_qr"),
        ("compras", "0019_destinos_identificadores_originales"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedenciaAdquisicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recepcion_original_id",
                    models.PositiveBigIntegerField(editable=False),
                ),
                ("linea_original_id", models.PositiveBigIntegerField(editable=False)),
                ("intento_original_id", models.PositiveBigIntegerField(editable=False)),
                ("item_original_id", models.PositiveBigIntegerField(editable=False)),
                ("activo_original_id", models.PositiveBigIntegerField(editable=False)),
                ("version_confirmada", models.PositiveIntegerField(editable=False)),
                ("referencia_unidad", models.CharField(max_length=200)),
                (
                    "unidad_normalizada",
                    models.CharField(editable=False, max_length=200),
                ),
                ("autor_original_id", models.PositiveBigIntegerField(editable=False)),
                ("motivo", models.TextField()),
                ("evidencia", models.TextField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "activo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion",
                        to="activos.activo",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion_confirmadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion",
                        to="compras.intentocompradepartamental",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion",
                        to="compras.itemcompradepartamental",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion",
                        to="compras.lineaordencompradepartamental",
                    ),
                ),
                (
                    "recepcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedencias_adquisicion",
                        to="compras.recepcionitemdepartamental",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.UniqueConstraint(
                fields=("recepcion_original_id", "unidad_normalizada"),
                name="comp_proc_unidad_origen_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.UniqueConstraint(
                fields=("recepcion_original_id", "activo_original_id"),
                name="comp_proc_equipo_origen_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(("version_confirmada__gt", 0)),
                name="comp_proc_version_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("unidad_normalizada", ""), _negated=True),
                    models.Q(("referencia_unidad", ""), _negated=True),
                    models.Q(("motivo", ""), _negated=True),
                    models.Q(("evidencia", ""), _negated=True),
                ),
                name="comp_proc_documentada",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("recepcion__isnull", True),
                    ("recepcion_id", models.F("recepcion_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_recepcion_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("linea__isnull", True),
                    ("linea_id", models.F("linea_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_linea_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("intento__isnull", True),
                    ("intento_id", models.F("intento_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_intento_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("item__isnull", True),
                    ("item_id", models.F("item_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_item_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("activo__isnull", True),
                    ("activo_id", models.F("activo_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_activo_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedenciaadquisicion",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("autor__isnull", True),
                    ("autor_id", models.F("autor_original_id")),
                    _connector="OR",
                ),
                name="comp_proc_autor_original",
            ),
        ),
    ]
