# Generated by Django 5.0.1 on 2026-07-02 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('respuestas_json', models.JSONField(blank=True, default=dict)),
                ('veredicto_ceo', models.CharField(blank=True, choices=[('APROBAR', 'Aprobar'), ('RECHAZAR', 'Rechazar'), ('POSPONER', 'Posponer'), ('PILOTO', 'Probar piloto'), ('PEDIR_DATOS', 'Pedir más datos')], default='', max_length=20)),
                ('resumen_ejecutivo_ceo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_consejo_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta al Consejo Estratégico de IA',
                'verbose_name_plural': 'Consultas al Consejo Estratégico de IA',
                'ordering': ['-creado_en'],
            },
        ),
    ]
