# Generated by Django 5.0.1 on 2026-03-15 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_userprofile_modo_captura_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=270)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Point product',
                'verbose_name_plural': 'Point products',
                'db_table': 'pos_bridge_products',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=220)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_bridge_branches', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Point branch',
                'verbose_name_plural': 'Point branches',
                'db_table': 'pos_bridge_branches',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('inventory', 'Inventory')], default='inventory', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point sync job',
                'verbose_name_plural': 'Point sync jobs',
                'db_table': 'pos_bridge_sync_jobs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point extraction log',
                'verbose_name_plural': 'Point extraction logs',
                'db_table': 'pos_bridge_extraction_logs',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointInventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('max_stock', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='pos_bridge.pointbranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='pos_bridge.pointproduct')),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point inventory snapshot',
                'verbose_name_plural': 'Point inventory snapshots',
                'db_table': 'pos_bridge_inventory_snapshots',
                'ordering': ['-captured_at', '-id'],
                'indexes': [models.Index(fields=['branch', 'captured_at'], name='pos_bridge__branch__6901f5_idx'), models.Index(fields=['product', 'captured_at'], name='pos_bridge__product_51036d_idx')],
            },
        ),
    ]
