# Generated by Django 5.0.1 on 2026-03-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0001_initial'),
        ('recetas', '0015_receta_categoria_receta_familia_alter_receta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsyncjob',
            name='job_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales')], default='inventory', max_length=32),
        ),
        migrations.CreateModel(
            name='PointDailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_endpoint', models.CharField(blank=True, default='/Report/VentasCategorias', max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='pos_bridge.pointbranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='pos_bridge.pointproduct')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_daily_sales', to='recetas.receta')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sales', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point daily sale',
                'verbose_name_plural': 'Point daily sales',
                'db_table': 'pos_bridge_daily_sales',
                'ordering': ['-sale_date', 'branch__name', 'product__name', 'id'],
                'indexes': [models.Index(fields=['sale_date', 'branch'], name='pbs_day_branch_idx'), models.Index(fields=['sale_date', 'product'], name='pbs_day_product_idx')],
                'unique_together': {('sale_date', 'branch', 'product')},
            },
        ),
    ]
