# Generated by Django 5.0.1 on 2026-03-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_modo_captura_sucursal'),
        ('maestros', '0007_insumo_tipo_item'),
        ('pos_bridge', '0003_alter_pointsyncjob_job_type'),
        ('recetas', '0021_planproduccion_cerrado_en_planproduccion_cerrado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsyncjob',
            name='job_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales'), ('recipes', 'Recipes'), ('waste', 'Waste'), ('production', 'Production')], default='inventory', max_length=32),
        ),
        migrations.CreateModel(
            name='PointProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_external_id', models.CharField(db_index=True, max_length=40)),
                ('detail_external_id', models.CharField(db_index=True, max_length=40)),
                ('source_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('production_date', models.DateField(db_index=True)),
                ('responsible', models.CharField(blank=True, default='', max_length=160)),
                ('item_name', models.CharField(max_length=250)),
                ('item_code', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('produced_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_insumo', models.BooleanField(default=False)),
                ('source_endpoint', models.CharField(blank=True, default='/Produccion/getProduccionGeneral', max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_lines', to='pos_bridge.pointbranch')),
                ('erp_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_production_lines', to='core.sucursal')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_production_lines', to='maestros.insumo')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_production_lines', to='recetas.receta')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point production line',
                'verbose_name_plural': 'Point production lines',
                'db_table': 'pos_bridge_production_lines',
                'ordering': ['-production_date', 'branch__name', 'item_name', 'id'],
                'indexes': [models.Index(fields=['production_date', 'branch'], name='pbp_date_branch_idx'), models.Index(fields=['production_external_id'], name='pbp_prod_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointWasteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_external_id', models.CharField(db_index=True, max_length=40)),
                ('source_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('movement_at', models.DateTimeField(db_index=True)),
                ('responsible', models.CharField(blank=True, default='', max_length=160)),
                ('item_name', models.CharField(max_length=250)),
                ('item_code', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('justification', models.TextField(blank=True, default='')),
                ('source_endpoint', models.CharField(blank=True, default='/Mermas/get_mermas', max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_lines', to='pos_bridge.pointbranch')),
                ('erp_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_waste_lines', to='core.sucursal')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_waste_lines', to='maestros.insumo')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_waste_lines', to='recetas.receta')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_lines', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point waste line',
                'verbose_name_plural': 'Point waste lines',
                'db_table': 'pos_bridge_waste_lines',
                'ordering': ['-movement_at', 'branch__name', 'item_name', 'id'],
                'indexes': [models.Index(fields=['movement_at', 'branch'], name='pbw_date_branch_idx'), models.Index(fields=['movement_external_id'], name='pbw_move_idx')],
            },
        ),
    ]
