# Generated by Django 5.0.1 on 2026-03-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_modo_captura_sucursal'),
        ('maestros', '0007_insumo_tipo_item'),
        ('pos_bridge', '0004_alter_pointsyncjob_job_type_pointproductionline_and_more'),
        ('recetas', '0021_planproduccion_cerrado_en_planproduccion_cerrado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsyncjob',
            name='job_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales'), ('recipes', 'Recipes'), ('waste', 'Waste'), ('production', 'Production'), ('transfers', 'Transfers')], default='inventory', max_length=32),
        ),
        migrations.CreateModel(
            name='PointTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_external_id', models.CharField(db_index=True, max_length=40)),
                ('detail_external_id', models.CharField(db_index=True, max_length=40)),
                ('source_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('registered_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=160)),
                ('sent_by', models.CharField(blank=True, default='', max_length=160)),
                ('received_by', models.CharField(blank=True, default='', max_length=160)),
                ('item_name', models.CharField(max_length=250)),
                ('item_code', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sent_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_insumo', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('source_endpoint', models.CharField(blank=True, default='/Transfer/GetTransfer', max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfer_lines', to='pos_bridge.pointbranch')),
                ('erp_destination_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transfer_destination_lines', to='core.sucursal')),
                ('erp_origin_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transfer_origin_lines', to='core.sucursal')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transfer_lines', to='maestros.insumo')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfer_lines', to='pos_bridge.pointbranch')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transfer_lines', to='recetas.receta')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_lines', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point transfer line',
                'verbose_name_plural': 'Point transfer lines',
                'db_table': 'pos_bridge_transfer_lines',
                'ordering': ['-received_at', '-registered_at', 'destination_branch__name', 'item_name', 'id'],
                'indexes': [models.Index(fields=['received_at', 'destination_branch'], name='pbt_recv_dest_idx'), models.Index(fields=['transfer_external_id'], name='pbt_transfer_idx')],
            },
        ),
    ]
