# Generated by Django 5.0.1 on 2026-03-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0005_alter_pointsyncjob_job_type_pointtransferline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDailyBranchIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_date', models.DateField(db_index=True)),
                ('contado_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credito_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('contado_tickets', models.PositiveIntegerField(default=0)),
                ('credito_tickets', models.PositiveIntegerField(default=0)),
                ('contado_avg_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credito_avg_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('total_avg_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_endpoint', models.CharField(blank=True, default='/Home/Get_indicadores', max_length=160)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_branch_indicators', to='pos_bridge.pointbranch')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_branch_indicators', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point daily branch indicator',
                'verbose_name_plural': 'Point daily branch indicators',
                'db_table': 'pos_bridge_daily_branch_indicators',
                'ordering': ['-indicator_date', 'branch__name', 'id'],
                'indexes': [models.Index(fields=['indicator_date', 'branch'], name='pbbi_day_branch_idx')],
                'unique_together': {('indicator_date', 'branch')},
            },
        ),
    ]
