# Generated by Django 5.0.1 on 2026-03-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_pointpendingmatch_visibility_and_classification'),
        ('pos_bridge', '0006_pointdailybranchindicator'),
        ('recetas', '0021_planproduccion_cerrado_en_planproduccion_cerrado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRecipeExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(blank=True, default='', max_length=160)),
                ('branch_hint', models.CharField(blank=True, default='', max_length=160)),
                ('root_codes', models.JSONField(blank=True, default=list)),
                ('max_depth', models.PositiveIntegerField(default=3)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_runs', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'verbose_name': 'Point recipe extraction run',
                'verbose_name_plural': 'Point recipe extraction runs',
                'db_table': 'pos_bridge_recipe_runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointRecipeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=220)),
                ('source_type', models.CharField(choices=[('PRODUCT', 'Producto final'), ('INSUMO', 'Insumo/preparación')], default='PRODUCT', max_length=20)),
                ('node_kind', models.CharField(choices=[('FINAL_PRODUCT', 'Producto final'), ('PREPARED_INPUT', 'Insumo preparado')], default='FINAL_PRODUCT', max_length=30)),
                ('point_pk', models.CharField(blank=True, default='', max_length=80)),
                ('point_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('point_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=270)),
                ('family', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('has_recipe_flag', models.BooleanField(default=False)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('yield_mode', models.CharField(choices=[('YIELD_WEIGHT', 'Por peso'), ('YIELD_VOLUME', 'Por volumen'), ('YIELD_UNIT', 'Por unidad'), ('YIELD_UNKNOWN', 'Sin rendimiento explícito')], default='YIELD_UNKNOWN', max_length=20)),
                ('yield_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('yield_unit_text', models.CharField(blank=True, default='', max_length=40)),
                ('raw_detail', models.JSONField(blank=True, default=dict)),
                ('raw_bom', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_nodes', to='maestros.insumo')),
                ('erp_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_nodes', to='recetas.receta')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pos_bridge.pointrecipeextractionrun')),
                ('yield_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_nodes', to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Point recipe node',
                'verbose_name_plural': 'Point recipe nodes',
                'db_table': 'pos_bridge_recipe_nodes',
                'ordering': ['depth', 'point_name', 'id'],
                'unique_together': {('run', 'identity_key')},
            },
        ),
        migrations.CreateModel(
            name='PointRecipeNodeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('point_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('point_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=270)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_text', models.CharField(blank=True, default='', max_length=40)),
                ('classification', models.CharField(choices=[('PREPARED_INPUT', 'Insumo preparado'), ('DIRECT_INPUT', 'Insumo directo'), ('PACKAGING', 'Empaque'), ('UNRESOLVED', 'Pendiente')], default='UNRESOLVED', max_length=20)),
                ('match_method', models.CharField(blank=True, default='', max_length=32)),
                ('match_score', models.FloatField(default=0.0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_lines', to='pos_bridge.pointrecipenode')),
                ('erp_insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_node_lines', to='maestros.insumo')),
                ('erp_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_node_lines', to='recetas.receta')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos_bridge.pointrecipenode')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_recipe_node_lines', to='maestros.unidadmedida')),
            ],
            options={
                'verbose_name': 'Point recipe node line',
                'verbose_name_plural': 'Point recipe node lines',
                'db_table': 'pos_bridge_recipe_node_lines',
                'ordering': ['node', 'position', 'id'],
            },
        ),
    ]
