# Generated by Django 5.0.1 on 2026-03-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0008_pointmonthlysalesofficial'),
        ('recetas', '0026_alter_productomonthclosure_opening_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointProductHistoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('report_path', models.CharField(max_length=500)),
                ('report_title', models.CharField(blank=True, default='', max_length=300)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('branch_name', models.CharField(blank=True, default='', max_length=200)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('latest_movement_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('latest_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_history_imports', to='pos_bridge.pointbranch')),
                ('point_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_imports', to='pos_bridge.pointproduct')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_history_imports', to='recetas.receta')),
            ],
            options={
                'verbose_name': 'Point product history import',
                'verbose_name_plural': 'Point product history imports',
                'db_table': 'pos_bridge_product_history_imports',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointProductCostReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('erp_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('variance_pct', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('MATCH', 'Coincide'), ('DELTA', 'Con diferencia'), ('MISSING_RECIPE', 'Sin receta ERP'), ('MISSING_POINT_COST', 'Sin costo Point'), ('MISSING_ERP_COST', 'Sin costo ERP')], db_index=True, default='DELTA', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_cost_reconciliations', to='pos_bridge.pointbranch')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_cost_reconciliations', to='recetas.receta')),
                ('import_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='pos_bridge.pointproducthistoryimport')),
            ],
            options={
                'verbose_name': 'Point product cost reconciliation',
                'verbose_name_plural': 'Point product cost reconciliations',
                'db_table': 'pos_bridge_product_cost_reconciliations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointProductHistoryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('movement_at', models.DateTimeField(db_index=True)),
                ('movement_type', models.CharField(blank=True, default='', max_length=160)),
                ('previous_existence', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('new_existence', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cancelled', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pos_bridge.pointproducthistoryimport')),
            ],
            options={
                'verbose_name': 'Point product history row',
                'verbose_name_plural': 'Point product history rows',
                'db_table': 'pos_bridge_product_history_rows',
                'ordering': ['-movement_at', '-row_number', '-id'],
                'indexes': [models.Index(fields=['import_record', 'movement_at'], name='pbphr_import_move_idx')],
                'unique_together': {('import_record', 'row_number')},
            },
        ),
    ]
