# Generated by Django 5.0.1 on 2026-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0010_pointsalesextractiontask_pointsalesqualityalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('branch_code', models.CharField(blank=True, max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_transactions', models.IntegerField(default=0)),
                ('source_report', models.CharField(default='POINT_MONTHLY', max_length=50)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Point monthly summary',
                'verbose_name_plural': 'Point monthly summaries',
                'db_table': 'pos_bridge_monthly_summary',
                'ordering': ['-year', '-month', 'branch', 'id'],
                'indexes': [models.Index(fields=['year', 'month'], name='pbms_year_month_idx'), models.Index(fields=['branch', 'year'], name='pbms_branch_year_idx')],
                'unique_together': {('year', 'month', 'branch')},
            },
        ),
    ]
