# Generated by Django 5.0.1 on 2026-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0011_pointmonthlysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransferline',
            name='is_open',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
