# Generated by Django 5.0.1 on 2026-08-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0018_pointtransferline_is_current_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsyncjob',
            name='job_type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales'), ('recipes', 'Recipes'), ('waste', 'Waste'), ('production', 'Production'), ('transfers', 'Transfers'), ('attendance', 'Attendance'), ('deliveries', 'Deliveries')], default='inventory', max_length=32),
        ),
    ]
