# Generated by Django 5.0.1 on 2026-09-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0020_pointinsumoinventorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistoricalInventoryClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado')], db_index=True, default='DRAFT', max_length=20)),
                ('source', models.CharField(choices=[('POINT_STOCK_HISTORY', 'Historial de existencias Point'), ('POINT_OFFICIAL_CLOSING_REPORT', 'Reporte oficial de cierre Point')], max_length=40)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('expected_branch_ids', models.JSONField(default=list)),
                ('expected_product_ids', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_bridge_historical_inventory_closings',
                'ordering': ['-operational_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointHistoricalInventoryClosingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=3, max_digits=18)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pos_bridge_historical_inventory_closing_lines',
                'ordering': ['closing_id', 'branch_id', 'product_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pointhistoricalinventoryclosing',
            constraint=models.UniqueConstraint(fields=('operational_date', 'source_fingerprint'), name='pb_hist_close_date_fingerprint_uq'),
        ),
        migrations.AddField(
            model_name='pointhistoricalinventoryclosingline',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_inventory_closing_lines', to='pos_bridge.pointbranch'),
        ),
        migrations.AddField(
            model_name='pointhistoricalinventoryclosingline',
            name='closing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos_bridge.pointhistoricalinventoryclosing'),
        ),
        migrations.AddField(
            model_name='pointhistoricalinventoryclosingline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_inventory_closing_lines', to='pos_bridge.pointproduct'),
        ),
        migrations.AddIndex(
            model_name='pointhistoricalinventoryclosingline',
            index=models.Index(fields=['closing', 'product'], name='pb_hist_close_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointhistoricalinventoryclosingline',
            constraint=models.UniqueConstraint(fields=('closing', 'branch', 'product'), name='pb_hist_close_branch_product_uq'),
        ),
    ]
