# Generated by Django 5.0.1 on 2026-09-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_bridge', '0021_pointhistoricalinventoryclosing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOpenTransferSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_date', models.DateField(db_index=True)),
                ('captured_at', models.DateTimeField()),
                ('row_count', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='open_transfer_snapshot', to='pos_bridge.pointsyncjob')),
            ],
            options={
                'db_table': 'pos_bridge_open_transfer_snapshots',
                'ordering': ['-operational_date', '-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PointOpenTransferSnapshotMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_line_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('transfer_external_id', models.CharField(max_length=40)),
                ('detail_external_id', models.CharField(max_length=40)),
                ('origin_branch_external_id', models.CharField(max_length=80)),
                ('origin_branch_name', models.CharField(max_length=200)),
                ('destination_branch_external_id', models.CharField(max_length=80)),
                ('destination_branch_name', models.CharField(max_length=200)),
                ('registered_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=160)),
                ('sent_by', models.CharField(blank=True, default='', max_length=160)),
                ('received_by', models.CharField(blank=True, default='', max_length=160)),
                ('item_name', models.CharField(max_length=250)),
                ('item_code', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('requested_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sent_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_insumo', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_transfer_snapshot_destination_members', to='pos_bridge.pointbranch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_transfer_snapshot_origin_members', to='pos_bridge.pointbranch')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='pos_bridge.pointopentransfersnapshot')),
            ],
            options={
                'db_table': 'pos_bridge_open_transfer_snapshot_members',
                'ordering': ['snapshot_id', 'transfer_external_id', 'detail_external_id', 'id'],
                'indexes': [models.Index(fields=['snapshot', 'transfer_external_id', 'detail_external_id'], name='pb_open_snapshot_ref_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pointopentransfersnapshotmember',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_hash'), name='pb_open_snapshot_source_uq'),
        ),
    ]
