# Generated by Django 5.0.1 on 2026-06-25 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_alter_usermoduleaccess_module'),
        ('fallas', '0006_reclasificar_cerrado_como_finalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('NORMAL', 'Visita normal'), ('QUINCENAL', 'Auditoría quincenal'), ('SEGUIMIENTO', 'Seguimiento'), ('EXTRAORDINARIA', 'Extraordinaria')], default='QUINCENAL', max_length=16)),
                ('estatus', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=16)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_sucursal_auditor', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_sucursal_creadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_sucursal_responsable', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_comerciales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Visita a sucursal',
                'verbose_name_plural': 'Visitas a sucursal',
                'ordering': ['-fecha_programada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HallazgoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('accion_correctiva', models.TextField(blank=True, default='')),
                ('responsable', models.CharField(blank=True, default='', max_length=160)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estatus', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=16)),
                ('requiere_falla', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporte_falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_visita', to='fallas.reportefalla')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='visitas_sucursal.visitasucursal')),
            ],
            options={
                'verbose_name': 'Hallazgo de visita',
                'verbose_name_plural': 'Hallazgos de visita',
                'ordering': ['estatus', '-prioridad', 'fecha_compromiso', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=220)),
                ('respuesta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SI', 'Cumple'), ('NO', 'No cumple'), ('NA', 'No aplica')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='visitas_sucursal.visitasucursal')),
            ],
            options={
                'verbose_name': 'Checklist de visita',
                'verbose_name_plural': 'Checklist de visita',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
