# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0033_incapacidad_fecha_check"),
        ("visitas_sucursal", "0002_visitasucursal_realizada_en_and_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitasucursal",
            name="gps_latitud",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="visitasucursal",
            name="gps_longitud",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="visitasucursal",
            name="gps_precision_m",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="visitasucursal",
            name="personal_presente",
            field=models.ManyToManyField(blank=True, related_name="visitas_sucursal_presentes", to="rrhh.empleado"),
        ),
        migrations.CreateModel(
            name="FotoVisita",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("foto", models.ImageField(upload_to="visitas_sucursal/%Y/%m/")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
                ("visita", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fotos", to="visitas_sucursal.visitasucursal")),
            ],
            options={
                "verbose_name": "Foto de visita",
                "verbose_name_plural": "Fotos de visita",
                "ordering": ["-creado_en", "-id"],
            },
        ),
    ]
