# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitas_sucursal", "0003_visitasucursal_gps_personal_fotovisita"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitasucursal",
            name="gps_distancia_sucursal_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitasucursal",
            name="gps_dentro_geocerca",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
