# Generated by Django 5.0.1 on 2026-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_sucursal', '0004_visitasucursal_geocerca_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitasucursal',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Visita normal'), ('BITACORA', 'Bitácora diaria'), ('QUINCENAL', 'Auditoría quincenal'), ('SEGUIMIENTO', 'Seguimiento'), ('EXTRAORDINARIA', 'Extraordinaria')], default='QUINCENAL', max_length=16),
        ),
    ]
