# Generated by Django 5.0.1 on 2026-07-02 17:05

from django.db import migrations, models


def eliminar_bitacoras_sucursal(apps, schema_editor):
    VisitaSucursal = apps.get_model("visitas_sucursal", "VisitaSucursal")
    VisitaSucursal.objects.filter(tipo="BITACORA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_sucursal', '0005_alter_visitasucursal_tipo'),
    ]

    operations = [
        migrations.RunPython(eliminar_bitacoras_sucursal, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='visitasucursal',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Visita normal'), ('QUINCENAL', 'Auditoría quincenal'), ('SEGUIMIENTO', 'Seguimiento'), ('EXTRAORDINARIA', 'Extraordinaria')], default='QUINCENAL', max_length=16),
        ),
    ]
