# Generated by Django 5.0.1 on 2026-07-31 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_sucursal', '0006_alter_visitasucursal_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitasucursal',
            name='detalle_extraordinaria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitasucursal',
            name='gps_radio_geocerca_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitasucursal',
            name='motivo_extraordinaria',
            field=models.CharField(blank=True, choices=[('SEGUIMIENTO_PENDIENTES', 'Seguimiento de pendientes'), ('QUEJA', 'Queja recibida'), ('OTRO', 'Otro')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='visitasucursal',
            name='estatus',
            field=models.CharField(choices=[('PROGRAMADA', 'Programada'), ('BORRADOR', 'Borrador'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PROGRAMADA', max_length=16),
        ),
        migrations.AlterField(
            model_name='visitasucursal',
            name='fecha_programada',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
