# Generated by Django 5.0.1 on 2026-07-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_sucursal', '0007_visitasucursal_detalle_extraordinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitasucursal',
            name='clave_idempotencia',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
