# Generated by Django 5.0.1 on 2026-02-23 09:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditlog_options_alter_departamento_options_and_more'),
        ('recetas', '0013_solicitudventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MermaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('codigo_point', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('producto_texto', models.CharField(blank=True, default='', max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('motivo', models.CharField(blank=True, default='', max_length=160)),
                ('fuente', models.CharField(blank=True, default='IMPORT_POS_MERMA', max_length=40)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_pos', to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_pos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Merma POS',
                'verbose_name_plural': 'Mermas POS',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha', 'sucursal'], name='control_mer_fecha_c20d75_idx'), models.Index(fields=['codigo_point', 'fecha'], name='control_mer_codigo__838708_idx')],
            },
        ),
        migrations.CreateModel(
            name='VentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('codigo_point', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('producto_texto', models.CharField(blank=True, default='', max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('tickets', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fuente', models.CharField(blank=True, default='IMPORT_POS', max_length=40)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_pos', to='recetas.receta')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_pos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Venta POS',
                'verbose_name_plural': 'Ventas POS',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha', 'sucursal'], name='control_ven_fecha_d84699_idx'), models.Index(fields=['codigo_point', 'fecha'], name='control_ven_codigo__17acc7_idx')],
            },
        ),
    ]
