# Generated by Django 5.0.1 on 2026-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_mermapos_source_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='mermapos',
            name='responsable_texto',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
