# Generated by Django 5.0.1 on 2026-04-28 05:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_mermapos_responsable_texto'),
        ('core', '0005_sucursal_fecha_apertura'),
        ('pos_bridge', '0011_pointmonthlysummary'),
        ('recetas', '0028_receta_excluir_cierre_recetaequivalencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionSucursalMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('unidades', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('motivo', models.CharField(choices=[('VIDA_UTIL', 'Vencimiento/Vida útil'), ('EXCEDENTE', 'Excedente de producción'), ('CALIDAD', 'Problema de calidad'), ('OTRO', 'Otro')], default='VIDA_UTIL', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_a_matriz', to='recetas.receta')),
                ('sucursal_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_a_matriz', to='core.sucursal')),
                ('transfer_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devolucion_vida_util', to='pos_bridge.pointtransferline')),
            ],
            options={
                'verbose_name': 'Devolución sucursal a matriz',
                'verbose_name_plural': 'Devoluciones sucursal a matriz',
                'ordering': ['-periodo', '-transfer_line__registered_at', 'receta__nombre'],
                'indexes': [models.Index(fields=['periodo', 'sucursal_origen'], name='devol_matriz_period_suc_idx'), models.Index(fields=['periodo', 'receta'], name='devol_matriz_period_rec_idx')],
            },
        ),
        migrations.CreateModel(
            name='MermaMensualSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(db_index=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('unidades_merma', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('costo_merma', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unidades_vendidas', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('pct_merma_sobre_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('justificacion_principal', models.CharField(blank=True, default='', max_length=200)),
                ('fuente', models.CharField(default='POINT_BRIDGE_WASTE', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas_mensuales', to='recetas.receta')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_mensuales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Merma mensual por sucursal',
                'verbose_name_plural': 'Mermas mensuales por sucursal',
                'ordering': ['-periodo', 'sucursal__codigo', '-costo_merma', 'nombre_producto'],
                'indexes': [models.Index(fields=['periodo', 'sucursal'], name='merma_mens_suc_idx'), models.Index(fields=['periodo', 'receta'], name='merma_mens_receta_idx')],
                'unique_together': {('periodo', 'sucursal', 'receta', 'nombre_producto')},
            },
        ),
    ]
