# Generated by Django 5.0.1 on 2026-04-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_devolucionsucursalmatriz_mermamensualsucursal'),
        ('core', '0005_sucursal_fecha_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mermamensualsucursal',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas_mensuales', to='core.sucursal'),
        ),
    ]
