# Generated by Django 5.0.1 on 2026-06-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sat_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('banbajio', 'BanBajio Empresas'), ('bbva', 'BBVA Empresas')], max_length=20, unique=True)),
                ('nombre_display', models.CharField(max_length=100)),
                ('id_site_syncfy', models.CharField(max_length=50)),
                ('id_credential', models.CharField(blank=True, max_length=100, null=True)),
                ('id_account', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=32, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('saldo_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='LogSyncfy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('mensaje', models.TextField()),
                ('movimientos_nuevos', models.IntegerField(default=0)),
                ('movimientos_total', models.IntegerField(default=0)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syncfy_client.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Log Syncfy',
                'verbose_name_plural': 'Logs Syncfy',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=10)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('fecha_transaccion', models.DateTimeField()),
                ('fecha_refresh', models.DateTimeField()),
                ('extra_raw', models.JSONField(blank=True, default=dict)),
                ('conciliado', models.BooleanField(default=False)),
                ('descargado_en', models.DateTimeField(auto_now_add=True)),
                ('cfdi_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='sat_client.cfdidescargado')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='syncfy_client.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['-fecha_transaccion'],
                'indexes': [models.Index(fields=['cuenta', 'fecha_transaccion'], name='syncfy_clie_cuenta__1ace8c_idx'), models.Index(fields=['monto', 'fecha_transaccion'], name='syncfy_clie_monto_9c6676_idx'), models.Index(fields=['conciliado'], name='syncfy_clie_concili_9ca5d8_idx'), models.Index(fields=['tipo', 'fecha_transaccion'], name='syncfy_clie_tipo_6d511d_idx')],
            },
        ),
    ]
