# Generated by Django 5.0.1 on 2026-06-11 17:22

from django.db import migrations, models


def seed_amex_manual_account(apps, schema_editor):
    CuentaBancaria = apps.get_model("syncfy_client", "CuentaBancaria")
    CuentaBancaria.objects.update_or_create(
        banco="amex",
        defaults={
            "nombre_display": "American Express Business Gold",
            "id_site_syncfy": "",
            "origen": "manual",
            "numero_cuenta": "01005",
            "activa": True,
        },
    )


def keep_amex_manual_account(apps, schema_editor):
    # Do not delete the account on rollback; it may already have imported movements.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('syncfy_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='origen',
            field=models.CharField(choices=[('syncfy', 'Syncfy'), ('manual', 'Carga manual')], default='syncfy', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.CharField(choices=[('banbajio', 'BanBajio Empresas'), ('bbva', 'BBVA Empresas'), ('amex', 'American Express')], max_length=20, unique=True),
        ),
        migrations.RunPython(seed_amex_manual_account, keep_amex_manual_account),
    ]
