# Generated by Django 5.0.1 on 2026-06-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncfy_client', '0003_movimientobancario_conciliacion_operativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='tipo_conciliacion',
            field=models.CharField(blank=True, choices=[('cfdi', 'CFDI'), ('ingreso_facturado', 'Ingreso facturado'), ('traspaso_cuentas', 'Traspaso entre cuentas'), ('linea_credito', 'Linea de credito'), ('tarjeta_credito', 'Tarjeta de credito'), ('comision_bancaria', 'Comision bancaria'), ('fiscal', 'Fiscal'), ('nomina', 'Nomina'), ('revision_operativa', 'Revision operativa'), ('soporte', 'Soporte sin CFDI')], max_length=30),
        ),
    ]
