# Generated by Django 5.0.1 on 2026-08-05 19:56

import django.db.models.deletion
from django.db import migrations, models


BANBAJIO_ACCOUNTS = [
    ("0410641890202", "Inversión", "apartado"),
    ("0410641890203", "Apartado BanBajío 0203", "apartado"),
    ("0410641890204", "Impuestos", "apartado"),
    ("0410641890205", "Gasto operativo", "apartado"),
    ("0410641890206", "Utilidad", "apartado"),
    ("0410641893101", "Cuenta PyME Negocios", "operativa"),
]


def configurar_cuentas_banbajio(apps, schema_editor):
    CuentaBancaria = apps.get_model("syncfy_client", "CuentaBancaria")
    principal = (
        CuentaBancaria.objects.filter(
            banco="banbajio",
            numero_cuenta__in=["410641890201", "0410641890201"],
        )
        .order_by("pk")
        .first()
    )
    if principal is None:
        return

    principal.numero_cuenta = "0410641890201"
    principal.nombre_display = "Cuenta principal"
    principal.tipo_cuenta = "principal"
    principal.cuenta_principal_id = None
    principal.save(
        update_fields=["numero_cuenta", "nombre_display", "tipo_cuenta", "cuenta_principal"]
    )

    for numero, nombre, tipo in BANBAJIO_ACCOUNTS:
        cuenta = (
            CuentaBancaria.objects.filter(
                banco="banbajio",
                numero_cuenta__in=[numero, numero.lstrip("0")],
            )
            .order_by("pk")
            .first()
        )
        if cuenta is None:
            cuenta = CuentaBancaria.objects.create(
                banco="banbajio",
                nombre_display=nombre,
                id_site_syncfy="",
                origen="manual",
                numero_cuenta=numero,
                tipo_cuenta=tipo,
                cuenta_principal_id=principal.pk,
                activa=True,
            )
            continue
        cuenta.numero_cuenta = numero
        cuenta.tipo_cuenta = tipo
        cuenta.cuenta_principal_id = principal.pk
        cuenta.save(update_fields=["numero_cuenta", "tipo_cuenta", "cuenta_principal"])


class Migration(migrations.Migration):

    dependencies = [
        ('syncfy_client', '0004_alter_movimientobancario_tipo_conciliacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuenta_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_relacionadas', to='syncfy_client.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('independiente', 'Cuenta independiente'), ('principal', 'Cuenta principal'), ('apartado', 'Apartado'), ('operativa', 'Cuenta operativa relacionada')], default='independiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.CharField(choices=[('banbajio', 'BanBajio Empresas'), ('bbva', 'BBVA Empresas'), ('amex', 'American Express')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['banco', 'activa'], name='syncfy_clie_banco_effcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['cuenta_principal', 'tipo_cuenta'], name='syncfy_clie_cuenta__e8c4d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_cuenta__isnull', False), models.Q(('numero_cuenta', ''), _negated=True)), fields=('banco', 'numero_cuenta'), name='syncfy_cuenta_banco_numero_unico'),
        ),
        migrations.RunPython(configurar_cuentas_banbajio, migrations.RunPython.noop),
    ]
