from django.urls import path
from .views import (
    ComprasSolicitudCrearOrdenView,
    ComprasSolicitudCreateView,
    ComprasSolicitudStatusUpdateView,
    ComprasOrdenCreateRecepcionView,
    ComprasOrdenStatusUpdateView,
    ComprasRecepcionStatusUpdateView,
    ForecastBacktestView,
    ForecastEstadisticoView,
    InventarioAjustesView,
    InventarioAjusteDecisionView,
    InventarioSugerenciasCompraView,
    MRPExplodeView,
    MRPRequerimientosView,
    PlanDesdePronosticoCreateView,
    PronosticoVentaBulkUpsertView,
    PresupuestosConsolidadoView,
    RecetaCostoHistoricoView,
    RecetaVersionesView,
    SolicitudVentaAplicarForecastView,
    SolicitudVentaBulkUpsertView,
    SolicitudVentaUpsertView,
    VentaHistoricaBulkUpsertView,
)

urlpatterns = [
    path("mrp/explode/", MRPExplodeView.as_view(), name="api_mrp_explode"),
    path("mrp/calcular-requerimientos/", MRPRequerimientosView.as_view(), name="api_mrp_calcular_requerimientos"),
    path("mrp/generar-plan-pronostico/", PlanDesdePronosticoCreateView.as_view(), name="api_mrp_generar_plan_pronostico"),
    path("ventas/pronostico-backtest/", ForecastBacktestView.as_view(), name="api_ventas_pronostico_backtest"),
    path("ventas/pronostico/bulk/", PronosticoVentaBulkUpsertView.as_view(), name="api_ventas_pronostico_bulk"),
    path("ventas/pronostico-estadistico/", ForecastEstadisticoView.as_view(), name="api_ventas_pronostico_estadistico"),
    path("ventas/historial/bulk/", VentaHistoricaBulkUpsertView.as_view(), name="api_ventas_historial_bulk"),
    path("ventas/solicitud/", SolicitudVentaUpsertView.as_view(), name="api_ventas_solicitud"),
    path("ventas/solicitud/bulk/", SolicitudVentaBulkUpsertView.as_view(), name="api_ventas_solicitud_bulk"),
    path("ventas/solicitud/aplicar-forecast/", SolicitudVentaAplicarForecastView.as_view(), name="api_ventas_solicitud_aplicar_forecast"),
    path("inventario/ajustes/", InventarioAjustesView.as_view(), name="api_inventario_ajustes"),
    path("inventario/ajustes/<int:ajuste_id>/decision/", InventarioAjusteDecisionView.as_view(), name="api_inventario_ajuste_decision"),
    path("inventario/sugerencias-compra/", InventarioSugerenciasCompraView.as_view(), name="api_inventario_sugerencias_compra"),
    path("compras/solicitud/", ComprasSolicitudCreateView.as_view(), name="api_compras_solicitud"),
    path("compras/solicitud/<int:solicitud_id>/estatus/", ComprasSolicitudStatusUpdateView.as_view(), name="api_compras_solicitud_estatus"),
    path("compras/solicitud/<int:solicitud_id>/crear-orden/", ComprasSolicitudCrearOrdenView.as_view(), name="api_compras_solicitud_crear_orden"),
    path("compras/orden/<int:orden_id>/estatus/", ComprasOrdenStatusUpdateView.as_view(), name="api_compras_orden_estatus"),
    path("compras/orden/<int:orden_id>/recepciones/", ComprasOrdenCreateRecepcionView.as_view(), name="api_compras_orden_recepciones"),
    path("compras/recepcion/<int:recepcion_id>/estatus/", ComprasRecepcionStatusUpdateView.as_view(), name="api_compras_recepcion_estatus"),
    path("presupuestos/consolidado/<str:periodo>/", PresupuestosConsolidadoView.as_view(), name="api_presupuestos_consolidado"),
    path("recetas/<int:receta_id>/versiones/", RecetaVersionesView.as_view(), name="api_receta_versiones"),
    path("recetas/<int:receta_id>/costo-historico/", RecetaCostoHistoricoView.as_view(), name="api_receta_costo_historico"),
]
